### ISSUE TITLE
Alert from Google Maps displayed on every page

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1000]
One every page, an alert message appears after load:

> **www.planningalerts.org.au says:**
> This page was unable to display a Google Maps element. Please contact the site administrator. If you are the administrator of this site, please check the JavaScript console or check the following page for troubleshooting: http://g.co/mapsJSApiErrors

See https://www.planningalerts.org.au/applications/676432 for example.

![screen shot 2016-06-14 at 9 46 52 am](https://cloud.githubusercontent.com/assets/1239550/16026974/b66abbbc-3215-11e6-91d8-017a69ca4755.png)

**Comment by equivalentideas** [comment]
The error is `API error: InvalidClientIdMapError`.

**Comment by equivalentideas** [comment]
Here's the [description of this error from Google](https://developers.google.com/maps/documentation/javascript/error-messages#deverrorcodes):

> The client ID included in the script element that loads the API is invalid, or expired. Please make sure you are using your client ID correctly. The client ID should start with "gme-" prefix. If you see this error even when using your client ID correctly, the client ID may have expired. Please contact your Google Account Manager.
>
> If you do not have Google Maps for Work license, you need to use a key parameter with your API key instead of the client parameter.

**Comment by equivalentideas** [comment]
I see in email that @henare is already on getting our access reactivated.

I'm going to look at anyway we can suppress the error.

**Comment by equivalentideas** [comment]
We could [comment out the id from .env](https://github.com/openaustralia/planningalerts/blob/master/.env#L60-L63), which would flip us back to the non-business version.

But, apparently a fix is in the works and it should be resolved shortly. Fingers crossed.

**Comment by henare** [comment]
I reported this to Google yesterday morning and they said they'd reactivate the client ID but it would take a few hours. 24 hours later and it seems to have worked. 

I've also started the process with them to renew our grant properly. It seems they (now?) want us to do it each year.
