### ISSUE TITLE
Address autocomplete suggests splitting the street number from the street name

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1003]
e.g. _123**,** King St, Newtown_ instead of _123 King St, Newtown_

![tooltip_002](https://cloud.githubusercontent.com/assets/48945/16069348/05d947f8-3311-11e6-8bb4-2b7661b8dac4.png)

I don't think this is having a massive impact but it's weird.

**Comment by davwood** [comment]
@henare take a look at the PR I just referenced to fix this when you get a chance.
