### ISSUE TITLE
Highlight or restrict councillors you can ask based on the ward of the application

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1007]
When you're asking your councillor about an application we currently show all councillors for an application. We initially did this because it's the simplest thing to do.

As we knew before we started development and as a number of people have pointed since we launched, councillors often represent specific geographic regions within the LGAs most commonly known as wards. Instead of simply showing all councillors, should we just show the people that represent the ward that the application is in? Or should we at least highlight the councillors that represent that ward?

**Comment by henare** [comment]
Here's a councillor saying they can't help someone because it's not their ward: https://www.planningalerts.org.au/applications/668775#reply36

**Comment by equivalentideas** [comment]
Would it be a useful and simple first start to just show the ward of the councillors?

**Comment by henare** [comment]
@equivalentideas how would that help people? I've got no idea what ward I'm in or what ward the development application is in.
