### ISSUE TITLE
Confirm comment email loses line breaks

### ISSUE THREAD

**Issue by CloCkWeRX** [openaustralia/planningalerts#1015]
1. Enter comment, with line breaks
2. Get the confirm email

Expected:
Formatting for comment is consistent with online version

Actual:
Line breaks have gone MIA.

![image](https://cloud.githubusercontent.com/assets/365751/16403136/45d84de8-3d31-11e6-9f85-43c077631a55.png)
vs
![image](https://cloud.githubusercontent.com/assets/365751/16403156/75100326-3d31-11e6-95f0-68c910d0cc0b.png)

**Comment by equivalentideas** [comment]
Great report @CloCkWeRX 👍 

Could the first step to this be getting through line breaks working? Are they coming through in the alert emails? If so, there might be a view helper there we could use.

**Comment by hisayohorie** [comment]
Hi I'm trying to recreate the bug and having hard time seeding the database. Do you have any suggestion to how to go about it? It seems like I need to have applications and authorities(and maybe other things?) in my database in order to recreate this bug?

**Comment by hisayohorie** [comment]
never mind I figured it out!

**Comment by henare** [comment]
Fixed by #1132.

@hisayohorie if you included "Fixes #1015" in the body of your pull request this would have automagically closed :sparkles: :smile:

**Comment by CloCkWeRX** [comment]
Your a wizard now @henare
- JK Rowling's lessor know github works
