### ISSUE TITLE
It's not easy to follow up on a comment I made

### ISSUE THREAD

**Issue by CloCkWeRX** [openaustralia/planningalerts#1016]
1. Make comment on an application
2. Close your browser
3. Try to locate the comment you made easily

You end up having to either:
- Go find the original planning alert email and click on that
- Find your comment confirmation email and work out that you can click 'confirm your comment' to view
- Search from the front page of planning alerts (by council ref fails, by exact address shows me things by recent location... which can rank the best match lowest)
- Google a bunch
- Or trawl through browser history

Instead, the comment confirmation should provide a number of links to let me easily revisit what I submitted.

![image](https://cloud.githubusercontent.com/assets/365751/16403191/da58bac0-3d31-11e6-9a99-aa6a22180049.png)

**Comment by equivalentideas** [comment]
> Search from the front page of planning alerts (by council ref fails, by exact address shows me things by recent location... which can rank the best match lowest)

This relates to #1020 .

This is a great issue by the way @CloCkWeRX 👍  the way you've broken down the experience is really helpful.

**Comment by mlandauer** [comment]
I think this would be mostly addressed by #1020 and #1166
