### ISSUE TITLE
On each application show how it stacks up against key measures of the local planning scheme

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1019]
How awesome would it be if for each application it showed you some of the parameters of the planning scheme that applied to that particular lot and how well the application stacked up e.g.
- minimum 2 car spaces required - this development has 3 :white_check_mark:
- maximum building height is 9m - this development is 12m :x:

etc.

**Comment by equivalentideas** [comment]
This is a really nice idea. It’s also something that someone (or god forbid a local council) could start doing for their area to provide much clearer info about applications, but also to show how the planning scheme works and why it might be something that matters or you might want to change ;-)

**Comment by equivalentideas** [comment]
For NSW some of the data to do this is in here http://data.environment.nsw.gov.au/dataset/standard-instrument-local-environmental-plan-height-of-buildings-hob

**Comment by mlandauer** [comment]
I love the idea. It's just too far away from practical right now. The rules for all the LEPs would need to be codified and then somehow linked up to the application. Or alternatively we would depend on users to figure this information out but how would we know that they're right?

Right now a user could say something to the effect of the development being out of whack with the LEP in a comment
