### ISSUE TITLE
Make it easier to find applications at a specific address

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#1020]
Listings appearance for a many results on a single address is bewildering

There are [lots of results for 490 Crown St](https://www.planningalerts.org.au/?q=490+Crown+St%2C+Surry+Hills+NSW+2010&sort=distance), Surry Hills. There's something fishy going on about this display, not apha-numeric and not by date. Looks like a bug of some sort!

One simple option would be to sort by most recent first by default for results on a single address, but I suspect this needs a bit more unpicking!

**Comment by kat** [comment]
this is specifically about unrelated DAs at a single address. For connected DAs at one address see #267

**Comment by kat** [comment]
reclassified as a bug because I thought it was doing alpha-numeric but on closer inspection is doing something weirder and wronger.

**Comment by equivalentideas** [comment]
Here's another example where this would be helpful https://www.planningalerts.org.au/?q=32-34+Perouse+Rd%2C+Randwick+NSW+2031&sort=distance

I think the most recent application at the address should come first.

It also strikes me that if you're sorting by proximity, we could do more to make the application _at_ the address more distinct from the other applications.

A user story here is:

_When I'm searching for applications at a specific address, make it clearer which applications are at the address, and which are most recent._

How might we make this clearer for people?

**Comment by equivalentideas** [comment]
Another example with strange ordering https://www.planningalerts.org.au/?q=64+Gollan+Ave%2C+Oatlands+NSW+2117&sort=distance

**Comment by equivalentideas** [comment]
@Henare and I were just talking about ways to help people looking for applications at a specific address. I came across this issue that has a few simple improvements so I've renamed this to cover the broader issue.

We were specifically talking about making applications at the address searched for visually distinct from the rest of the results by putting them at the top of the results—which is already suggested here. They could also come under a heading (like “applications at this address”). They should also definitely be sorted newest to oldest.

**Comment by jamezpolley** [comment]
> There are [lots of results for 490 Crown St](https://www.planningalerts.org.au/?q=490+Crown+St%2C+Surry+Hills+NSW+2010&sort=distance), Surry Hills. There's something fishy going on about this display, not apha-numeric and not by date. Looks like a bug of some sort!

There are still lots of applications at this address, but they no longer seem weird. It's a single premises with several licenced establishments, and the (recent, at least) applications are all related to changes to licencing conditions at an establishment. 

It would still be useful to have an easier way to find applications at a specific address though.
