### ISSUE TITLE
On an application page, give an option to see all the applications at that address

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#1021]
see all listings at this address” on a DA for that address if there are more than one on the search result for a single DA organised by date. Also see #1020

**Comment by kat** [comment]
This is specifically about separate or unrelated DAs at one address. Also see #267 which is to display those which are at one address and related.

**Comment by mlandauer** [comment]
I think we should try to implement this in some form. I don't think we should try to figure out at the same time whether the other applications are related because I think that's probably quite difficult and we probably simply don't have the necessary information to do that.
