### ISSUE TITLE
Rails 4.1 is no longer supported

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1022]
http://weblog.rubyonrails.org/2016/7/13/Rails-4-2-7-and-4-1-16-have-been-released/

**Comment by equivalentideas** [comment]
Some relevant sections from [the upgrade notes](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-1-to-rails-4-2) :

> ## 3.2 Responders
> ## 3.11 Action Mailer
> ## 3.12 Foreign Key Support

**Comment by equivalentideas** [comment]
Deprecation warnings:

* [ ] DEPRECATION WARNING: `#deliver` is deprecated and will be removed in Rails 5. Use `#deliver_now` to deliver immediately or `#deliver_later` to deliver through Active Job.
* [ ] DEPRECATION WARNING: The configuration option `config.serve_static_assets` has been renamed to `config.serve_static_files` to clarify its role (it merely enables serving everything in the `public` folder and is unrelated to the asset pipeline). The `serve_static_assets` alias will be removed in Rails 5.0. Please migrate your configuration files accordingly. (called from block in <top (required)> at /Users/Luke/git/planningalerts-app/config/environments/test.rb:16)
* [ ] DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.
    You can opt into the new behavior and remove this warning by setting:

    config.active_record.raise_in_transactional_callbacks = true

   (called from block in tsort_each at /Users/Luke/.rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/tsort.rb:150)
* [ ] DEPRECATION WARNING: `named_routes.helpers` is deprecated, please use `route_defined?(route_name)` to see if a named route was defined.

**Comment by equivalentideas** [comment]
@henare I've just pushed what I did on Tuesday onto branch [`rails-4-2-7`](https://github.com/openaustralia/planningalerts/tree/rails-4-2-7) .

After you left I quickly decided to do the jump to 4.2 first and then do the point releases from there, so I was dealing with less errors at a time. That looked good, then I had to leave.

**Comment by equivalentideas** [comment]
Having an interesting time with this. Tests failing but I can do the steps in the running app. Googling I've found that there's problems with Rails 4.2 and rspec 2.

It's recommended to first upgrade rspec to at least 3.1. https://gist.github.com/kostia/f896d21628d750b94ced#upgrading-rails-41-to-42-with-rspec-2

So I'm going to do that in a fresh PR with all tests green and then rebase this work onto that.

**Comment by equivalentideas** [comment]
Upgrading rspec fixed almost all the errors 👍 

Still one failure that I can't fix. I'm going to post this on a PR to work through there.

**Comment by henare** [comment]
Fixed in #1023.
