### ISSUE TITLE
Support community experts in contributing their knowledge to improve developments?

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1024]
We're interested in civil society groups using our projects. This is a bit of an all over the place issue, comes out of a discussion with @kat these groups and our projects.

On [this issue](https://www.planningalerts.org.au/applications/703994#comment57087), a civil society org have made a contribution about how a development could be improved for their special interest group (cyclists in this case).

> WestConnex is about to destroy Euston Road (upgraded to 6 lanes). The viability and future liveability of this development will depend on retention of the current low-traffic aspect of Maddox St. Further, due to planned development of the Alexandra Canal cycleway, Maddox St will become a regionally significant cycling route, and with that, east-west "crossability" (walking and cycling) of Euston is and will be hugely important.
> 
> This development application should be revised to have its Section 94 contributions directed to traffic calming measures aimed at: 
> - limiting the impact of high-speed traffic (including rat-running) through Maddox St caused by the vastly increased Westconnex traffic volumes and speeds, and 
> - retaining east-west "crossability" of Euston Rd at Maddox St (in future, signal phasing for Westconnex will significantly reduce east-west "green time" - consider the limited north-south crossing opportunities on Gardeners Rd by comparison) 
> - limiting the ingress of out-of-area traffic into Maddox St. The City should consider - through this development application - reconfiguring the entrances to Maddox as low traffic" or even "filtered permeability" ingress.

**Comment by mlandauer** [comment]
I don't understand what this issue is actually proposing. So, closing it.
