### ISSUE TITLE
Fix Darebin scraper to include missing Development Applications

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#1025]
A user documented discrepancies between DAs on PlanningAlerts and those on Darebin's website.

'email alerts for Darebin VIC are restricted to subdivision and other benign events, whilst neglecting to notice planning applications for multiple multi-storey units and apartments, of which there are many. Query data import process, and sorting rules for Darebin." Examples below

Please let me know if there is any other reason as to why the service may have become attenuated, or if there is anything that I can contribute to this process.

regards

Stewart

+++++++++++++++++++++++++++++
Examples of non-alerts and inaccurate information reported for Darebin
(1) I have not received an alert for the following site which about 1 km distant, and inside my rule "within 2 km of 662 Plenty Road, Preston VIC 3072"
https://www.planningalerts.org.au/applications/689512

(2) The system reports the following statistics for Darebin
https://www.planningalerts.org.au/authorities/darebin

"For Darebin City Council 0 applications have been collected in the last week, 83 in the last month and 1376 since 16 Dec 2009, when this authority was first added to PlanningAlerts. That's a median of 4 applications per week (ignoring weeks without any applications at all)."

An independent audit finds teh following numbers of applications for 2016:
69 (jan), 128 (feb), 161 (mar), 144 (apr), 153 (may), 136 (jun), 164 (july), 12 (aug 4 days only) and 967 (total).'

Additional documentation attached

[planning_alerts_info_140816.pdf](https://github.com/openaustralia/planningalerts/files/429474/planning_alerts_info_140816.pdf)

**Comment by henare** [comment]
We should open this issue on the scraper repository: https://github.com/planningalerts-scrapers/darebin

**Comment by kat** [comment]
ok.... thanks @henare see https://github.com/planningalerts-scrapers/darebin/issues/2
