### ISSUE TITLE
Set alert by Post Code or Local Government Area.

### ISSUE THREAD

**Issue by ghost** [openaustralia/planningalerts#1029]
One suggestion I would love to have is to be able to set up alerts by Post Code or Local Government Area, for example 5063 or Parkside SA. Sometimes the 2 km radius does not cover everything I need, or I need to set up multiples. An example is how Realestate.com.au handles it. 

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ely5)

**Comment by jamezpolley** [comment]
This would be particularly useful for eg local action groups who are often interested in a region much larger than our standard radius

**Comment by mlandauer** [comment]
Less keen on this idea for general use than the idea of just allowing user to increase the alert radius. Doing an alert for a whole LGA feels like something more in the territory of a "pro" service for real estate agents.
