### ISSUE TITLE
Out of date, unused Layar code is still in the app

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1032]
As I understand it Layar is a augmented reality platform that PlanningAlerts was using to help people see application through their phone cameras. We don't support it anymore and it's well out of date. But we still have layar code in the app. It recently raised an error in production https://app.honeybadger.io/projects/37075/faults/31199193 , which made us look at it and think it's not in there for any reason.

**Comment by mlandauer** [comment]
I'm pretty sure all the layar code has been surgically removed
