### ISSUE TITLE
How many people are unsubscribing from alerts each week?

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1035]
We don't have a good idea of how many people are unsubscribing from alerts each week, but we think it could be in the hundreds. We worked this out by comparing the number of new alerts each week (roughly 450) to the growth in total subscribers (from our memory). So this is really rough, but we’re not currently doing anything special to track this.

If it is high, and we could reduce it, that it another way to increase overall users of PlanningAlerts—and make sure it's really useful to people.

**Comment by equivalentideas** [comment]
Based on the [Jacaranda](https://github.com/openaustralia/jacaranda) messages, about 730 new email addresses are confirmed each fortnight at the moment, and the total/net subscriber count only goes up ~600. So that's about ~130 people unsubscribing each fortnight or 65 a week.

![screen shot 2016-10-10 at 1 52 58 pm](https://cloud.githubusercontent.com/assets/1239550/19225985/e2385654-8ef0-11e6-94a2-0b0341e7e436.png)

**Comment by kat** [comment]
Is this issue done now we have Jacaranda stats? What do we want to do with this information @equivalentideas

**Comment by equivalentideas** [comment]
Yeah I think the fortnightly count is close enough. We want to use it to benchmark work to make less people want to leave:

> If it is high, and we could reduce it, that it another way to increase overall users of PlanningAlerts—and make sure it's really useful to people.
