### ISSUE TITLE
Show comments from council differently

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1045]
From time to time council adds comments on PlanningAlerts, e.g.

* https://www.planningalerts.org.au/applications/737223#comment58512
* https://www.planningalerts.org.au/applications/737028#comment58441

We could use their email domain to show these differently.

**Comment by mlandauer** [comment]
Lovely to see that this has happened. I'm not aware of it being a regular occurrence unfortunately. So I think we'll have to put this idea on the backburner
