### ISSUE TITLE
Send 404 for error: ArgumentError: invalid value for Integer(): "6'A=0"

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1046]
This seems to be happening where a bot is hitting this path, possibly probing. We shouldn't be raising and throwing a 500 here, it should be 404.

## Backtrace

    line 14 of [PROJECT_ROOT]/app/controllers/comments_controller.rb: index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/37075/faults/31270657)

**Comment by equivalentideas** [comment]
More examples:

* https://app.honeybadger.io/projects/37075/faults/31270657#notice-summary
* https://app.honeybadger.io/projects/37075/faults/31723825

**Comment by zoek1** [comment]
Hi, can anybody show the logs? 'cause honeybadger show me that I'm not allowed and I don't know if the bug is what i reproduced.

**Comment by henare** [comment]
@zoek1 it looks like it's someone probing the server. Here's a URL from Honeybadger's log you can use to test:

`https://www.planningalerts.org.au/authorities/kuringgai/comments?page=4%22%20or%20(1,2)=(select*from(select%20name_const(CHAR(111,108,111,108,111,115,104,101,114),1),name_const(CHAR(111,108,111,108,111,115,104,101,114),1))a)%20--%20%22x%22=%22x`

**Comment by hisayohorie** [comment]
Due to the <a href="https://github.com/openaustralia/planningalerts/pull/1144">fix</a> of <a href="https://github.com/openaustralia/planningalerts/issues/669">issue#669</a>(adding validate_page_param in application_controller.rb's before_filter, we don't get that error anymore, FYI!
