### ISSUE TITLE
Optimise ‘authorities’ Google AdWords campaign to improve quality score

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1048]
Currently all the different authorities are named under a single ad group. We should

* [ ] bring these up a level so we have an ad group for each authority

This will allow us to test multiple keywords for authorities. We can also then:

* [ ] Set a better URL for the ads, probably the [authority applications index page](https://www.planningalerts.org.au/authorities/camden/applications) which has a title with the authorities name, a signup form, and a list of applications so people can see what they'll get in the alerts.
* [ ] Taylor the ad language more
* [ ] When we do this we should also make sure all the authorities in PlanningAlerts are covered

**Comment by equivalentideas** [comment]
I'm sure the way we approach an [AdWords setup for Right To Know authorities](https://github.com/openaustralia/righttoknow/issues/660) will be really informative for how we do this. We should do that first since we've got some [specific advice](https://github.com/openaustralia/righttoknow/issues/660#issuecomment-272354757).

**Comment by mlandauer** [comment]
Closing this as a won't fix.
