### ISSUE TITLE
Test an alternate AdWords Ad for our PlanningAlerts Authorities Campaign

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1049]
This campaign has fed 25 alert signups in the last 30 days. We only currently have one Ad that's shown. I just added a variation to see if that helps. We'll check back and compare in a few weeks.

(your suburb becomes the keyword they searched, e.g. Penrith)

## Existing ad

![screen shot 2016-11-22 at 10 05 25 am](https://cloud.githubusercontent.com/assets/1239550/20504428/6eb06aba-b09b-11e6-83e7-b817f5c36562.png)

## New ad

![screen shot 2016-11-22 at 10 05 41 am](https://cloud.githubusercontent.com/assets/1239550/20504434/76a8fcc8-b09b-11e6-9972-2844eac955c3.png)

**Comment by equivalentideas** [comment]
The old ad is outperforming the new variation by a bit, mainly because it's get served much more. I've also added other variations that are doing much better in terms of % served and clicks, but not as well on conversion. I dont have any idea why, so this might be a good example to get some advice on.

![screen shot 2017-01-03 at 1 26 43 pm](https://cloud.githubusercontent.com/assets/1239550/21598885/783b6b5a-d1b8-11e6-8194-353fdd15bf4e.png)

**Comment by equivalentideas** [comment]
We got some advice from Megan (Amire):

> 
> - A little mysterious on the conversion % front, sometimes what delivers a better CTR doesn’t translate directly into a better conversion rate.
> 
> **Better CTR:**
> {Keyword: Your Local Area}
> Get Free Planning Alerts
> Find Out What’s Happening in Your AreaWith Free PlanningAlerts Emails.
> 
> **Better Conv %:**
> {Keyword: Your Local Area}
> Who’s Building Near You?
> Free Email Alerts. Keep an Eye on {Keyword: Your Neighbourhood}.
> 
> **Theory:**
> The better conv % ad does a better job of qualifying users by mentioning the Suburb twice in the ad so attracts a more motivated searcher?

Megan made the really good suggestion to set AdWords to display all the ads we're testing evening for a few weeks at the beginning of a test so we can properly judge clickthrough and conversion. That makes a lot of sense. I'm going to change these to be served equally now.

**Comment by equivalentideas** [comment]
I can't see the "rotation settings" section on the campaign, as per these instructions https://support.google.com/adwords/answer/6034106?hl=en.

I've asked Megan for help :)

**Comment by equivalentideas** [comment]
Megan explained that the settings are only in the AdWords Editor. And I changed them for this campaign 20 days ago. But that doesn't seem to be effecting which ads are served 😕 

![screen shot 2017-02-02 at 11 24 42 am](https://cloud.githubusercontent.com/assets/1239550/22532258/3eb0a0e6-e93a-11e6-8330-a20fb956b89a.png)

**Comment by mlandauer** [comment]
Closing this as a won't fix
