### ISSUE TITLE
Address search doesn’t recognise “23 Rodeo Drive, HILLVUE, NSW 2340” as a valid street address

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1054]
When you enter that valid street address you get the form error “Please enter a full street address like ‘36 Sowerby St, Goulburn, NSW’”.

![screen shot 2016-11-23 at 12 24 57 pm](https://cloud.githubusercontent.com/assets/1239550/20548487/ef855ede-b177-11e6-86ee-379f0e229b09.png)

This is the address for this DA, https://eproperty.tamworth.nsw.gov.au/ePropertyProd/P1/eTrack/eTrackApplicationDetails.aspx?r=P1.WEBGUEST&f=%24P1.ETR.APPDET.VIW&ApplicationId=DA2017%2f0146 , which wasn't loaded into PlanningAlerts for some reason.

**Comment by henare** [comment]
We use Google Maps for this and that address is not being recognised: https://www.google.com.au/maps/search/23+Rodeo+Drive,+HILLVUE,+NSW+2340/

This can be reported to Google to add that address but I'm closing this as it's an issue with Maps, not PlanningAlerts.

> which wasn't loaded into PlanningAlerts for some reason.

Maybe it couldn't be geocoded for the reason above so it couldn't be loaded?
