### ISSUE TITLE
How many people have commented, but aren't signed up for alerts?

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1055]
These seem like good people to be signed up for PlanningAlerts. Are there many of them?

**Comment by mlandauer** [comment]
I've always naively assumed people would sign up for alerts first but now that you say it it's perfectly possible that someone is told by a friend about an application and they comment on it without ever having signed up for email alerts

**Comment by mlandauer** [comment]
I'm going to take a guess that this doesn't happen too often so probably not a high priority
