### ISSUE TITLE
Invite existing PlanningAlerts users to become backers

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1061]
Especially people who've donated.

**Comment by henare** [comment]
To test the work we're doing we'd like to invite people in cohorts.

Should these be just random samples? People that have donated before are almost certainly going to behave differently to someone that hasn't. Should they be treated differently?

**Comment by mlandauer** [comment]
We do an annual fundraising drive which includes all current PlanningAlerts users
