### ISSUE TITLE
Many static maps in email alerts are missing

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1063]
I've noticed that many maps images are missing in my email alerts when reading the message in Gmail:

![selection_001](https://cloud.githubusercontent.com/assets/48945/20585921/4819edb8-b253-11e6-8a14-aa9c8b12591c.png)

Checking browser developer tools shows the maps are 404ing. However if you visit the image link in another tab they appear fine.

What's going on? Is this just me?

**Comment by auxesis** [comment]
How long are the map urls?

I've noticed on Got Gastro that if the URLs are longer than 2,000 characters [they won't render in some browsers](http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers).

**Comment by henare** [comment]
Thanks for the hint @auxesis.

I just checked one and it's 410 characters, including the Gmail image proxy part. The link itself is only 140: https://maps.googleapis.com/maps/api/staticmap?zoom=16&size=150x150&maptype=roadmap&markers=color:red%7C-33.9220806,151.1372811&sensor=false

**Comment by henare** [comment]
Oh my, it looks like it's a known issue (for years): https://code.google.com/p/gmaps-api-issues/issues/detail?id=7279

**Comment by henare** [comment]
I've got another theory about this. Static maps now [need an API key](https://developers.google.com/maps/documentation/static-maps/get-api-key?hl=en_GB) - could signing our static maps URLs make them more reliable?

**Comment by mlandauer** [comment]
This is all fixed, as far as I'm aware, now that we sign the maps api urls
