### ISSUE TITLE
Can't use some emoji in comments

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1064]
We made our tables UTF-8 a while back after people had problems with emoji in comments but we just got another error. I think it was someone trying to use this funky emoji: http://emojipedia.org/emoji-modifier-fitzpatrick-type-3/

This [could be the problem](https://web.archive.org/web/20161017220138/http://jasonseifer.com/2014/06/20/rails-4-mysql-and-emoji-mysql2error-incorrect-string-value-error):

>You might think that you’re safe inserting most utf8 data in to mysql when you’ve specified that the charset is utf-8. Sadly, however, you’d be wrong.

**Comment by equivalentideas** [comment]
[Honeybadger says](https://app.honeybadger.io/projects/37075/faults/32195115#notice-summary) we've seen this a couple of times this month. Here's the latest for your testing pleasure:

```
ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect string value: '\xF0\x9F\x98\xB6 ' for column 'text' at row 1:
INSERT INTO `comments` (`application_id`, `name`, `text`, `address`, `email`, `created_at`, `updated_at`, `confirm_id`) VALUES (xxx, 'resident ', 'How rediculous the site is on a bend and one lane . With school and daycare, and shops why build up traffic congestion. Ridiculous speechless 😶 ', 'xxxxxx ', 'xxxxxxxx', '2017-01-24 12:15:03', '2017-01-24 12:15:03', 'xxxxx')
'\xF0\x9F\x98\xB6 '
```

**Comment by mlandauer** [comment]
Fixed by switching to utf8mb4 in https://github.com/openaustralia/planningalerts/commit/b06536ad0e55830cea3e878b1a0adac023fcc248
