### ISSUE TITLE
Post results of daily scrape to Slack so volunteer scraper hackers can check it

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1066]
This should be really easy to do and would help spot some obvious problems and get them fixed.

**Comment by equivalentideas** [comment]
What would a useful output in Slack look like @CloCkWeRX @LoveMyData ? Would this be an individual message for each scraper? Or something like “150 PlanningAlerts scrapers ran, 5 had errors: example/scraper ...”.

**Comment by CloCkWeRX** [comment]
I use the email feed at the moment for this kind of thing.

If I had something like newrelic that captured the error,  backtrace, params, etc and had a one-click log issue button (newrelic has jira integration, which I use at work); that'd be interesting.

**Comment by henare** [comment]
@equivalentideas this is the current output, and what I was proposing to post into a Slack room with the [email to Slack thing](https://get.slack.help/hc/en-us/articles/206819278-Send-emails-to-Slack): https://gist.github.com/henare/773be42dc76c1146359d9b5b127f3e0c

**Comment by equivalentideas** [comment]
> I think thats more of a morph.io feature though

Nice idea @CloCkWeRX , raise an issue on morph.io for it?

> @equivalentideas this is the current output, and what I was proposing to post into a Slack room with the email to Slack thing: https://gist.github.com/henare/773be42dc76c1146359d9b5b127f3e0c

Nice 👍 That seems like a great first pass to make that useful data available. Would that be helpful start @CloCkWeRX @LoveMyData ?

**Comment by LoveMyData** [comment]
Just the ERROR and remove duplicates maybe useful. Otherwise, it is just another log need to read... I am sure all of us have read way too many logs...

**Comment by henare** [comment]
Done: see #planningalerts-log in Slack.
