### ISSUE TITLE
Invite people who have paid and free subscriptions to PlanningAlerts pro to become backers

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1071]
There are 5 people paying $5 a month for access to three or more alerts. There's another few dozen people who we gave free access, “a free subscription”. We're planning on removing this concept from PlanningAlerts so what should happen to these people?

* [x] backup subscribers data from PlanningAlerts - https://docs.google.com/spreadsheets/d/1wP-X-Ioxbrylae07A2-mKuCV1LZlDDxPRCagCllbmfg/edit#gid=0
* [x] Remove all the Subscriptions data from PlanningAlerts production
* [x] switch subscriptions off for one subscriber in stripe
* [ ] invite that subscriber to become a backer
* [ ] Invite everyone who was on free plans to become backer

**Comment by henare** [comment]
>There are 5 people paying $5 a month for access to three or more alerts.

There's only 1 remaining active $5 subscriber. All the others have been marked inactive in Stripe.

When we're ready to roll out Backers let's just switch this off for that person and invite them to become a backer.

>There's another few dozen people who we gave free access, “a free subscription”. We're planning on removing this concept from PlanningAlerts so what should happen to these people?

Nothing special? What were you thinking?

**Comment by equivalentideas** [comment]
> When we're ready to roll out Backers let's just switch this off for that person and invite them to become a backer.

Nice one.

> Nothing special? What were you thinking?

Hadn't thought too much, but I was thinking may as well email them to tell them to start donating for some small amount.

**Comment by mlandauer** [comment]
Closing this as a won't fix
