### ISSUE TITLE
[PlanningAlerts/production] ActiveRecord::RecordInvalid: Validation failed: Radius meters isn't selected

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1078]
## Backtrace

    line 46 of [PROJECT_ROOT]/app/controllers/alerts_controller.rb: area

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/37075/faults/32298050)

**Comment by equivalentideas** [comment]
Not sure how this could happen, but seems like it shouldn't. I haven't investigated, but this issue is a note to check this out.
