### ISSUE TITLE
Mention our Google Grant on the about page

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1079]
Google have just been nice enough to increase our Maps quota they provide as part of our Google Grant and asked if we'd be open to mentioning it on the site. That seems reasonable to me so let's add a specific bit to the About page.

**Comment by Riyuzakii** [comment]
I would like to do that if you tell me how to.
It's my first time on Github .

**Comment by equivalentideas** [comment]
👋 Hi @Riyuzakii you'd need to edit this file https://github.com/openaustralia/planningalerts/blob/master/app/views/static/about.html.haml to add a paragraph with something like "PlanningAlerts receives free access to use Google Maps services through the Google Grants program."

**Comment by equivalentideas** [comment]
Added in https://github.com/openaustralia/planningalerts/pull/1109

**Comment by equivalentideas** [comment]
This is now deployed, you can see it here https://www.planningalerts.org.au/about

@henare you might like to check the wording, and also let Google know if you were planning that.
