### ISSUE TITLE
Explain how a commerical license holder might use the API to achieve things they want

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1080]
People who ask us about commercial use often ask about:

* filtering applications by type (keyword?) e.g. applications for car parks or daycare centers
* filtering applications by postcode/suburb.

In our information for commercial users, it might be helpful to provide examples from their perspective. For example, "You might want to know whenever an application for a car park is being advertised in Melbourne. Here's an example of how you might use the API to filter down applications".

That might help people understand the practical value of the data more concretely.

**Comment by mlandauer** [comment]
I think this is a great idea. Frankly it's a miracle we have commercial customers at all with the complete lack of explanation of benefits we have currently.
