### ISSUE TITLE
Share on facebook/social media/etc

### ISSUE THREAD

**Issue by CloCkWeRX** [openaustralia/planningalerts#1083]
So recently, I came across https://www.facebook.com/parepgsa/photos/a.1684947738433022.1073741828.1658756407718822/1813208835606911/?type=3&notif_t=page_reengaged&notif_id=1486081402181604

![image](https://cloud.githubusercontent.com/assets/365751/22580478/aaa39d00-ea28-11e6-8e9d-acf5647069ca.png)

Observations:
 * It connected people to an issue quickly by location
 * There's people interested via various aggregators (community groups, etc) that rely on those aggregators to find developments of interest
 * Facebook conversation might capture a lot of negative input, but that isn't shared with the planning authority the same way planningalerts does.

#769 sort of explores this specifically for comments; but I'd go further and:
 * Review/improve the OpenGraph metadata for development applications on planning alerts (https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fwww.planningalerts.org.au%2Fapplications%2F774752 - optimized for twitter at the moment)
 * Put a number of 'share' links beyond the existing "Tweet" and "Like" controls
![image](https://cloud.githubusercontent.com/assets/365751/22580439/61263f7a-ea28-11e6-802e-09a5e79286e5.png)
 * Improve the user flow from a facebook/social media link to 'make an informed comment' to 'share'

**Comment by equivalentideas** [comment]
@CloCkWeRX this is awesome. Would you be up for making your suggestions into individual issues? I'm not sure about "Put a number of 'share' links beyond ..." because I'm not sure how much those existing links are getting used—but aside from that we should definitely fix up the open graph stuff and improve the flow for people sharing 👍

**Comment by mlandauer** [comment]
Closing this issue in favour of the more detailed issues that it references
