### ISSUE TITLE
Consider use of '3d' maps within google to help understand the context of a planning appplication

### ISSUE THREAD

**Issue by CloCkWeRX** [openaustralia/planningalerts#1084]
I read about a proposed telephone tower. The development application had renderings of what it would look like, and some alternatives (no renderings).

My default action was to use google maps, where there is high quality LIDAR based 3d modelling to better understand the location.

It looks like:
![image](https://cloud.githubusercontent.com/assets/365751/22580587/a1f138e2-ea29-11e6-9c58-a6a1676ab3e6.png)

https://developers.google.com/maps/documentation/javascript/maptypes talks about 45 degree imagery; while http://stackoverflow.com/questions/2660201/what-parameters-should-i-use-in-a-google-maps-url-to-go-to-a-lat-lon I think describes how to deep link to 'google earth' mode.

I think this actually works better than street view imagery in some cases.

Similar to #427

We should look at ways to deep link in a new tab (perhaps a 'see more' link near the maps controls) or similar

**Comment by equivalentideas** [comment]
This looks really good @CloCkWeRX the perspective makes it easy to locate an address and also get a feel how the development change could impact the street.

**Comment by mlandauer** [comment]
I agree. I think this 45 degree view gives you a really good overview of how things are arranged in an area. I wonder if they're available in all urban areas in Australia?
