### ISSUE TITLE
Improve opengraph headers specifically for facebook sharing of development applications

### ISSUE THREAD

**Issue by CloCkWeRX** [openaustralia/planningalerts#1085]
Parent issue #1083

https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fwww.planningalerts.org.au%2Fapplications%2F774752

### Warnings
 * The 'og:url' property should be explicitly provided, even if a value can be inferred from other tags.
 * The 'og:title' property should be explicitly provided, even if a value can be inferred from other tags.
 * The 'og:description' property should be explicitly provided, even if a value can be inferred from other tags.
 * The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags.
 * The 'fb:app_id' property should be explicitly provided, Specify the app ID so that stories shared to Facebook will be properly attributed to the app. Alternatively, app_id can be set in url when open the share dialog.
 * The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags.

### Current appearance - Facebook
![image](https://cloud.githubusercontent.com/assets/365751/22635778/0aaba6de-ec86-11e6-8fee-c502230df157.png)

 * Needs a better description, such as "Development application for (address) to (modifications)" or similar
 * Could use a call to action, like "Comment on this application if it affects you"
 * Could use lat/long data (https://developers.facebook.com/docs/reference/opengraph/object-type/place/)
 * Could use a proper image - either a static maps API rendering or a planning alerts logo

### Other metadata
Worth checking schema.org for useful types, such as https://schema.org/Event for the notification period.

**Comment by equivalentideas** [comment]
A little old, but this is great reading on this topic https://alistapart.com/article/like-able-content-spread-your-message-with-third-party-metadata

**Comment by trang20t** [comment]
Hi there! In order to contribute to this, do I submit a html page or png image?

**Comment by henare** [comment]
@trang20t you'll need to set up the Rails application and then add these additional meta tags.

**Comment by TheChirpyWitch** [comment]
@equivalentideas I have resolved this issue. Please merge my pull request. Thanks!

**Comment by equivalentideas** [comment]
> @equivalentideas I have resolved this issue. Please merge my pull request. Thanks!

Thanks @TheChirpyWitch 🏞 I'll leave this till that PR is merged, there appears to be ongoing discussion there :) https://github.com/openaustralia/planningalerts/pull/1137
