### ISSUE TITLE
Improve metadata / google indexing for development applications

### ISSUE THREAD

**Issue by CloCkWeRX** [openaustralia/planningalerts#1086]
Part of #1083

Right now its not particularly easy to locate a specific application on planningalerts.org via the search controls.

People are also likely to hear about a development and put it into google (via mobile or desktop) to try and find out more.

Right now, some applications aren't even indexed:

![image](https://cloud.githubusercontent.com/assets/365751/22635950/95ffb60c-ec87-11e6-8aa0-1cb7b3883663.png)

When crawled, they don't have much structured data
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.planningalerts.org.au%2Fapplications%2F774752

We should:
  * Add a sitemap (https://support.google.com/webmasters/answer/183668?hl=en or other standardized format)
 * Describe the pages with relevant metadata via schema.org

**Comment by henare** [comment]
Great catch @CloCkWeRX :+1: 

>Add a sitemap

We [already generate one](https://github.com/openaustralia/planningalerts/blob/master/lib/tasks/planningalerts.rake#L26-L30) though, [don't we](https://www.planningalerts.org.au/sitemap.xml)? Is there something more we need to do?

**Comment by CloCkWeRX** [comment]
Interesting - its odd Google wasn't indexing some of those applications then. Does https://www.google.com/webmasters/tools/home?hl=en-GB shed any light?

**Comment by CloCkWeRX** [comment]
https://support.google.com/webmasters/answer/183668?hl=en#addsitemap

```
There are two different ways to make your sitemap available to Google:

Submit it to Google using the Search Console Sitemaps tool
OR
Insert the following line anywhere in your robots.txt file, specifying the path to your sitemap:
Sitemap: http://example.com/sitemap_location.xml
```

robots.txt is a bit empty at the moment
```
# See http://www.robotstxt.org/wc/norobots.html for documentation on how to use the robots.txt file
#
# To ban all spiders from the entire site uncomment the next two lines:
# User-Agent: *
# Disallow: /
```
so if its not submitted, needs a line in there

**Comment by henare** [comment]
>so if its not submitted, needs a line in there

It was submitted.

>Interesting - its odd Google wasn't indexing some of those applications then. Does https://www.google.com/webmasters/tools/home?hl=en-GB shed any light?

Search Console Sitemaps said over 700,000 items had been submitted but only about 4,000 indexed. I've resubmitted so let's see what happens. Here's what it looks like now:

![selection_001](https://cloud.githubusercontent.com/assets/48945/22870202/7b0f5970-f1f9-11e6-8ea8-1155fa5899f0.png)

@CloCkWeRX I've also given you full access to the search console for PlanningAlerts.
