### ISSUE TITLE
Create a facebook application for planningalerts.org.au

### ISSUE THREAD

**Issue by CloCkWeRX** [openaustralia/planningalerts#1087]
Part of #1083 

https://developers.facebook.com/apps/ -> Create new application

![image](https://cloud.githubusercontent.com/assets/365751/22636092/9a58184c-ec88-11e6-89a4-0abbab1eacf7.png)

This basically lets you define high res thumbnails, descriptions, etc for links to planningalerts shared on facebook.

That will likely enable https://github.com/huacnlee/social-share-button or similar

**Comment by mlandauer** [comment]
We've already got one. See https://github.com/openaustralia/infrastructure/commit/a88b3f16a037b1b28bc8eac472042d2d8dd3e9d6
