### ISSUE TITLE
Move to a gem or similar to provide social share buttons

### ISSUE THREAD

**Issue by CloCkWeRX** [openaustralia/planningalerts#1088]
Part of #1083 
https://github.com/openaustralia/planningalerts/blob/master/app/views/applications/_facebook_share_button.html.haml right now is a 'like' control, as opposed to a call to action to 'get your friends to comment on this'.

https://github.com/openaustralia/planningalerts/blob/master/app/views/applications/_twitter_share_button.html.haml is a bit better ("Look at what is planned for (address)") in terms of a call to action.

These might be better with https://github.com/huacnlee/social-share-button or a similar plugin; and revamped to become part of the user flow (After a user has submitted comment, prompt to share with their friends/family/neighbours via social media)

Current:
![image](https://cloud.githubusercontent.com/assets/365751/22636239/ae567144-ec89-11e6-9e9e-ad6d26bdab7c.png)

Proposed:
![image](https://cloud.githubusercontent.com/assets/365751/22636351/38c43adc-ec8a-11e6-92f5-bf3cd8628c80.png)

**Comment by equivalentideas** [comment]
Here's some relevant reading for this https://bigmedium.com/ideas/no-mobile-share-buttons.html

It would be great to see on this issue some references to what other sites are doing with this and find out what the best way of adding these links is for people today.

**Comment by mlandauer** [comment]
We implemented #1316 already and after a quick google I couldn't see any gems that do any nice privacy preserving versions of these buttons. So, closing this.
