### ISSUE TITLE
Google Maps API warning: RetiredVersion

### ISSUE THREAD

**Issue by CloCkWeRX** [openaustralia/planningalerts#1090]
https://www.planningalerts.org.au/applications/774752

View console:
```Google Maps API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version```

**Comment by mlandauer** [comment]
This doesn't appear to be happening anymore. So, I'm assuming we must have already fixed it by upgrade the google maps api
