### ISSUE TITLE
Maps don't gracefully degrade without JavaScript

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1097]
They used to so something has changed:

![selection_001](https://cloud.githubusercontent.com/assets/48945/22725917/5cc38532-ee24-11e6-80f4-9e2060c2f2e0.png)

**Comment by mlandauer** [comment]
Just did a quick test on https://www.planningalerts.org.au/applications/1062250

With javascript:
![image](https://user-images.githubusercontent.com/2221/129608098-c2778ff4-6e00-4590-8e83-77d1cb5859fa.png)

And no javascript:
![image](https://user-images.githubusercontent.com/2221/129608169-748614d3-af88-4ec7-96be-7889af3cdb9f.png)

So looks good to me. The basic map is a static image and the streetview doesn't work as expected.
