### ISSUE TITLE
[PlanningAlerts/production] NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1099]
## Backtrace

    line 17 of [PROJECT_ROOT]/app/controllers/alerts_controller.rb: create

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/37075/faults/32614295)

**Comment by equivalentideas** [comment]
This looks like a bug in the new alert signup logic I introduced. I'll check it out.

**Comment by henare** [comment]
It's only happened once. Have we had signups since?

The error report says that no parameters were passed:

![selection_001](https://cloud.githubusercontent.com/assets/48945/22761820/8bb8323e-eeb0-11e6-9175-838d3b926618.png)

Could it just be a client problem, or someone probing?

**Comment by equivalentideas** [comment]
> It's only happened once. Have we had signups since?

Hmmm, yep heaps. I think you're right that this looks like probing. Someone firing post requests.

What could a client problem be causing this?

**Comment by henare** [comment]
>What could a client problem be causing this?

The browser not sending the form params with the request.

**Comment by equivalentideas** [comment]
> The browser not sending the form params with the request.

Ah right, so in practice that would be a browser bug to not sent the form data with the request. In that case, should we close this and resolve the honeybadger alert to see if it ever happens again?

**Comment by henare** [comment]
>In that case, should we close this and resolve the honeybadger alert to see if it ever happens again?

I agree with closing it but not because of this case. Instead because of the more likely...

>I think you're right that this looks like probing. Someone firing post requests.
