### ISSUE TITLE
If something goes wrong during stripe billing, you can no longer donate until an admin deletes your subscription

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1101]
If this happens you see this error "ActiveRecord::RecordInvalid: Validation failed: Email has already been taken".

https://app.honeybadger.io/projects/37075/faults/32624471

This is because a donations plan is still created for your email in the failed transaction, so when you try again, you're email is taken.

**Comment by equivalentideas** [comment]
In https://github.com/openaustralia/planningalerts/compare/1c91aec781ef...08b3881f74ec I added a notice to display when the donation is invalid:

![screen shot 2017-05-22 at 4 52 16 pm](https://cloud.githubusercontent.com/assets/1239550/26295806/1b92aa2a-3f0f-11e7-881b-70bb1aa529eb.png)

**Comment by equivalentideas** [comment]
That didn't actually fix this issue, it just made the result much less confusing for users and prompts them to tell us about it.

**Comment by mlandauer** [comment]
We're now receiving all donations through donorbox
