### ISSUE TITLE
People are commenting on an application because they're being scammed by someone at the same address

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1110]
https://www.planningalerts.org.au/applications/187121

It seems they've done a web search for the address of the person that's sending them products they haven't ordered and in desperation are leaving a comment. This isn't good for the site (we have lots of out-of-place, angry comments), the planning authority (they're getting complaints about a scam, not DA submissions), or the people complaining (they're not going to get helped). How can we make things better?

**Comment by mlandauer** [comment]
As far as I'm aware this hasn't happened again so closing this issue as a won't fix. If this happens again in the future we should just deal with it pragmatically as we do everything else, hide the comment, etc...

If it reoccurs more consistently then we should reopen this ticket
