### ISSUE TITLE
Should there be so much whitespace on the desktop Backers page?

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1112]
There seems to be heaps of whitespace below the titles and donation box:

![selection_001](https://cloud.githubusercontent.com/assets/48945/23533948/d50d3308-0008-11e7-95a1-a047aacf1be6.png)

It's not there on mobile so I'm wondering why this is the case and if we should reduce it.

![selection_002](https://cloud.githubusercontent.com/assets/48945/23534072/8d83ad5e-0009-11e7-89ee-70129f3a28ba.png)

**Comment by equivalentideas** [comment]
> Should there be so much whitespace on the desktop Backers page? 

Nien :) There's meant to be a big background image that reminds people of their experiences using PlanningAlerts which they love.

But, just before I deployed the page I broke my arm and so wasn't able to shoot the image 🚲 

> The if I'm able I'll shoot the new background image for the header. I've made the page look reasonable without that, so if I can't do it tomorrow I'll probably finish this and deploy without it. 

https://github.com/openaustralia/planningalerts/issues/1082

I think we replace this issue with that one and add the image now that I'm healed!

**Comment by equivalentideas** [comment]
Closing this since the answer is in last comment
