### ISSUE TITLE
define purpose of each mini milestone and measure success of backers' page

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#1114]
What response are we looking for from people who go to the backers page? Define this.

**Comment by equivalentideas** [comment]
> What response are we looking for from people who go to the backers page? Define this.

Our aim for the backers page is for people to sign up to start donating to us regularly. We're tracking the effectiveness of the page and form in Google Anaytics see https://github.com/openaustralia/planningalerts/issues/1116#issuecomment-308665698 and we're seeing donations flow in via Slack.

The thing we really want to measure is income per month, I'll make a new issue for that.
