### ISSUE TITLE
Set up analytics to track mini-milestones in #1114

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#1116]

**Comment by equivalentideas** [comment]
We've got detailed event tracking on the form and links to the donation page, and we've got an event set up so we can see the funnel for this.

![screen shot 2017-06-15 at 6 30 02 pm](https://user-images.githubusercontent.com/1239550/27172479-cc9e96de-51f8-11e7-9174-7673d421edd2.png)

I think that's done.
