### ISSUE TITLE
Require HTTPS for the API

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1119]
Currently HTTPS is optional only on the API. I think we originally did this for performance reasons - is this still necessary? It would be much better if everything went over HTTPS not least because API keys are potentially sent in plain text. It would also allow us to get all the HTTPS stuff out of the code and leave that to the serving layer.

**Comment by mlandauer** [comment]
I just checked. This is still the case. Yes, it would be good to change this.

The thing to do is check how the api is currently being used. If anyone is still using http, we should warn them ahead of time by sending them an email explaining that they have 2 months (or whatever) to switch over to using https or their requests will be redirected to https automatically. We can't depend on their clients handling redirects so we definitely need to warn them

**Comment by mlandauer** [comment]
We're now forcing https for the API as well. Nobody was using http anymore as the documentation had been updated a long time ago.
