### ISSUE TITLE
"Return to" text and link on "now check your email" page broken

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1120]
![selection_001](https://cloud.githubusercontent.com/assets/48945/23643881/87fc2cce-0358-11e7-94ba-b13acf7b383b.png)

**Comment by equivalentideas** [comment]
That should say something like 'applications near 123 Parramatta Rd, Annandale NSW 2038' and link to the search for that page, e.g. https://www.planningalerts.org.au/?q=123+Parramatta+Road%2C+Annandale%2C+New+South+Wales

**Comment by ShubhiL** [comment]
I would like to solve this issue.
Since, it's my first time on Github, I will ask you questions and work on this.

**Comment by Liceth** [comment]
Hi @henare 
I will try to work on this.

**Comment by akve17** [comment]
Hi @henare 
I have recently made some commits on this issue. Please review them.

**Comment by equivalentideas** [comment]
@akve17 could you please open a [Pull Request](https://help.github.com/articles/about-pull-requests/) with your fix?

**Comment by equivalentideas** [comment]
@akve17 could you please open a [Pull Request](https://help.github.com/articles/about-pull-requests/) with your fix?

**Comment by equivalentideas** [comment]
Fixed by https://github.com/openaustralia/planningalerts/issues/1142
