### ISSUE TITLE
A large number of alerts and comments go unconfirmed

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1121]
Around 16% of both alerts and comments are never confirmed. Is this expected or something we can improve on? It seems like a lot.

I'd also like to know how this is changing over time - an excellent candidate for a performance/feedback hackday!

**Comment by equivalentideas** [comment]
Just seen that 80 of 418 comments on this DA went confirmed https://www.planningalerts.org.au/applications/793257

That feels real bad to me :(

I agree we should start tracking this somehow and do something about it.

Potential avenues for solutions that come to mind:

* check all the UX of the flow to confirm comments and alerts.
* send a reminder email a few days later (depending on when the da submissions close?).

**Comment by mlandauer** [comment]
Eek. I hope this is still not as bad as this. I would hope a more standard user registration process would almost magically make this go away #1530
