### ISSUE TITLE
As someone that's just changed email addresses I want to update all my PlanningAlerts with my new email address

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1147]
Fairly frequently (once a week?) we get an email from someone asking us to update their email address for their alert(s). Currently we just tell them to unsubscribe and sign up again. This is obviously a bit of a hassle for them, especially if they have a few alerts signed up. It would be nice if there was an easy, automated way for them to do it themselves.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_e97x)

**Comment by mlandauer** [comment]
I think this would be best solved by having user login and registration and for their email alerts to be attached to their user accounts. This way they can change their email address and everything will magically work.
