### ISSUE TITLE
See if we can request planningalerts.org to be directed to planningalerts.org.au

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1148]
Yesterday I told someone about PlanningAlerts and saw them type planningalerts.org into their browser and be confused because they got a Ghandi.net holding page and not PlanningAlerts.

A whois reveals John Handelaar owns it so he might be up for redirecting to us until he finishes the Irish PlanningAlerts? Once the Irish version is up we could even put a redirector on that domain that bounces you to your local version.

We could also see about doing the same with planningalerts.com that Chris Taggart has. It doesn't look like that's going to be resurrected as the UK one any time soon.

**Comment by handelaar** [comment]
Plus I only registered it about four days before this message.... didn't see it (@ me next time, matey)

It's been picked up with intent to use. Perhaps we should do that Gaze thing we do on TWFY sites with these.

Meanwhile as soon as I remember to get round to it, will put a proper holding page up which contains something along the lines of "If you're looking for PlanningAlerts in Australia, it's over here". If I've not done that by next week, prod me

**Comment by handelaar** [comment]
Done that. You'll see it imminently or right now depending on the state of your local DNS caches.

**Comment by henare** [comment]
@handelaar Nice one, thank you! [I think I didn't @ you originally because I didn't want to bug you...yet :smile:]

I'll keep this issue open to remind us to do something a bit nicer like the geo-detection.

**Comment by mlandauer** [comment]
I see that there is a link to the australian site on planningalerts.org. So, closing this.
