### ISSUE TITLE
Improve discoverability of JSON version of applications

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1149]
#947 wanted to make it easy to get a JSON version of applications for an authority. #1133 added this so it's now simple to click a link.

However the link is right at the bottom of the page. I knew it was on the page somewhere but even I found it difficult to find. To make it easy to find that there's a JSON representation of an authority's application this should be more visible.

**Comment by mlandauer** [comment]
Not so keen on this anymore. I think separating out the API from the rest of UX is good because they have quite different audiences.
