### ISSUE TITLE
Limit API trial accounts

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1150]
We currently allow anyone to sign up for an API key which more-or-less gives you unlimited use of the API. If you want to use it commercially or in high-volumes we ask you to contact us. We routinely discover commercial or high-volume users that haven't bothered to contact us so we have to go through the whole process of trying to get them to abide by our very reasonable terms.

In other words the onus is currently on us to keep checking that everyone is doing the right thing. We need to turn this on its head a bit. When you sign up for a key you should get 14 days of use (more than enough time to explore) before you need to contact us. If you'd like to keep using it beyond 14 days for low-volume, non-commercial use then we'll remove that restriction. If you want to use it commercially or in high-volumes then we need to come to a commercial arrangement.

When we do this we should make sure it also applies to existing users too - we'll have to email them to tell them about the change.

**Comment by henare** [comment]
We've actually got this documented elsewhere and the plan was a 7 day trial so I obviously don't know what I'm talking about :smile: We also have a bunch of other plans documented there too: https://oaf.slack.com/archives/G032NMVRU/p1479771723000002

**Comment by equivalentideas** [comment]
>  We also have a bunch of other plans documented there too: https://oaf.slack.com/archives/G032NMVRU/p1479771723000002

Those plans also seem to be about reducing the overhead on us to sign up new commercial customers. We're getting a lot of requests over the last few months, so I'd say that's potentially quite valuable work.

**Comment by mlandauer** [comment]
@katska and I have finally decided that this is a priority. It doesn't matter how clear you make it that commercial use is not allowed without an agreement in place people will take advantage. It's very disappointing but unfortunately it's been our experience again and again :(

**Comment by JoannaHill** [comment]
This is a great description of the issue and discussion we are currently having, albeit, many years after the initial issue was created. I want to keep this.

**Comment by JoannaHill** [comment]
Design mockup are in Figma here: https://www.figma.com/design/GEaOuajueHGvfaFPsOUZ9n?node-id=4732-1546#907566862
Looking forward to some feedback.

**Comment by JoannaHill** [comment]
2 week limit has been imposed on all new API trial keys as of last week. Along with API keys now stored in Accounts area.
