### ISSUE TITLE
When an authority receives many comments for an application, make it easier for them to respond all the people who commented

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1152]
Currently when an authority gets loads of comments for a DA, they have to get the email address for each commenter out of the emails they've received in order to provide a response. That can be time consuming if there's hundred of commenters. In this situation, the authority might just not notify people.

City of Sydney decided only to email us, rather than the people who made submissions, because they felt "overloaded" with submissions on a specific DA. This is a bad outcome for people because we're unlikely to start managing this response process for councils—we just don't have the resources to do this manually.

## Possible solution

In the City of Sydney case, we worked with them to come up with a solution. We exported them a list of all the commenters email addresses which they could paste into the BCC field of an email. They're now entering all the addresses into their system to send out the usual correspondence.

Could we automate this with an email after the application closes?

We don't know the close date for lots of applications, so I'm not sure what we'd do in that situation. This needs more thought.

**Comment by mlandauer** [comment]
I haven't come across this happening again. So doing anything feels premature.
