### ISSUE TITLE
API documentation request: clarity around pagination

### ISSUE THREAD

**Issue by charliedotau** [openaustralia/planningalerts#1155]
Hi there,

Its not clear to me in your API doco, how I'm to tell when there aren't more pages of data available for a given reqest.  

In the absence of a specific header, such as `rel`, I figured it would be the HTTP header (e.g non 200 when no more pages); apparently not??    

I'm paging `https://api.planningalerts.org.au/authorities/moreland_city/applications.js?key=XXX&page=200` and I simply get an empty JSON array.    That some URL to page 5 (or 20 or 30) returns real data.

I'm not clear if this behaviour is correct (e.g empty array = no more data) or if this is an error?  Clearer doco I think would avoid this confusion.   

I'm new to paginated APIs so if there are conventions around this that I'm overlooking then apologies.

Thanks
Charlie

**Comment by mlandauer** [comment]
I think this would be addressed by implementing #1528
