### ISSUE TITLE
Allow people to sign up as a PlanningAlerts Backer using PayPal

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1156]
Over the weekend someone who works for a major Australian environmental NGO told me that in their last online fundraising campaign over 50% of donations were made through PayPal. They also told me that apparently over 11million people in Australia have PayPal accounts.

I had no idea it was so ubiquitous. Clearly people want to donate this way, so we should help them help us.

**Comment by kat** [comment]
we have a verified non-profit paypal account FYI.

**Comment by mlandauer** [comment]
We're not taking donations directly through PlanningAlerts anymore
