### ISSUE TITLE
Main delayed job queue is getting backlogged

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1158]
I originally encountered this issue because manually running a scrape for an authority was taking too long. I had loaded an authority and as part of that I wanted to run a scrape to make sure the data came through OK. I clicked _Scrape_ in the backend and waited, and waited. I figured it must have been stuck in the queue behind one or two email batches.

After waiting even longer I decided to check the queue and found 374 jobs waiting (`run_at_time > now()`) in the main delayed job queue! Timeliness of email alerts doesn't really matter but it is a bit worrying. If this is normal then that means we often have a backlog of alerts going out (I recently observed getting 2 alerts in less than 24 hours, which would be a symptom of this).

As a first step it would be good to quantify the problem with some data about the queue size and also to understand what other problems this might be causing.

**Comment by equivalentideas** [comment]
Great work documenting this @henare I noticed that running scrape was really slow but didn't think to check this out!

> As a first step it would be good to quantify the problem with some data about the queue size and also to understand what other problems this might be causing.

Is something like http://graphs.morph.io/dashboard/db/morph what you're imaging or something simpler?

**Comment by henare** [comment]
Thanks @equivalentideas.

>Is something like http://graphs.morph.io/dashboard/db/morph what you're imaging or something simpler?

Whatever helps us understand the size of the problem. I haven't given much thought to what form that would take.

**Comment by henare** [comment]
Had to mention this issue in the documentation about adding a scraper :disappointed: https://github.com/openaustralia/planningalerts/pull/1265/files#diff-04c6e90faac2675aa89e2176d2eec7d8R367

Remove when it's fixed.

**Comment by mlandauer** [comment]
We've now moved over to using sidekiq so we're going to get much better visibility on things (and better throughput). So closing this.
