### ISSUE TITLE
Authority coverage leaderboard

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1159]
A volunteer just mentioned they want to help get full coverage for their state. That's a really cool idea and it made me think that some kind of leaderboard for this would be a great motivator to keep writing scrapers :smile: 

This would probably need #559 first.

[![](https://pbs.twimg.com/media/C4ZSTz5WEAE2l_c.jpg)](https://www.getyarn.io/yarn-clip/3e4385ae-c1db-40b0-bba9-50c2118a3fd9)

**Comment by equivalentideas** [comment]
This reminds me that It's been niggling at me for a while to make the coverage page more useful to volunteers in lots of ways. Maybe this is something that could be part of that, or maybe not ¯\_(ツ)_/¯. Coverage for councillors, is another bit. @hisayohorie’s design principles for our other project seem useful for guiding how we could make that page great https://github.com/openaustralia/australian_local_councillors_popolo#design-principles .

**Comment by mlandauer** [comment]
I think this would be great and it would replace the hacky google spreadsheet that we started all those years ago
