### ISSUE TITLE
Let contributors see what authorities are missing email addresses or councillor information

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1163]
On the authorities page you can see what authorities are possibly broken so you know which ones might need their scraper fixed but you can't tell which ones are missing email addresses (so people can comment to the authority) or councillors (so people can ask their councillors).

**Comment by equivalentideas** [comment]
Would a really dumb first pass of this be just a table per state with the three things, "Scraper working?", "Contact email?", "Councillors?":

![img_5443](https://user-images.githubusercontent.com/1239550/27168649-fe6e8f02-51e9-11e7-923f-666c22a55f76.JPG)

**Comment by henare** [comment]
I think it needs to be more sophisticated than that. The hard thing here is not getting the information but how to display it well. Another thing to watch out for is that this page now has 2 distinct audiences - normal users looking to see if they're covered and contributors checking for things to help out with.

That means we probably want something quite subtle so that normal users don't get distracted by information that's not useful to them but allows contributors to quickly see where and how they can help.
