### ISSUE TITLE
When trying to reset a password on an account that doesn't exist be more helpful and don't leak information

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1165]
Similar to #1164. When you try to reset the password for an account that doesn't exist we currently say:

![selection_002](https://user-images.githubusercontent.com/48945/27161883-9c07902a-51c1-11e7-8432-c4768394022a.png)

That's not very helpful for someone genuinely resetting their password and it also leaks information to someone probing to see if an email already has a PlanningAlerts account.

Instead of that message we should send a helpful email to the person. If they have an account they get the existing password reset email, if not they get an email that helps them sign up for an account.

**Comment by mlandauer** [comment]
I think this is just a simple devise setting to fix this.
