### ISSUE TITLE
Help me see if I made a comment on a specific development application

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1166]
There's no easy way to do this currently, but it seems like an important thing to be able to confirm that you made a comment for accountability reasons.

**Comment by henare** [comment]
>There's no easy way to do this currently...

What's wrong with visiting the application page and finding your comment?

**Comment by equivalentideas** [comment]
> What's wrong with visiting the application page and finding your comment?

I think that would be a good first step, but it might be hard to find the application. It was in the case of the person I was helping. They knew they had commented on a few applications around an area, but couldn't remember which one had the specific issue they wanted to look at. They couldn't remember the street address. I couldn't think of how they could find the application except searching. They thought they made the comment about a year earlier so it was hard to remember specifics.

They could have searched their email for the comment confirmation email to find it—but I didn't think of that at the time.

**Comment by mlandauer** [comment]
I think this would be nicely addressed by having all users register and they make comments and add alerts via their user login. Then they can also have a page showing their alert(s) and all the comments they've made
