### ISSUE TITLE
Track and display somewhere the monthly income we get from PlanningAlerts Backers

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1168]
We should be tracking the most direct results that show how we're going towards goal of increasing income from donations from PlanningAlerts Backers: the amount of income we receive from them over time.

The best way to get this information is probably the stripe API, where we can get information about how much was actually charged each month. Monthly feels like a good pulse as that's how often people are charged.

**Comment by mlandauer** [comment]
I think this part of a bigger question of better tracking of donations across OAF projects. So, closing this.
