### ISSUE TITLE
Add feature flag for the councillor info contribution feature

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1176]
This will allow us to deploy early versions without risking disrupting people using PlanningAlerts.

Extracted from #1160

**Comment by equivalentideas** [comment]
Next steps for this are:

* [ ] @equivalentideas write the integration test to describe what we want
* [ ] @hisayohorie to implement it :)

**Comment by equivalentideas** [comment]
@hisayohorie I've changed the test to show that if the feature flag isn't set, the user gets a 404 response https://github.com/openaustralia/planningalerts/commit/8bfa81541e94eab28788c2b6967f9ed2c1975b06

Make a PR to this branch https://github.com/openaustralia/planningalerts/tree/feature_flag with the implementation.

This feature flag works with an environment variable. That means we can set different values on the staging app and the production app, and also in local development. It's quite a simple and flexible way to add a feature flag.

You'll see in the applications controller that `@councillors` are only assigned if the feature flag `COUNCILLORS_ENABLED` is on (via a method on the authority). There's also a description of how that works in the readme here https://github.com/openaustralia/planningalerts/tree/person_contributes_councillor_info#global-feature-flag

And you can [see the template in the .env file](https://github.com/openaustralia/planningalerts/blob/master/.env#L40).

See how you go with implementing our flag for this :)

**Comment by hisayohorie** [comment]
Fixed in #1184
