### ISSUE TITLE
Councillor info contributor provides their details so the admin can contact them about their contribution and thank them

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1177]
To contact them, we'll need people’s email address. To be able to thank them, recognise their contribution and communicate with them in a nice friendly way, we need their name too.

We should get these details at the end of the process, so they can get straight into adding councillors.

Extracted from https://github.com/openaustralia/planningalerts/issues/1160

**Comment by hisayohorie** [comment]
in relation to #1179 and the design principle, I think the information of the user should be optional. 
Also, for the user contribution flow, I think it is a nicer/less work experience for user if the form of the suggested councillor and their (optional) user info can be submitted all at once with one click(flow 2 in the chart
![user_contribution_flow](https://user-images.githubusercontent.com/12241881/27352991-91890260-55d0-11e7-8700-b55acf0092e2.png)
).

**Comment by hisayohorie** [comment]
So the main issues here are:
1) Does the user information need to be optional or mandatory?
2) Does the submission of data need to be 1 step or 2 steps?

1) Does the user information need to be optional or mandatory?
 mirroring to our principle, I think users need to have control of where and when they give up their information. so I still think it needs to be optional.

For 2), After a bit of research, I started to lean toward for 2 steps submission. 
1 step submission
**pros**
- Less work for users.

**cons**
-  Presenting optional input with mandatory input may send a mixed message

2 steps submission
**pros**
- It is obvious that the user information input is optional by the way it presents itself as a follow-up
- It makes the input more conversational

**cons**
- More work for users

From a bit of research, I am leaning toward 2 steps submissions. It feels to me that there are more pros than cons.
![user_contribution_flow_2](https://user-images.githubusercontent.com/12241881/27399381-8fae5f3e-568a-11e7-8678-8d45cd7c6bfd.png)

**Comment by henare** [comment]
>is this the right direction? @equivalentideas @henare

Hey @hisayohorie, as we've discussed in other channels this is looking good and is all headed in the right direction :+1: 

>Does the submission of data need to be 1 step or 2 steps?

We've all [discussed this a bit in another thread](https://github.com/openaustralia/planningalerts/pull/1186#issuecomment-311117290). I think I might have disrupted things by suggesting we keep it simple on the 1 page for now. Both @hisayohorie and @equivalentideas have said they think 2 step is the way to go so if we want to change this now then I'm up for that.

**Comment by equivalentideas** [comment]
Sounds good to me, what do you recon @hisayohorie ? If you're into it maybe we should change the title of this issue to be "Councillor info contributor provides their details on *a second page after adding councillors* so the admin can contact them about their contribution and thank them".
