### ISSUE TITLE
Add basic styles to the councillor contribution form

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1180]
It currently appears as:

![screen shot 2017-07-27 at 8 14 14 pm](https://user-images.githubusercontent.com/1239550/28665801-3966dd96-7308-11e7-8b1d-8bc5878ca129.png)

Extracted from #1160

**Comment by equivalentideas** [comment]
So I think the basic things to get this into shape for the first pass are:

* [ ] get the heading down to a size that doesn't dominate the form, it should draw attention so people know what the page is about and lead people into the next action.
* [ ] Style the form input elements to match the general app style that works well, bolder labels and clearer inputs.
* [ ] Differentiate the submit form and add a councillor buttons, in both colour and proximity. I think the 'add a councillor' button should align to the left hand side of the inputs so it's a clear line down the form (sitting it the place that the new councillor form will appear). The submit button should be on the right (conventionally signifying progressing through something), and be a bit lower than the form itself. The submit button should be the colour of the submit buttons across the site, the add a councillor button should be grey maybe? or blue?
* [ ] align the form inputs, and the submitted council records horizontally, so that the names and emails of all the councillors submitted line up. This helps you see if there's a typo in the email formatting, and quickly scan up and down the names.

**Comment by equivalentideas** [comment]
I'm mid way through this, working on [branch `councillor_contribution_basic_styles`](https://github.com/openaustralia/planningalerts/tree/councillor_contribution_basic_styles):

![screen shot 2017-07-28 at 6 37 16 pm](https://user-images.githubusercontent.com/1239550/28709509-f235ee64-73c3-11e7-93c9-fed370323bb3.png)

Haven't done anything with the submitted councillors yet:

![screen shot 2017-07-28 at 6 39 47 pm](https://user-images.githubusercontent.com/1239550/28709567-32b7b918-73c4-11e7-82a5-2074c1c598a7.png)

@hisayohorie it would be great to get your thoughts and feedback on this. Going in the right direction?

**Comment by hisayohorie** [comment]
@equivalentideas yes, I think it looks great!

**Comment by equivalentideas** [comment]
> @equivalentideas yes, I think it looks great!

Thanks @hisayohorie I'll continue along that path then 🚠

**Comment by equivalentideas** [comment]
I've done the bits on [the list above](https://github.com/openaustralia/planningalerts/issues/1180#issuecomment-318574099) and a couple of small other bits, I'll open a PR 🖼

**Comment by equivalentideas** [comment]
Closed by https://github.com/openaustralia/planningalerts/pull/1207
