### ISSUE TITLE
jQuery CDN failure fallback doesn't work

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1188]
I just noticed we had a bunch of 404s for the URL `/assets/jquery-1.8.0.min.js` which seems to have come from https://github.com/openaustralia/planningalerts/blob/96409192e7ab20856e0980bf0e11e6e1486d0e48/app/views/layouts/application.html.haml#L30-L34 so I guess that doesn't work (do we even need it?).

**Comment by mlandauer** [comment]
It looks to me like the fallback still works in development but doesn't work in production. Maybe this is because `jquery-1.8.0.min.js` is now in `vendor/assets/javascripts`?
