### ISSUE TITLE
Explain on the 'Get the data' page that we don't filter the data so you can just get alerts about a specific kind of application e.g. daycare centres

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#1190]
In the past OAF took a particular view on not allowing commercial access to the API for purposes that could be considered spammy, ie. in helping allow companies to target types of developments to send unsolicited email to their developers (eg. for the purposes of selling a product or service). 

(background) OAF views on this come from a legal (not allowed in some states, although hard to track that information down when we looked recently-ish) There's a more broadly moral position. We don't want to contribute to people being spammed, regardless of whether it's currently a permitted use of the data.

It would be useful to review, clearly articulate that policy, and display on the "Get the Data" page.

**Comment by equivalentideas** [comment]
> It would be useful to review, clearly articulate that policy, and display on the "Get the Data" page.

I agree. That is our policy as far as I know, but because it's not documented anywhere (that I know of) it's easy to slip by.

I think we could just put something on the page and then if we have a need to change the policy we just do it then, rather than reviewing the policy first.

With that in mind, I'm changing the title of this issue to be about making that change to the page.

**Comment by mlandauer** [comment]
I'm closing this issue in favour of #537 which I think is a more direct way of handling the issue of potentially bad actors using the API. We can't use a technical solution to stop people using the API data in bad ways. For example, we can't stop people from doing their own filtering of the data. So, the best we can do is make our policy on the use of the data clear and explain what the law is in different states. This is what is suggested in #537.

**Comment by mlandauer** [comment]
@jamezpolley please explain why you reopened the issue. Thanks!

**Comment by mlandauer** [comment]
Closing this again
