### ISSUE TITLE
Help people contribute correct councillor email addresses by validating their input

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1198]
We validate people’s email addresses when they sign up for alerts, we can do the same thing to help them contribute good councillor information.

The email field for councillors should not be blank, and should be a valid email address.

Extracted this idea from @hisayohorie comment https://github.com/openaustralia/planningalerts/issues/1182#issuecomment-313275951

**Comment by hisayohorie** [comment]
I'm having a bit of issue here using `validates_email_format_of` gem, which is used for email validation in other models already. 
I have the `validates_email_format_of :email` in suggested controller model, but the validation only works on `councillor_contribution#create`, and contributions with invalid email format still display as suggested councillor list.
This email format is invalid(not following email@address.com format)
<img width="628" alt="screen shot 2017-07-29 at 7 50 31 pm" src="https://user-images.githubusercontent.com/12241881/28749552-2961a178-7499-11e7-830e-d6a3ce6f3503.png">
But still display as suggested councillor list, as it is not yet created
<img width="562" alt="screen shot 2017-07-29 at 7 51 01 pm" src="https://user-images.githubusercontent.com/12241881/28749558-5077dbb0-7499-11e7-8c90-56edf2cc4fb1.png">
And when i finally submit, the validation works
<img width="840" alt="screen shot 2017-07-29 at 8 07 27 pm" src="https://user-images.githubusercontent.com/12241881/28749567-94840aae-7499-11e7-9ee2-d3af4cd155bf.png">

But the validation should work before create to prevent displaying suggested councillor list. 
I'm wondering if this is one of the complication not using #edit and #update method. This is more complicated than I initially thought. any idea? @equivalentideas

**Comment by equivalentideas** [comment]
@hisayohorie good explanation of what's going on 👍 If you've got any existing commits you could push up at "[WIP]" (work in progress) pull request to show how it's working too.

> I'm wondering if this is one of the complication not using #edit and #update method. 

Right you are 👍 Currently the SuggestedCouncillors being displayed aren't being validated, because neither the `.update` or `.create` is being run on them ([ActiveRecord runs `.save` as part of those methods, which includes running validations](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/validations.rb#L36-L38)). In the change we made in https://github.com/openaustralia/planningalerts/pull/1192/files#diff-4e6e47af64933754a3c27c29e4d93ed9R8 each time we hit the `#new` action the SuggestedCouncillor objects for our form are being build again from the params, but not saved to the database until the user is actually ready to submit them all. This is good 👍 

Good reading on when validations are called here http://guides.rubyonrails.org/v4.2/active_record_validations.html#when-does-validation-happen-questionmark

This means we need to check if the records are valid ourselves in the controller, possibly with the `.valid?` method. Good reading on running the validations and accessing the error messages here http://guides.rubyonrails.org/v4.2/active_record_validations.html#valid-questionmark-and-invalid-questionmark .

What’s your thinking on when the best time is for the person entering the information to get the validation messages about councillors they've entered incorrect details for? e.g. I'm entering a councillor and forget the email (it's happened to me before 😸 ), when should I find out?

Is it when they hit 'Another Councillor' or when they try to submit them all? (this is the non-javascript version, with JS later we could validate as they input or something as well as an option).

I hope all that helps!

**Comment by hisayohorie** [comment]
@equivalentideas I am thinking when `Another Councillor` is hit, it should inform the contributor if the format is invalid, and prevent it from displaying. It reminded me that in 2nd iteration we are introducing a review phase for the contributor before submit the contribution, so in that case it might be ok to display invalid format. But since it's not the scope of this iteration, I think it contributor should be informed when hitting `Another councillor`/before display when the format is invalid.

**Comment by equivalentideas** [comment]
> @equivalentideas I am thinking when Another Councillor is hit, it should inform the contributor if the format is invalid, and prevent it from displaying. It reminded me that in 2nd iteration we are introducing a review phase for the contributor before submit the contribution, so in that case it might be ok to display invalid format. But since it's not the scope of this iteration, I think it contributor should be informed when hitting Another councillor/before display when the format is invalid.

@hisayohorie that sounds good to me. I seems helpful to get feedback on your input as soon as possible. Some of the councillor data is across different pages on the council website, so if you had to wait till the end to find out you forgot something, or copied an email wrong, that could be really annoying to have to go find the page again—I expect people would find it easier to get the feedback while they still have the source of the data at hand. 👌

**Comment by equivalentideas** [comment]
Closed by #1206
