### ISSUE TITLE
Help people contribute councillor names in the format we need them

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1199]
We want councillor's names in a specific format:

* full name e.g. "Sarah Liu", not "Sarah"
* capitalised, e.g. "Sarah Liu", not "sarah liu"
* not blank
* and not including titles like "Dr", "Clr", "Ms" etc.
* no spaces around the outside e.g. "Sarah Liu" not " Sarah Liu ".

We could enforce validations that require all this, but I think that might be overkill. I start thinking of corner cases like, 'what if someone only has one name'? 'What if someone prefers their name not all small caps'?

It's hard to what the problems will be without having this deployed so I'm hesitant to say we should have many validations—I think we start with just the basic 'not blank'. We could also do some processing automagically for people, like the capitalisation and the spaces where that's helpful.

For the full name bit, and titles, I think we could do a lot with design here, e.g. make sure the form input field says "Full Name", not just "Name". We could also add some helpful next below the input asking people not to include titles like "Dr" etc—I don't think we should do that until we see people actually add them in their contributions though, because it might be a problem that doesn't actually happen in the wild.

Extracted this idea from @hisayohorie comment https://github.com/openaustralia/planningalerts/issues/1182#issuecomment-313275951

**Comment by equivalentideas** [comment]
I think the only clear wins here at the moment are:

* [ ] making sure the input says "Full Name"
* [ ] making sure people get a helpful message when they enter an invalid councillor with a blank name.

**Comment by equivalentideas** [comment]
That first point "making sure the input says "Full Name"" completed by @hisayohorie in https://github.com/openaustralia/planningalerts/pull/1204 🍁

**Comment by hisayohorie** [comment]
@equivalentideas the current basic validation(`validates :councillor_contribution, :name, :email, presence: true`)  works to not let blank submission go though, and gives "Name cannot be blank" rails build in message. Are we looking for more than that in this issue?

**Comment by equivalentideas** [comment]
@hisayohorie sounds to me like "making sure people get a helpful message when they enter an invalid councillor with a blank name" is covered by that 👍 we could make the message more friendly in the future, but this is successful as a first pass. Once that's merged we'll close this issue.

Can you please add the text "closes #1199" to the description of that Pull Request (you can read about these [GitHub keywords here](https://help.github.com/articles/closing-issues-using-keywords/)) ? That will mean this automagically get closed when it is merged.

**Comment by equivalentideas** [comment]
Closed by #1206
