### ISSUE TITLE
Let admins see just the councillors made in a single contribution and the details of the contributor

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1202]
Currently on the admin page for councillor contributions you just see a big list of all the councillors contributed.

![screen shot 2017-07-28 at 3 41 23 pm](https://user-images.githubusercontent.com/1239550/28704019-434c8bc8-73ab-11e7-82ec-700cdc6207d8.png)

They cant seen which councillors are connected to the latest contribution, or who made the contribution.

The admin reviewing this needs to know:

* which councillors were submitted in which contribution
* when then contribution was made (is it new or old?)
* the contributors details, if they've been submitted

Then they can load them into the spreadsheet and thank the person.

**Comment by hisayohorie** [comment]
@equivalentideas Can I do a bit of user research here?

I managed to make councillor contribution tab, and I'm not sure what is the useful information for you to see in the table.
right now I have this
<img width="1199" alt="screen shot 2017-08-09 at 7 00 14 pm" src="https://user-images.githubusercontent.com/12241881/29147473-39a5e4fa-7d35-11e7-8cae-7830fc880abd.png">

and when you click `view` I have this

<img width="1124" alt="screen shot 2017-08-09 at 7 00 29 pm" src="https://user-images.githubusercontent.com/12241881/29147484-47f67894-7d35-11e7-8792-2b9c0c9207d1.png">

I want to write tests, but not quite sure what I want to see in these pages. From user point of view, what are the useful thing to see in those tables?

**Comment by equivalentideas** [comment]
Great work @hisayohorie that's looking like what I would expect when admining this.

Reading the issue:

> They cant seen which councillors are connected to the latest contribution, or who made the contribution.
> 
> The admin reviewing this needs to know:
> 
> * which councillors were submitted in which contribution
> * when then contribution was made (is it new or old?)
> * the contributors details, if they've been submitted
> 
> Then they can load them into the spreadsheet and thank the person.

I'd say some solutions to enable that are:

* Contributions page shows:
  * contributions sorted with the newest one first.
  * date and time of each contribution, in a human readable format.
  * the name of the authority
  * the name of the contributor
* the single Contribution page shows:
  * the date and time it was submitting in a human readable format.
  * the list of councillors in a table with their names and emails
  * the name and email of the contributor
  * the authority

Looks like you've already got a lot of that in there! Is that what you where after?
