### ISSUE TITLE
I don't know which councillors need to be contributed

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1212]
How do I know which councillors you need for this authority? Do you have the old ones and just need the new ones after an election? or should I enter them all?

![screen shot 2017-08-02 at 2 38 00 pm](https://user-images.githubusercontent.com/1239550/28952016-df801ee0-7911-11e7-9447-11424c86c6ed.png)

I think it would be better to provide some clear direction about this. It also makes the value of the person's contribution more concrete. 'We have 0 councillors for Bayside. Thanks to you, we now have 12.'

Not sure where or how this is best communicated to people.

**Comment by henare** [comment]
I think an easy first pass of this is to pre-populate contribution fields with the data for a council that we already have. 

This makes edits easy because the contributor just makes the edit to the existing list and submits. The admin can just then copy and paste the whole list over what we already have - edit done.

It also signifies to potential contributors what we already have so they don't submit data that's already been gathered.

**Comment by hisayohorie** [comment]
Does it mean a whole array of suggested_councillors are submitted every time? 
In a lot of cases for the existing council information, when there are new councillors, likely there are discontinued councillors. 
When the contributor makes the edit, I think it is unclear for the contributor to know how to replace/update the councillor information when discontinued councillor information is in the form. what do you think @henare @equivalentideas ?

<img width="783" alt="screen shot 2017-08-22 at 2 39 10 pm" src="https://user-images.githubusercontent.com/12241881/29582068-58302494-8749-11e7-9942-635f55cf10a5.png">

**Comment by henare** [comment]
@hisayohorie yeah it probably means you need a way of removing people from the list. I can imagine if I was contributing data I'd just remove and add people until the list looked correct.

**Comment by equivalentideas** [comment]
> This makes edits easy because the contributor just makes the edit to the existing list and submits. The admin can just then copy and paste the whole list over what we already have - edit done.

Is it relevant that we currently need to know the `start_date` and `end_date` of the person's membership of the Council in order to mark them current or not?

Also a note that this solution feels like it's bordering on expanding the scope of our project to include updating councillors where we have some already—which I thought we had set aside.

`</thoughts>`
