### ISSUE TITLE
When adding councillor data and I can't find an email address for one of the councillors, what should I do?

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1213]
We [currently have validations](https://github.com/openaustralia/planningalerts/blob/master/app/models/suggested_councillor.rb#L4) that require the presence of an email address so the person would not be able to submit the form if they come across a councillor that they can't find an email address for.

**Comment by hisayohorie** [comment]
@equivalentideas @henare I want to ask you as admins, do you want to have a contribution of only name/email, not as a set?

**Comment by equivalentideas** [comment]
We're now got some instructions asking people to email us in this situation 
![screen shot 2017-08-24 at 5 00 27 pm](https://user-images.githubusercontent.com/1239550/29653606-e8f0a814-88ed-11e7-820e-d58d7110982b.png)
