### ISSUE TITLE
Contributor's email address not shown to admin

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1218]
So they can thank them :smile:

**Comment by equivalentideas** [comment]
@henare is this referring to when then admin is looking at the page for the contribution?

![screen shot 2017-08-16 at 3 05 08 pm](https://user-images.githubusercontent.com/1239550/29348087-60657880-8294-11e7-928f-9a551f73d293.png)

**Comment by henare** [comment]
@equivalentideas :+1:
