### ISSUE TITLE
Ask contributors to optionally specify a source for their councillor data contributions

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1221]
This allows admins to check the accuracy of a contribution.

**Comment by hisayohorie** [comment]
I imagine the steps for this would be
* adding source url for suggested_councillor table or councillor_contribution table(?)
* creating input form for the source url
* creating a table for source url in admin/councillor_contribution#show

I want your insight here @henare @equivalentideas I'm wondering the source url needs to be

* One source url per contribution: the home page of the council website, such as
https://www.hobartcity.com.au/Home
<img width="791" alt="screen shot 2017-08-17 at 3 03 59 pm" src="https://user-images.githubusercontent.com/12241881/29429173-b62f7b16-835d-11e7-85d5-afb8f065b5b7.png">

* One source url per contribution: the page of the councillors profiles, such as
https://www.hobartcity.com.au/Council/Aldermen/Current-Aldermen
<img width="804" alt="screen shot 2017-08-17 at 3 04 20 pm" src="https://user-images.githubusercontent.com/12241881/29429136-916f52f6-835d-11e7-908a-2e43edd1c2f4.png">

* One source url for each suggested councillors: the individual profile page, such as
https://www.hobartcity.com.au/Council/Aldermen/Current-Aldermen/Lord-Mayor-Alderman-S-L-Sue-Hickey
<img width="665" alt="screen shot 2017-08-17 at 3 08 49 pm" src="https://user-images.githubusercontent.com/12241881/29429264-1282b87e-835e-11e7-9d27-d561411689a9.png">

**Comment by henare** [comment]
@hisayohorie great write up of the process and different options :star2: 

As we discussed I think the simplest solution to try first is a single field per contribution. We could just ask, "where did you find this information? please include a link if possible". This also allows for input we're not expecting, i.e. not a URL, that might be something like, "I found the information in my local newspaper".

I believe this permissive design approach is generally a good idea but especially with ideas like this that are at their early stages and where we can change as we go :ocean:
