### ISSUE TITLE
It's not obvious that you can contribute a whole series of councillors in one go

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1222]
In our testing, the person looked at the page and thought they were meant to submit the councillors one by one. They didn't notice the 'Add another councillor' button or interpret that they could build up a contribution of multiple councillors from it. I think there's a few reasons that could be:

* The title of the page is "Add a new councillor for South Gippsland Shire Council" using the singular, not "Add **new councillors** for South Gippsland Shire Council" using the plural.
* The most prominent button on the page reads "Submit 1 new councillor"
* The add new councillor button is very small and visually pushed back, the text is a bit hard to read.
* There's only a form for adding one councillor.

I'm not sure what combination of changing things and adding new things like instructions etc. are most effective here. But I think two obvious small improvements would be:

* [x] fixing the title ( done in https://github.com/openaustralia/planningalerts/commit/37b3116ecd41fa4faba952c5d5b0498c36d15cbd )
* [x] making the 'Add another councillor' button more prominent.

**Comment by hisayohorie** [comment]
Addressed in #1234 (having instruction on the page)

**Comment by equivalentideas** [comment]
In https://github.com/openaustralia/planningalerts/compare/6314f90d2525...e63e30c7fbb5 I've made the button to add another councillor not so tiny any more and also gave it a little more surrounding white space. This is to help people see this option so they get that they can add multiple councillors in one contribution.

**Comment by equivalentideas** [comment]
I'm gonna try another visual change to this: moving the submit button over to the right, so that there's more white space around the 'add another' button. I think this will also have the helpful effect of separating the vertical process of adding councillors, from the 'next step' bit of submitting them. We'll see ¯\_(ツ)_/¯

**Comment by equivalentideas** [comment]
> I'm gonna try another visual change to this: moving the submit button over to the right, so that there's more white space around the 'add another' button. I think this will also have the helpful effect of separating the vertical process of adding councillors, from the 'next step' bit of submitting them. We'll see ¯_(ツ)_/¯

I've had a crack at this, gonna deploy it and do some guerilla testing to see how it goes:

![screen shot 2017-09-05 at 4 52 41 pm](https://user-images.githubusercontent.com/1239550/30048695-ca3c3a20-925a-11e7-9297-b5b7b23b4741.png)

I feel like the submit button is dominating a bit now, but I do like that it's aligned separately from the list of councillors :)

**Comment by equivalentideas** [comment]
Yay, just tested the form with someone after all these changes and they immediately started using the 'add another councillor' button and found it very clear that they could contribute a whole series of councillors in one go.

I'll close this.
