### ISSUE TITLE
The majority of the councillor contribution page is visual noise that competes with the contribution interface

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1225]
When a person is looking at the interface to contribute councillor information, most of what they see is visual noise that doesn't have anything to do with the task at hand:

![screen shot 2017-08-16 at 5 15 39 pm](https://user-images.githubusercontent.com/1239550/29351627-dcb1f15e-82a6-11e7-88ad-562f1e106307.png)

I think we should remove as much of this as is helpful, possibly just leaving the PlanningAlerts branding so they know they're on the right site. In testing the interface with one of our volunteers I felt that it would have been easier for them if the page was clearer of distractions.

The 1password signup process is a good example of this https://1password.com/choose-type/

![screen shot 2017-08-16 at 5 22 06 pm](https://user-images.githubusercontent.com/1239550/29351782-86edfee2-82a7-11e7-8365-2339639902c6.png)

![screen shot 2017-08-16 at 5 21 58 pm](https://user-images.githubusercontent.com/1239550/29351784-88fb21d8-82a7-11e7-9882-f9d7096a1b77.png)

![screen shot 2017-08-16 at 5 22 28 pm](https://user-images.githubusercontent.com/1239550/29351786-8b02f028-82a7-11e7-91bf-41661cf0278a.png)

**Comment by hisayohorie** [comment]
@equivalentideas as we decided to have light weight instruction on the page, this issue speaks louder now!  https://github.com/openaustralia/planningalerts/pull/1235#issue-252076769 Can I assign this to you?

**Comment by equivalentideas** [comment]
>  Can I assign this to you?

@hisayohorie yep my pleasure :)
