### ISSUE TITLE
Contributor details can be overwritten

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1228]
An attacker can overwrite contributor details. To reproduce:

* Alice submits councillor details
* Attacker Bob visits URL that includes ID of Alice's contribution, e.g. https://www.planningalerts.org.au/contributors/new?councillor_contribution_id=1
* Bob puts his own details on form and submits it

The current behaviour is that Bob's details overwrite Alice's. This should definitely not be possible.

**Comment by hisayohorie** [comment]
Maybe we can add this `has_secure_token` in councillor contribution model? 🤔 

http://blog.bigbinary.com/2016/03/23/has-secure-token-to-generate-unique-random-token-in-rails-5.html

**Comment by henare** [comment]
@hisayohorie :white_check_mark: that's one way. I think @equivalentideas had another idea about putting this all in a flow somehow.

**Comment by equivalentideas** [comment]
>  I think @equivalentideas had another idea about putting this all in a flow somehow.

Here's that https://github.com/openaustralia/planningalerts/issues/1229#issuecomment-325914899 we're looking to have this fixed in https://github.com/openaustralia/planningalerts/pull/1246#pullrequestreview-61088368

**Comment by equivalentideas** [comment]
This is fixed in https://github.com/openaustralia/planningalerts/pull/1246
