### ISSUE TITLE
Admin councillor contribution show page title isn't very helpful

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1231]
The current page title is the timestamp of the contribution. As the admin I don't really need to know this much less have it prominently as the page title.

![selection_003](https://user-images.githubusercontent.com/48945/29443199-bf84928e-8419-11e7-84ec-abffb48fcaa9.png)

The title should describe what the page is about instead.

**Comment by hisayohorie** [comment]
Addressed in #1226

**Comment by equivalentideas** [comment]
> The title should describe what the page is about instead.

With #1226 merged the title now describes what the page is, and includes the authority and the date; two seemingly important details to differentiate between the contributions you might be looking at, and whether it's a new one or an old one.

> ## Councillor Contribution for Marrickville Council, August 02, 2017

That seems a lot more helpful 🎉 Closing this, reopen, or open a new issue if there's more specific changes we want :)
