### ISSUE TITLE
Let me download the csv file of the suggested councillors

### ISSUE THREAD

**Issue by hisayohorie** [openaustralia/planningalerts#1238]
Extracted from https://github.com/openaustralia/planningalerts/pull/1237#issuecomment-325045949

While admin can download the csv file of the suggested councillors, the data should be open for everyone who wants it to download. 

A couple of things to consider: 

* Is it useful for the user to download csv file of individual councillor contribution that is not yet proofread/approved by admin?
* Where in the user flow we can have the link for the csv download?

**Comment by equivalentideas** [comment]
We're not sure that this is useful for people, so @hisayohorie and I have decided to close this for now. Reopen if the need comes up :)
