### ISSUE TITLE
Switch off Ask Your Councillors for NSW councillors until WriteIt has the current Popolo data

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1256]
Due to my mistake of not noticing that WriteIt hadn't pulled in the Popolo source data for NSW councillors before I updating our writeit_id values for councillors https://github.com/openaustralia/planningalerts/issues/1254 — messages to NSW councillors are currently not being sent. They're managed by Active Job, so they will get sent through when the WriteIt accepts the Popolo JSON.

Only one comment is in this stalled situation.

I've disabled "Write To Councillors" for all the NSW councils until this is fixed. I did it in the admin by [sorting the list of authorities by state](https://www.planningalerts.org.au/admin/authorities?order=state_asc) and then editing the setting on each NSW council with the feature enabled.

The councils I've switched off the option for are:

* City of Sydney
* Wollongong City Council
* Lake Macquarie City Council
* Ku-ring-gai Council
* Penrith City Council
* North Sydney Council
* Hornsby Shire Council
* The Hills Shire Council
* Waverley Council
* City of Ryde
* Newcastle City Council
* Bathurst Regional Council

Turn them back on when WriteIt is accepting the 'data source' "https://raw.githubusercontent.com/openaustralia/australian_local_councillors_popolo/master/data/NSW/local_councillor_popolo.json" again.

Also resolve the related error in Honey badger at the same time https://app.honeybadger.io/projects/37075/faults/34621838

This relates to https://github.com/ciudadanointeligente/write-it/issues/1218#issuecomment-333023627

**Comment by jamezpolley** [comment]
Closing this, as we've entirely disabled Ask Your Concillors due to privacy concerns with WriteIt
