### ISSUE TITLE
John Gouldson - Toowoomba Regional Council - is no longer councillor

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1268]
From a user: "Toowoomba regional council: I can advise you that John gouldson is no longer a councillor of the trc.  He did not contest the last local Govt election."

**Comment by LoveMyData** [comment]
Tried to uncheck the '[current](https://www.planningalerts.org.au/admin/councillors/27)' box in PA admin portal then hit save. Unfortunately, it doesn't save the value properly in the backend and councillor remains current.

**Comment by equivalentideas** [comment]
Hey @LoveMyData here's instructions for how to update the councillor data https://github.com/openaustralia/australian_local_councillors_popolo#when-councillors-come-and-go whether they're current or not is based on that repo/source of truth, and shouldn't actually be editable on the planninglalerts side to my memory :)

**Comment by mlandauer** [comment]
We're not showing councillors right now
