### ISSUE TITLE
Double letters being removed

### ISSUE THREAD

**Issue by Janice80** [openaustralia/planningalerts#1272]
Hi There,

I have noticed on the site that when there is a name with double letters one of the letters is removed - for example a search for Woolgoolga shows the location as "Wolgolga" and the road Crabbee as "Crabe".

I have only conducted searches for DAs in the Coffs Harbour LGA so am not sure is this is affecting other locations.

Many thanks if you could have a look at it.

Jan

**Comment by mlandauer** [comment]
Closing this as it's a duplicate of https://github.com/planningalerts-scrapers/coffs_harbour/issues/6
