### ISSUE TITLE
Bad geocoding for Daintree Court, Park ridge QLD 4125

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1274]
https://www.planningalerts.org.au/?q=22+daintree+court+park+ridge+qld

Shows results on Daintree Park Way, Fitzgibbon - 55km away by road

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_diod)

Connected to #1281

**Comment by mlandauer** [comment]
Should be fixed now. See #1281.
