### ISSUE TITLE
Donations database doesn't allow >1 donation from the same address

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1275]
- This system was originally designed to track regular donations
- We don't want someone to end up with multiple concurrent regular donations, so the database requires that the email address be unique, which prevents a second regular donation on the same email address.
- Now that it allows one-offs, this means that it will prevent a person from making a second one-off donation

**Comment by mlandauer** [comment]
We're now not doing donations inside of planningalerts. So, this isn't relevant anymore
