### ISSUE TITLE
Bad geocoding result for 11 Lorikeet Cl, Weston 2326 NSW

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1276]
https://www.planningalerts.org.au/applications/996246?utm_campaign=view-application&utm_medium=email&utm_source=alerts

https://www.google.com.au/maps/search/11+Lorikeet+Cl,+Weston+2326+NSW/

First match is in Woronora Heights in Sydney

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_dmnp)

Connected to #1281

**Comment by mlandauer** [comment]
Should be fixed now. See #1281.
