### ISSUE TITLE
Add "Your Name will be public" closer to the name box

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1277]
The comment form does note that "Your name and comment will be posted publicly above."; but that note is above the comment box, while the name is entered underneath.

I think that expanding the note under the name box (which currently says "Please use your real full name if possible.") to be more specific about the use of the name field would be clearer.

Off the cuff, I'm thinking of something like: "The name entered here will be displayed on the website here and included on the submission to the Planning Authority, who may also publish it as a response to this application. If possible, it's usually best to use your real full name here", and a link similar to the existing "Why do you need my full address?" link (https://www.planningalerts.org.au/faq#address)

I'm wondering whether it might even be worth having two boxes here: one for "Name to display on website" and another for "Full name (sent to council, not displayed here)". I'm not sure how useful that would be though, if the submission to the council ends up getting published with the full name anyway.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_e69h)

**Comment by jamezpolley** [comment]
Further comment from the user who suggested this:

> I think in terms of improving the system there should be a note on the online form that asks you if you want your full name appearing online,  or, perhaps a seperate box to insert a screen name - so that it is clearer that an identity will be shown online. 
> This is the norm for newspaper comments. 

However, I'm not sure how useful this would be. Some councils will reject comments if they can't link the name to one of their constituents; so we'd probably still need to ask for the real name and supply that to council. Many councils publish responses online, so even if we don't display it, it's likely to end up online somewhere anyway.

**Comment by katska** [comment]
Agreed that in the future it could be good to have real name and display name, with text along the lines you discuss. 

I suggest a first step could be to change one piece of text to make the messages really clear. Moving "your name will be publicly displayed here" to the text under the name field could help.
Currently this information is separated from the name field by the text comment. Filling out the comment is the big piece of work they're doing and may not remember the previous information by the time they go to add their personal details or see it onscreen at that moment.

![Screen Shot 2019-11-12 at 11 30 25 pm](https://user-images.githubusercontent.com/1001129/69390873-bc721c00-0c85-11ea-8b64-1a48c97f5161.png)

It would also be consistent with the guidance shown below the following text fields, which make it clear that we well never display email details.

![Screen Shot 2019-11-12 at 11 30 14 pm](https://user-images.githubusercontent.com/1001129/69390872-bc721c00-0c85-11ea-8451-3f6e7bb6b080.png)

**Comment by katska** [comment]
This is a short term fix

**Comment by mlandauer** [comment]
I agree that putting information about how the name is used next to the name field much increases the chances that someone reads it. This is a simple change but could make a difference.
