### ISSUE TITLE
Bad geocoding for 20 Hughes Ave, Harrington Park 2567 NSW

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1279]
Maps web interface today returns the harrington park area; but the map on the site shows an address in Rydalmere

[Alert](https://www.planningalerts.org.au/applications/1039981)

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ebwl)

Connected to #1281

**Comment by mlandauer** [comment]
Should be fixed. See #1281.
