### ISSUE TITLE
Problems with Google Geocoding handling of new developments

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1281]
In cases where there's a new development, with planned new streets that don't yet exist, our current Geocoding implementation often gives results that aren't useful.

As an example, https://www.planningalerts.org.au/applications/1055843 - the address that's being used here seems to be the Apple store in Rundle Mall.

A better location would have been to match on the suburb of Virginia: 

https://www.google.com.au/maps/place/Virginia+SA+5120/@-34.6699155,138.5333328,13z

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_elx9)

Updating this description to include a list of test addresses:

- [ ]  1 Wickham Street Marsden Park NSW 2765
   - Google puts this in Newcastle instead of Marsden Park
- [ ] 7 Bradfield Street Flagstone QLD 4280
  - Google puts this somewhere else in brisbane. Mappify/OSM can't find the address at all.
- [ ] 21 Beck Street Park Ridge QLD 4125
  - Google puts this at 21 Beck St Paddington :/
- [ ] 8 Bennelong Cres Lloyd NSW 2650
  - Google puts this in 2614 (Macquarie ACT) instead of 2650
- [ ] 16 Hilltop Gr, Cliftleigh 2321 NSW
  - Google puts this in 2430
- [ ] 17 Isabella Close, Narara NSW 2250
- [ ] 41 Foxall Street Riverstone NSW 2765
- [ ] 29 Larkin Street Marsden Park NSW 2765

**Comment by andrewharvey** [comment]
Hah that's interesting, Google Maps fails to find that address, but it is in GNAF http://results.openaddresses.io/sources/au/countrywide and other Geocoding API providers which use GNAF should be able to locate it.

![google](https://user-images.githubusercontent.com/117278/46017748-930a3e80-c11b-11e8-9ad9-e10143ea2373.png)

For example the [Mapbox Geocoder](https://www.mapbox.com/geocoding/) can find [12 Apple Close Virginia SA 5120](https://www.mapbox.com/search-playground/#{%22url%22:%22%22,%22index%22:%22mapbox.places%22,%22staging%22:false,%22onCountry%22:true,%22onType%22:true,%22onProximity%22:true,%22onBBOX%22:true,%22onLimit%22:true,%22onLanguage%22:true,%22countries%22:[{%22name%22:%22Australia%22,%22code%22:%22au%22}],%22proximity%22:%22%22,%22typeToggle%22:{%22country%22:false,%22region%22:false,%22district%22:false,%22postcode%22:false,%22locality%22:false,%22place%22:false,%22neighborhood%22:false,%22address%22:false,%22poi%22:false},%22types%22:[],%22bbox%22:%22%22,%22limit%22:%22%22,%22autocomplete%22:true,%22languages%22:[],%22languageStrict%22:false,%22onDebug%22:false,%22selectedLayer%22:%22%22,%22debugClick%22:{},%22query%22:%2212,%20Apple%20Close,%20Virginia%20SA%205120%22}
)

![mapbox](https://user-images.githubusercontent.com/117278/46017861-d795da00-c11b-11e8-96ef-66e27c059708.png)

Have you considered moving to another Geocoding service?

**Comment by jamezpolley** [comment]
Another example:

https://www.planningalerts.org.au/applications/1011072?utm_campaign=view-application&utm_medium=email&utm_source=alerts

https://www.google.com.au/maps/search/26+Daintree+Court+Park+Ridge+QLD+4125/@-27.8777813,152.9920807,11.25z

Second result gets the right suburb at least...

Mapbox and OpenAddresses.io (using GNAF) can find the address. Google can't.

**Comment by jamezpolley** [comment]
https://www.planningalerts.org.au/applications/1109991
10 Hilltop Gr, Cliftleigh 2321 NSW

Geocoding is showing this at Hilltop Grove, 2430 - a 165km drive away. https://www.google.com/maps/dir/Cliftleigh,+New+South+Wales+2321/Hilltop+Grove,+Tallwoods+Village+NSW+2430/@-32.4408397,151.4422309,9z/

**Comment by mlandauer** [comment]
Demonstrated that it's fixed by 27bd5212dae8890a4089e513a696d069f8522eb0
