### ISSUE TITLE
PA back end not collecting morph data for Alexandrina Council, South Australia

### ISSUE THREAD

**Issue by LoveMyData** [openaustralia/planningalerts#1282]
Alexandrina Council

https://www.planningalerts.org.au/admin/authorities/262 and source data from https://morph.io/planningalerts-scrapers/alexandrina_council_sa_development_applications

PA admin console is reporting
```
0 new applications found for Alexandrina Council, SA with date from 2018-09-06 to 2018-09-20
```

However, in morph, there are 1341 records, some are between the date range mentioned.

**Comment by LoveMyData** [comment]
Looks like some records are slowly rolling in, but nothing before 6-Sep.

Maybe add the ability to reset the initial date. So it will download records scraped before 6-Sep.

**Comment by mlandauer** [comment]
Everything is going through the planning SA portal for SA now
