### ISSUE TITLE
Email Authorities with failed Scrapers

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/planningalerts#1286]
Start emailing some of the Authorities who have bad scrapers to see if they have an API or ATDIS that we could use.

**Comment by katska** [comment]
Would a first step to be seeing why they are failing and log them as issues in [Github PA scrapers](https://github.com/planningalerts-scrapers/)?

**Comment by mlandauer** [comment]
The experience so far has been that councils have very little in the way of any expertise to answer our questions or fix any problems. We've made little progress for relatively large amount of effort in the past by dealing with councils directly. So, I'm closing this issue.
