### ISSUE TITLE
update port stephens council contact email

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1287]
Change contact email address contact for Port Stephens Council, which has changed.

**Comment by katska** [comment]
This is odd because the address they currently list on their website https://www.portstephens.nsw.gov.au/grow/development-applications/development-application-process is the same one we have listed for them.

**Comment by katska** [comment]
I've written to Port Stephens Council to ask them about this. The mail hasn't bounced yet.

Also, some mail is certainly getting through from planningalerts.org.au, as new comment has been lodged only a day ago https://www.planningalerts.org.au/authorities/port_stephens/comments

**Comment by benrfairless** [comment]
@kat I was going to have a look for this in the back-end, but I think emails for planning alerts are sent via cuttlefish, is that right?

**Comment by mlandauer** [comment]
Looks like this isn't an issue. So, closing this.
