### ISSUE TITLE
Experiment outsourcing the fixing of two broken scrapers to something like freelancer.com

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1289]
This is something we've talked about trying but have never followed through on. 
The task of fixing a broken scraper (or even potentially writing a new one) is something that is relatively well contained, easily testable and a significant burden to our developers and volunteers.

So, let's do an experiment and outsource two or three broken scrapers to two or three separate people and see how it works.

Some questions to answer for us to evaluate how effective this approach is:
* Is it good value for money?
* Does it actually save us time? (What is the time required to manage the process versus actually doing the work?)
* What is the quality of work like?
* How long does it take to get fixed?

**Comment by jamezpolley** [comment]
I wonder if https://github.com/planningalerts-scrapers/gold_coast/issues/3 would be a good candidate for this; it's been broken for quite a while and it seems like it's a fair amount of work to get going. Perhaps that makes it a bad candidate?

**Comment by mlandauer** [comment]
Thanks @jamezpolley. I think if it's broken and for a large council that makes it a good candidate even if it's a fair amount of work. More generally, I think there should be an easy way to look at all the broken scrapers ordered by population. Then we can target ones based on population. I don't know why we haven't done this obvious thing before. I'll create some tickets for this.

**Comment by mlandauer** [comment]
These new issues are #1311 and #1312

**Comment by mlandauer** [comment]
@jamezpolley and sure enough if you look at https://www.planningalerts.org.au/authorities?order=population the gold coast scraper comes out on top as the most important to fix

**Comment by mlandauer** [comment]
@jamezpolley after a little more consideration I think the gold coast scraper might not be such a good choice after all. This is because it's basically writing a new scraper from scratch. I think it's safer to start this experiment by getting some people to fix scrapers as this is a simpler task and is likely to result in maintenance issues for us if it's not done particularly well.

**Comment by mlandauer** [comment]
I think this is less pertinent just at the moment because we have a fair number of fairly complex scrapers that can scrape multiple authorities. So, this approach is less well suited to that situation
