### ISSUE TITLE
Investigate possible memory leak

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1295]
Monitoring graphs show memory usage slowly creeping up over time. We also recently had a period where performance degraded across the course of ~6 weeks, while memory usage climbed, until the box ran out of memory and everything was restarted. That fixed performance and also memory usage dropped dramatically.

![screenshot from 2018-10-31 14-46-03](https://user-images.githubusercontent.com/216918/47764977-e6277080-dd1b-11e8-80bd-def0ad6b9d19.png)

**Comment by mlandauer** [comment]
Looking at the memory since the beginning of December 2018 to now (end of January 2019) I'm seeing a pretty stable memory usage at around 70%. So I don't think we have a memory leak. So, closing this.
