### ISSUE TITLE
Clarify public/private information when making a comment

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1298]
There has been a long-standing issue that some people don't see that their name will be published. There have been several attempts to improve this some of which have made things better but there are still occasional problems.

It dawned on me this morning that we could split the comment form into two sections with different headings:
"Publically shown on this site"
"Not shown and sent to the council"

To try to make this even more clear. That would mean that the explanation of the comment and name being public would not have to be hidden at the end of a paragraph.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_iyr1)

**Comment by jamezpolley** [comment]
* When people choose the option to send to a councillor, their information also gets published on write-it, and as per #1361 there doesn't seem to be (at present) any way for us to take that down. I feel that we should add a warning about that.

* Councils want to have a name that they can verify is a resident; but for the purposes of civil discussion on our site, a partial name or pseudonym would probably be suitable. Could we have two name fields - one for Council purposes and one for display purposes?

* We should probably make it clear that councils may choose to publish responses, including the address and full name details, elsewhere.

**Comment by jamezpolley** [comment]
This section from #1277 seems relevant here:

> Off the cuff, I'm thinking of something like: "The name entered here will be displayed on the website here and included on the submission to the Planning Authority, who may also publish it as a response to this application. If possible, it's usually best to use your real full name here", and a link similar to the existing "Why do you need my full address?" link (https://www.planningalerts.org.au/faq#address)
> 
> I'm wondering whether it might even be worth having two boxes here: one for "Name to display on website" and another for "Full name (sent to council, not displayed here)". I'm not sure how useful that would be though, if the submission to the council ends up getting published with the full name anyway.

It seems like it would be easy to change the email template we send to councils to include a note saying that the commenter has provided their full name solely for the purpose of council being able to verify their identity; but they request that only the display name be published. 

Perhaps a small "Extra comments for council" box to allow the commenter to say "I don't wish my full name to be published; please contact me on 1234 5678 for more details" would help?

**Comment by jamezpolley** [comment]
#922 and #923 seem relevant here as well.

I think that this comment form is trying to achieve three things:

1. We want to make it easy for people to have their say about planning decisions in their neighborhood
2. We want to encourage a continuous civil discourse about the future of neighborhoods. We want people to think of DAs as part of an ongoing community-wide discussion rather than as a propose/object cycle.
3. We want to help people making comments to have those comments be considered by the planning authority.

We ask for the real name and address because of (3), but it's not required for (2). It's certainly a good default setting for (2) but I'd like to see us accomodate the cases where it's not practical for a person's full name to be part of the public record.

An abuse policy would seem to be targeted at (2), but I think that broadening it a little would help with (3) as well: a comment that is focused on the development in question and fact-based and clear should be easier for the Authority to take into consideration than one that is focused on irrelevant issues. If we can encourage comments that say "I do/don't like the idea of this development in my area because I think it harms/helps issue X", that's both less abusive and also more helpful than a comment saying "PERSON X WHO SUPPORTS THIS PROPOSAL IS SCUM" or "THE DEVELOPERS STOLE MY BIRTHDAY CAKE!"

**Comment by mlandauer** [comment]
The overriding experience of designing and iterating on this comment form is that people don't read explanatory text anywhere as much as you would expect. So, any design change has to be very careful not to load more words on to the page.

Also, we're trying to keep a potentially complex process as simple as possible. Some of that simplicity comes from us designing a sensible path (based on a detailed knowledge of how everything actually works), designing for that path, and hiding the complexity away. For instance, we hide as much as possible about the differences between what we do and what the council does because frankly it's bloody complicated and it would be put anyone off.

As a user if I'm faced with a form field asking for my name and I understand that name will be displayed on planningalerts and sent off to the council then I can make an assesment of the risk of doing that.

If I'm presented with two places to put my name and each has it's own rules on how they're dealt with I think the chances of me understanding correctly what's happening are pretty small, and so the chances of me doing a correct risk assessment for myself are small. Furthermore the idea of a "display name" is not one that is common to most people.

**Comment by jamezpolley** [comment]
> The overriding experience of designing and iterating on this comment form is that people don't read explanatory text anywhere as much as you would expect. 

I agree with all of this. Sensible path and sensible prompts are better than lots of words.

All the other things that I've mentioned already have other issues tracking them; if we happen to be able to close two issues at once that would be great, but none of them are required for closing this ticket. I'm happy to leave them for later.

**Comment by jamezpolley** [comment]
A relevant comment that just came from a concerned person:

> I made comment on a planning alert that appeared on your site and you have forwarded to council with my details. They have published this on PDonline ipswich with all my contact details.
> 
> Your site mentions my address and phone number is so council can contact me and know I am from the area not so they can publish private information. What is going on?

**Comment by mlandauer** [comment]
@jamezpolley that experience for the user sure does suck and feel like a break of trust. I've made a suggestion that we clearly direct council on how we expect private information to be handled - https://github.com/openaustralia/planningalerts/issues/1378. 

This idea is based on a similar idea you've mentioned above but rather than giving users an extra optional field to fill out we do the sensible thing and direct councils to respect the privacy of their users.

**Comment by jamezpolley** [comment]
> rather than giving users an extra optional field to fill out we do the sensible thing and direct councils to respect the privacy of their users.

Agree about not adding the optional field. Could we update our wording so that instead of just saying that we send it to the council, we also say something about the council possibly publishing details?

**Comment by mlandauer** [comment]
Closing this in favour of #1378
