### ISSUE TITLE
QLD Incorrect Address

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/planningalerts#1300]
Someone has received an alert for 23 Beck St, Park Ridge QLD 4125 however they advise that the address is actually Paddington not Park Ridge.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_h3p9)

Connected to #1281

**Comment by mlandauer** [comment]
This problem should hopefully not reoccur now. See #1281.
