### ISSUE TITLE
New Scraper Request - Town of Cambridge

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/planningalerts#1301]
We have received a request to cover the Town of Camrbidge on PlanningAlerts:

Link to Applications: http://www.cambridge.wa.gov.au/Develop-Build/Planning/Advertised-Planning-Applications

I would like to try creating this myself but I can't find any useful information on how to create a scraper.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_h3pp)

**Comment by mlandauer** [comment]
@benrfairless is https://www.planningalerts.org.au/how_to_write_a_scraper any use?

**Comment by mlandauer** [comment]
We also have relatively few scrapers in WA so this would make a great addition. Also looking at the page https://www.cambridge.wa.gov.au/Develop-Build/Planning/Advertised-Planning-Applications it looks like a relatively straightforward custom scraper
