### ISSUE TITLE
Limit geocoding results to within council boundaries

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1307]
We're currently having lots of problems with the google geocoder since the end of 2017 when they made a major update which made the geocoder a *lot less* reliable when the addresses are ambiguous or unknown. In quite a few cases we're getting results in a completely different state than the given address (thanks!) for example. This is obviously a super bad thing and causes quite a few problems for users where they receive alerts for DAs happening 1000km away. Yup, I know. This clearly lowers trust in the service as a whole and is generally a bad thing. So, let's fix this by collecting bounding box information for each council and prioritising and limiting results to within those bounding boxes. That should make things a lot better

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_icgt)

**Comment by jamezpolley** [comment]
A simple way to do this might be to make a change at https://github.com/openaustralia/planningalerts/blob/1f4585cd3e86fda80896960d16079ae7a84aedc2/app/models/application.rb#L153 to pass along the postcode

https://google-developers.appspot.com/maps/documentation/utils/geocoder/#q%3D16%2520Hilltop%2520Gr%252C%2520Cliftleigh%25202321%2520NSW%26in_country%3DAU%26in_postal_code%3D2321 isn't entirely correct, but at least it's in the right area. https://google-developers.appspot.com/maps/documentation/utils/geocoder/#q%3D16%2520Hilltop%2520Gr%252C%2520Cliftleigh%25202321%2520NSW%26in_country%3DAU (same lookup but without the postcode) is way off base.

So if we simply pass along the postcode, we probably don't need to worry about finding the bounds for each Authority.

.... this is making the assumption, of course, that we *have* a postcode; which is probably true for things we've pulled off a council's website but may not be true if we're taking user input from the search box.

**Comment by mlandauer** [comment]
@jamezpolley I'm pretty sure we can't depend on the postcode being there. From memory many councils just list their DAs by suburb name. I think it would be tricky to go down the road of trying to extract structured data from the address. It feels better to lean completely on the geocoder to do that bit of magic.

**Comment by mlandauer** [comment]
The current stop-gap approach we're taking is to look at the result of the google geocode and see whether it's a "partial match" which is as far as I've seen always the case when the result is in completely the wrong area. So, by ignoring these results (and just failing to geocode these applications) we shouldn't see the problem anymore and the approach outlined in this issue shouldn't be necessary. So, closing this.
