### ISSUE TITLE
Modify schema to allow versioning of application information

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1317]
At present, once we've scraped an Application we never update its details.

It should be relatively simple to add a "version_number" or suchlike field to the application in a way that would allow us to add a new updated version later on.

This would allow for us to do things like: 

 - Update an application when the details change on a council website, and still have version history
- Update bad geocoding, and still have version history to show the old details in case people wonder why they got an alert
- Update an application with the outcome (approved/rejected)

It would also allow us to go back and correct applications with incorrect data from issues such as planningalerts-scrapers/coffs_harbour/issues/6

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_icl9)

**Comment by jamezpolley** [comment]
Connects to #653 
Connects to #557

**Comment by mlandauer** [comment]
It looks like it's time to bite the bullet and start thinking about implementing this. It would lay the foundations for being able to update applications with whether they've been approved or not which is something that is of very obvious value to users and to the users of the API.
