### ISSUE TITLE
Create multiple API keys for better tracking of where hits come from

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1323]
Currently, we can see that we have lots of hits on the Static Street View API

It's not clear if this is coming from page views, from emails, crom OpenGraph metadata etc.

Google's console only has limited methods for splitting out the traffic; and the only one we can control is API key. 

- [ ] One way for us to learn more would be for us to bounce streetview URLs through our servers (as suggested as one item on #1320); another way might be for us to use different API keys for different purposes - one for signing URLs to put in email alerts, another for opengraph metadata, another for use inside noscript tags.

- [ ] Bouncing through our own servers would probably give us better metrics though.

Depends on #1327 
Depends on openaustralia/infrastructure/pull/119

**Comment by mlandauer** [comment]
I think using different api keys (as in #1327) is a good solution for now. So, closing this as fixed.
