### ISSUE TITLE
Add links direct to headings on FAQ pages

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1324]
I'd like to send someone a link that takes them direct to the "I'm a programmer and want to help" heading. This is trivial, as the header has an ID: https://www.planningalerts.org.au/getinvolved#hacker goes right there. But there's no link on the page, so I have to inspect the source to find the header and construct the link by hand.

A simple little permalink glyph that appears to the left of the header on hover, or a "link to this answer" link at the bottom of the answer, would make this much easier.

**Comment by mlandauer** [comment]
Won't fix. See #1527
