### ISSUE TITLE
Change ID for "hacker" faq

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1325]
Relates to #1324 

I'm talking to a non-programmer and I want to tell them "If you know someone who can write some code, have them take a look at https://www.planningalerts.org.au/getinvolved#hacker to find out how they can help us out"

But "hacker" is a word that is misunderstood by non-hackers. So I'd really like that to not be in the link I'm going to non-hackers. "developer" or "coder" or "programmer" would be a better choice.

**Comment by mlandauer** [comment]
Won't fix. See #1527
