### ISSUE TITLE
Align concepts of user and alert subscriber in database

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1338]
We used to have an alert subscriber table but I removed it because it wasn't being used for anything.

I just realised that it would be better instead to use the users table to store alert email addresses. This way we would automatically create a user in the system when a new person creates an alert and we would have a way to tie multiple alerts to the same person and we would also potentially allow people to manage their alerts via an account that they login to using an email and password combination (which is more conventional than how we do things currently).

Also currently we use email and password accounts for people using the api but somewhat confusingly this is not at all tied to an email address that they use for alerts.

We could more simply create features:
* Manage your alerts by logging in with username and password
* Manage all your alerts in one place
* Unsubscribe from all alerts at once
* Send all alerts for the same email at the same time of day (rather than randomly spread throughout the day)
* Or create a digest email with all alerts in one place
* Change your email address for alerts (currently this is done by unsubscribing and resubscribing for alerts)
* Create new alerts without having to reconfirm your email address

We could also tie comments back to users in the same way - that would allow us to do many of the same things.

The nice thing about this approach is that we can phase it in gradually in terms of how it affects users. Initially it won't look any different but over time will give users more control and visibility on things. 
*

**Comment by mlandauer** [comment]
This is important one and one the cards for working in the next few months

**Comment by mlandauer** [comment]
Extracted another issue which covers the more general case: #1530

**Comment by katska** [comment]
@mlandauer reopening because I really think we want this!

**Comment by mlandauer** [comment]
This has now been done
