### ISSUE TITLE
Add privacy protecting share count for non tracking social share buttons

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1344]
In #1316 we're replacing the default twitter and facebook share buttons by simple links that do not send any information to twitter or facebook unless the user actively shares on one of those platforms.

However, this does not show how often the page was shared on facebook which the default button shows.

The facebook graph api provides functionality to get the share counts. This is implemented on theyvoteforyou in https://github.com/openaustralia/publicwhip/blob/master/app/assets/javascripts/shareCount.js. However, there is a significant problem with that implementation. So, we don't want to copy it as is. If we use javascript to call the facebook graph api we're still sending a web request to facebook and it's possible that they use this track users. In fact Firefox, with content blocking enabled, will block this request anyway.

What would be better is if the server proxies requests to the share count api for the client. That why the server effectively anonymizes the data so facebook can't figure out who made the call. There could be issues with quotas and authorisation so this might not be trivial so we'll see.

**Comment by mlandauer** [comment]
This would help with engagement without telling facebook and/or twitter everything. So I do think it would be good to do at some stage.

**Comment by katska** [comment]
Only missed this one last week because flooding broke the local internet and phone services. Reopening.
