### ISSUE TITLE
Enhance https://www.planningalerts.org.au/geocode_queries/ to rerun geocoding

### ISSUE THREAD

**Issue by softgrow** [openaustralia/planningalerts#1346]
https://www.planningalerts.org.au/geocode_queries/ displays a list of geocoding queries giving the results and discrepancy between geocoding providers.

When resolving an issue with geocoding, it would be useful to be able to rerun the query to confirm end-to-end that a change made by the geocoding provider has actually resolved the issue.

An example of use, Go to https://www.planningalerts.org.au/geocode_queries/2871 and then the enhancement would allow you to rerun the query. This could be done by a button "Rerun this query" on this page. Alternatively provide a form where a query could be typed in and the results displayed.

Raised as a result of Issue #1345 (now resolved)

**Comment by jamezpolley** [comment]
Currently this is problematic because we have never wanted to update the records for a DA. However, one of the benefits of #1317 (currently in progress) is that we'll be able to do this.

**Comment by mlandauer** [comment]
I really want to avoid any kind of manual intervention on geocoding problems. The point of showing issues with the geocoding was to use that as a clue to a better general approach
