### ISSUE TITLE
Remove content from WriteIt

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1361]
We've had someone ask us to remove their comment from PA as it had too much private information in, as they hadn't realised it was going to be published on the site. Google had cached this data and it was putting them at risk.

We've removed this from PA; but the data is still on WriteIt and still coming up in Google searches there. Can we have it taken down from there?

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_livp)

**Comment by jamezpolley** [comment]
Going forward, #1298 would probably help minimise the chance of similar things happening in future.

**Comment by mlandauer** [comment]
@jamezpolley I'm not aware of whether it's possible to easily do this. We should probably just ask, right?

**Comment by mlandauer** [comment]
See above. I've posted a question to the writeit developers.

**Comment by jamezpolley** [comment]
We've made contact with Jordi from FCI who has taken these posts down for us.
