### ISSUE TITLE
When streetview is turned off, add a call-to-action for donations

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1363]
In #1330 we added the ability to turn off Streetview in the web UI and in emails due to Google reducing the amount they're willing to give us as a grant.

When streetview is turned off, we might have an opportunity for a call to action, asking for donations so that we can keep Streetview on all the time.

**Comment by mlandauer** [comment]
I don't think asking for money to pay directly to Google makes sense. Paying the electricity bill is not what gets people interested in the work we do. I think we motivate people to donate by highlighting the many ways in which we do unique and valuable work. So, closing this issue as a "won't fix"
