### ISSUE TITLE
InnerWest Council scrapers - ignore until details are added

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1365]
The Inner West Council site has a "Status" field for applications. If the status shows "Status: Lodgement", this DA is essentially blank - it's got an address and it's been assigned a number, but that's about all.

Scraping this and alerting people to it isn't a great experience: if they click the link, they see no details and think the site is broken.

If we ignore the DA until it gets to "Status: Public Notification", the DA now has enough detail for people to understand what's happening and to make meaningful comments on the application.

This applies to all the Inner West scrapers: Leichardt, Ashfield, and Marrickville.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_m1t1)

**Comment by mlandauer** [comment]
I'm going to look at this issue now that we have some of the versioning infrastructure in place. The versioning might not even be relevant... let's see.

**Comment by mlandauer** [comment]
Inner West council needs an entirely new scraper. See https://github.com/planningalerts-scrapers/issues/issues/10. So, this issue is relevant anymore.
