### ISSUE TITLE
Consider only alerting on an application once it has sufficient detail online

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1368]
We've received feedback from multiple directions all approaching this from different angles. 

planningalerts-scrapers/yarra/issues/5 is one particular example: in this case, the DA was opened - and a planning nubmer was allocated and listed on the Authority's site, and we scraped it and sent out email alerts about it - in December 2018.

However, it's only on the 4th April 2019 that the application got to the "Advertised" stage. Before this date, there was no information online for people to read, beyond the application number, address, and a very very brief description.

This is a bad experience for:

- Local residents. They got alerted in December 2018 to the fact that something was happening, but there wasn't enough detail for them to know what was happening.
 - The council. They may have been receiving feedback about this as early as December 2018. Some of this feedback would have been assuming that the website is broken, which is frustrating for council staff. All of the feedback would have been based on insufficient information, because the informatoin about the DA just wasn't available.
 - Local residents, again, because as of the 4th April this application is now ready for review, but we aren't telling them about it.

#1365 is another related issue we've opened in the past, where the same problem was showing up on a different council's site.

At a minimum, the action I'd like to see from this issue is a decision - and documentation about the decision - stating that we do prefer to only alert about applications once sufficient information is available for people to be able to make an informed response.

Once #1317 is fully implemented, this might perhaps mean that we scrape an application as soon as it's on the site, but we don't send email alerts until there's enough information for people to respond to. 

Or perhaps it means we send an email alert as soon as we see the application, but flag it as being an early alert. We could send another alert once we see more detail, or we could give people the option to "subscribe" to a particular DA and be notified of all changes to it.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_mdnh)

**Comment by jamezpolley** [comment]
I'll note that https://github.com/openaustralia/planningalerts/issues/1317 has been completed for quite a while now.

It's not perfect, as we don't always get the information we'd need for this. But we do have interest from both the public (who want to be alerted about an application once it's got sufficient information, or when it's available for comment) and from potential commercial interests, so this might be worth looking into

**Comment by mlandauer** [comment]
It's not great that a council is putting applications into their system and making them public when the information there is not close to complete. I'm pretty sure there is not a generic solution that we're going to be able to come up with that will deal with the messy reality of how different councils do things. So, any workaround really needs to happen at the level of the scraper. If, for instance the scraper knows the data isn't useful yet it should skip over that particular application.
