### ISSUE TITLE
RSS feeds for address queries broken

### ISSUE THREAD

**Issue by drzax** [openaustralia/planningalerts#1369]
[For example](https://www.planningalerts.org.au/applications.rss?address=114+Grey+St%2C+South+Brisbane+QLD+4101&radius=2000.0) from this [address query page](https://www.planningalerts.org.au/?q=114+Grey+Street%2C+South+Brisbane+QLD)

![image](https://user-images.githubusercontent.com/596563/56334791-2b156580-61dd-11e9-9a91-c88fd6b0cb59.png)

**Comment by mlandauer** [comment]
That's because to do that query you'll need an API key. See https://www.planningalerts.org.au/api/howto
