### ISSUE TITLE
Get php planningalerts scrapers working again after morph platform update

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1371]
Now that we can set the platform type on morph we should get the php scrapers working again. I'm assuming it should just be a simple switch, right?

This should be a simple fix with a big win - approximately 10 (?) scrapers working again.

**Comment by mlandauer** [comment]
@jamezpolley would you mind picking this up as you did the work on the morph platform change? It would be a very good test of the changes

**Comment by mlandauer** [comment]
Here's a list of the php scrapers currently broken with "Failed to download minimal PHP for bootstrapping.":
- [ ]  https://morph.io/planningalerts-scrapers/kingston
- [ ]  https://morph.io/planningalerts-scrapers/townsville
- [ ]  https://morph.io/planningalerts-scrapers/tweed-shire
- [ ]  https://morph.io/planningalerts-scrapers/albury
- [ ]  https://morph.io/planningalerts-scrapers/griffith
- [ ]  https://morph.io/planningalerts-scrapers/KingboroughCouncil
- [ ]  https://morph.io/planningalerts-scrapers/cessnock
- [ ]  https://morph.io/planningalerts-scrapers/camden
- [ ]  https://morph.io/planningalerts-scrapers/wingecarribee
- [ ]  https://morph.io/planningalerts-scrapers/greatlakes
- [ ]  https://morph.io/planningalerts-scrapers/goulburn
- [ ]  https://morph.io/planningalerts-scrapers/bogan

**Comment by jamezpolley** [comment]
Yep, I've added this to my list.

**Comment by jamezpolley** [comment]
Kingston is done; but it's been broken for a year so if I enable it now, I think it's going to send a year of alerts all at once

**Comment by jamezpolley** [comment]
I've added a question at https://help.morph.io/t/i-dont-usually-develop-php-how-can-i-update-composer-lock/554/2 to document what I did to update the composer.lock

**Comment by jamezpolley** [comment]
I've prepared pull requests for all of these except for bogan (where accidentally the original repo instead of a fork) and Goulburn.

Goulburn is.. a problem. Their eservices instance is incredibly slow. Every time we run a scraper on morph it times out. That could be simply because their service is so slow; but it could also be that they're deliberately blocking our traffic.

**Comment by jamezpolley** [comment]
All of these have been dealt with, one way or another, except:

 - Goulburn - which is either actively blocking us, or just has their website so under-provisioned as to be unuseable; and
 - Griffith, which is serving only a partial SSL chain, so the certificate can't be verified.
