### ISSUE TITLE
Spam appearing on PlanningAlerts because honeypot on comments form isn't 100%

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1373]
We're getting spam comments created, but not confirmed, and so they're not getting displayed on the site. It's not a huge problem because there's nothing user visible. However, it does mean that there's a lot of crap in the database with no obvious way to sift out sensible comments that for one reason or another or not getting confirmed.

**Comment by mlandauer** [comment]
In #1151 it's mentioned that the similar spam honeypot stopped working on the abuse report form. How annoying.

**Comment by katska** [comment]
more spam coming. for example https://www.planningalerts.org.au/applications/1843351#comment96677

**Comment by katska** [comment]
this one WAS confirmed

**Comment by katska** [comment]
This means that spam submissions are going to council. Not good!
