### ISSUE TITLE
Help people to understand why we've alerted them to something that doesn't have details on the Authority's website

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1375]
At present, we send out alerts to subscribers as soon[1] as we see a new DA on an authority's website. In some cases, this means that we're sending out an alert at a point in time when there's no detail on the Authority's website other than the address and perhaps a brief description.

This can lead to a bad experience for subscribers, who want to find out more about the alert they've just received, but can't.

#1368 suggests that we consider delaying the initial notification until there's some more detail on the Authority's site (and this in turn depends on #1317 which allows us to start tracking changes on an application). However, it's not clear whether we'll be able to implement #1368 even once #1317 is complete: it depends on how readily we're able to determine whether each DA is "ready". Unless that proves simple, we'll probably want to err on the side of alerting to early and allowing people to manually track applications that they're interested in.

Until that becomes practical, we might be able to help subscribers by setting their expectations around the level of detail they can expect to see on a new application.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ndtp)

**Comment by jamezpolley** [comment]
I'm not entirely sure where or how we could do this. My first thought would be to add a note to the top of alert emails and perhaps on applications newer than 7 days saying something like "This is a very recent application, there's a high likelihood that the council don't have all the details yet, please be patient". But I suspect that such a notice wouldn't easily be noticed

**Comment by mlandauer** [comment]
I agree. I don't know how this could be done without undermining things somewhat. We'd effectively be saying to people "hey, here's a new application, but it might be so new that it's not got any useful information on it". That's effectively saying that this service "might or might not be rubbish".

I'd rather we come up with a solution that "just works" or at least does the most sensible thing given the constraints rather than just telling people the data might be rubbish.

**Comment by mlandauer** [comment]
As I mentioned in https://github.com/openaustralia/planningalerts/issues/1368#issuecomment-899637018 I think we have to deal with this at the scraper level by just delaying scraping of an application if we can figure out that the information isn't yet useful. How we recognise this will depend entirely on what a particular council is doing.
