### ISSUE TITLE
Tell councils to not publish email address and street address in email

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1378]
In the email sent to councils when a comment is made add instructions that the email address and street address is provided for verification purposes and is expressly NOT to be published unless they contact the person and get express permission.

Councils will probably ignore that but we can at least try and that way they can't say we didn't tell them even though you would hope that they didn't actually need to be told.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4h4at)

**Comment by mlandauer** [comment]
I'd quite forgotten about the idea of doing this. It feels like it could solve some problems we've seen and definitely puts responsibility on the councils to get permission

**Comment by katska** [comment]
@mlandauer I agree! In NSW at least there is provision in [GIPA ](https://legislation.nsw.gov.au/view/html/inforce/current/act-2009-052). If we provide blanket wording for across the country this could be a good start. If there is pushback that we do need to specifically refer to people's rights in each state and territory.

**Comment by katska** [comment]
words [here ](https://docs.google.com/document/d/1w8DNsbpxhjdF-LgM1pnrHoHfhPJaerokAvLpEz_37Bs/edit?usp=sharing)

**Comment by katska** [comment]
Here's another go from @mlandauer and I following a chat with a lawyer

IMPORTANT PRIVACY NOTICE - PLEASE READ
You do NOT have permission to publish, nor share with anyone outside [planning authority name]  the email address and street address without express written permission from [commenter name].

The email address and street address are provided to [planning authority] only so you can contact, identify and verify [commenter name], and not for any other purpose.

[is there something we could say here as a last paragraph which says something to the effect of we think that the privacy act means that you need to respect this notice?]

Where [planning authority] and [commenter name] come from the details we already have.

**Comment by katska** [comment]
Taken it here too https://docs.google.com/document/d/1w8DNsbpxhjdF-LgM1pnrHoHfhPJaerokAvLpEz_37Bs/edit

**Comment by katska** [comment]
Suggested boilerplate, following discussion with lawyer (admins can see email response 09/03/2022)

IMPORTANT PRIVACY NOTICE - PLEASE READ

You do NOT have permission to publish, nor share with anyone outside [planning authority name]  the email address and street address without express written permission from [commenter name].

The email address and street address are provided to [planning authority] only so you can contact, identify and verify [commenter name], and not for any other purpose.

We specifically confirm that any consent given in any form (including pursuant to your privacy policy) to disclose personal information to third parties is withdrawn.

@mlandauer It's not as plain language as I'd like with the pursuant bit, but given the context that this goes to councils and other planning authorities I believe it does the job. If you agree please can you add this to the outgoing mail to planning authorities?

**Comment by katska** [comment]
I'm now going to look at #1562 in light of this

**Comment by katska** [comment]
I realise I missed a bit, which is that we only provide the information for them to correspond about a specific development application and not anything else.

**Comment by katska** [comment]
Update including restricting use of Information for one purpose *in bold**

The email address and street address are provided to [planning authority] only so you can contact, identify and verify [commenter name], **in response to [DA number]**, and not for any other purpose.

**Comment by katska** [comment]
Full update, worked with wonderful help from Justin at Marque lawyers to arrive at:

IMPORTANT PRIVACY NOTICE - PLEASE READ

You [planning authority] do NOT have permission to publish, nor share with anyone outside [planning authority name]  the email address and street address without express written permission from [commenter name].

The email address and street address are provided to [planning authority] only so you can contact, identify and verify [commenter name], in response to [DA number], and not for any other purpose.

We specifically confirm that any consent given in any form (including pursuant to your privacy policy) to disclose personal information to third parties is withdrawn.

adding updates to #1561 and #1562 next

**Comment by katska** [comment]
definitely still a live issue
