### ISSUE TITLE
As an elected representative, I would like to receive notifications of all applications in my electorate

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1385]
Currently I'm able to sign up for alerts in a 2km radius; or use the API to look in a wider region. However, email alerts covering that wider region would be easier for me to access.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_nl6l)

**Comment by mlandauer** [comment]
Sorry to ask this but why the hell don't they use their own website?

**Comment by mlandauer** [comment]
And when you say electorate you don't mean a local councillor?

**Comment by jamezpolley** [comment]
This was based on a request from a state-level MP, so their area of interest would span several councils. 

But even for councillors, I think there are potential cases where the DAs don't go through their website - eg, in NSW if it's State Significant and gets processed at the state level, or by one of the various non-council Authorities that operate around City of Sydney. If I'm wrong about this (perhaps even the state-significant applications have to go through the council as a formality?) then maybe this would only be useful for state/federal MPs

**Comment by mlandauer** [comment]
Going to close this because it's too specific a use case for us to build special functionality I feel.
