### ISSUE TITLE
Council_references sometimes change

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1386]
While [working on fixing](https://github.com/planningalerts-scrapers/kingston/pull/5) a scraper that had been out of action for a while, we noticed that the council has changed their council_references on existing DAs. For instance, the DA formerly known as `KP-189/2018` is now `KP-2018/189`

In this case, the scraper was (we think) broken for other reasons at the time the change happened, so this hasn't (as far as we know) resulted in any data duplication.

However, if this happened to an active scraper, it would result in all the applications within the scraping window being duplicated.

**Comment by jamezpolley** [comment]
References changed again in https://github.com/planningalerts-scrapers/griffith/pull/4; this scraper already implements a morph_period and so it's only pulling in applications from the last 10 days, so it's not as big a problem.

**Comment by mlandauer** [comment]
There's not a lot we can do about this. The council_references are essentially unique id's within the council. If they change it it causes trouble for them. So, we have to assume it's not going to happen very often.
