### ISSUE TITLE
Address used by "Closest First"/"Most Recent First" don't match the address searched for

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1390]
- https://www.planningalerts.org.au/?q=1+Rowitta+Rd%2C+Lindisfarne+TAS+7015 has a list of search results
- The "Closest first" button points to https://www.planningalerts.org.au/?q=Lady+Gowrie+Child+Centre%2C+1+Rowitta+Rd%2C+Lindisfarne+TAS+7015&sort=distance and "Most recent" points to https://www.planningalerts.org.au/?q=Lady+Gowrie+Child+Centre%2C+1+Rowitta+Rd%2C+Lindisfarne+TAS+7015&sort=time
- Both of those links give the "Sorry we only got a partial match on that address" error page.
- https://www.planningalerts.org.au/?q=1+Rowitta+Rd%2C+Lindisfarne+TAS+7015&sort=distance does work, and shows an application at that exact address

**Comment by mlandauer** [comment]
Yes, I've seen this problem as well with an address that I was personally looking at. Woohoo, more geocoding fun!
