### ISSUE TITLE
Mappify.io usage - ~$50/month

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1395]
Mappify.io is now costing us around $50/month.

Is this expected? Is it worthwhile? Can we get more value from this?

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ueh1)

**Comment by mlandauer** [comment]
I've updated the "admin" email where invoices are sent to contact@oaf.org.au. I can see one invoice in my inbox for about $50 for last month's usage. At a guess I would suspect that last month's usage was much higher than usual for geocoding. I wouldn't in general expect us to be paying $50 each month. If we are regularly paying that amount I think something isn't quite right and we should look again at this.

**Comment by mlandauer** [comment]
@jamezpolley does that sufficiently answer your question?

**Comment by jamezpolley** [comment]
Yep, thanks. I'll keep an eye out and revisit if we consistently get charged
