### ISSUE TITLE
Turn off Ask Your Councillors for all councils

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1396]
In light of #1361 we've decided to turn off Ask Your Councillors until such time as we have the ability to take down posts.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_uzut)

**Comment by mlandauer** [comment]
Also, it seems from recent communications with the folk that run WriteIt that they don't really support it and might well shut it down. So, it feels like a very risky piece of infrastructure to be depending on.

**Comment by mlandauer** [comment]
Also, we should record which authorities have it currently switched on (here?) so when/if we come to switch it all back on we can do it for the correct authorities

**Comment by mlandauer** [comment]
Here is the list of authorities for which "write to councillors" is currently enabled
```
$ cd /srv/www/production/current
$ bundle exec rails c production
> p Authority.active.where(write_to_councillors_enabled: true).pluck(:id)
[42, 49, 61, 84, 87, 93, 99, 106, 116, 119, 120, 121, 137, 138, 139, 142, 143, 147, 148, 149, 157, 159, 162, 164, 165, 168, 173, 174, 176, 179, 180, 181, 189, 190, 197, 204, 207, 210, 212, 240, 243]
```

**Comment by mlandauer** [comment]
To disable the feature for all authorities
```
> Authority.update_all(write_to_councillors_enabled: false)
```

To double check that it worked
```
> p Authority.where(write_to_councillors_enabled: true).pluck(:id)
[]
```

**Comment by mlandauer** [comment]
It is done

**Comment by jamezpolley** [comment]
Thanks
