### ISSUE TITLE
Possible commerical offering: "Saved search" alerts across broader areas

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1405]
We've had a request from someone who would be interested in something along the lines of a once-per-month listing of all applications nationwide that matched a keyword search.

This isn't something that we offer at present, but it's something that could be done relatively easily with the bulk API.

1) Would this fit within our objectives?
2) If it would, is this something that we'd consider implenting?

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_11irp)

**Comment by mlandauer** [comment]
I don't think we know that there are a large enough need for this to justify the development at the moment. So, closing.
