### ISSUE TITLE
"Delete Application"  in admin interface returns 500

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1410]
In the attached Front message, we've received an urgent request to take down personal details which were inadvertently published by a council.

The council has removed the personal information on their site, but it's still cached on planningalerts.

Pressing "Delete application" returns a 500 error.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1cq11)

**Comment by jamezpolley** [comment]
[HoneyBadger ](https://app.honeybadger.io/projects/37075/faults/54949672) has some more information:

````
ActiveRecord::DeleteRestrictionError: Cannot delete record because of dependent versions
````

**Comment by mlandauer** [comment]
@jamezpolley "hide" the application rather than delete it.

**Comment by jamezpolley** [comment]
@mlandauer I'm not seeing a button for hiding the application. How do we do that?

**Comment by mlandauer** [comment]
@jamezpolley sorry brain fart. There's no hiding of an application - only comments. Let me take a look.

**Comment by mlandauer** [comment]
Made the update by hand in the rails console:
```
> a = Application.find(1399078)
> CreateOrUpdateApplicationService.call(authority: a.authority, council_reference: a.council_reference, attributes: {description: "Vegetation Clearing - J Dening"})
```

So now the text is the same as it is on the council website
