### ISSUE TITLE
Year-old application showing as trending

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1411]
https://www.planningalerts.org.au/applications/976402

Most recent comment is a year old.

![image](https://user-images.githubusercontent.com/216918/67897483-9390c680-fbb2-11e9-95f5-02209993e51d.png)

![image](https://user-images.githubusercontent.com/216918/67897514-a4413c80-fbb2-11e9-81f6-a080a44fd218.png)

**Comment by mlandauer** [comment]
I think this is still happening. Well I guess that's not surprising because I don't think I've tried to fix this yet!

**Comment by mlandauer** [comment]
This still really needs fixing. I've unassigned myself because I clearly haven't been actively working on it!
