### ISSUE TITLE
Allow API users to get updated versions of applications

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1415]
**Please Describe The Problem To Be Solved**
In order to ensure that any updated data provided by Authorities flows through to users of our APIs, we want to require those users who cache data to be able to check for updated versions of applications.

We don't have to worry about API users who don't cache, or who cache only for a short time; they'll get the updates automatically the next time they make a request that returns the updated application.

I can think of three categories of updates to applications; there may be others I haven't thought of.

1. Corrections to published data
  - Usually happen within the first few days/weeks, and are (for the most part) automatically caught by our scrapers
2. Status updates as an Application is approved/rejected/etc 
  - May happen weeks or months, not usually captured at present but may be in future
3. Corrections for erroneous or erroneously released information
  - May happen months or years later

II think it's probably safe to assume that a user searching for applications near an address will be just as interested in applications that were updated yesterday as those lodged or scraped yesterday.

**(Optional): Suggest A Solution**

* Add a `date_updated` field to the API output, in addition to `date_scraped` and `date_received`.
  * If there are no updates since the initial scrape this will have the same value as `date_scraped`[^1]
  * If there are updates, `date_scraped` will be the date we first saw the application and `date_updated` will be the date we most recently saw an update

* Add parameters to API calls to allow the API user to request sorting by `date_updated` or `date_scraped` or `date_received`
* Perhaps also add a parameter to request only updates since a provided date? This would make it ultra-simple for API users to check for all updates since their last check

* Consider the default ordering for each API call.
  * I'm thinking that `date_updated` probably makes the most sense as a default for most calls. I think people looking for applications in their neighbourhood will want to see updated applications just as much they want to see freshly-filed applications - perhaps more, as the most recent update is most likely to have the most complete and accurate information.

[^1]: Alternatively, the field could be blank or absent if there are now updates. However, this means that sorting by `date_updated` would require a sort by `date_updated if present; else date_scraped`. I'm guessing that it's simpler to always list `date_updated`. I'm guessing that `date_scraped` is most likely a field on the `application` object while `date_updated` would be the equivalent field on the `version` object.

**Comment by mlandauer** [comment]
Yes we definitely should support this use case for the API better. It's not an urgent feature for any of our current users of the API but it should be there for completeness for sure.
