### ISSUE TITLE
New scraper: Golden Plains Shire

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1420]
Murray Buchanan has written new scraper: https://github.com/muzza1976/golden_plains_shire

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_26gzp)

**Comment by jamezpolley** [comment]
@mlandauer @muzza1976 has pinged us to remind us that this isn't live yet. Are you still working on this?

**Comment by mlandauer** [comment]
@jamezpolley it is live and has been for a while. See https://www.planningalerts.org.au/authorities/golden_plains_shire. One of the problems was that the scraper wasn't set to auto-run each day on morph.io.
