### ISSUE TITLE
New scraper required: Georges River council

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1421]
As mentioned in https://github.com/planningalerts-scrapers/multiple_masterview/issues/3, Georges River Council (formerly Kogarah and Hurstville councils) now has a new non-Masterview site which needs a new scraper.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_27h8l)

**Comment by tuppa** [comment]
Hey @jamezpolley, I've written a scraper in Python for Georges River Council.

[morph.io](https://morph.io/tuppa/georges_river_council_etrack)

The GRC eTrack site appears to be running on Technology One eTrack, but the URL appears to be different from the multiple_technology_one scraper.

Also, the existing scraperwiki libraries are not Python 3 compatible, hence I fallback to calling sqlite3 directly. But just to get the scraper up and running for now.

Feel free to reach out if you have further questions or feedback, thanks!

**Comment by tuppa** [comment]
I've emailed contacts@planningalerts.org.au but haven't heard anything so far, so trying to reach out via this github issue.

**Comment by mlandauer** [comment]
Georges River is now working (https://www.planningalerts.org.au/authorities/georgesriver) so closing
