### ISSUE TITLE
New URL for our site

### ISSUE THREAD

**Issue by Janice80** [openaustralia/planningalerts#1427]
**Describe the bug**
We have a new system in place with TechOne for our planning product. Everyone using your site is now getting a site not found error as the URL has changed.
**To Reproduce**
1. Go to your site
2. Click on any existing DA "further information"
3. See error

NEW URL FOR OUR SITE: https://chcc-icon.saas.t1cloud.com/Public/Common/Common/terms.aspx

**Expected behavior**

You need to be able to scrape the new site and update all records.
https://chcc-icon.saas.t1cloud.com/Public/Common/Common/terms.aspx

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2kif9)

**Comment by mlandauer** [comment]
This was fixed by https://github.com/planningalerts-scrapers/icon_scraper/commit/a1ebece447228cdccc1340cec2af3311d685ed17
