### ISSUE TITLE
Don't show/send alerts for the change of rates on properties (section 7 and 187 notifications)

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1428]
Don't show or send alerts for notifications of change of rates on properties (section 7 and 187 notifications)
example given https://www.planningalerts.org.au/applications/1584363?utm_campaign=view-application&utm_medium=email&utm_source=alerts

**Is your feature request related to a problem? Please describe.**
Requested by a planningalerts user 

**Describe the solution you'd like**
Don't display planningalerts for section 7 and 187 
Arguably you could say it's a bug that these appear. Alternatively you could note these changes in a different way as an additional information service, but its not core planningalerts business to do that in it's current form.

**Comment by mlandauer** [comment]
This would have been an issue for the particular scraper on that particular council which was in SA. That particular scraper isn't being used anymore. It's been replaced by the SA Planning Portal scraper. So, this shouldn't be relevant anymore, I think.
