### ISSUE TITLE
display % population covered on coverage page

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1455]
Display how much of the population is currently covered by PA, in summary as a percentage, in a sentence. 

https://www.planningalerts.org.au/authorities

**Comment by mlandauer** [comment]
It's already there!

> We currently cover 84% of Australia's population within 255 authorities. For this number we're only counting places where the main planning authority is covered. As an example, most of Victoria is covered by the SPEAR system but not all Victorian planning applications go through it. So, we don't include SPEAR in our population count.
