### ISSUE TITLE
Rebuild front-end of PlanningAlerts using Bootstrap or Tailwind CSS

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1462]
As mentioned in #1461 our current front-end is built using a very old mixture of susy, compass, blueprint and an old version of bourbon. The css has evolved over a long period of time. From memory we've once done a complete rebuild to get our grid system but there's still a lot of historical cruft.

The idea of rebuilding it in Bootstrap is to remove much of the old cruft, simplify things, hopefully tidy up the design a little (for instance make the type sizes and colours a little more consistent) but basically keep it visually very similar.

We will then be in a much better position to do new things. We can lean on bootstrap to make things easier and by removing some of the old tech it won't get in the way of future upgrades.

We'll also be in a better position to do a visual/UI/UX redesign in the future.

To reiterate - don't make the site look that different. Keep the same basic page structures and content. Maybe tidy up the typography, colours and whitespace but don't do anything fundamental to the structure just yet. This will hopefully keep this task scoped to an achievable end.

We followed a similar approach in building [TheyVoteForYou](https://theyvoteforyou.org.au/):
* We started with an initial design which was ugly and super complicated
* We shifted over to a bare-bones bootstrap implementation of the same design (without any styling).
* We then worked on the typography and the content, removing things, adding things and rearranging things.
* Only at the end did we start adding colour and final flourishes.

For the PlanningAlerts work I suggest we follow these steps:
* Implement a bare bones bootstrap implementation of our current design (without any styling)
* Work on the typography first to bring it closer to what we have now but feel a little more consistent
* Only then add the colour

**Comment by mlandauer** [comment]
@katska does this provide enough clarity for you in terms of scoping this and putting boundaries around the work? If not, what do I need to explain, explain more or make more clear?

**Comment by katska** [comment]
yes @mlandauer super clear thank you!

**Comment by mlandauer** [comment]
There's been some initial work on this. If you're an admin on PlanningAlerts you can actually switch between the current design and a completely bare-bones (literally no styling) bootstrap version of the interface. So given a bit of time we are in a good position to do a rebuild of the site using bootstrap being able to deploy and test in production without affecting the site for normal people.

So, still very much a thing I would like to do.

**Comment by mlandauer** [comment]
Another approach (similar in spirit, different in details) is to use [Tailwind CSS](https://tailwindcss.com/). We would be more implementing the design from scratch but using something where we pretty much the whole design is done in html markup. It's a pretty radical departure from what's generally considered good practice but after reading a fair bit about it there's a lot that appeals especially for someone like me that has always struggle somewhat with css and it's scoping, best practise and its tendency to accumulate craft and weirdness over time.
