### ISSUE TITLE
make it easier to scan comments when there are a lot of them

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1470]
[This DA ](https://www.planningalerts.org.au/applications/1619124) for example, has a lot of comments - it's not very easy to navigate or get an idea of what's going on.

**Comment by mlandauer** [comment]
@katska I don't really know what you're suggesting here to make it easier when there are a lot of comments. What exactly is the problem? Obviously there are a lot of comments but there's not much we can do about that. Do you have a specific suggestion?

I'm going to close this. Please reopen it if necessary
