### ISSUE TITLE
when hiding a comment display "comment is hidden" on the site

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1472]
If we hide a comment as the result of an abuse report, we should display that we have hidden it for transparency and accountability.

The issue came up following someone venting about a problem they had with PlanningAlerts, a subsequent abuse report https://www.oaf.org.au/2020/09/29/the-story-of-a-tiny-almost-invisible-change/

It was troubling to me that we would remove without trace. After discussion, we decided that it's best if we acknowledge removal or correspondence, as we would do on RightToKnow.

also see #284

**Comment by mlandauer** [comment]
Here's a first pass:

![image](https://user-images.githubusercontent.com/2221/94637247-6a286f80-031a-11eb-926e-fd662145cee9.png)

@katska thoughts / suggestions?

**Comment by katska** [comment]
Good first pass!

**Comment by katska** [comment]
Reference to reason for removal? Or not? Comments are either removed because they are abusive: 'Reasons comments are reported either they have been reported as abusive can include that the comment is spam, abusive, unlawful or harassing — in other words, where people are going out of their way to cause harm. Please explain clearly why you think the comment should be removed.' or someone who posted then requested removal due to exceptional circumstances.

**Comment by mlandauer** [comment]
> Reference to reason for removal? Or not? Comments are either removed because they are abusive: 'Reasons comments are reported either they have been reported as abusive can include that the comment is spam, abusive, unlawful or harassing — in other words, where people are going out of their way to cause harm. Please explain clearly why you think the comment should be removed.' or someone who posted then requested removal due to exceptional circumstances.

I think that's a great idea for what should go in #284 and for what should be part of the admin process. The administrator chooses from a selection of reasons that the comment was hidden and this is recorded and shown next to text above.

**Comment by mlandauer** [comment]
That's now deployed to production. See for example https://www.planningalerts.org.au/applications/1674559#comment91522
