### ISSUE TITLE
Make a new campaign for donors to Planningalerts

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1474]
Create a new campaign for during the course of the year, that doesn't have a goal. 
Then we can switch out from general to end of year when do we have campaign with a goal.

Link to it from planningalerts.org.au > Back planningalerts that goes to https://www.oaf.org.au/donate/planningalerts/

**Comment by mlandauer** [comment]
I'm assuming this issue relates to a donorbox campaign. If so then this is already done! See https://www.oaf.org.au/donate/planningalerts/
