### ISSUE TITLE
forward comment updates to planning authorities

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1481]
when people ask for a comment to be redacted or have other requests to amend their comments or details Planningalerts should send the updates to council. Ideally these would also be annotated on the site, similarly to correspondence on RTK. (separate issue?)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_39mbp)

**Comment by mlandauer** [comment]
Yes, this would be a great thing to do automatically. It would save a lot of administration time and would be the best thing to do from the user point of view.
