### ISSUE TITLE
improve 'more information' following link experience when link is no

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1482]
There's a wide variety of possibilities when someone follows a link to more information. 
When the result is not directly 'more information' that's confusing. Is there something we can do to improve this? 
Prompted by: People write to us about this when the link doesn't take them to a page about the DA

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_39pc5)

**Comment by mlandauer** [comment]
Duplicate of #1328
