### ISSUE TITLE
add Derwent Valley Council

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1483]
Please add Derwent Valley Council

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_39pdx)

**Comment by mlandauer** [comment]
Website is at https://www.derwentvalley.tas.gov.au. The only reference to published development applications that I can see is here: https://www.derwentvalley.tas.gov.au/council/latest-news?f.News+category%7CnewsCategory=Public+Notice&query=%21FunDoesNotExist&collection=derwent-valley-council-news

This looks like just a list of published "news" posts in some free-form non-structured form that looks too hard to scrape. Sorry

Maybe Derwent Valley Council would be a good candidate for a system where the council could directly upload their data? #1533
