### ISSUE TITLE
Improve Name handling and display

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1485]
Some names are loaded one way or another and should be displayed differently. The name that goes to the council doesn't have to be the name we display. 
As people connect with the right to be forgotten, there could also be a case for changing full names to initials over time or only first names or some other symbol that is meaningfully tied to specific identities.

More immediately pressing is that a small number of people reach out and ask that their identity be protected, because they are in a vulnerable, or in a sensitive situation or because they're otherwise concerned about being easily identified in association with an address. It's not everyone's right to know where everyone else lives, even if it's important for the council to understand that someone for example lives next door to a proposed development. 

Also see short term measure #1277 and #1298

**Comment by katska** [comment]
I think there are a few issues to tease apart here, so this is a first go. One option is that we have separate display name and real name, another is to link it to a sort of 'relationship to development' declaration by default. If someone wants their name hidden then we give them options to say why. This would cut down the burden of administration of post moderation.

ie. Name < > your name will be sent to the council.

**Comment by katska** [comment]
To better work with this issue, I want to provide more information. People write to us asking their name be removed for a number of reasons. These are some of the reasons I've seen over the years of supporting people who write to us at plannignalerts.org.au  why people have requested their name be removed. 
- because its still coming up in a google search, and this is not the first thing they want associating with their online presence.They have moved house. They are selling their house. They have a restraining order on an ex family member.  Fear of personal retribution for the comment. Other legal reasons to hide their name. They simply want to exercise a right to be forgotten. Their location is clearly identified. Someone else has addressed them directly in response and this was an unpleasant/uncomfortable experience. They have a unique name and are easily personally identified. They are well known in the community.

**Comment by mlandauer** [comment]
Also related to #1378 which asks councils not publish email and street address by default

**Comment by mlandauer** [comment]
Weird stalebot didn't remove the wontfix label
