### ISSUE TITLE
find out council policies on name and address display

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1486]
When we send a comment / submission to council, how does council work with the name and address?

Can we clarify if someone doesn't want their name displayed or shared, and support their request to council that their name is not shared, as a part of making the submission.

While the council may require a name to consider the submission, I don't know if they publish those by default.

**Comment by mlandauer** [comment]
Perhaps if we set a specific sensible expectation of handling of privacy in our emails to councils, such as in #1378 where we ask councils to not publish email and address by default then we are likely to find out one way or another when that request clashes with a council policy.

@katska does that seem like a reasonable approach or were you imagining something where we directly contact each council to try to find out this information? If so how will we do this with the large number of councils there are?

**Comment by katska** [comment]
Also related to #1561

**Comment by katska** [comment]
I think this is covered by our approach, and no need to make work for ourselves.
