### ISSUE TITLE
oaf blog: write about supporting planningalerts

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1488]
I've been consistently supporting planningalerts for some time, what have I noticed, learned. Schedule time to create  at least one, if not a series of pieces about what I've observed and experienced.

**Comment by mlandauer** [comment]
@katska I think this is a great idea. Are you still planning to do this?

**Comment by mlandauer** [comment]
@katska I think this would be really interesting and also super valuable for a new person coming to work at OAF

**Comment by katska** [comment]
I guess I wanted to do this but didn't get very far. So I need to schedule it in!
