### ISSUE TITLE
BCC update to re-notify when more documents are submitted

### ISSUE THREAD

**Issue by duttonw** [openaustralia/planningalerts#1489]
Just want to say i love the website, just wondering if it can be tweaked to re-trigger an alert if more documents are submitted on the same da. I submitted a response to BCC for this 
https://www.planningalerts.org.au/applications/1479750?utm_campaign=view-application&utm_medium=email&utm_source=alerts bcc link https://pdonline.brisbane.qld.gov.au/MasterViewUI/Modules/ApplicationMaster/default.aspx?page=wrapper&key=A005327341
sadly i did not get notifications when they did a stop/start (paused the da approval process) and then reused the same da number.

If there is an "Information Request" can it be reset to resend alerts when a "Information Request Response" is uploaded?

**Comment by mlandauer** [comment]
Related to #1506

**Comment by mlandauer** [comment]
Also I guess one issue is that we're not capturing anything about documents in what we scrape. So, if new documents are added to the DA the scrapers would not know about it.
