### ISSUE TITLE
ask users more directly for business/organisation information

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1492]
On the [API registration page](https://www.planningalerts.org.au/users/sign_up), require users to enter a business or organisation name.
Instead of "Your company name or leave blank if this is for personal, non-commercial use"
"Your company, or organisation name"
Add "ABN" field

There could be a more useful extended set of questions for users.

**Comment by mlandauer** [comment]
The approach we are planning to use now is to direct people to separate pages for applying for a "non-commercial API key" (#1541) and for applying for a "commercial API key" (#1542). So, we can ask different questions on each. We can also then remove the "company name" field on the user registration page. Closing this in favour of those issues.
