### ISSUE TITLE
Add a definition of commercial and non-commercial use

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1497]
This section on commercial and non-commercial use could be clearer on the howto page.

**Comment by mlandauer** [comment]
@katska any suggested wording?

**Comment by katska** [comment]
I'm working on this [here](https://docs.google.com/document/d/14mg_FpDR1l0U70QYJqwY-poh0VUH_N3H6AjeKhe5ocI/edit)
This document currently has limited access.
