### ISSUE TITLE
DA not appearing on search

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1501]
This application https://www.planningalerts.org.au/applications/1847948 doesn't appear in search results on https://www.planningalerts.org.au/ 
address
Alvin House, 2041-2043 Malvern Road, Malvern East VIC 3145 
Searches tried 2041 Malvern Road, 2043 Malvern Road, Malvern Road

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3k551)

**Comment by katska** [comment]
strangely it does appear through a google search 

https://www.google.com/search?q=2041-2043+Malvern+Road+planningalerts.org.au&client=firefox-b-d&sxsrf=ALeKk03QI58VbnZwQ0bW4CA4xudJ8sNpTA%3A1619488761709&ei=-W-HYL_uKpS-9QOEj5XICw&oq=2041-2043+Malvern+Road+planningalerts.org.au&gs_lcp=Cgdnd3Mtd2l6EANQ4AxY4Axg0A9oAXAAeACAAaEDiAGhA5IBAzQtMZgBAKABAaoBB2d3cy13aXrAAQE&sclient=gws-wiz&ved=0ahUKEwj_zu_iqZ3wAhUUX30KHYRHBbkQ4dUDCA0&uact=5

**Comment by mlandauer** [comment]
That's because it doesn't have latitude and longitude information. You can tell because it doesn't show a map on the application page. This is likely to have happened because the address failed to get geocoded correctly. So, currently this is expected behaviour.
