### ISSUE TITLE
Allow user to modify comments

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1503]
User requests that they should be able to modify or delete comments themselves.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3k5ad)

**Comment by katska** [comment]
user emailed: "Could you please let me know how can I modify or delete my comment. I think that all systems should provide a method for modifying and/or deleting comments.

Could you please let me know what do I need to modify my comment and if that’s not possible, I would like it removed from the database."

**Comment by mlandauer** [comment]
This will be much more straightforward if we implement a user registration/login in #1530
