### ISSUE TITLE
Task based administrator tool

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1505]
This is a very high level issue for a potentially big new piece of work. Our current admin interface is a very simple CRUD based interface. It focuses on very simple changes to basic objects in the system (like Application, Comment, Report, Authority, etc..)

The idea with this issue is that we design a new interface that is focused on common tasks that an administrator has to do. These could be, for example, things like:
* A user has asked to remove their name from a comment
* A user has reported another user's comment
* A user has reported that there is private information in the text of a development application

Each of these tasks is pretty involved to handle currently. It might involve looking in different systems and updating things in different places and sending several follow emails. 

The intention of this new "task based tool" is not to automatically respond without any human involvement but rather to take the grunt work out of the myriad of tasks for the administrator so that they can spend more of their time being a helpful human to other humans and less time pushing buttons and figuring out and remembering how to do things.

As a first step I envisage that we would create a catalogue of common tasks and that the task based tool starts of being simple documentation to remind the administrator how to handle common situations. Over time this could then evolve into a more automated tool.

For instance, if a user has asked for their name to be removed from a comment for privacy reasons we might do the following:
* Redact the comment (making it clear to anyone else looking that a redaction has taken place)
* Email the user who made the comment (we might have some standard wording that can be updated by the administrator)
* Email the updated comment to the council explaining that the user requested a change

None of these steps individually is particularly hard or difficult but when you have to do many of them as an administrator to handle a single user request it becomes tiresome and gets in the way of doing a good job for everyone involved. So, let's remove the drudge work by making each step a little easier and more seamless.

**Comment by mlandauer** [comment]
Initial content is in https://docs.google.com/document/d/1N_jSBp_uFam5i_krJdt9eZaOh0cWmcrqmjO58FG638E/edit?usp=sharing 

Note that this google doc is viewable and commentable by anyone.

**Comment by katska** [comment]
Where's the hide comment button? I can only see the hidden status but not where to change it

**Comment by katska** [comment]
ok that's in EDIT

**Comment by katska** [comment]
big important work we need to figure out how to do. Keeping open.

**Comment by katska** [comment]
see also #1502
