### ISSUE TITLE
update DA when planning authority updates it

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1506]
when there's a mistake fixed or if there's a second go at a DA with the same number - example 1.  the person applying for the DA changed the details to comply with feedback given by council and repropose 6 months later and it goes on public notice again (happens more with bigger developments) or 2. if the council updated the details of a DA number because of a typo during the same notice period.
We don't catch either of these cases currently.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3kb45)

**Comment by mlandauer** [comment]
We **do** update the contents of a DA if it changes at council. However what we don't do currently is email people about those changes.

**Comment by mlandauer** [comment]
I'm going to close this
