### ISSUE TITLE
allow users to contribute outside "comments"

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1507]
Say there's something wrong with the text of the DA, if there's a new version or there's some associated information that's helpful to understand - allow users to contribute something that isn't the usual submission to council.  
Maybe it wouldn't be open to everyone, or need to be treated quite differently - akin to the supporters of Right To Know who give assistance there.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3kb5x)

**Comment by mlandauer** [comment]
The idea of this seems sensible enough to me. I guess the big question I have is if there are multiple ways of commenting which do different things how do we make it so that it isn't confusing to users?

**Comment by mlandauer** [comment]
Or is this more about alerting the administrators of a problem in a structured way? More like an abuse report? Like a "this application requires administrator intervention"?
