### ISSUE TITLE
create summary report for planning authorities DAs/comment received

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1508]
it would be helpful for people who have sent a comment and for councils to receive a report showing the number of comments and perhaps some other statistics about the status of these comments. 
Individual DAs and overall (weekly, monthly?)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3kbd1)

**Comment by mlandauer** [comment]
It's not clear to me why this would be useful to councils or why users would be interested in more general stats and what stats?
