### ISSUE TITLE
when a scraper is broken prompt people to take action

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1510]
When a scraper breaks or there is a failure for some reason, prompt people receiving the alert to get involved and help keep it online 
see https://www.planningalerts.org.au/getinvolved
encourage neighbourhood volunteering and participation! 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3kbgl)

**Comment by mlandauer** [comment]
I think this is a very good idea. It is possible to do if we let authorities know their own boundaries #374
