### ISSUE TITLE
Tag issues

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1512]
Noted in a [tictec thread ](https://groups.google.com/g/tictecbymysociety/c/UwMewSRwgk4?pli=1)- Tag or characterise comments with the problem area, or social issue (homelessness, climate change, etc.). Can we adopt/adapt an existing open framework / taxonomy?

**Comment by mlandauer** [comment]
@katska I can't see that thread. If it's not a private conversation could you please link to a public archive or alternatively copy the content of the message here.

**Comment by katska** [comment]
@mlandauer good point, thanks! - I've revised the link to the original and public tectec convo ☝️

**Comment by mlandauer** [comment]
@katska I think this issue would benefit from a much more descriptive title. Any chance you could update?
