### ISSUE TITLE
stop comment reports being abused

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1513]
It seems possible for people or programs spamming or generally being abusive themselves to report other comments on planningalerts. 

Require reporting a comment to be confirmed by the email address would be one way to stop this. Maybe there are other ways?
I'm reporting this today because of the offensive language used in one such report. I guess it took me by surprise and I felt quite emotionally disturbed by it.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3kyh1)

**Comment by mlandauer** [comment]
I agree that it makes sense for their email address to be confirmed. It will cut down on abuse and spam and also provide a more reliable way for us to communicate back to the person putting in the abuse report.

I think this also fits into the bigger putting things under a user login umbrella.

**Comment by mlandauer** [comment]
This is now done. People need to be logged in to report a comment.
