### ISSUE TITLE
make it easier to confirm comment is on the right DA

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1518]
A small number of people have accidentally recently commented on the wrong DA. When asked, one reported:

"The way the screen is set up the list of applications are a bit cramped together and sometimes it is possible to click on the wrong link. 
I noticed another person's comment was for an STA but posted on a wrong link."

**Comment by mlandauer** [comment]
What I don't understand about this report is that people need to click on the application detail page to comment. So that takes them to the page with all the information. If they comment there that means they haven't read the page they're on. So, I'm inclined to close this as a won't fix.
