### ISSUE TITLE
improve location information in NSW with SIX maps

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1520]
It's been suggested we use SIX maps to resolve our addresses over google maps in NSW, as this is where councils update their information (for example when new lots are released) 
In a small percentage of addresses, google maps is not up to date, or doesn't know how to resolve an address/location information we pick up from councils. 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3pphh)

**Comment by mlandauer** [comment]
We don't get to use a geocoder provided by the NSW government. SIX doesn't directly provide a web service (API) that we can use for free.
