### ISSUE TITLE
in at least some cases, the API is returning oldest first instead of newest first

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1523]
Someone reported the following problem in accessing the most recent DAs in 2 authorities in Tasmania. 

This page indicates it should be newest to oldest?

https://www.planningalerts.org.au/api/howto

"All the API calls listed below return planning application sorted by the date they were scraped from the planning authority website with the most recent listed first."

https://api.planningalerts.org.au/authorities/launceston/applications.rss?key=*****

Starts returning results from 2012. If I add a page=43 parameter, we get current applications.

 

https://api.planningalerts.org.au/authorities/hobart/applications.rss?key=*****

Same for Hobart

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3qu11)

**Comment by mlandauer** [comment]
This is now deployed to production as well.

@katska this bug was only on one of the API calls - the authority search one. The other API calls were doing the right thing. That's why we hadn't noticed this problem. Sigh. Anyway, it's all fixed now.
