### ISSUE TITLE
Document (and make it the default) the v2 API with better paging information

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1528]
There is a version 2 of the API which returns a slightly different result format which gives you better information about the total number of applications and the total number of pages.

I think the url scheme for it is terrible and we should rethink that but otherwise it's a good thing and we should make everyone use it.

**Comment by katska** [comment]
I don't see any note that says this was done, it looks like it was closed by default - but looks useful so reopening.
