### ISSUE TITLE
Force / verify geocoding result of application address by checking it lies within the boundary of the authority

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1529]
We have a set of problems where geocoding can go very badly wrong. A simple way that we completely stop the worst offending instances (where example an application is in completely the wrong state) is to use the known boundary of the planning authority to either force a result within the bounds (if the geocoder supports it) or just reject the result if it lies outside the boundary.

This issue is the best solution that resulted from a conversation in #1431 

This is dependent on adding boundary data for each authority (#374)

**Comment by katska** [comment]
Yes please!
