### ISSUE TITLE
allow person commenting to edit the comment before confirming/finalising it

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1532]
Requested by someone who wanted to edit their comment before confirming it.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3t805)

**Comment by mlandauer** [comment]
The only place it makes sense to me for this to happen in the current flow would be in the email confirmation. The email could say something to the effect of "this is your comment. To confirm and sent it as click here. To edit click here"

However once we implement user registration #1530 this can't be the flow anymore as people won't need to confirm their email at the specific moment when they comment. As we're probably intending to implement user registration fairly soon I suggest we don't do this but rather prioritise people editing their comments after they're published which is probably the more common use case.
