### ISSUE TITLE
Deprecate style option in API

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1534]
The main use of the `style=html` option was for embedding a google map with PlanningAlerts information. Google maps removed the ability to use georss feeds a long time ago and so the main purpose isn't there anymore.

I had a quick look in our API logs and I can see that this feature is now only being used by one person, @drzax.

@drzax would you be terribly sad if we removed the `style=html` option from the API?

**Comment by drzax** [comment]
I would not mind at all. To be honest, I'm not sure where I'd be using that, can you shed any further light?

**Comment by mlandauer** [comment]
> I would not mind at all. To be honest, I'm not sure where I'd be using that, can you shed any further light?

It looks like you're using it hooked up to a slackbot of some sort. Does that sound right?

**Comment by drzax** [comment]
Ahh, yes I am. But it's just using an RSS feed integration and only uses
the link to the planning alerts site, so definitely no concern if the style
option is removed.

Thanks for checking.

**Comment by mlandauer** [comment]
Brilliant. Thanks for checking @drzax. Much appreciated. It will feel good to delete code that is no longer used :-)
