### ISSUE TITLE
Restrict api#area call to a maximum area and/or optimise database requests for api call

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1548]
Currently with a relatively small number of API requests, the area call is taking a disproportionate amount of database time which is affecting the overall performance of the application.

We can do one of two things (or both):
* Try to improve the performance of the database query so that it takes less time
* Restrict the maximum allowed size - this is reasonable as we don't want people to abuse a call to try to get "everything". If we do that we should also restrict the maximum radius

**Comment by katska** [comment]
@mlandauer still need to restrict api#area call to a maximum area and/or optimise database requests for api call ?
