### ISSUE TITLE
make search area more editible to sign up for alerts

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1551]
A radius is a good general starting point for interest but doesn't cover all eventualities. 

Someone reports being irritated by receiving alerts for an area that's phyically close but geographically distant, separated by water, and over 30 minutes drive away.  See example at Teagardens

<img width="712" alt="Screen Shot 2021-09-22 at 14 22 19" src="https://user-images.githubusercontent.com/1001129/134283482-dba3da20-8fea-4df9-90a1-6c9dfda5fab8.png">

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3va11)

**Comment by mlandauer** [comment]
@katska what exactly are you suggesting here? Where a person can put in an arbitrary boundary and search within that? That all sounds pretty complicated and pretty niche to me to be honest.

**Comment by katska** [comment]
It's an open question, how can we make the search areas more useful. 
 In this case I don't know how to geographically describe that the place is more distant by being across the water.  Maybe it's niche and maybe we stop and think about it for a minute. Not an urgent priority but definitely feels relevant on a land where many people live around wiggly lines around water.
