### ISSUE TITLE
blank screen after destroying a comment

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1554]
From the report page, viewing a list of comments, I identify a spam comment and click on 'destroy'
The page goes blank (white)and the URL shown is that of the comment I just destroyed.
<img width="1194" alt="Screen Shot 2021-09-28 at 12 37 16" src="https://user-images.githubusercontent.com/1001129/135013410-3800ed43-672e-454d-833e-7368f6ad9cfe.png">

Ideally I should still be on the report page.

**Comment by mlandauer** [comment]
I'm pretty sure this happens when a report has already been deleted by someone else. So, closing this as a won't fix
