### ISSUE TITLE
Unable to update authority details

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1565]
From the [authority admin page](https://www.planningalerts.org.au/admin/authorities/189), I tried to add a new email address to fremantle council and got the following error
<img width="1012" alt="Screen Shot 2021-12-07 at 12 01 03" src="https://user-images.githubusercontent.com/1001129/144946953-2be70fc2-d4ec-4f25-926c-76681d64c689.png">

**Comment by mlandauer** [comment]
Fixed by 36d098742973b96e9a21cb1a12b4f9db6357f9f2
