### ISSUE TITLE
Investigate how councils respond when we notify them about a hidden user comment that was reported as abusive

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1571]
**Background**
When someone reports a comment as abusive on planningalerts, and in the case where we agree, then hide it from view, mostly that's the only action we take. 

In a very small number of cases I've contacted the planning authority to let them know also.
I'd like to get an understanding of what councils do in the case that submissions are reported in different circumstances.

I'd like to better understand what planning authorities do in these cases and the context of their actions. 
Why? 

**What problem are we trying to solve?**
Improve support for difficult public conversations.

Related to #284 and #1477

**Comment by JoannaHill** [comment]
Merged with Automate process after someone submits an abuse report on a comment (PA-270) #284
