### ISSUE TITLE
emails to hotmail addresses bouncing/held back

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1573]
planningalerts emails failing to deliver to hotmail email addresses. Some hard bouncing some held back.
Reputation report on cuttlefish reports UCEPROTECT3 as the denylist.

https://github.com/mlandauer/cuttlefish/issues/411

**Comment by katska** [comment]
I started looking methodically through the list of people who are signed up to receive email alerts at hotmail addresses at planningalerts.org.au The latest emails sent out to the fist three I looked were sent emails in February and were NOT successfully delivered. So this looks like a consistent and current problem.

**Comment by katska** [comment]
ok I found some reference to this in a slack convo but it doesn't really help me move forwards. @mlandauer any suggestions?

**Comment by mlandauer** [comment]
I signed up for https://sendersupport.olc.protection.outlook.com/snds/index.aspx which is telling me that our ip address is "Blocked due to user complaints or other evidence of spamming".

Taking a close look at the data over the last 70 days it appears we had a single day about a month ago when spam was at 0.2%. Every other day it was < 0.1%. The amount of recipients has significantly dropped over the last month. I've requested our IP to be unblocked. So, let's see what happens

**Comment by mlandauer** [comment]
Our IP has been unblocked. Including the full response email here for easy future reference:

> Dear Matthew Landauer
> 
> We have completed reviewing the IP(s) you submitted. The following table contains the results of our investigation.
> 
> Conditionally mitigated
> 23.239.22.35
> Our investigation has determined that the above IP(s) qualify for conditional mitigation. These IP(s) have been unblocked, but may be subject to low daily email limits until they have established a good reputation.
> 
> Please note that mitigating this issue does not guarantee that your email will be delivered to a user’s inbox.
> 
> Ongoing complaints from users will result in removal of the mitigation.
> 
> Mitigation may take 24 - 48 hours to replicate completely throughout our system.
> 
> If you feel your issue is not yet resolved, please reply to this email and one of our support team members will contact you for further investigation.
> 
> 
> Regardless of the deliverability status, Outlook.com recommends that all senders join two free programs that provide visibility into the Outlook.com traffic on your sending IP(s), the sending IP reputation with Outlook.com and the Outlook.com user complaint rates.
> 
> Junk Email Reporting program (JMRP) When an Outlook.com user marks an email as "junk", senders enrolled in this program get a copy of the mail forwarded to the email address of their choice. It allows senders to see which mails are being marked as junk and to identify mail traffic you did not intend to send. To join, please visit
> 
> https://sendersupport.olc.protection.outlook.com/snds/JMRP.aspx
> 
> Smart Network Data Services program (SNDS). This program allows you to monitor the ‘health’ and reputation of your registered IPs by providing data about traffic such as mail volume and complaint rates seen originating from your IPs. To register, please visit http://postmaster.live.com/snds/.
> 
> There is no silver bullet to maintaining or improving good IP reputation, but these programs help you proactively manage your email eco-system to help better ensure deliverability to Outlook.com users.
> 
> Thank you,
> 
> Outlook.com Deliverability Support

**Comment by mlandauer** [comment]
@katska the person trying to comment that you sent me the details of yesterday should now be able to try again. I've checked that they're no longer on the cuttlefish deny list and with some luck the email should now go through to outlook. So, closing this.

**Comment by katska** [comment]
@mlandauer  could you please update this issue with the newer information/links process overview you went through today to fix a similar problem. Sadly I could not grab those from a screen share.

**Comment by mlandauer** [comment]
I filled out this form to get our IP delisted: https://olcsupport.office.com/
