### ISSUE TITLE
New systematic comment spamming problem

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1587]
On https://www.planningalerts.org.au/applications/1948697 there are 438 spam comments (out of 439). These spam comments are ones where the email address has been confirmed by the clicking of the link. This is the first time we've seen this happen on this scale.

These comments are coming from slightly different email addresses every time but only 10 different domains. These domains are:
* iupes.fodiscomail.com
* egiuz.fodiscomail.com
* pazew.fodiscomail.com
* odiwe.elighmail.com
* ereqd.fodiscomail.com
* omofu.fodiscomail.com
* odadu.fodiscomail.com
* ulabo.elighmail.com
* exilh.elighmail.com
* ixeze.elighmail.com

These are all subdomains of:
* fodiscomail.com
* elighmail.com

**Comment by katska** [comment]
@mlandauer just a word to clarify the nature of this problem, I have only seen one off spam comments that seem to have been individually confirmed. When you say 'at this scale' it sounds like it has happened at some scale more than individual comments before, which as far as I know is **not** the case.

**Comment by katska** [comment]
all the subdomains look like they're pointing at the same IP address as the domain they're connected to,
On https://www.planningalerts.org.au/applications/1948697 there are 438 spam comments (out of 439). These spam comments are ones where the email address has been confirmed by the clicking of the link. This is the first time we've seen this happen on this scale.

These comments are coming from slightly different email addresses every time but only 10 different domains. These domains are:

iupes.fodiscomail.com
egiuz.fodiscomail.com
pazew.fodiscomail.com
odiwe.elighmail.com
ereqd.fodiscomail.com
omofu.fodiscomail.com
odadu.fodiscomail.com
ulabo.elighmail.com
exilh.elighmail.com
ixeze.elighmail.com
These are all subdomains of:

fodiscomail.com - 
elighmail.com - 

http://www.fodiscomail.com  looks like a list of spam content
elighmail.com redirects to https://daaz.com domain name registration

DNS records 
Name: FODISCOMAIL.COM
Registry Domain ID: 2691869534_DOMAIN_COM-VRSN
Domain Status:
clientTransferProhibited
Nameservers:
B.NS14.NET
C.NS14.NET
D.NS14.NET
Dates
Registry Expiration: 2023-04-25 18:24:14 UTC
Updated: 2022-05-19 16:31:06 UTC
Created: 2022-04-25 18:24:14 UTC

and NS14.NET info see - https://www.nslookup.io/domains/b.ns14.net/dns-records/#cloudflare
shows the A records (eg. 217.160.113.231) registered to InterNetX GmbH in Frankfurt Am Main

**Comment by katska** [comment]
Quite a few more spam comments this morning on this notice. Someone who’s signed up for alerts in the area received notice of only a couple of new spam comments this morning. I wonder if some have already been caught as spam or if it just came as one notice. I've asked them to forward what they received today so I can double check it's what I'd expect they'd receive.

**Comment by katska** [comment]
@mlandauer any news? There have been a lot more comments gone through to the council.

**Comment by mlandauer** [comment]
Okay this should be reasonably under control I think. At least for the time being. No comments with email addresses from those two domains can be created on PlanningAlerts now and I've gone through the last 50,000 comments and hidden any from those domains.

**Comment by mlandauer** [comment]
Even after all this it turned out there were about 3300 unconfirmed comments from the same spammers. Even though we were blocking new comments from the spammers they could have potentially confirmed those comments which would have then be sent to council, etc... So, instead of allowing that we took the drastic step of deleting the comments from the spammers so they couldn't even be confirmed.
