### ISSUE TITLE
Update old DA details by hand 

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1593]
The details of [ DA REC13/0135.06 ](https://www.planningalerts.org.au/applications/2188433) have been updated to remove applicants names. This now need to be updated on PlanningAlerts to match. However the DA is 10 months old and won't be scraped again by planning alerts.org.au. So the details need to be replaced by hand.

Information at council for this DA now reads "11 Maracas Bay Cl YAROOMBA - Change to Development Approval - Reconfig of Lot (Development Permit to Reconfigure a Lot (1 Lot into 37 Residential Lots and 2 common property lots) - JDBA Certifiers" 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4yhl1)

**Comment by mlandauer** [comment]
Done!
