### ISSUE TITLE
make help info easier to find and use

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1595]
bring together information from FAQ, canned responses that are specifically about the website to begin with into a searchable resource.

**Comment by katska** [comment]
trying out Zendesk for this

**Comment by katska** [comment]
Have copied some canned responses to https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#

[Using the Website](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.d53j14e691bc)
[Search for an Address](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.ugwy37wdcn21)
[Find a Specific Address](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.hddzy85taiq)
[When Something’s Wrong](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.w3rg7rr723x)
[Broken Link More Info*](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.i1srgx8gk4ye)
[Google address is wrong](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.j472g7kg2y9s)
[Bad-Geocoding](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.tefafekeg4v8)
[Geocoding is wrong](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.618cx7skzqpf)
[Council Provided Bad Data*](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.9zboh6cze4cr)
[Sign Up for, Manage and unsubscribe from Alerts](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.sibl1jn7x97v)
[Sign Up for An Alert](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.kz4yaz6976sh)
[Change Email Alert Email Address](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.eeiey6q535hd)
[Unsubscribe to change email address](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.ikit951826yc)
[How Do I Unsubscribe?](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.e4wecmg4inp7)
[Making Comments](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.wg93bnjoy8is)
[Comments where do they go?](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.jupbse6eh36v)
[Not the Gov or Builders](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.k3q6tt5h2x7j)
[When People Send Accidental Emails](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.wrcrcrueej22)
[Emailed OAF Not Commented](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.f9zyml207abd)
[OOPS PA SEND*](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.7xwo5p3j5wiw)
[Email/Confirm*](https://docs.google.com/document/d/19T3gsKGefMs9-lGzIyhCloarjCxi7IRYSYietOElFkE/edit#heading=h.k284bz228vzb)

**Comment by katska** [comment]
I put some of these in Zendesk, which seems like it's a giant thing and this is only a small and slightly complicated part of what Zendesk does. Most of which we don't need right now. 

In search of a simpler more elegant answer, I came across helpcenter.io
It's pretty easy to copy and paste information there. There are categories, but not tags.

**Comment by katska** [comment]
I'd like to get everything in one place, then do an overhaul on the content, and hope to only have to have the information in one place.

I added everything that's in the document mentioned above to planningalerts.helpcenter.io. as an 'article'
Also added what's currently in the FAQ page(with very only minor wording changes on Can I have the data) as FAQ entries
WI haven't added yet (from frontapp)
- abuse report responses
- a few other miscellaneous responses
- new content on privacy, partly because there are changes that need to be implemented elsewhere, as we refer to instructions we aim to give to councils but have not incorporated that yet.
- a bunch of the identified reasons why people get in touch from Jo's exploration
I think the next step for those is to find responses for those, adapt them and decide where the source of truth list should then be for these from now on. Do I put them straight into helpcentre

**Comment by katska** [comment]
looking at the content on a phone, the categories take up a lot of screen, would be nice to have options around this. @mlandauer I'm keen to hear what you think.

**Comment by katska** [comment]
Also is there other content on the website that we want to move to a help centre?

**Comment by mlandauer** [comment]
Related to #1684
