### ISSUE TITLE
number of email alerts and comments are inconsistently reported between pages

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1596]
comments page reads 

<img width="885" alt="Screen Shot 2022-10-13 at 6 11 35 pm" src="https://user-images.githubusercontent.com/1001129/195527014-62a36d0d-613e-4a25-a4b3-af0b082cdbbb.png">

vs 

<img width="913" alt="Screen Shot 2022-10-13 at 6 11 51 pm" src="https://user-images.githubusercontent.com/1001129/195527002-25f182b1-bbc7-4ed6-bc94-cf091060bfa1.png">

**Comment by mlandauer** [comment]
I don't think this is anything to worry about. Those numbers are cached. Maybe the cache was invalidated between the two requests?
