### ISSUE TITLE
add a "How it works" content block to the landing page

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1647]
This is similar to what we currently have on righttoknow.org.au

I think it helps with people understanding what the service does, who we are and convince them it is unique and of value. A perfect fit for the landing page!

**Comment by katska** [comment]
@mlandauer do you have specific ideas about this? Please assign me if you want me to look at it.

**Comment by katska** [comment]
Currently looks like this <3 So good to have this overview. Definitely getting there! 
<img width="1171" alt="Screenshot 2023-07-27 at 9 36 02 am" src="https://github.com/openaustralia/planningalerts/assets/1001129/052741e4-6e1b-4125-80b6-73cd056bf494">
Now we've all had a break, time to look afresh and see if we think it does the job. If not what's missing? Be specific. Do we roll out initially as is and see if this helps, iterating the content from there?

**Comment by katska** [comment]
Should discussion of tweaks be here or in [figma?](https://www.figma.com/file/GEaOuajueHGvfaFPsOUZ9n/Application-detail-page?type=design&node-id=321-373&mode=design&t=48b59Wh9fI9OAVSc-0)
