### ISSUE TITLE
Review terms of design stripe to see if we can use their illustrations on new website

### ISSUE THREAD

**Issue by JoannaHill** [openaustralia/planningalerts#1654]
https://designstripe.com/license

**Comment by mlandauer** [comment]
On first reading of this it looks like we're in a grey area. 
> You may not publish or redistribute Design Materials outside of designstripe

but on the other hand you are expressly allowed to
> In perpetuity, but subject to these Terms, use, reproduce, copy, publish and distribute any Outputs, and any Integrated Materials within an Output.

They specifically disallow people to include the images as part of templates or use it as the main design element for a product which all seems perfectly fine and sensible.

There would clearly not be a problem with just using the image on a closed-source website. That's what the service is for.

The only issue is that it would be included in a piece of open source software. We would obviously need to be very clear in the README and the site itself that the illustrations are not from us and are copyright them.

Thinking this through I think we're okay to use them. It's extremely unlikely that someone would attempt to reuse the images from our source code which is the main threat to them that they're trying to mitigate. We'll also be clear that they can't be reused.
