### ISSUE TITLE
Model wikidata/website/strong identifiers for a council/authority

### ISSUE THREAD

**Issue by CloCkWeRX** [openaustralia/planningalerts#1669]
Example:
https://www.planningalerts.org.au/authorities/bayside is a bit ambiguous - is it  https://www.bayside.vic.gov.au/ or https://www.bayside.nsw.gov.au/ ?

It turns out it's Bayside NSW.
AKA
* https://en.wikipedia.org/wiki/Bayside_Council
* https://www.wikidata.org/wiki/Q26835506
* https://www.openstreetmap.org/relation/7038238 (which in turn points to a bunch of other IDs)

Modelling the wikidata id would let you at a minimum link to more information about the authority/council area/etc; or do an ajax request to get a whole bunch of data on the fly:
https://www.wikidata.org/wiki/Special:EntityData/Q26835506.json (population, websites, census urls etc being community maintained)

Or alternatively, using schema.org / sameAs terms, you could describe the https://www.planningalerts.org.au/authorities/bayside url as being the same as Q26835506; potentially ranking it higher in search results.

**Comment by mlandauer** [comment]
I LIKE!

**Comment by mlandauer** [comment]
> Or alternatively, using schema.org / sameAs terms, you could describe the https://www.planningalerts.org.au/authorities/bayside url as being the same as Q26835506; potentially ranking it higher in search results.

I don't understand this bit @CloCkWeRX. Could you please explain a little more please!

**Comment by CloCkWeRX** [comment]
https://schema.org/docs/gs.html basically + https://schema.org/sameAs is the what-is-it

https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data - is the how-does-it-improve things for search engine/result visibility.

**Comment by mlandauer** [comment]
Each authority now has a field for populating with the wikidata identifier. This is then used by a rake task to get the website url, the population and the ASGS 2021 ABS identifier which in turn is used by another rake task to get the boundary data for the authority. This isn't used anywhere publically yet but opens up a whole bunch of possibilities.

Oh yes and to enable the boundary data we migrated the whole PlanningAlerts application from mysql to postgres/postgis.

**Comment by CloCkWeRX** [comment]
WOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoooooooooooooooooooooooooooooooooOOOOOOOOOOOOOOOOOOOOOOOOOOooooooooooooooooooooooooooooooooooooooooooooooooOOOOOOOOOOOOOOOOOOO!
