### ISSUE TITLE
Design the landing page (desktop and mobile) using current production UX and content

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1670]
The purpose of this is to test and learn if the design decision around scale of things and proportion of things e.g. text, nav, images work well on a mobile, tablet and desktop. We're interested in whether the overall size of the text and line widths and the proportions of the pages is "right" across different devices. We're also interested in the course scale responsive behaviour (e.g. how two columns shifts to one column for mobile and what the breakpoints are).

At this stage we're much less interested in the detail of the design like colours, interaction, etc.

What we learn can be fed back into the master design system.

**Comment by JoannaHill** [comment]
We decided that the current landing page is the right balance of simple and complicated elements that make it a great page to use as a prototype for this milestone. We'll apply the new design look and feel to this page without redesigning the UX.

**Comment by JoannaHill** [comment]
![Image](https://user-images.githubusercontent.com/17328152/222009756-4810e876-5f47-4c28-97b0-8e9cdd5657c3.png)

Here is the design for the existing landing page using the new styles. Content unchanged, but new colours, type and imagery.

**Comment by JoannaHill** [comment]
Decided to leave out the footer because it doesn't affect the overall design at this stage.
