### ISSUE TITLE
Decide what menu items goes in the navigation

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1672]
In production currently the menu items are:
* Search
* Alert
* FAQ
* Coverage
* Get Involved
* Get the Data
* About
* Sign In

In the design currently (as of Feb 6 2023):
* Home
* Applications
* FAQ
* About
* Sign In

We need to finalise this so that we can be sure that the navigation design works for the number of menu items we have.

Some of the menu items (e.g. Coverage) in production currently are only accessible from the navigation so if we decide to not include them on the navigation then we need to figure out another way that users can access them.

**Comment by katska** [comment]
@JoannaHill done?
