### ISSUE TITLE
Design the interactive states of the header

### ISSUE THREAD

**Issue by JoannaHill** [openaustralia/planningalerts#1674]
Things like navigation (desktop, tablet and mobile), button, hover states for text links, images links. Do not include error states.

**Comment by JoannaHill** [comment]
@mlandauer Should we design all the interactive states for the accounts too?

**Comment by mlandauer** [comment]
> @mlandauer Should we design all the interactive states for the accounts too?

Do you mean the navigation showing the user when they're logged in? If so yes. Or do you mean something else?

**Comment by JoannaHill** [comment]
Yes I meant the navigation showing when the user is logged in/or logged out. Great.

**Comment by JoannaHill** [comment]
Making a list so I know what to cover here:

- [ ] Main navigation, off, hover and on states
- [ ] Logo, linking to homepage
- [ ] Search button
- [ ] Body text in trending applications linking to application page
- [ ] View more, trending application

.............

Could add more but they're not design.

**Comment by JoannaHill** [comment]
Matthew and Jo decided to just focus on the interactive states within the header (navigation including the account stuff). Ignore the rest till later milestone.

**Comment by JoannaHill** [comment]
We've designed all the interactive states for the menu area. They're all in figma here:
https://www.figma.com/file/GEaOuajueHGvfaFPsOUZ9n/Application-detail-page?node-id=168%3A82&t=tnKJsmrrS9GVUX4j-1

**Comment by katska** [comment]
@JoannaHill looks like the 'done' label doesn't close the issue. Closing.
