### ISSUE TITLE
Create a contact us page - Iteration 2

### ISSUE THREAD

**Issue by sabpop** [openaustralia/planningalerts#1684]
**What is it?**
A contact us form similar to Right to Know. That clearly states we are separate from planning authorities. It support people to clearly articulate their problem and aligns with email tags on Front app. 
It contains links to a series of help articles to encourage people to resolve their issues on their own first. 

**What we heard?**
Through research we found that:
- people are not always clear when they write in to us
- many people have assumptions that we are connected to a planning authority and mistakenly write in wanting something we can't help with
- A large potion of people are emailing in by mistakenly replying to an alert email without much context
- there's a desire from support staff to help people to solve their own issues first so they only need to assist on really tricky issues rather than known issues. 

These kinds of emails require back and forth to figure out which can be labour intensive for support staff who's time could be better spent on higher value interactions. 

Read more in the User Experience Map on Miro here:
https://miro.com/app/board/uXjVPrTUbvg=/

All card in the map apply as they are based on the inbox study of why people are getting in touch with Planning Alerts. But you can focus on: Replying to an alert, When an alert is missed or late, Contacting PA thinking it's council, Amending a comment, There's a problem, General feedback and questions. 

**Hypothesis**
A Contact us form would:
- Encourage people to be more thoughtful in describing their inquiry
- Reduce the amount of people emailing in by mistake
- Reduce the amount of people emailing in about known issues

**Design specifications**
- Editing and refining of copy on this page will be required
- When people are logged in they won't need to fill in their name and address
- When selecting reason for getting in touch: select closest relevant reason
- When selecting reason: "I'm trying to reach council" text appears to say "maybe you should go to your council site instead" (or similar) but still allow them to fill out form
- Create a button to allow file attachment
- Automatically record the last thing the person looked at and add it to support request.
- Emphasise we are not connected to planning authorities in context eg. with a reminder next to the submit button like on Right to Know
- Link to a page with links of all planning authorities websites.

**Sketch/ wireframe**
![Contact us_Iteration 2](https://user-images.githubusercontent.com/127382981/224222239-6309a7bc-48fa-4dd3-a76e-0582b99307db.jpg)

**Comment by mlandauer** [comment]
Also we could simplify this a little bit by combining the list of common problems under "Contact the PlanningAlerts Team" with the select box "I'm getting in touch because" in the following way:
* The "I'm getting in touch because" becomes the first field to fill out.
* As soon as you've selected something it immediately shows you some related links.
* If they're not useful you can carry on filling out the form.

This has the advantage that it simplifies the content and makes the prompt appear only after you fill something in it which makes it more relevant and more obvious. It's harder to miss that compared to some static content above the form

**Comment by sabpop** [comment]
We discussed today that there are a lot of options in the drop down menu and that it might be better to triage a bit so that's it's not an overwhelming list of things. 
I will have a look for some examples of this and add to this thread.

**Comment by sabpop** [comment]
@mlandauer I've had a look at the trends in UX for triaging support from the contact form. It looks like most places are presenting visually high level categories and then when you click on a category you get more specifics. This allows them to also connect help articles to those same categories. I'd say it seems that this makes it look like a less overwhelming list to users. 

**Etsy** Less visual more text
![Screenshot 2023-05-09 at 5 37 30 pm](https://user-images.githubusercontent.com/127382981/237029049-5031a26a-195b-4f4f-9532-bbc859f1cabe.png)

**Ebay** text boxes
![Screenshot 2023-05-09 at 5 34 42 pm (1)](https://user-images.githubusercontent.com/127382981/237030259-4aa60078-ad5d-4ae2-aa4b-52d9a1271f94.png)


**Apple** more visual
![Screenshot 2023-05-09 at 5 45 12 pm](https://user-images.githubusercontent.com/127382981/237029619-0d6ee03a-c31b-437c-909f-ec0c1aedd425.png)
![Screenshot 2023-05-09 at 5 29 57 pm (3)](https://user-images.githubusercontent.com/127382981/237029799-32920d4a-446a-42b2-b17e-f9eaf4926dfa.png)

**Amazon** start off visual
![Screenshot 2023-05-09 at 5 45 35 pm](https://user-images.githubusercontent.com/127382981/237029898-2c53bc2f-62dd-41ef-898b-f426a45ee23c.png)

I've also seen with Etsy, Ebay, etc. they have another level of triage for the type of user. eg buyer vs seller etc. 
![Screenshot 2023-05-09 at 5 34 42 pm (1)](https://user-images.githubusercontent.com/127382981/237031028-5ab60b54-f14d-46b3-bd23-8cc1a2fdcfbd.png)
![Screenshot 2023-05-09 at 5 51 26 pm](https://user-images.githubusercontent.com/127382981/237031047-7e47de22-3c77-4200-9d07-4559af255634.png)

Airbnb divides their support page by type of query this way:

![Screenshot 2023-05-09 at 5 52 27 pm](https://user-images.githubusercontent.com/127382981/237031196-cf436f69-8e76-4ab7-9c42-8a5618761d26.png)

**Comment by mlandauer** [comment]
@sabpop Super helpful. Thank you!
