### ISSUE TITLE
Contact us page - Iteration 1

### ISSUE THREAD

**Issue by sabpop** [openaustralia/planningalerts#1685]
**What is it?**
The first and most basic iteration of the Contact us page. 
See full version (iteration 2) here: https://github.com/openaustralia/planningalerts/issues/1684

**Key differences:**
- This is a more basic version more similar to the Right to Know Contact us page
- This iteration does not contain 'help articles'
- This iteration does not contain an 'attachments button'

![Contact us_Iteration 1](https://user-images.githubusercontent.com/127382981/224225727-61303e1e-8d17-4f00-a719-30a8982ca580.jpg)

**Comment by mlandauer** [comment]
Looks good to me

We'll also need to update all the links across the site where we just give the email address (contact@planningalerts.org.au) and instead link to this new page. Also we should update the "contact us" links on the footer.

**Comment by mlandauer** [comment]
@sabpop @katska I've rolled out a first pass of this to production at https://www.planningalerts.org.au/help/contact. Please have a look when you can and give me any feedback. There's a few words about what went into this at https://github.com/openaustralia/planningalerts/pull/1689

Note that this page isn't yet linked to from anywhere until it gets the 👍🏼 from people. When it's linked to and rolled out to production we can close this issue.

**Comment by sabpop** [comment]
Hey @mlandauer looks good to me. Just a couple of adjustments from me:
1. If possible, could you make these titles bolder: 
- Contact a planning authority
- Contact the Planning Alerts team

2. Put a link where you mention OpenAustralia Foundation.
3. Add a comma after: "To help us better help you" 
4. Can you make the text box a bit shorter, so that people can see the bottom of the page without needing to scroll too far. 

That's all I can think of for now.

**Comment by mlandauer** [comment]
Hi @sabpop thanks for that. I think I've addressed all your points in the latest deploy to production at https://www.planningalerts.org.au/help/contact. I'm a bit constrained by the current header sizes and formatting but within that I think it's a bit clearer now.

**Comment by mlandauer** [comment]
The changes addressing @sabpop's feedback were made in 44183cb7fed3d6a022319530bac78e9fd024f96a and ad01932c6b3487dcd2af417a2c84a6f5153c7925
