### ISSUE TITLE
Example address in address search should cycle through more examples

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1686]
I don't think in all the years we've been running PlanningAlerts anyone has pointed out to us or mentioned what the example address is "1 Sowerby St, Goulburn NSW 2580". I think we need to make it more obvious by cycling through the addresses of more big things. Here's a list (without street addresses) which might be a helpful starting point https://en.wikipedia.org/wiki/Australia%27s_big_things

**Comment by katska** [comment]
How about the big banana

And maybe some other big things?
