### ISSUE TITLE
Indirect link support - from development application page

### ISSUE THREAD

**Issue by sabpop** [openaustralia/planningalerts#1699]
**What is it?**
When users click on _'Get more information'_ on the development application page instead of being redirected straight away to the council or planning authority home page, and interim Planning Alerts page comes up to let them know they are being they are leaving Planning Alerts and going to a planning authority home page because there is no direct link to the application. 

**What we heard?**
- People with less experience with Planning Alerts dont understand why they are being redirected
- People struggle to understand why they can't go to a direct link of the application. The process of being redirected to a home page feels lengthy and convoluted as they need to type in the application number in order to find the application on the planning authority site
- When a link doesn't go directly to the application page, some users think there is something wrong and they write in to Planning Alerts to report a problem with the link. 

**Read more in the User Experience Map on Miro here:**
https://miro.com/app/board/uXjVPrTUbvg=/

Focus on cards: Finding documents, Lack of understanding leads to misinformed comments, There's a problem, 

**Hypothesis**
This would:
- Help people understand why this is happening and help prepare them for what they need to do to find the application. 
- Reduce amount of emails sent in reporting a problem with the link. 
- Help people to self serve. 

**Design specifications**
- Explain why this is happening and what happens now
- Include a link so they can learn more about this
- The wireframe shows a pop-up but this may be better as an entire page
- Include an option to go back to Planning Alerts or to go onto the planning authority site
- Let them know they will need the application number and include a 'click to copy' ie. "you'll need the application number: [display number with 'copy']".

Use human language, for example:
- "We'd love to send you to the right place but we can't.."
- "hold tight this might be tricky.. you are now leaving planning alerts."
- "Good luck, we hope you find what you're looking for"

**Implementation notes:**
This is a fiddly piece of work, it requires testing and understanding what different council websites do

**Sketch/ wireframe**
![Screenshot 2023-04-18 at 9 47 25 am](https://user-images.githubusercontent.com/127382981/232634266-d031dc6e-1c58-4579-b2b8-9c3a2dac7ddb.png)

**Comment by JoannaHill** [comment]
Quite shockingly, a design of this has been created, implemented and is now live and receiving great feedback! Well done team.. a great example of research to live.
