### ISSUE TITLE
when contact form subject line contains ' it appears garbled in frontapp

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1707]
When the contact form subject has an apostrophe it's garbled when it gets to frontapp subject

so **can't** turns into **'&#39;'** in the subject line of an email. I don't know how to write that here so it doesn't translate the characters into another apostrophe, so I'm going to spell it, the apostrophe in the email subject is displayed as ampersand hash thirty nine semi-colon!

for example:
Contact form: I can & # 3 9 ; t find a development application (no spaces in between the chars)

Can this be fixed? If not can workaround the subjects and remove the **'**s, maybe just a frontapp problem

**Comment by mlandauer** [comment]
I checked that this doesn't appear to be happening in PlanningAlerts. So if Front was showing those email subject as garbled it's likely a Front problem. I had a look in Missive and didn't see the same thing happening so I'm going to assume that this isn't a problem anymore.

Please reopen if it's still a problem
