### ISSUE TITLE
follow up when someone activates their account?

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1709]
I think there's something missing from the experience, because people write to PlanningAlerts to let us know they've activated their account. 

Congratulations. Next Steps. Set Expectations.... what should our response be at this important moment?
Why are they doing this? 

![Screen Shot 2023-04-27 at 4 02 20 pm](https://user-images.githubusercontent.com/1001129/234775338-5a63dc94-003c-4ae8-ac63-c497a2789948.png)

**Comment by mlandauer** [comment]
@katska can you email/talk to one of the people that emails us to let us know and ask them why they are doing this? It's hard to know what we can do if we don't know what people are thinking. Any ideas or gut feelings?

**Comment by katska** [comment]
I'm leaving it open in the research bucket for now and will follow up when it happens again if I remember
