### ISSUE TITLE
Purchase subscription to https://designstripe.com/

### ISSUE THREAD

**Issue by JoannaHill** [openaustralia/planningalerts#1713]
Having decided design stripe is a great service to use for our new Planning Alerts illustrations, Jo is ready to start accessing real illustrations for implementation.

**Comment by katska** [comment]
I've written to them asking if they have a nonprofit discount or freebie. If not I'll sign up for the plan. @JoannaHill What designstripe plan do we need and for how long?

**Comment by katska** [comment]
they're going to give us some kind of non-profit deal

**Comment by katska** [comment]
we got three months free, so we're good til August.
