### ISSUE TITLE
put a charity tick in the footer

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1714]

**Comment by katska** [comment]
we agree to these terms and conditions

Charity Tick - terms and conditions

Registered charities must read and accept these Terms and Conditions in order to access the Registered Charity Tick
1. Use of the Registered Charity Tick is subject to this license Copyright in the Registered Charity Tick is owned by the Commonwealth of Australia, represented by the Commissioner of the ACNC. The ACNC provides a license to use the Registered Charity Tick subject to these terms and conditions and solely at the discretion of the ACNC. This license is revocable at any time and at the sole discretion of the ACNC, it conveys a non-exclusive right to use the Registered Charity Tick, and it is non-transferrable. You cannot sub-license the Registered Charity Tick. For clarity, this is a license to use the Registered Charity Tick only. It does not constitute a license to use the ACNC logo.
2. Term of license This license commences on the date on which it is downloaded from the ACNC Charity Portal and ceases if the entity is no longer a registered charity under clause 5 or upon notice by the ACNC under clause 1.
3. The Registered Charity Tick is not an endorsement of an efficiently run, effective charity The Registered Charity Tick is a way for registered charities to easily show the public that they are registered with the ACNC, and it will also help members of the public find information about the charity on the Charity Register. The ACNC encourages members of the public to use the information on the Charity Register to make informed giving decisions.
4. It's for ACNC registered charities only  Only charities registered with the ACNC are able to claim that they are a "registered charity". Prior to using the Registered Charity Tick, charities need to ensure that they are registered with the ACNC. The easiest way to do this is by searching for the charity's name or ABN on the [Charity Register](https://edit.acnc.gov.au/charityregister). If charities need help to clarify their charity status, they can contact the ACNC advice line on 13 ACNC (13 22 62).
5. If an entity is no longer registered as a charity with the ACNC, it can no longer use the Registered Charity Tick If a charity has its registration as a charity revoked by the ACNC, the charity is required to immediately discontinue using the Registered Charity Tick. This includes no longer distributing printed materials containing the Registered Charity Tick. If a registered charity uses the Registered Charity Tick on printed materials and its registration as a charity is subsequently revoked, the cost of replacing printed materials will be borne by the entity.
6. It can be used on both electronic and print media  The easiest and most cost effective way of using the Registered Charity Tick will be electronic media, such as on the organisation’s website, email footer, social media and videos. Registered charities are welcome to use the Registered Charity Tick on print or display material, such as letterheads or banners, as long as the Registered Charity Tick is not presented in a way that may imply the ACNC’s endorsement of that material or its content. Please refer to the ACNC [Registered Charity Tick Style Guide](https://edit.acnc.gov.au/sites/default/files/Registered%20Charity%20Tick%20Visual%20Style%20Guide.pdf) for examples of appropriate use on electronic and print media. If registered charities are unsure about appropriate use of the Registered Charity Tick, they can contact [charitytick@acnc.gov.au](mailto:charitytick@acnc.gov.au).
7. Please link the Registered Charity Tick to the Charity Register If a registered charity is using the Registered Charity Tick for electronic media, the ACNC expects the registered charity to hyperlink the Registered Charity Tick to the Charity Register listing. This will give the public a direct link to the information the ACNC holds about the registered charity.
8. Unfortunately we’re unable to provide technical support  The ACNC is happy to provide the Registered Charity Tick and some general instructions, however we aren’t resourced to resolve any technical issues.
9. Registered charities must meet their legal requirements  The [ACNC Act](https://acnc.gov.au/about/acnc-legislation) sets out the obligations of registered charities and the ACNC website provides further information at [acnc.gov.au/managemycharity](http://acnc.gov.au/managemycharity). Registered charities must submit their Annual Information Statement within six months of the due date (avoiding the “red-mark” on the Charity Register) unless an extension has been granted, and meet all other obligations to maintain their registration status with the ACNC if they wish to use the Registered Charity Tick. The use of the Registered Charity Tick does not alter or lessen a registered charity’s obligations to the ACNC.
10. Access to download Registered Charity Tick If a registered charity has not filed its Annual Information Statement as required by the Australian Charities and Not-for-profits Commission Act 2012 (Cth) (ACNC Act), or is the subject of an enforcement power under the ACNC Act which is published on the ACNC Register under section 40-5(1)(f) of the ACNC Act, it will not be permitted to download the Registered Charity Tick.
11. Restrictions regarding the display of the Registered Charity Tick The Registered Charity Tick may only be used and displayed in accordance with the requirements set out in the [Registered Charity Tick Style Guide](https://acnc.gov.au/sites/default/files/Registered%20Charity%20Tick%20Visual%20Style%20Guide.pdf) regarding its appearance, including its colour, size and font.
12. Dispute resolution If you fail to comply with these terms and conditions, the Commonwealth of Australia represented by the Commissioner of the ACNC, reserves the right to take action against you to enforce its copyright ownership of the Registered Charity Tick.
13. Acceptance By downloading the Registered Charity Tick, you agree to these terms and conditions and agree to be bound by them. These terms and conditions may be changed or updated from time to time.

**Comment by katska** [comment]
Shared the tick with you in slack @mlandauer Sadly the style guide pages are broken. Emailing the ACNC about this.

**Comment by katska** [comment]
A couple of examples of how these are included on charity websites. 
![volunteeringQLD](https://github.com/openaustralia/planningalerts/assets/1001129/754f93c6-b790-42d1-9960-72c10bf4789c)

![womenlawyers_charitytick](https://github.com/openaustralia/planningalerts/assets/1001129/0cbbfa19-d1c2-420a-81c7-f249655a49ce)

**Comment by mlandauer** [comment]
This should be very helpful for @JoannaHill to figure out how not to make that weird ribbon thing not look completely out of place! Thanks @katska

**Comment by katska** [comment]
oh I found their [style guidelines](https://www.acnc.gov.au/sites/default/files/documents/2021-12/Registered%20Charity%20Tick%20Visual%20Style%20Guide_0.pdf) too

**Comment by JoannaHill** [comment]
Mocked up footer with charity logo. Matthew approved. SVG file sent for implementation.
