### ISSUE TITLE
NT LIS no longer have direct url to specific planning application

### ISSUE THREAD

**Issue by krisgesling** [openaustralia/planningalerts#1721]
For any NT planning application - if you select "Read more information" on the Planning Alerts page you receive a system error page on the NT Land Information System (NTLIS) website.

It looks like they have moved to a Vue based site and are dynamically loading specific planning applications in JS. I haven't yet found any url schema that will load a single specified page. You can get urls for linked documents but not the application overview.

Eg https://www.planningalerts.org.au/applications/2970590
is planning reference PA2023/0210

You now need to visit: https://www.ntlis.nt.gov.au/planning-notices-online/notices#/index
and search for the planning reference code.

**Comment by krisgesling** [comment]
I haven't had the time to look at this any further. However I wonder if a stop gap measure would be to change the "Read more information" link to point to the notices search page that I linked above?

Better than sending users to an error page I'd say.

**Comment by katska** [comment]
[krisgesling](https://github.com/krisgesling) Its been a long time coming but the new Planning Alerts now has a work around for those councils' pesky non-persistent URLs with an interim page that includes copy/paste the DA number. That's part one. Part 2 is updating the location to send you from 'more information' as per your suggestion. I'm hoping this is a quick fix once someone can get onto it.
