### ISSUE TITLE
Sign out option in main menu please

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1738]
I'd like to be able to sign out from the main menu shown in the screenshot below:

![IMG_A22255B3265A-1](https://github.com/openaustralia/planningalerts/assets/1001129/a106ce05-9edb-4cee-99eb-87eb52698c27)

**Comment by mlandauer** [comment]
@katska it's not obvious to me why logging out should be in the main menu especially on mobile. I'm guessing it's something that people only generally need to do occasionally if at all. The only situation that comes to mind where people need to regularly log out is using a shared computer and I would guess that that is much more likely to be a desktop computer (a la old school internet cafes).

Anyway, the way it is currently is that it is only one click further away. You click on the "Kat Szuminska" and then you can click on "Sign out"

**Comment by JoannaHill** [comment]
Not implemented.
I have added it to a list of ideas we might wish to test in usability testing.
