### ISSUE TITLE
Design and implement page after unsubscribing from an alert via an email. Not sure how this should relate to the process of unsubscribing in the web application under the profile section.

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1748]
Design and implement page after unsubscribing from an alert via an email. Not sure how this should relate to the process of unsubscribing in the web application under the profile section.

[https://www.bugherd.com/projects/366470/tasks/34](https://www.bugherd.com/projects/366470/tasks/34)

**Comment by JoannaHill** [comment]
Design created and implemented see Figma
