### ISSUE TITLE
Should we make it so that these notice type flash messages can be dismissed? Alternatively they could remove themselves after a certain amount of time though I've always disliked that because it assumes the person is going to instantly read it.

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1749]
Should we make it so that these notice type flash messages can be dismissed? Alternatively they could remove themselves after a certain amount of time though I've always disliked that because it assumes the person is going to instantly read it.

[https://www.bugherd.com/projects/366470/tasks/35](https://www.bugherd.com/projects/366470/tasks/35)

**Comment by JoannaHill** [comment]
Yes. Resolved through design and testing. Now implemented.
