### ISSUE TITLE
Purple help box overlaps with error text.

Only happens when the error is show on the contact us page

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1753]
Purple help box overlaps with error text.

Only happens when the error is show on the contact us page

[https://www.bugherd.com/projects/366470/tasks/39](https://www.bugherd.com/projects/366470/tasks/39)

**Comment by mlandauer** [comment]
Now that I've looked at this for five minutes I actually think it needs some design input. It makes sense to me that the error should be right below the form but the purple box completely dominates visually. First I thought why not remove the purple box when there is an error but then I thought "no that's exactly the point at which someone needs the guidance, when they're just starting to write their message".

**Comment by JoannaHill** [comment]
Resolved in Figma designs
