### ISSUE TITLE
Before public launch do some structured usability testing on new design

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1754]
Rather than just leaning on a beta phase with feedback using bugherd we would get more confidence that we haven't made any major boo-boos by doing some small usability testing maybe even including with accessibility in mind.

@JoannaHill would you be up for doing this?

**Comment by mlandauer** [comment]
I spoke to @JoannaHill about this and she was up for it. Furthermore, we will learn far more from doing some structured testing vs doing the beta rollout to a small group and asking for feedback. So, once we've done structured usability testing and have addressed the issues we should just roll the new design out to everyone and skip the beta rollout thing entirely.

**Comment by mlandauer** [comment]
I guess we need a plan on how to do this and what we need to do to prepare. Things that come to mind are:
* Plan on recruiting volunteers for usability testing
* How do we allow users during testing to do things with real-life consequences (like sending out comments or reporting comments) without causing issues? Do we design comments that can be ignored? Do we create a special test instance with fake data? Or something else?
* What tools do we need for testing? Do we do remote testing or in-person testing?
* What further changes do we need to make to the app to set up a user with the new theme?

**Comment by JoannaHill** [comment]
We decided to push on with going live for new look and do some usability testing afterwards. Jo will lead the mini project. More to come.

**Comment by JoannaHill** [comment]
No testing was conducted as part of the new designs instead we agreed to test optimisations and updates and also make use of the inbox to inform us of the biggest user issues and also invite those users to do research interviews with us.
