### ISSUE TITLE
Should the logo be clickable and take you to home? It's sort of standard practise I guess

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1758]
Should the logo be clickable and take you to home? It's sort of standard practise I guess

[https://www.bugherd.com/projects/366470/tasks/46](https://www.bugherd.com/projects/366470/tasks/46)

**Comment by mlandauer** [comment]
Sounds good! unless you're already home, in which case not :)

**Comment by JoannaHill** [comment]
Implemented and now live.
