### ISSUE TITLE
Main content of email alerts is below the fold. The introductory area which says pretty much the same thing as the subject of the email (with a little illustration) is too long IMHO and makes the email as a whole less impactful

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1763]
Main content of email alerts is below the fold. The introductory area which says pretty much the same thing as the subject of the email (with a little illustration) is too long IMHO and makes the email as a whole less impactful

[https://www.bugherd.com/projects/366470/tasks/48](https://www.bugherd.com/projects/366470/tasks/48)

**Comment by JoannaHill** [comment]
Completely redesigned to have items above the fold, and now live.
