### ISSUE TITLE
Would a little more space between the lines improve legibility here? Also this is a test comment. I'm definitely looking at the new theme

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1766]
Would a little more space between the lines improve legibility here? Also this is a test comment. I'm definitely looking at the new theme

[https://www.bugherd.com/projects/366470/tasks/9](https://www.bugherd.com/projects/366470/tasks/9)

**Comment by JoannaHill** [comment]
Tailwind's leading heights created more space in the header and has now been implemented and live.
