### ISSUE TITLE
Should this strip remain visible when scrolling to make it visually easier to navigate back to a page on planning alerts on a phone browser?

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1778]
Should this strip remain visible when scrolling to make it visually easier to navigate back to a page on planning alerts on a phone browser?

[https://www.bugherd.com/projects/366470/tasks/55](https://www.bugherd.com/projects/366470/tasks/55)

**Comment by JoannaHill** [comment]
Strip removed. Closed in bugherd too.
