### ISSUE TITLE
I like the element highlighting the number of comments on an application. Yet, the location doesn't seem quite right, especially on a mobile when it appears on a new line between 'comments on this application' and 'comments made here were sent to Casey ...

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1783]
I like the element highlighting the number of comments on an application. Yet, the location doesn't seem quite right, especially on a mobile when it appears on a new line between 'comments on this application' and 'comments made here were sent to Casey City Council".  I'm not sure if that's because I'd like to see the number read as part of a sentence and I currently find it hard to get used to.

[https://www.bugherd.com/projects/366470/tasks/56](https://www.bugherd.com/projects/366470/tasks/56)

**Comment by mlandauer** [comment]
@[Matthew Landauer](466560) I'd like your view on whether the scale of issue I use is appropriate, here I've said minor, as it doesn't screw up the page and it's not to hard to figure out what's meant.

**Comment by JoannaHill** [comment]
Fixed.
