### ISSUE TITLE
both 'contact us' and 'get in touch' currently link to emailto: and should instead point to https://www.planningalerts.org.au/help/contact - preferably with the "I want API access / commercial use" dropdown selected although that doesn't currently look ...

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1784]
both 'contact us' and 'get in touch' currently link to emailto: and should instead point to https://www.planningalerts.org.au/help/contact - preferably with the "I want API access / commercial use" dropdown selected although that doesn't currently look possible.

[https://www.bugherd.com/projects/366470/tasks/60](https://www.bugherd.com/projects/366470/tasks/60)

**Comment by mlandauer** [comment]
This is the same on the current theme for Planning Alerts. From memory this was an intentional choice at the time to leave those two links just in case there was a bigger problem with the contact us form that we didn't know about. 

I think those concerns are behind us so I think it makes sense to change that now on both the new and the old theme.

**Comment by katska** [comment]
@mlandauer true! People seem to be finding their way to the form already some of the time when they want commercial access of some sort. It certainly helps keep the inbox in order :)
