### ISSUE TITLE
include "across Australia" in the body of the about text. 

Either in position [1] or [2] - I think I prefer [1] but [2] also works :)

Planning Alerts is a free service [1] across Australia which searches as many planning authority websites as it can f...

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1785]
include "across Australia" in the body of the about text. 

Either in position [1] or [2] - I think I prefer [1] but [2] also works :)

Planning Alerts is a free service [1] across Australia which searches as many planning authority websites as it can find [2] and emails you details of applications near you. The aim of this to enable shared scrutiny of what is being built (and knocked down) in peoples' communities.

[https://www.bugherd.com/projects/366470/tasks/61](https://www.bugherd.com/projects/366470/tasks/61)

**Comment by katska** [comment]
Note to self - I reported this one in bugherd. 
@mlandauer are you concerned these issues come is as you even if I report them? It just means I'm more likely to forget about them, though hey that might not matter!

**Comment by mlandauer** [comment]
How about "Planning Alerts is a free Australian service which searches..."? @[Kat Szuminska](467994)

**Comment by mlandauer** [comment]
> Note to self - I reported this one in bugherd. @mlandauer are you concerned these issues come is as you even if I report them? It just means I'm more likely to forget about them, though hey that might not matter!

I'm less than impressed with the bugherd integration with github. This problem is one of the several ways it just sucks. I'm tempted to just turn it off. It just means we'll have to work in bugherd for these issues alone which feels kind of wrong to me.
