### ISSUE TITLE
In this example the text in the left hand column is much longer than the text in the right hand column. To me visually the big space in the right hand column between the three applications and the "view more latest applications" seems strange. I'm prett...

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1787]
In this example the text in the left hand column is much longer than the text in the right hand column. To me visually the big space in the right hand column between the three applications and the "view more latest applications" seems strange. I'm pretty sure though it's been built as per the design but I'm now questioning the design here.

[https://www.bugherd.com/projects/366470/tasks/63](https://www.bugherd.com/projects/366470/tasks/63)

**Comment by JoannaHill** [comment]
Limited each side to same number so it's even now.
