### ISSUE TITLE
edges of type look crunchy. Is it an aliasing/rendering problem?

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1789]
edges of type look crunchy. Is it an aliasing/rendering problem?

[https://www.bugherd.com/projects/366470/tasks/65](https://www.bugherd.com/projects/366470/tasks/65)

**Comment by mlandauer** [comment]
@[Kat Szuminska](467994) it looks okay to me on my machine and also what I see matches the screenshot. Are you seeing something different?

**Comment by mlandauer** [comment]
@[Matthew Landauer](466560) hard to know. I'll look on the laptop. Definitely looks off on my big screen. I haven't played with the screen settings at all though. I'll need to investigate. Do you have settings you can recommend if not default?

**Comment by JoannaHill** [comment]
No longer seems to render 'crunchy'.
