### ISSUE TITLE
Whimsy needed. Something nice happens when you mouse over "thanks"? like confetti sparkles or some other huzzah

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1790]
Whimsy needed. Something nice happens when you mouse over "thanks"? like confetti sparkles or some other huzzah

[https://www.bugherd.com/projects/366470/tasks/62](https://www.bugherd.com/projects/366470/tasks/62)

**Comment by JoannaHill** [comment]
Sparkles have been added. Great suggestion.
