### ISSUE TITLE
on a phone scrolling down, the order of elements doesn't make sense. Application search is 1. From there I hit search and How it works and 1,2 3 steps are long gone - or I scroll to the steps but cant act on them. I don't have an answer. Also I'm having...

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1792]
on a phone scrolling down, the order of elements doesn't make sense. Application search is 1. From there I hit search and How it works and 1,2 3 steps are long gone - or I scroll to the steps but cant act on them. I don't have an answer. Also I'm having trouble using bugherd on the phone so reporting via desktop set to phone settings. In this case what I show is the same if the experience is very different

[https://www.bugherd.com/projects/366470/tasks/67](https://www.bugherd.com/projects/366470/tasks/67)

**Comment by JoannaHill** [comment]
Item resolved in design and now live.
