### ISSUE TITLE
"Search Results" Sorted by section should come after "save this search" section, The title of search results would then be with the results.

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1793]
"Search Results" Sorted by section should come after "save this search" section, The title of search results would then be with the results.

[https://www.bugherd.com/projects/366470/tasks/68](https://www.bugherd.com/projects/366470/tasks/68)

**Comment by JoannaHill** [comment]
This has been switched around now: https://www.planningalerts.org.au/applications/address?q=470+Main+Arm+Road%2C+Main+Arm+NSW#results
