### ISSUE TITLE
a little more line space between each element here please. 
eg. half line space between "it was received by them 2 days earlier." and "Notified" Similiarly between notified and Comments. 

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1794]
a little more line space between each element here please. 
eg. half line space between "it was received by them 2 days earlier." and "Notified" Similiarly between notified and Comments. 

[https://www.bugherd.com/projects/366470/tasks/69](https://www.bugherd.com/projects/366470/tasks/69)

**Comment by JoannaHill** [comment]
Space increased. Now live.
