### ISSUE TITLE
Be a clear guide here at the culmination of the warning, provide solid instruction for our adventurer. "Copy the application reference number, you'll probably need it" something like that. The repetition of copy reinforces its importance.

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1797]
Be a clear guide here at the culmination of the warning, provide solid instruction for our adventurer. "Copy the application reference number, you'll probably need it" something like that. The repetition of copy reinforces its importance.

[https://www.bugherd.com/projects/366470/tasks/72](https://www.bugherd.com/projects/366470/tasks/72)

**Comment by JoannaHill** [comment]
Copy updated and now live: https://www.planningalerts.org.au/applications/3147976/external
