### ISSUE TITLE
would it be crazy for the "save this alert" process to not interrupt the page and simply refresh in this grey box with an announcement that this is saved, perhaps along with a link to manage alerts

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1799]
would it be crazy for the "save this alert" process to not interrupt the page and simply refresh in this grey box with an announcement that this is saved, perhaps along with a link to manage alerts

[https://www.bugherd.com/projects/366470/tasks/74](https://www.bugherd.com/projects/366470/tasks/74)

**Comment by JoannaHill** [comment]
Comment from Bugherd record:
Yes, it's possible but IMHO it's not worth the effort right now. In whole site we've got no ajax form submission anywhere. There are places that it might be helpful but we've kept away for simplicity sake. I think it's not on the critical path right now.

I've also noted this interuption as something to attend to in testing. https://github.com/openaustralia/planningalerts/issues/1835
