### ISSUE TITLE
Margin too wide leaving narrow area for words,  also text like most text is a bit big viewed on a mobile 

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1800]
Margin too wide leaving narrow area for words,  also text like most text is a bit big viewed on a mobile 

[https://www.bugherd.com/projects/366470/tasks/75](https://www.bugherd.com/projects/366470/tasks/75)

**Comment by JoannaHill** [comment]
Ammended text sizes and margins. Now live.
