### ISSUE TITLE
When there aren’t any comments, seeing the title ‘comments’ and ‘0 comments’ and absence of comments numerically spelled out seems repetitive 

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1801]
When there aren’t any comments, seeing the title ‘comments’ and ‘0 comments’ and absence of comments numerically spelled out seems repetitive 

[https://www.bugherd.com/projects/366470/tasks/76](https://www.bugherd.com/projects/366470/tasks/76)

**Comment by JoannaHill** [comment]
Been addressed in the new design and now live. No numbers if no comments.
