### ISSUE TITLE
Add guidance for making comments. Even if the extended version of guidance is further down the roadmap, we could improve the basics. Please comment on this @mattthew and assign back to me if needed

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1802]
Add guidance for making comments. Even if the extended version of guidance is further down the roadmap, we could improve the basics. Please comment on this @mattthew and assign back to me if needed

[https://www.bugherd.com/projects/366470/tasks/77](https://www.bugherd.com/projects/366470/tasks/77)

**Comment by JoannaHill** [comment]
Believe this has been addressed in the form hints until larger help project gets underway.
