### ISSUE TITLE
Feature Request: Admin Tool to Resend Confirmation Emails

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1803]
#### The Problem:
New users get stuck because they're not getting their confirmation emails. This seems to happen for a few reasons, like emails getting lost or bouncing back (some hard bounce but then other emails get through later). Asking them to look for the confirmation email has had zero positive results. Once lost this email seems lost for good. Right now, our only fix is to tell them to sign up again, which isn't great for them or us.

#### What We Need:
A workaround - a way for us to hit a button and resend those confirmation emails to anyone who didn't get them the first time. This would make things way smoother for our users and save us a lot of time dealing with these issues.

#### Why It Matters:
- **For Our Users:** It's frustrating to sign up and then get stuck because the confirmation email went missing. We want to make this first step as easy as possible for them.
- **For Us:** We're spending a lot of time tracking down what went wrong and telling users to try signing up again. It's a hassle, time suck, and not a great look. 

#### What's Needed to Make It Happen:
- A simple button in the admin area to resend confirmation emails.
- Make sure it's safe and won't be abused.
- A way to keep track of when we resend emails, just so we know what's going on.

#### Final Thoughts:
Fixing this would be a big win for everyone. It's a small thing that can make a big difference in making things run smoother and keeping our users happy. Plus, it'll free up admin time up to work on other stuff instead of dealing with this over and over.

Thanks for looking into this. It's one of those things that seems small but can really improve how we help our users and make admin role a little more satisfying.

**Comment by mlandauer** [comment]
Fixed by 97fd45aedc9a0fb738f27168ec74953d26caf66e. There is actually a resend confirmation email page which is hidden away. I've added a link on the registration page.

So, the "resend confirmation email" page is at:
https://www.planningalerts.org.au/users/confirmation/new

And the updated registration page (with the new link is at):
https://www.planningalerts.org.au/users/sign_up
