### ISSUE TITLE
this section feels directly related to the first section of statistics, would it make sense for them to be together or appear consecutively on the page

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1805]
this section feels directly related to the first section of statistics, would it make sense for them to be together or appear consecutively on the page

[https://www.bugherd.com/projects/366470/tasks/79](https://www.bugherd.com/projects/366470/tasks/79)

**Comment by JoannaHill** [comment]
New grouped together. Now live: https://www.planningalerts.org.au/authorities/blue_mountains
