### ISSUE TITLE
Words on "how to lobby your council" are out of date and have at least one broken link

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1806]
```
  <%# TODO: This following two sections are out of date with broken links %>
```

https://github.com/openaustralia/planningalerts/blob/3905560c6f967af36abddcef02205423fdc42206/app/views/_tailwind/documentation/how_to_lobby_your_local_council.html.erb#L19

**Comment by mlandauer** [comment]
The current wording is:

Use Mosman Council as an example of what good local councils can do. They provide a list of machine readable feeds which are licensed under a Creative Commons licence.

In NSW the Government Information (Public Access) Act 2009 (the GIPA Act) places requirements on local councils to publish the information they hold about development applications on their websites. For further arguments you can use, see the Federal Government's "Declaration of Open Government" of 2010 in which it was stated that the government supports
> strengthening citizen’s rights of access to information, establishing a pro-disclosure culture across Australian Government agencies including through online innovation, and making government information more accessible and usable

The reference to Mosman is completely wrong now. I'm really not sure what we should do instead. @katska any ideas?

**Comment by katska** [comment]
There are a few councils that either have been in contact with us directly wanting to make sure we can still see their data, and/or promote Planning Alerts as a way for people to stay informed, on their own websites (find the latter with [this search](https://www.google.com/search?client=firefox-b-d&q=planningalerts.org.au+site%3Answ.gov.au). Next step for me is to have a look at what they're doing, see if we have more success keeping those sites up than others, eg. common vendor. 

What does good look like now? Would we still prefer an ATDIS feed? Is that feasible? It not then what else?

**Comment by katska** [comment]
Currently a version of this reads:

How to lobby your local council to publish their planning data better

Here are just a few of the arguments that you can use when lobbying your local council to publish its planning data in a machine readable format. These are jumping off points to get you started.

    Be prepared for the first response being "No". That's normal. Have your arguments ready and be persistent.

    Use Mosman Council as an example of what good local councils can do. They provide a [list of machine readable feeds](http://portal.mosman.nsw.gov.au/pages/xc.track/ChooseFeed.aspx) which are licensed under a [Creative Commons licence](https://creativecommons.org/licenses/by/2.5/au/).

    In NSW the [Government Information (Public Access) Act 2009](https://legislation.nsw.gov.au/view/html/inforce/current/act-2009-052) (the GIPA Act) places requirements on local councils to publish the information they hold about development applications on their websites. For further arguments you can use, see the Federal Government's "[Declaration of Open Government](https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id:%22media/pressrel/AKCX6%22)" of 2010 in which it was stated that the government supports

        “… strengthening citizen’s rights of access to information, establishing a pro-disclosure culture across Australian Government agencies including through online innovation, and making government information more accessible and usable” 

Would you like to discuss the best approach? Have questions? Then [contact us](https://www.planningalerts.org.au/help/contact).

**Comment by katska** [comment]
Mosman link and creative commons licensing are still operational. Interesting to see the Mosman feed was down last year - https://www.planningalerts.org.au/authorities/mosman

**Comment by JoannaHill** [comment]
@katska and @mlandauer I believe we can close this issue. Could you confirm?
https://www.planningalerts.org.au/how_to_lobby_your_local_council

**Comment by katska** [comment]
I'm happy with this, and also can to suggest improvements to this page

Let's start with the headline:

**How to Lobby Your Local Council to Publish Better Planning Data**

I know we're referring to usable format not asking for better content, but it scans better and still just about covers that meaning.

Also how about we remove numbering from the suggestions, as they don't follow one another but are rather independent ideas. I also have some material that's been evolving in recent canned responses from when Councils are no longer making their data available. 
@JoannaHill It's recently becoming a bigger problem that councils are blocking Planning Alerts from scraping their website so the call to action for properly open data is ripe to bursting at this point. So is this the beginning of something more substantial - "Help free my local planning data" (its Friday evening now, so I'll come back to this question).

**Comment by katska** [comment]
@JoannaHill NSW and Open Government sections are different items also. 

Also, I'm not sure these are super helpful, nor if we have any idea about what influences planning authorities to do something different. Quite the opposite in fact. Could we plan to put some research time into this? And what do we feel convinced about in the meantime?

**Comment by JoannaHill** [comment]
I'm going to close this issue and start a new one with your suggested improvements
