### ISSUE TITLE
Bring back 'How is this free" section

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1807]
The style and sentiment around "how is this free" section on the homepage are great. 
Refine it now focusing on 'we're small, be nice" and perhaps "thanks for your patience" and don't say so much about the specifics of our daily lives or operations while keeping the general impression.

@mlandauer having reflected on your observations of the initial text there now, that's feels like a good starting point. Do you want to keep the picture? Is there anything else?

**Comment by katska** [comment]
How about this for another pass @mlandauer (I think there are a few different messages here, and is the title the right thing, I'm not sure the words below really answer that question, nor do they seem to be aimed at answering that question). Still here's a go at the brief, and adding 'keep it positive' as an extra, and there's a bit of humility and a bit of pride:

How is this free?

We're on a mission to make sure you're informed and empowered to have your say, all for free! What began as an experiment became a labor of love, and has evolved into a service operating Australia-wide

Clever use of design and technology help offer you a service that steps in where planning authorities fail. Our sleek design refresh helps smooth things along, but it's still our tiny team that keeps Planning Alerts running. 

So, please bear with us if we're a bit slow to reply to emails or if things occasionally slip through the cracks. We're juggling a lot with a little, aiming to give you an exceptional experience. Thanks for understanding our limitations and celebrating our successes with us. Your support keeps us going strong!

**Comment by JoannaHill** [comment]
This issue has been superceded by this issue: https://github.com/openaustralia/planningalerts/issues/1836
We can carry on the conversation there.
