### ISSUE TITLE
In all the places where we say "create an account or sign in" we could just say "sign in" instead which would simplify the somewhat clumsy language. The sign in link would take you to a page where you could register. It would be an extra click for regis...

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1808]
In all the places where we say "create an account or sign in" we could just say "sign in" instead which would simplify the somewhat clumsy language. The sign in link would take you to a page where you could register. It would be an extra click for registering but give a much clearer path for users I think.

[https://www.bugherd.com/projects/366470/tasks/80](https://www.bugherd.com/projects/366470/tasks/80)

**Comment by JoannaHill** [comment]
Believe this has been addressed in the hint text in the form and is now live.
