### ISSUE TITLE
It feels inconsistent to be able to see comments from a year ago when clicking "view all comments..." , but see no applications when clicking through view all recent applications. The way this is displayed makes it seem they're a parallel data set. Shou...

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1810]
It feels inconsistent to be able to see comments from a year ago when clicking "view all comments..." , but see no applications when clicking through view all recent applications. The way this is displayed makes it seem they're a parallel data set. Should "recent applications" change to "all applications" and show the most recent ones so that the experience is consistent across comments and applications options here?

[https://www.bugherd.com/projects/366470/tasks/82](https://www.bugherd.com/projects/366470/tasks/82)

**Comment by JoannaHill** [comment]
This issue is listed twice. Closing this and keeping: https://github.com/openaustralia/planningalerts/issues/1825
