### ISSUE TITLE
when I see this comment I'm curious and want to see what application it was commenting on. There doesn't seem to be an option for this here.

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1811]
when I see this comment I'm curious and want to see what application it was commenting on. There doesn't seem to be an option for this here.

[https://www.bugherd.com/projects/366470/tasks/83](https://www.bugherd.com/projects/366470/tasks/83)

**Comment by JoannaHill** [comment]
Design improved and already now live: https://www.planningalerts.org.au/comments
