### ISSUE TITLE
Design for "now check your email" pages for both account registration and activation. These pages are what you're sent to after you sign up for an account or ask to activate your account

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#1812]
Design for "now check your email" pages for both account registration and activation. These pages are what you're sent to after you sign up for an account or ask to activate your account

[https://www.bugherd.com/projects/366470/tasks/84](https://www.bugherd.com/projects/366470/tasks/84)

**Comment by JoannaHill** [comment]
Designs implemented and live
