### ISSUE TITLE
Investigate alternative methods to submit user comments to the council when they are not accepting them through Planning Alerts

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1817]
More than isolated incident now, and in need of attention. While there may be other work to do to ensure that comments made via planning alerts are accepted, is there something else we can do that could help make sure the comment gets where it needs to go and is considered?

**Comment by katska** [comment]
So this one is about making sure the comment reaches council somehow.

**Comment by JoannaHill** [comment]
Matthew says he doesn't want us to institutionalise comments not being accepted within our service.
