### ISSUE TITLE
Bring back "distance from Alert address" for each DA in an alert

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1828]
Someone would like the distance between the alert address and the location of each DA in the alert shown.
Is that something intentionally removed? Are we willing to reinstate?

Feedback is:
"Nice and fresh new look guys however previously you would show the distance from [address at centre of alert supplied]
Can I still be notified regarding this??"

**Comment by mlandauer** [comment]
Personally I think the distance is quite valuable. @JoannaHill can you have a think if this could work in the new email design?

**Comment by JoannaHill** [comment]
Yay feedback. Yeah sorry foiks I accidently dropped that off the designs. Reinstated and available for preview in Figma: https://www.figma.com/design/GEaOuajueHGvfaFPsOUZ9n?node-id=4166-1605#854308710

**Comment by katska** [comment]
@JoannaHill looking good to me!

**Comment by katska** [comment]
Missive conversation: https://mail.missiveapp.com/#inbox/conversations/7ed905db-6f2a-42c8-86e8-107192a7065e

**Comment by mlandauer** [comment]
Also now deployed to production 🎉
