### ISSUE TITLE
Wrong applications displayed as most commented from "Search" page

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1830]
Applications displayed under most commented applications display "0 comments". 

As viewed from selecting "Search" from main menu - https://www.planningalerts.org.au/applications/address
![Screenshot 2024-06-28 at 10 24 18 AM](https://github.com/openaustralia/planningalerts/assets/1001129/7fe5eda0-2b88-46fd-b434-48e4d0f3da0e)

Further investigation shows they're not the most commented applications, so the problem is that the wrong applications are displayed on this page only.

However all fine if looking from the homepage.

**Comment by mlandauer** [comment]
Fixed by 17ee55c0b09653c5d3955212dd8e6b254d4bf9f4
