### ISSUE TITLE
Links not working for some users in alerts

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1834]
Links aren't working in the new email alerts for some users.

--
Source: https://mail.missiveapp.com/#sent/conversations/d8cba30a-6d4d-452c-b13d-4fdded22e13a

**Comment by mlandauer** [comment]
No. not everyone. We know they are working in a bunch of browser and email clients because we've tested them

**Comment by katska** [comment]
@mlandauer  ooops! That was a super unclear description, that's not what I meant at all, specifically its that they're not working for some users in some circumstances. Thanks for pointing this out! I've changed the issue description.

Latest report 
"I cant click on anything in PINK in the email to go to the alert notice. I am using PC with Windows 11 and Microsoft Edge as my browser. Email is Outlook."

**Comment by katska** [comment]
Missive conversation: https://mail.missiveapp.com/#inbox/conversations/ce86967c-f741-4dc7-9535-2edd487b0df1

**Comment by katska** [comment]
Missive conversation: https://mail.missiveapp.com/#inbox/conversations/96e6fc88-aec4-4f07-bcc4-02bd2d8b4fac

**Comment by katska** [comment]
Missive conversation: https://mail.missiveapp.com/#inbox/conversations/19c8124b-b8ee-44db-a2d0-c6bfa14e5967

**Comment by katska** [comment]
Missive conversation: https://mail.missiveapp.com/#inbox/conversations/3a64703c-8ec7-412c-892b-b1ae6bc549d1

**Comment by katska** [comment]
Missive conversation: https://mail.missiveapp.com/#inbox/conversations/40f560d2-ab8d-4b53-94a8-b5a294976060

**Comment by katska** [comment]
Missive conversation: https://mail.missiveapp.com/#inbox/conversations/0ed5ae30-17ce-4752-b514-10fc0db9659a

**Comment by mlandauer** [comment]
@katska I've pushed out a change I've been working on today. I hope that it might fix the problem with the links. There are still lots of layout issues with outlook which I'm not going to tackle today. I'll leave this open until we hear back from some users that it's been fixed.

**Comment by JoannaHill** [comment]
@katska any feedback since the change?

**Comment by katska** [comment]
@JoannaHill @No new reports and no responses from those who reported the issue. Looking via cuttlefish reported clicks and opens... 🥁 ... I think we can call this one fixed!
