### ISSUE TITLE
From bugherd: Content suggestions for 'Get the data' section (see description)

### ISSUE THREAD

**Issue by JoannaHill** [openaustralia/planningalerts#1845]
- On the request page/ under 'What happens next' title - copy change suggestion: "Your request will be reviewed by a human at the OpenAustralia Foundation. We will try to do this quickly and reply to your request by email."... this also shifts the decision making point to the org not the service.
- Change page title to "Request a Community Supported API key'
- Change subtile to from "What exactly do you mean by non-commercial?" to "Who Can Apply for Community Supported API Access?"
- In the form, add API key email address to the form, according to our process they sign up for an API key first and try it out. 
- Include contact email / name if different to a API key email address (will there be an additional page for more contact info / org / ABN if applicable / address etc).
- Button title change to: Send Request
- In the pricing page, remove all the body copy from 'Under certain..."
-

**Comment by JoannaHill** [comment]
See related ticket: https://github.com/openaustralia/planningalerts/issues/1782

**Comment by katska** [comment]
in the process we trust, this is not done but not relevant now.
