### ISSUE TITLE
Add some light guidance for making comments

### ISSUE THREAD

**Issue by JoannaHill** [openaustralia/planningalerts#1853]
From Kat from Bugherd: 
Add guidance for making comments. Even if the extended version of guidance is further down the roadmap, we could improve the basics. 

Bigger version of guidance sort of documented in Sabina's issue here: https://github.com/openaustralia/planningalerts/issues/1691

**Comment by JoannaHill** [comment]
![Screen Shot 2024-07-18 at 12 48 23 pm](https://github.com/user-attachments/assets/d35c863d-faa8-4d2b-b82d-b65416fae6e5)

**Comment by katska** [comment]
Using the points seen as useful in #1691 to start with, and turning these into questions as requested there into a kind of checklist

-     What details from the application support your view? (could include a prompt to review "more information")
-     Can you list your key points clearly and concisely? Would bullet points help?
-     Why is your feedback important? What makes you qualified to comment? 
-     How will this development impact you, your family, or your community?
-     Who are you representing—yourself, your family, your business, or a group?
-     Have you checked your spelling and grammar for clarity?

I'm not quite sure about turning the point about being respectful into a question for a checklist: Have you presented your views respectfully and without insulting anyone? seems a bit heavy handed.
@JoannaHill does this feel like it's in the ballpark? feedback very welcome.
Also I note that some of the questions seem dry without examples, for instance "what makes you qualified to comment" which might be as simple "as I live nearby/down wind of this development"

**Comment by JoannaHill** [comment]
Closing this in favour of better idea and better issue description over here: https://github.com/openaustralia/planningalerts/issues/1691
