### ISSUE TITLE
Title change suggestion: How to Lobby Your Local Council to Publish Better Planning Data

### ISSUE THREAD

**Issue by JoannaHill** [openaustralia/planningalerts#1856]
This issue relates to this page on the website (and the links to it)
https://www.planningalerts.org.au/how_to_lobby_your_local_council

From Kat:

- Title change: How to Lobby Your Local Council to Publish Better Planning Data
I know we're referring to usable format not asking for better content, but it scans better and still just about covers that meaning.

- Also how about we remove numbering from the suggestions, as they don't follow one another but are rather independent ideas. I also have some material that's been evolving in recent canned responses from when Councils are no longer making their data available.

- @JoannaHill It's recently becoming a bigger problem that councils are blocking Planning Alerts from scraping their website so the call to action for properly open data is ripe to bursting at this point. So is this the beginning of something more substantial? - "Help free my local planning data" (its Friday evening now, so I'll come back to this question).

- @JoannaHill NSW and Open Government sections are different items also.
Also, I'm not sure these are super helpful, nor if we have any idea about what influences planning authorities to do something different. Quite the opposite in fact. Could we plan to put some research time into this? And what do we feel convinced about in the meantime?

**Comment by JoannaHill** [comment]
I have updated the design in Figma to reflect your suggestions @kat 
I think the title change and taking off numbers can be done quickly. 

It sounds like there may be a bigger piece of work underlying this. Maybe we can write it up together for the backlog?

**Comment by JoannaHill** [comment]
Figma mock up is here for review: https://www.figma.com/design/GEaOuajueHGvfaFPsOUZ9n?node-id=3141-380#909107538

**Comment by mlandauer** [comment]
Fixed by dc809c1be55a0c0fc1b134a084bf3220b24ca757 and 309cc5e7d9dcecf798e12aaca6479a18c31c1e89
