### ISSUE TITLE
Design and make work a screenshot of the website when sharing on LinkedIn etc

### ISSUE THREAD

**Issue by JoannaHill** [openaustralia/planningalerts#1857]

**Comment by mlandauer** [comment]
@JoannaHill Please design an image at a resolution of 1200x630. Also we want this image to be just for the landing page.

**Comment by JoannaHill** [comment]
Design for this in Figma here: https://www.figma.com/design/GEaOuajueHGvfaFPsOUZ9n?node-id=4643-2945#885501079


![Image](https://github.com/user-attachments/assets/f7ffe649-673c-4bb0-8f74-240950164087)
