### ISSUE TITLE
Display the status of an application (on website and in alerts)  e.g. 'on display'/'out of display' period

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1858]
Some come from the general "Planning Register" that may contain DAs and other items at any stage of development. Now and then someone complains that the DA is not yet in the official notice period. 

Yes, anyone can still find these applications on the council website. However there's an unnamed expectation from the process we describe - sign up, get notified, comment and an early warning of DAs in the works doesn't neatly fit this idea. 

@JoannaHill @mandauer do you think sharing DAs early and often (ie as soon as they hit the authority planning register) is better, or having a consistent approach to what's shared as far as possible (ie only those on the public notice period)?

Should we try to learn whether it's generally considered a help or hindrance?

**Comment by katska** [comment]
Prompted by someone who initially wrote in via the contact form who said they found it useless to receive notices about DAs that are not yet on public notice. They suggest that if some people want to see them before they're on notice, that "could be solved by a tick-box. Do you want an alert as soon as the notice is registered or as soon as it’s “at advertising”

**Comment by JoannaHill** [comment]
From a conversation with Matthew I'm learning it's a PA principle to display applications whether they are available for comment or not (either too early or too late). So I guess we are questioning the principle?

Technically it sounds near impossible to reliably display only DA's ready for comment. But I'll let Matthew express that better.

**Comment by katska** [comment]
@JoannaHill @mlandauer  AFAIK when a DA appears on Planning Alerts is not consistent from council to council. 
If it's a principle, can/should we communicate clearly that we publish them as soon as they're available - ie. if there is a planning register we publish from there if possible, and if not, then we take from the 'on notice' list. Is that true. where should we say this?

**Comment by JoannaHill** [comment]
I have significantly altered this issue from it's original purpose to be more in line with what we have done in the new site. 
The new site accidentally left off any notifications about the status of the application. This is a great opportunity to review the experience of this and improve it.

**Comment by JoannaHill** [comment]
Double up. Closing this in favour of this:
https://github.com/openaustralia/planningalerts/issues/1861
