### ISSUE TITLE
People want to see a DA if it's on notice for a second time

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1862]
People write in semi regularly expecting to see a DA pop in their inbox when it's on notice again. We don't currently refresh updates to DAs so they're not updated and people aren't notified again. It would be especially useful when a DA has been contentious and required changes over time.

Whether it was contentious or not I don't know, but I'll link a convo where someone raised the issue.

**Comment by katska** [comment]
Missive conversation: https://mail.missiveapp.com/#inbox/conversations/f77a0077-0da1-4267-92ff-5e051bca6e20

**Comment by JoannaHill** [comment]
Issue double up.
Better written one over here: https://github.com/openaustralia/planningalerts/issues/1814
