### ISSUE TITLE
Make link text more specific so user knows what to expect when clicking "Email alerts" on an application

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1864]
The sentence here is related to a specific address, but when I follow the link to 'email alerts' it takes me to 'create new alert' without the address of the DA page I just came from prefilled which is what I expected, although it's incongrous to me. I'm curious to know if anyone uses it to sign up? 

![Screenshot 2024-07-26 at 3 35 34 PM](https://github.com/user-attachments/assets/82b7e486-36c3-4b89-ab20-fa06e731ebb9)

**Comment by JoannaHill** [comment]
Omg good pick up, this is so unclear for a user what this link will do! I am questioning it's very existence given we invite user to save the search just a little further down the page (and in very specific terms).

**Comment by JoannaHill** [comment]
@mlandauer how would you feel if we removed the link enitrely?

**Comment by JoannaHill** [comment]
Matthew and Jo are reviewing propose text change: Notify Me!

**Comment by mlandauer** [comment]
Makes more sense on second thoughts to get rid of the link because you can sign up for the alert in the big grey box just below. So, fixed by 987a15b145da1fe1174c238decc55f399c1eb109.
