### ISSUE TITLE
incite action of some kind when a council rejects comments made via planning alerts

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1865]
Sometimes councils stop accepting comments made via Planning Alerts. Getting in touch with them has not thus far helped. It's been talk to the hand scenario, they've already decided to put them in the too hard basket. 

Why? 
and What can we do about it?

One example is Moreton Bay, which is beyond my comprehension:

"For a submission to be deemed 'Properly Made' it must include the Person's Name & Address.  Due to the Privacy Notice the local council when lodging the comments against the DA the council marked the Person's Name & Address  details as 'Redacted' effectively making the Submission not properly made."

I read this as, because we have a privacy notice that is specifically about only using the info shared with them in connection with commenting on the DA, they then do something that scuppers its raison d'etre. Bureaucracy gone mad.

So now what? Putting this here as a place to regroup and problem solve.

**Comment by katska** [comment]
Missive conversation: https://mail.missiveapp.com/#inbox/conversations/d8f76e65-40a8-4e58-9c2a-746252e70414

**Comment by katska** [comment]
related to https://github.com/openaustralia/planningalerts/issues/1818

**Comment by JoannaHill** [comment]
Double up, now merged to https://github.com/openaustralia/planningalerts/issues/1826
