### ISSUE TITLE
daily limit disappears when editing when mouse not over on API key user page

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1877]
editing an [API key page in the admin interface ](https://www.planningalerts.org.au/admin/api_keys/#/edit) ...
I see a limit I type in when mouse is over the field but not when mouse is not hovered, see screenshots below
(hover)
<img width="615" alt="Screenshot 2024-08-05 at 2 21 40 PM" src="https://github.com/user-attachments/assets/c24ef8a1-6f31-489f-9a5b-2727b6a0ec39">
(not hovered)
<img width="607" alt="Screenshot 2024-08-05 at 2 21 46 PM" src="https://github.com/user-attachments/assets/273acebf-87d1-4cd4-b261-a9ce6897558f">

**Comment by mlandauer** [comment]
It looks like the culprit was upgrading to the beta for administrate. That seems to have broken something in the stylesheet. I'll revert that.
