### ISSUE TITLE
Create a way for Andy to have access to the Admin Panel to better analyse API usage and users

### ISSUE THREAD

**Issue by JoannaHill** [openaustralia/planningalerts#1891]
At the moment admin access is all or nothing. If we think there's enough of a benefit development work could be done to provide Andy view access to live API usage data for analysis and strategy.

**Comment by mlandauer** [comment]
Done! There is now a "api_editor" role which a person with "admin" role can now assign to a user that gives them permission to access the admin interface but only view users and view and edit api keys.
