### ISSUE TITLE
Improve FAQ: add info about why you may not see a DA

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#487]
Prompted by a question from a user about whether if there is no DA on planningalerts for a property there is indeed no DA? There are a number of reasons why we might not see a DA for a property, some of which are covered in the FAQ, but not all.

Not covered. 
- there was a break in service when a scraper was broken.
- a DA was for whatever not published on their website by the Authority in their usual way (we have no way of knowing)

**Comment by mlandauer** [comment]
Won't fix. See #1527
