### ISSUE TITLE
Explain what people can and can not do with API data (e.g. no spamming)

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#537]
There are things you clearly can and cannot do with information you collect from DA's, and this varies state by state, eg. you can't spam everyone who is putting in a DA (in some places). Research and write a very clear set of guidelines about these and about PlanningAlerts position on what is acceptable use, based on what we find here and our own moral compass. No spammers here!

**Comment by mlandauer** [comment]
Yes, I think we should do this.

**Comment by mlandauer** [comment]
I think we now do this under a "be nice" section
