### ISSUE TITLE
Add GeoJSON support to API

### ISSUE THREAD

**Issue by DylanFM** [openaustralia/planningalerts#539]
I may be mistaken here, but it appears that the JSON returned by the API is not GeoJSON. How would you feel about offering [GeoJSON](http://geojson.org/) in the API? Would make integration with libraries like [Leaflet](http://leafletjs.com/reference.html#geojson) super easy.

I understand that in the interest of backwards compatibility this would need to be offered as another format or possibly as a default if we released a new version of the API.

Do we have any data of API usage - number of clients, hits, what formats etc they're requesting? We may be in a position to remove features that aren't used.

**Comment by charliedotau** [comment]
+1 for GeoJSON
