### ISSUE TITLE
guidelines for authorities

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#575]
Create clear guidelines to councils to help them be planningalerts friendly. There is not much love on our get involved page to them at the moment. One issue is set up their responses to comments from planningalerts.org.au correctly. ie their reply goes to the commenter, and not planningalerts. This is happening with only two councils at the moment Boroondara and just now Victor has just started doing this.

Not sure if this should go under councils at http://www.planningalerts.org.au/getinvolved, or be part of more information talking specifically to councils perhaps on another page.

**Comment by mlandauer** [comment]
I don't see any evidence that a council has ever really looked at the site to try to find that kind of information. If they had I would have expected some indication when they emailed us.
