### ISSUE TITLE
Don't resend comment when confirmation link is clicked again

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#579]
Currently every time you click a comment confirmation link it gets resent to council. This should not happen.

**Comment by mlandauer** [comment]
This was fixed a long time ago in https://github.com/openaustralia/planningalerts/commit/5dde57e40d2bdfcc3d8b41e6b5bc3ecb0a7c22d2#diff-50540c55884d52c08d3e6888c9ebed3214922e11d08beb6d399f80dab858d989
