### ISSUE TITLE
Comments on JRPP applications should go direct to council

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#595]
Recently Lisa from the NSW Department of Planning & Environment contacted us to say that comments on [JRPP applications](http://www.planningalerts.org.au/authorities/nsw_jrpp) should normally go direct to the council instead of to them (they've been kindly forwarding them on so far).

**Comment by mlandauer** [comment]
It seems we have may a similar problem going on now with the SA Planning Portal
