### ISSUE TITLE
Update the email signup policy to say we will occasionally email about donations/feedback

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#602]
This should let people know that we will email them occasionally about donations or other things related to improving the project.

Here is the [current notice](http://www.planningalerts.org.au/alerts/signup) :

> You will receive email only when there are new applications nearby and no more than once per day.

**Comment by mlandauer** [comment]
Yes, we should do this.

**Comment by mlandauer** [comment]
We should definitely do this! It's a simple wording change and we don't make it clear enough that's what we do
