### ISSUE TITLE
Add a notice asking citizens to donate to application page, if they've come from alert

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#605]
If people are signed up to alerts and are visiting an application via one, they are likely to be getting use from the project and may want to support the project with a donation.

We place put a notice underneath the application, but above the comment section. It's not the most important thing on the page, that's the application the citizen has come to see, so it shouldn't site above that.

Text could be:

> **Do you find Planning Alerts useful?**
> An independent charity, the [OpenAustralia Foundation](oaf.org.au), runs this project to make sure people are informed about changes to their local area. Chip in to support PlanningAlerts with a tax deductible donation.

then a button, ['donate'](oaf.org.au/donate/planningalerts).

**Comment by mlandauer** [comment]
This feels like it might get in the way of the utility of the page and be a bit "in your face". We've learned over the years that we can be more successful with end of financial fundraising drive via email
