### ISSUE TITLE
make /donate text clearer and more direct

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#606]
Here’s the current text at http://www.planningalerts.org.au/donate :

> Donate to the OpenAustralia Foundation
> 
> PlanningAlerts is brought to you by the charity the OpenAustralia Foundation. We are a Charitable Institution with Deductible Gift Recipient (DGR) status which means that any donation you make over $2 is tax deductible.
> 
> To date the OpenAustralia Foundation has achieved much on minimal funding and generous volunteer input. To maintain the services we offer and to build new and exciting projects however, we need the financial support of the public.
> 
> We're very proud of what we have achieved and would like to continue growing and providing a free service to the community. Your donations will help us do this. So, please make a tax-deductible donation. We will put your donation to work straight away.
> 
> The donation button below will take you to the secure PlanningAlerts donation page at the OpenAustralia Foundation website. Thank you for your support!

**Comment by CloCkWeRX** [comment]
https://www.openaustraliafoundation.org.au/donate/ by itself is really good; hits all of the notes of something like https://www.redcross.org/donate/donation

Might be better to link directly there. 

Failing that; something like:

![image](https://cloud.githubusercontent.com/assets/365751/14225683/409898cc-f913-11e5-899b-b2bade9bb441.png)

Might improve things.

**Comment by mlandauer** [comment]
We're now accepting donations only through donorbox. That page gets redirected to the main OAF donation page
