### ISSUE TITLE
replace configuration.rb with .env variables

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#616]
I'm no dev ops, but having keys in the app/models/configuration.rb file seems a bit nasty?

It's also a bit of a drag in dev, having it as an uncommitted file.

**Comment by henare** [comment]
:+1: :+1: :+1:

**Comment by henare** [comment]
Cool, this is all done now.

Most configuration should Just Work. There are [some settings](https://github.com/openaustralia/planningalerts/blob/master/.env#L23-L32) you might like to change in development.
