### ISSUE TITLE
Always capitalise Western Australia abbreviation "WA"

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#625]
WA appears as “Wa”. My understanding is that both letters should be captialised.

See http://www.planningalerts.org.au/?q=129-131+Edward+Street%2C+Perth%2C+WA+6000 for example.

**Comment by mlandauer** [comment]
I think that's an issue with the scraper

**Comment by henare** [comment]
Looks like the scraper has it OK https://morph.io/planningalerts-scrapers/vincent

It might be our address capitalisation-fixing code.

**Comment by equivalentideas** [comment]
Could it be in what's coming back from maps api?
