### ISSUE TITLE
Add a note to the readme about the theming

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#627]
Contributors need to test changes across both themes, but there's no way of knowing this currently without digging in the config file :)

Here's the note from @mlandauer from #626 :

> Point your browser at nsw.127.0.0.1.xip.io:3000
> 
> You'll see in app/models/configuration.rb there's a THEME_NSW_HOST - if the browser sees that domain it will show the other theme.
> 
> The theming only affects the views so it doesn't matter for tests unless they're view tests (of which there are very few).

**Comment by mlandauer** [comment]
This issue relates to a theming which we have removed. So, closing.
