### ISSUE TITLE
Compile list of local councillors

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#652]
Starting point was:
* http://www.pastvtr.elections.nsw.gov.au/LGE2012/lge-index.htm - this is "protected" by some anti scraping tech that means that you need to have javascript switch on. This is now possible with morph.io

Just discovered this:
http://www.olg.nsw.gov.au/sites/default/files/lgdfull.txt
which was on the page
http://www.olg.nsw.gov.au/content/download-council-contact-details

For some reason the list of councillors is only on one of the downloadable datasets and not in a structured format. Definitely better than tons of scraping

**Comment by mlandauer** [comment]
See https://morph.io/openaustralia/nsw_lg_directory_councillors

Also discovered a list from NSW greens which we could cross-reference to get contact details for those councillors.

http://nsw.greens.org.au/councillors-by-council

I wonder if other parties have similar lists

**Comment by mlandauer** [comment]
For victoria: http://www.dtpli.vic.gov.au/local-government/find-your-local-council

The downloadable spreadsheets don't look like they contain the councillors' names but the web page for each council does so this could be scraped.

**Comment by mlandauer** [comment]
As far as I can tell on council websites there is no mention of councillors' party affiliation which seems strange to me because that is mentioned quite a lot during elections so does seem to me to be a vital bit of information that's missing.

On the NSW electoral commission website there is even no mention of party affiliation unless for they're independent which seems odd again.

On the ABC election site http://www.abc.net.au/elections/nsw/2012/council/ it does mention the party of each person so this might be another useful site for scraping.

Scraped version of the Greens NSW councillor contact details list is now here: https://morph.io/openaustralia/nsw_greens_councillors_contact_details

**Comment by kat** [comment]
found [TAS Mayors/council list](http://www.lgat.tas.gov.au/page.aspx?u=221) as a doc

**Comment by kat** [comment]
WA has a list of councillors and ward boundaries among other info in their Local Gov Contact Directory 2015 (printed format only) for ~$65 - order via a [PDF form](http://www.walga.asn.au/Portals/0/Templates/Coms%20Events/Publications/Directory/Order%20Form%20for%20Directory%202015%20-%20Public.pdf) on which they like credit card details and EMAIL to them.

**Comment by mlandauer** [comment]
Scraper for Victorian names of councillors: https://morph.io/openaustralia/vic_lg_directory_councillors

**Comment by kat** [comment]
almost nothing on data.gov.au (3 random councillor related results)

**Comment by kat** [comment]
this commercial company sells lists of council contact info http://azgovbiz.com.au/index.php/list-of-marketing-lists

**Comment by mlandauer** [comment]
QLD Local government directory is at http://www.dsdip.qld.gov.au/local-government-directory/search-the-local-government-directory.html

It seemed to load stuff very fast when you pick a council... Hmmm... 

A little bit of digging and presto! Structured data for local government directory for QLD https://services.dsdip.qld.gov.au/lgguide/sampleData/lgaInfo.json

**Comment by kat** [comment]
[list of councillors/councils for TAS](https://drive.google.com/open?id=0B_0JrLy9bmIPRlRwZ3I1cVJwY0x3dGlOM1lEb3ZQdGZINWNR&authuser=1) doesn't contain email addreses

**Comment by mlandauer** [comment]
Here's the scraped data for Queensland local councillors: https://morph.io/openaustralia/qld_lg_directory_councillors

**Comment by kat** [comment]
https://data.sa.gov.au/dataset/api-statewide-local-government-datasets seems to have API including councillor information. Also SA local gov mayors list for download at http://www.lga.sa.gov.au/page.aspx?u=992 - can order a full list of councillors there too.

**Comment by kat** [comment]
not much luck for NT so far just a list of councils from the [NT Department of local government and communities]( http://www.localgovernment.nt.gov.au/home/council_information) The [NT electoral commission](http://www.ntec.nt.gov.au/) has data from past local elections. It's locked up in unstructured documents.

**Comment by mlandauer** [comment]
Here's scraped SA data using their parse.com based API https://morph.io/openaustralia/sa_lg_councillors

**Comment by mlandauer** [comment]
Here's a spreadsheet that combines all the data that we've found so far:

https://docs.google.com/a/openaustralia.org/spreadsheets/d/16G9amVprzG6l-isK-5F57ZwtUrnlJkHa6up3Y7nnJRY/edit?usp=sharing

It's a total of 4500 councillors so far!

**Comment by henare** [comment]
We've now got a repository of open and structured data collecting this: https://github.com/openaustralia/australian_local_councillors_popolo
