### ISSUE TITLE
update PlanningAlerts when DA is updated automatically

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#653]
DAs should be updated when their details change. 

The following DA for an event which was originally intended to be every week was not updated on PlanningAlerts when the DA was amended to be for every two weeks. A change like this could have a significant impact on how the DA is perceived in the local community and change how people respond to it. 

Prompted by a PlanningAlerts user who sent in the following request on this issue.

This application:
https://www.planningalerts.org.au/applications/477512
I got a thing in the letterbox saying they'd amended it and sure enough it is amended on the council site to "every second Saturday" but that hasn't flowed through to Planning Alerts.

I imagine you'd want to re-notify people when that happens. And probably highlight the variations, which is something the council didn't do in their letter.

http://www3.marrickville.nsw.gov.au/ePropertyProd/P1/PublicNotices/PublicNoticeDetails.aspx?r=$P1.WEBGUEST&f=$P1.ESB.PUBNOT.VIW&ApplicationId=DA201400613

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_e92l)

**Comment by CloCkWeRX** [comment]
Very close to #557

**Comment by jamezpolley** [comment]
I've just had another user point out an issue on another DA, which was originally put online as being for a "Residential Flat Building Consisting of 6 Units " which was changed to "3 units" on the council's website, but not on PlanningAlerts.

I can't even find a way to update this manually in the admin interface.

**Comment by jamezpolley** [comment]
One problem with doing this automatically is that scrapers on morph are designed to be append-only; we don't really have a way to go back and alter the existing row. We'd probably have to add a new row with a new date, and then have PlanningAlerts understand the "history" of the versions of the row. That's doable, but it's a little more work than amending the existing row.

A problem with doing it manually is that there is only so much admin time, and it could easily be entirely consumed updating DAs.

Perhaps this might be a place where community annotations might be useful? Ie, we could have the ability for commenters to add flags to say that the description is inaccurate or has been updated or add the correct description.

**Comment by katska** [comment]
Another example this week where someone's name was accidentally in the DA description and they did not want to be found. It's possible a long way round right now to make this change - Matthew was able to do it from the depths of the system with raw commands, but updating should be accessible from the admin panel.

**Comment by mlandauer** [comment]
This now happens (sort of... mostly). Since we added versioning for development applications the scrapers are now *not* append only. They always write the latest data. When planningalerts gets that data from the scraper on morph if it's changed it will change the data on planningalerts (but it's versioned internally so we never lose anything). So if council amends a description we should get that change.

*However* and this is a big one, some scrapers only rescrape applications that are something like two weeks old or maybe even less. So, if the description is updated much later that will not flow through automatically. I don't know a good way to solve this that doesn't involve scrapers scraping everything all of the time. Eek!

**Comment by mlandauer** [comment]
I'm going to close this as fixed then.
