### ISSUE TITLE
reduce number of email requests for alerts

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#657]
We get a lot of emails from people asking us to set them up with alerts for a new address. They can do this themselves through the application. For example (addresses removed):

> Hello,
> Thanks for the planning alerts, they are a great way to keep up with the developments in our area!
> 
> I was wondering if there have been any planning applications for:
> 
> 123 Fake Street
> 456 Phoney Street

Why do people think they need to email us?

Is there a way we can make it clear that you can set up new requests yourself?

Maybe #156 would make this more obvious?

**Comment by henare** [comment]
>Why do people think they need to email us?

We should ask them.

**Comment by equivalentideas** [comment]
> We should ask them.

:+1: :+1:
