### ISSUE TITLE
Provide an easy way to go to an application's admin page when you're viewing it

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#660]
If you're logged in as an admin and you're looking at an application page you need an easy way to view its corresponding admin page so you can make changes.

**Comment by henare** [comment]
@Anishka0107 I've updated the description to be more about the problem than my initial idea of a solution.

Originally I was suggesting changing this link from going to the usual /admin page and instead taking you to the /admin/applications/123 page for this application.

![selection_002](https://cloud.githubusercontent.com/assets/48945/24899371/6b6c4be2-1ee3-11e7-8668-fb55e8a16547.png)

However that's probably not great usability-wise because it changes the behaviour of that link but nothing else (except the context that you're on an application page).

I'll let you or whoever works on this issue decide where the best place for the link would be :smile:

**Comment by akve17** [comment]
I want to work on this issue. 
I guess i will need the 'Admin' login credentials for this.

**Comment by akve17** [comment]
I want to work on this issue.

**Comment by mlandauer** [comment]
Still a good small usability improvement for admins

**Comment by katska** [comment]
Yes this would save some time now, but the main admin link in the top menu isnt' the right place for it. If there's an admin link for the application this would make more sense to be in the application section of the page. eg.
<img width="827" alt="Screen Shot 2022-02-15 at 2 53 07 pm" src="https://user-images.githubusercontent.com/1001129/153991656-0ea43ec0-bafe-4b33-8ae1-aaead694e7d0.png">

**Comment by katska** [comment]
This is also a back and forth problem, because it's not easy to switch between the application page and the admin page of a DA.
