### ISSUE TITLE
Bad page number parameters cause ArgumentError to be raised

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#669]
https://www.planningalerts.org.au/?page=2[&q=George+Street%2C+Redfern+NSW
## Backtrace

```
line 18 of [PROJECT_ROOT]/app/controllers/applications_controller.rb: index
```

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/37075/faults/5869537)

**Comment by hisayohorie** [comment]
working on this!
