### ISSUE TITLE
New scraper for Ballarat

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/planningalerts#672]
It looks like the Ballarat DA data is now being uploaded daily to data.gov.au. See https://twitter.com/mattswards/status/605591831523393536

On data.gov.au at https://data.gov.au/dataset/ballarat-planning-applications-currently-on-advertising/resource/2db587db-4552-482a-aa69-913e0ee9cf03

We already have a scraper for Ballarat but structured data is much nicer ;-)

**Comment by CloCkWeRX** [comment]
Shifting
