### ISSUE TITLE
Planning Alerts needs a logo

### ISSUE THREAD

**Issue by mithro** [openaustralia/planningalerts#674]
You need some type of logo.

**Comment by equivalentideas** [comment]
@mithro why?

**Comment by mithro** [comment]
So it can appear in the UI at https://github.com/openaustralia/morph/issues/789
So it appears in the favicon.ico
So it can be put on a t-shirt :)

**Comment by equivalentideas** [comment]
What does that mean to people?

**Comment by mlandauer** [comment]
Closing this as it's really part of a bigger question of the design for the site,.
