### ISSUE TITLE
Web pages should have "Suggest a feature / report a bug" links

### ISSUE THREAD

**Issue by mithro** [openaustralia/planningalerts#675]
You have these links on your newer sites like morph.io and TheyVoteForYou.org.au but I couldn't find the equivalent on the planning alerts website and just ended up using my knowledge about github to find the right place to add it.

**Comment by mlandauer** [comment]
This is such a good and simple idea. I can't believe we haven't done this. A "logical" place for this to go would be in the footer.

**Comment by mlandauer** [comment]
See #1538 for good footer design

**Comment by mithro** [comment]
Blast from the past!
