### ISSUE TITLE
Send devise emails using background queue

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#676]

**Comment by hisayohorie** [comment]
https://github.com/plataformatec/devise#password-reset-tokens-and-rails-logs

According to this doc, we could change the log level. since we are using recoverable module, we should lower the log level so the token won't get leak from the log? Would it be ok if I make the change? @equivalentideas

**Comment by henare** [comment]
@hisayohorie well spotted! :eyeglasses: When we make the change this issue describes we should also set the log level to warn.

**Comment by hisayohorie** [comment]
@henare 🤓 ok will make the change and PR!
