### ISSUE TITLE
Automatically convert HTML entities from scrapers back into normal characters

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#681]
Often scrapers miss converting HTML entities in the description field, e.g. https://www.planningalerts.org.au/applications/530099

When we suck in data from scrapers we should automatically convert these back into normal characters.

**Comment by hisayohorie** [comment]
I am working on this issue!

**Comment by mlandauer** [comment]
As mentioned in #1145 it's probably simpler to delegate responsibility for this always to the scraper. It has full knowledge of where the data is coming from so should handle it in whatever way makes sense to turn it in to proper normal utf8.

However, maybe we could do some sanity checking that warns us in some way if there are fields with things that look like html entities in them. Then, we know we need to fix the scraper.
