### ISSUE TITLE
Can't hide comments

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#686]
When I check the 'hidden' option in the comment admin screen (e.g. https://www.planningalerts.org.au/admin/application_comments/12345) and then hit update, I get the notice 'Comment was successfully updated' but I can see that the hidden attribute is still set to false.

In other words, the comment hiding function is broken.

**Comment by equivalentideas** [comment]
The error is:

> Can't mass-assign protected attributes for Comment: confirmed, hidden

**Comment by equivalentideas** [comment]
This error has appeared because Rails 4 blocks mass assignment for by default. It requires that attributes be explicitly made accessible in the model, but prefers whitelisting of attributes using the permit method in the controller http://api.rubyonrails.org/v4.1.11/classes/ActionController/Parameters.html http://edgeguides.rubyonrails.org/action_controller_overview.html#strong-parameters.

We could mark the confirmed and hidden attributes as accessible in the controller, but making the confirmed attribute could be a spam problem as someone could inject a confirmation into their initial comment submission.

I think (after speaking with @henare ;-) ) that implementing the strong parameters pattern for active admin is a better solution. Here's how to do strong parameters in active admin http://activeadmin.info/docs/2-resource-customization.html

I'll do a quick PR now.

**Comment by equivalentideas** [comment]
I stuck on this.

Using the using the ['permit_params'](http://activeadmin.info/docs/2-resource-customization.html) method supplied by ActiveAdmin isn't working for me.

After adding:

      permit_params :text, :name, :email, :address, :confirmed, :hidden 

to app/admin/comments.rb, I'm now getting getting:

> Can't mass-assign protected attributes for Comment: text, name, email, address, confirmed, hidden

I have a feels that this is because we're not using the strong parameters pattern in other places, but if that is causing an issue, I'm not sure why.

**Comment by henare** [comment]
Fixed in ee21d7f.
