### ISSUE TITLE
Set up google analytics events/goals for commenting

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#687]
So we can better understand and test how people are using the form. For example, do most people who comment come from the comment emails or the alert emails?

**Comment by equivalentideas** [comment]
So this is broken at the moment because GA goal expects people to hit a page /comments/[:comment_id]/confirmed but no one ever hits that page because we redirect to the application show view, https://github.com/openaustralia/planningalerts/blob/master/app/controllers/comments_controller.rb#L34 .

We can track the comment confirmation with an ga event fired when the confirmation message is on the application show page and see how that works. Unfortunately that means we can't define a funnel in GA goals (as far as I can tell) because you can't define funnels or event based goals. We can track the event flow info though, but it's more annoying/complex. That's the best option I can think of.

**Comment by henare** [comment]
Can we do it server-side as part of the controller action?

**Comment by equivalentideas** [comment]
hmmm that's a good question. It appears it is, using the [GA Measurement Protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide). It involves getting data from a cookie on the client.

It seems like it'd be simpler to do it client-side to me—but I've never done anything with cookies before, I'm not sure what the considerations and work involved for that would be.

**Comment by equivalentideas** [comment]
I'm going to make a PR to do with on the client, seems simplest to me.

**Comment by equivalentideas** [comment]
We also should be tracking clicks on the comment submit button to see if people aren't confirming their comment. I'm going to add that to #763 .

**Comment by equivalentideas** [comment]
One more thing to track in this process before we close this I think:

* [ ] track when people click the link at the top of a list of comments to make a comment

**Comment by equivalentideas** [comment]
I've just set the goal up.
