### ISSUE TITLE
Make sure old subscribe pages are removed

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#690]

**Comment by equivalentideas** [comment]
This is the only page: https://www.planningalerts.org.au/subscriptions/new 

We're reusing the 'create' view in the new in the new subscriptions concept.
https://github.com/openaustralia/planningalerts/blob/subscription/app/views/subscriptions/create.html.haml

**Comment by henare** [comment]
We're reusing the old pages so this is all good.
