### ISSUE TITLE
Feature flows for several alert subscription

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#692]
These are the flows @equivalentideas and I mapped out at our kick-off meeting:

![feature_flow](https://cloud.githubusercontent.com/assets/48945/9103751/5834804e-3c45-11e5-9fc9-0831cb14a5e5.jpg)

Now we need to extract these out into issues.

**Comment by equivalentideas** [comment]
I've broken out #697 #698 #699 #700
