### ISSUE TITLE
Alerts for people on a trial subscription should include a banner

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#695]
That tells them about the trial and about how they can sign up.

**Comment by equivalentideas** [comment]
I'm going to start this off the an integration test for someone who gets an alert with the banner.

**Comment by equivalentideas** [comment]
Sending the email in the integration test was too tricky for me right now, so I've moved onto the banner that will be in the email.

Here's an idea using the blue from the donations banner quick is really distinct from the rest of the email.

![screen shot 2015-08-10 at 4 59 46 pm](https://cloud.githubusercontent.com/assets/1239550/9160870/b244528c-3f81-11e5-903d-cdacbb3725aa.png)

The text focuses on the positive, but makes it clear that as they're not a 'personal user' receiving alerts for multiple addresses, they need to subscribe.

A more direct (but potentially rude) way of saying this would be:

> Personal use of PlanningAlerts is free. You are receiving alerts for several addresses, which requires an active subscription.

I prefer the more direct now that I look at it.

I'm happy with this as a first pass to iterate on so I'll implement it.

**Comment by equivalentideas** [comment]
We could also do something in the 'header' but I think it's too subtle for now

![screen shot 2015-08-10 at 4 17 24 pm](https://cloud.githubusercontent.com/assets/1239550/9161056/03fb72d0-3f83-11e5-9df3-fd1c0d565b5a.png)
![screen shot 2015-08-10 at 4 17 17 pm](https://cloud.githubusercontent.com/assets/1239550/9161057/040648f4-3f83-11e5-8744-9b6ab62ac834.png)
![screen shot 2015-08-10 at 4 17 02 pm](https://cloud.githubusercontent.com/assets/1239550/9161058/0442ba78-3f83-11e5-8982-b9545f98cff0.png)

**Comment by equivalentideas** [comment]
Once you click the link in the banner you need to go to a page to subscribe. I think this should be as simple as possible. Here's an rough idea:

![screen shot 2015-08-11 at 10 32 12 am](https://cloud.githubusercontent.com/assets/1239550/9187470/4f5a8432-4014-11e5-8299-5e69a1cb0937.png)
![screen shot 2015-08-11 at 10 31 08 am](https://cloud.githubusercontent.com/assets/1239550/9187471/4f64e8a0-4014-11e5-800c-151238f21089.png)

Text and layout would need tweaking.

I also feel like there's some way to say 'There's been 200 new applications in the areas you track this week' or something to help demonstrate the benefit. Maybe that's overkill for the first pass.

**Comment by equivalentideas** [comment]
Thinking about this overnight, I started asking why are we telling people about why they need to subscribe in the alert email?

Isn't it simpler to just have 'Trial subscription, 6 days remaining' and the 'subscribe now' link?

![img_4139](https://cloud.githubusercontent.com/assets/1239550/9239193/c1515b36-419c-11e5-918c-c27847e46f8d.jpg)

I think it's a better flow to see that you're on a trial, think 'what's this about', click on subscribe now and read about it there. Then if you don't want to subscribe, each day you get the reminder '5 days left', '4 days left' and you know what it's about—but you have more space to think and the banner is clear, but out of the way so you can focus on the value of the alert.

This feels simpler to me, with a more structured journey through the process.

For people using PlanningAlerts for non-commercial purposes, we can have something very clear on the new subscription page so they no what to do see #722

**Comment by equivalentideas** [comment]
^^^^ @henare does that make sense to you? keen for you thoughts before I implement something as the css will be a little fiddly.

**Comment by henare** [comment]
@equivalentideas Yeah I like this. They will have already been told when the sign up for their 3rd alert about the trial so I like the idea of the thing in the alert just being a teaser/reminder.

**Comment by equivalentideas** [comment]
> @equivalentideas Yeah I like this. They will have already been told when the sign up for their 3rd alert about the trial so I like the idea of the thing in the alert just being a teaser/reminder.

Nice :+1: I'll implement this then.

**Comment by equivalentideas** [comment]
I think the colour of/in the banner needs to work better with the colour of the subscribe button on the page.

**Comment by equivalentideas** [comment]
I think it's actually nicer with the subscribe button on the left as the main action people are meant to take, then with the info next to it.

![screen shot 2015-08-13 at 1 12 55 pm](https://cloud.githubusercontent.com/assets/1239550/9241907/11837876-41bd-11e5-9c41-6e4a71c2bcf7.png)
