### ISSUE TITLE
If I have a subscription, don't ask me to subscribe again when I add new alerts

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#697]
See TODO: https://github.com/openaustralia/planningalerts/blob/subscription/app/views/email_confirmable/confirm/alert.html.haml#L7

**Comment by equivalentideas** [comment]
@henare could you leave a note on why this was closed?

**Comment by henare** [comment]
@equivalentideas :point_up: oops, hadn't pushed.
