### ISSUE TITLE
Decide on term for 'subscriptions'

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#705]
Is 'subscription' the best way to describe what this is?

**Comment by equivalentideas** [comment]
Some alternatives could be:

* premium plan
* account
* membership

I think 'account' and 'membership' imply something that's too new and specialised from the rest of the app, and goes against our aim to change as little as possible, particularly the perception of the service.

'Plan' isn't clear without a qualifier like 'premium' which again, implies something special. I don't mind that, but it doesn't feel right for the time being.

I think subscription is better that these as it's very neutral, implies payment, is distinct from the alerts concept—except for 'unsubscribing' from the alerts.

**Comment by equivalentideas** [comment]
There are other words around this that we need too. What do we call turning on and off your subscription?

I think 'activating/activate your subscription' and 'subscribe now' for short (e.g. button/link text), and 'cancel your subscription'. I think 'cancel' is a good word for payment related things as it's quite common to think of 'cancelling payments' and it's also very clear.

We could go with that for a first pass, then might want to refine back to always 'activate you subscription' or 'subscribe now'.

I feel like just 'subscribe now' could be a little confusing as you've already got a trial subscription and all these alerts.

**Comment by equivalentideas** [comment]
I'm pretty happy with 'subscription' @henare.  Unless you've got more thoughts I'm happy to close this.

**Comment by henare** [comment]
@equivalentideas great to have your thoughts documented here :+1:
