### ISSUE TITLE
When I want to activation my subscription from the trial banner, take me to page where I can subscribe

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#708]
We need a page at /subscriptions/new where people can subscribe.

**Comment by equivalentideas** [comment]
I had an [initial idea for this based on the old subscription page](https://github.com/openaustralia/planningalerts/issues/695#issuecomment-129657292), but thinking about it a bit more, I think that's the wrong direction.

I think we want people to see this as a natural part of the current site, rather than something new. I think we should then draw much more on the current design. The most common page for a new alert sign up is the [application page](https://www.planningalerts.org.au/applications/552719):

![screen shot 2015-08-11 at 12 16 20 pm](https://cloud.githubusercontent.com/assets/1239550/9188768/6284afba-4023-11e5-9ce1-052298f391fa.png)

I think a layout and design like this, with the introduction copy on the left with a box to the right the button, is a good first direction.

**Comment by equivalentideas** [comment]
Here's a quick version of this:

![screen shot 2015-08-11 at 12 44 45 pm](https://cloud.githubusercontent.com/assets/1239550/9189059/cc2af32c-4026-11e5-9633-b83bbea84dd4.png)

Any thoughts @henare ? Do you think this is getting too close to a marketing page? I've got a feeling that it should feel like the idea isn't getting 'sold' to you, it's just a logical part of the application—but you still need to be convinced to pay.

**Comment by henare** [comment]
Yes I agree. We seem to have got a lot of different design elements here for something that should be quite simple. I think this over-complication may have come from trying to draw from the current design as a starting point.

How about putting that aside and come up with the simplest thing that can do this job. Once you're happy with that you can iterate from there to make it better and/or fit with the rest of the site.

**Comment by equivalentideas** [comment]
That's a good approach I think @henare. Here's an go at something more stripped back—I think it works much better:

![screen shot 2015-08-11 at 2 02 01 pm](https://cloud.githubusercontent.com/assets/1239550/9189825/af5097b0-4031-11e5-8a23-28a4a18e0e64.png)

**Comment by equivalentideas** [comment]
I was just thinking, maybe the about/faq page is a better place to explain that non-commercial access to multiple alerts is free if you contact us?

**Comment by equivalentideas** [comment]
I'm going to implement this as a first pass to build on.

**Comment by equivalentideas** [comment]
I think we can close this as we have the page that the issue description asks for.
