### ISSUE TITLE
Once I've successfully entered by payment details, take me to a confirmation page so I know the status of my subscription

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#709]

**Comment by equivalentideas** [comment]
This page needs to let the person know:

* that their subscription has been activated
* they can now sign up for as many alerts as they like
* they can cancel at any time by contacting us

I think we draw on the alert confirmation page design for this—it's a pattern in the app that will be familiar to these users.

![screen shot 2015-08-05 at 2 35 16 pm](https://cloud.githubusercontent.com/assets/1239550/9188120/dd5f8b68-401b-11e5-9a95-1f6ef803e5aa.png)

**Comment by henare** [comment]
We've already got this page implemented. Improvements are needed, see #712.
