### ISSUE TITLE
Subscription information on alert activation page is confusing

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#711]
When you subscribe for your 3rd alert you see this page:

![selection_001](https://cloud.githubusercontent.com/assets/48945/9189503/a9e19cd4-402c-11e5-967a-30979d9aafda.png)

The two biggest issues I can see are:

* The box says "your alert has been activated" but it also contains a button "Subscribe now $49/month". Which one is it, have I subscribed or not?
* The text explaining stuff about subscriptions doesn't clearly state what's happened, why it's happening, what will happen (i.e. your trial will end), and what you need to do about it

**Comment by equivalentideas** [comment]
One way to approach this could be that when someone confirms their 3rd alert, the main thrust of the page is about starting the trial high volume subscription, rather than about confirming the alert:

> Thanks, you are now signed up to 3 alerts.
> While low volume and non-commercial use of PlanningAlerts is free, you require an active subscription to receive alerts for several locations.
> After a 7 day trial you'll need to active your subscription to continue receiving these alerts, or you can subscribe right away if you're already happy with your alerts.

**Comment by henare** [comment]
It should also make sense if you're subscribing to another alert during your trial.

**Comment by equivalentideas** [comment]
Here's another pass at text for this page:

> Thanks, you now have alerts set up for 3 street addresses.
> 
> You need a subscription to get planning applications near several addresses, or to use them in your professional work. Subscriptions are $49 per month. Once you’re subscribed you can get alerts from as many locations as you need.
- if has no subscription:
> We’ve set you up a 7 day free trial subscription, so you can start getting your new alerts straight away.
- if has subscription:
> You still have 4 days remaining on your free trial subscription, so you’ll start getting your new alerts straight away.

> Non-commercial use of PlanningAlerts is free for any number of addresses. If this sounds like you, please email us—we’ll be happy to help with a free, non-commercial subscription.
> 
> If you’re happy to skip the trial you can [subscribe here](https://www.planningalerts.org.au/subscriptions/new).

**Comment by equivalentideas** [comment]
Note that this changes it so you don't subscribe from the confirmation page, you have to go to the new subscription page via a link if you want to subscribe.

For some reason this feels more straight-forward to me—having the button on the page (as in the screenshot above) feels like there's too many different things happening on this page already.

Any thoughts @henare

**Comment by henare** [comment]
That sounds good @equivalentideas.

**Comment by equivalentideas** [comment]
Cool, I'm gonna do a PR for this :+1:
