### ISSUE TITLE
Subscription activated page needs some work

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#712]
![selection_001](https://cloud.githubusercontent.com/assets/48945/9189696/88cfd724-402f-11e5-9654-c20a526ad4e9.png)

* There's no space after the first sentence.
* The sparse page looks a little out of keeping with the rest of the site. We don't normally use black text for headings, for instance.
* The last paragraph has a hanging word, which I know totally Grinds @equivalentideas' Gears (hey, that rhymes).
* It doesn't tell you the wonderful thing that happens (i.e. that you've unlocked unlimited alerts or that your alerts will start working again now)

**Comment by henare** [comment]
The "contact us" link goes to an email. Maybe we should change it to say "email us".

I say this because often "contact us" links go to a contact page whereas this will open your email client which may be unexpected.

If we change it to email us we probably should also include the email address since so many people use webmail these days and are probably used to copy and pasting text (but not links).

**Comment by equivalentideas** [comment]
> If we change it to email us we probably should also include the email address since so many people use webmail these days and are probably used to copy and pasting text (but not links).

Sounds good :+1:
