### ISSUE TITLE
New subscription page has nowhere to enter your email

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#720]

**Comment by equivalentideas** [comment]
Do you mean in the payment form or elsewhere? There is this one when the person clicks 'subscribe now':

![screen shot 2015-08-12 at 4 40 06 pm](https://cloud.githubusercontent.com/assets/1239550/9217928/e58d13a0-4110-11e5-9150-12681d0dc247.png)

**Comment by henare** [comment]
@equivalentideas Does that work? i.e. if you enter an email does it create a subscription for that email address?

**Comment by equivalentideas** [comment]
No, you need to already have an active subscription. We could create the subscription when this is submitted if there isn't one already.

That would let people who don't have 3 alerts subscribe—which I think we said we wanted to allow.

**Comment by henare** [comment]
>No, you need to already have an active subscription.

Does it even work with a subscription present?

**Comment by equivalentideas** [comment]
> Does it even work with a subscription present?

Yep it works.

**Comment by henare** [comment]
Oh amazing, this can be closed then.

**Comment by equivalentideas** [comment]
Closed as there is an email input already

**Comment by henare** [comment]
Ah cool, it's because our JS injects it: https://github.com/openaustralia/planningalerts/blob/e3771dfd92c2672e0bddd1df9eb0fc5341e92f25/app/assets/javascripts/application.js#L23
