### ISSUE TITLE
New subscription page doesn't tell you what to do if you're a non-commerical user

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#722]
Also, it should emphasise that PlanningAlerts is free for low-volume, non-commercial use.

**Comment by equivalentideas** [comment]
This feels to me like an idea for implementing #699 rather than it's own issue. I'll close and you can reopen if you like.

**Comment by henare** [comment]
Whilst this might be part of #699 I think this is a specific issue so I'm reopening it.

**Comment by equivalentideas** [comment]
@henare What do you think of something like this:

![screen shot 2015-08-13 at 9 31 59 am](https://cloud.githubusercontent.com/assets/1239550/9239350/3b207108-419e-11e5-9790-d33f92c0d1fe.png)

I like the way that something like this plays off the other wording, reenforcing that it's not free for commercial use.

**Comment by henare** [comment]
Nice. Can you make it part of the main text?

**Comment by equivalentideas** [comment]
You think move it above the button? My thinking was better to not get in way of the initial flow straight into the button. But having it up above could add to the information there well. What’s your reasoning?

**Comment by equivalentideas** [comment]
Here's how it could appear above the button:

![screen shot 2015-08-13 at 10 12 38 am](https://cloud.githubusercontent.com/assets/1239550/9239914/e8a30d4a-41a3-11e5-93bb-02ebf8121fc8.png)

**Comment by henare** [comment]
>You think move it above the button?

I didn't mean the placement, I meant can we inline the text to make it part of the main copy?

>What’s your reasoning?

To make it simple and clearer.

**Comment by equivalentideas** [comment]
> I meant can we inline the text to make it part of the main copy?

I think it's clearer as two separate paragraphs, quicker to scan too. Two simpler paragraphs better than one longer one with two separate thoughts in it.
