### ISSUE TITLE
Allow people who don't have 3 alerts to subscribe on the new subscriptions page

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#723]
They can currently enter their email, but because they don't have a subscription (as they haven't had one created when they signed up for their 3rd alert), the form wont submit.

![screen shot 2015-08-12 at 4 40 06 pm](https://cloud.githubusercontent.com/assets/1239550/9217928/e58d13a0-4110-11e5-9150-12681d0dc247.png)

**Comment by henare** [comment]
Nicely spotted :+1:
