### ISSUE TITLE
The payment form error message is unfriendly

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#731]
It's currently:

> Sorry there was an error in the form. Please contact us.

It's important that people know they haven't been charged. Something like:

> Whoops, something went wrong. You have not been charged. Please email us and we’ll sort this out.

**Comment by equivalentideas** [comment]
@henare I can't quite work out the situation in which you would see this error. We show this from the subscriptions controller if somehow the email params are missing.

But we prefil that field for most people, and if somehow it's not, it's a required field in the stripe form.

**Comment by henare** [comment]
Good catch, you're right. This will raise an error if there's a problem with the email: https://github.com/openaustralia/planningalerts/blob/master/app/controllers/subscriptions_controller.rb#L8

**Comment by equivalentideas** [comment]
> here's a problem with the email

What type of problem? Like the email gets created and it doesn't validate, or it already exists and is found, but there's some error there?

**Comment by henare** [comment]
Because it's a `find_or` call it won't error if it already exists - it will update the existing record. However if there's another validation that fails it will error (such as the parameter being missing now that e73227d3bf102aed8bcc46cc6366910161b048c0 is added).
