### ISSUE TITLE
Subscribe banner not aligned on mobile

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#735]
![screenshot_2015-08-14-22-35-52](https://cloud.githubusercontent.com/assets/48945/9296301/505817ce-44cd-11e5-99e3-fc76e5194e11.png)

**Comment by equivalentideas** [comment]
Nice catch @henare 

I think our template needs some work to make it more stable across clients. Different bits of text are wildly different sizes in ios Mail app, and the ios gmail app—then different again above.

**Comment by henare** [comment]
>Nice catch @henare 

omnomnomnomnom dogfood.

**Comment by equivalentideas** [comment]
@henare when you get you're next alert with the banner, could you please screen shot it and chuck it up here so we can confirm that this is fixed by changes in #746 ?

**Comment by henare** [comment]
Will do.

**Comment by equivalentideas** [comment]
Cool, I'ma move this back to ready until we know more so it's outa the way.

**Comment by henare** [comment]
I created #748.

**Comment by equivalentideas** [comment]
Nice thanks. I'll close this one.

**Comment by henare** [comment]
:+1:
