### ISSUE TITLE
Email subscribe banner is missing something

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#736]
I think the problem is that it's telling me something and I might not understand that but the only available action is to "subscribe now". Maybe it's as simple as putting a link on "trial subscription"?

**Comment by equivalentideas** [comment]
I get what you mean. Where would the link on 'trial subscription' take me?

I feel like we could also remove the 'now' so it's a tad less forceful.

**Comment by henare** [comment]
>Where would the link on 'trial subscription' take me?

To the subscribe page where there's more information about What Is Going On Here.

**Comment by equivalentideas** [comment]
> To the subscribe page where there's more information about What Is Going On Here.

:+1: Sounds Good Too Me
