### ISSUE TITLE
The term “alert” is used to describe both the thing that sends you emails, and the emails themselves

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#738]
I think we're picking up a bit of the confusion of the duel meaning of “alert” in the app.

Sometimes we refer to “alerts” as the individual emails notifying you of new development applications:

> Find out for free what is being built and knocked down in your area and receive email alerts when something new is planned.
> 
> Subscribe here to get alerts of planning applications near several addresses. 
> 
> you received 72,791 email alerts

And sometimes we use “alert” to refer to a thing sends you email notifications for DAs around an address:

> You can change the size of the area covered by this alert
> 
> Create alert
> 
> you signed up for 308 new email alerts

Is this confusing to people? It makes writing some of the interface text [a bit tricky](https://github.com/openaustralia/planningalerts/pull/737). I wonder if it makes it slower to comprehend what the application is saying/asking of you?

We could have a look through the January survey results to see if there are any hints there as to how people using the service think about this.

**Comment by mlandauer** [comment]
I've not seen an example where this is causing confusion
