### ISSUE TITLE
Create a task for selecting random people with several alerts and give trial subscriptions for them

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#745]

**Comment by equivalentideas** [comment]
I think a staged roll out could be good, to maybe 200 people at a time. There are about 1600 people getting 3 or more alerts. 200 should be enough to start seeing some feedback.

How does that sound to you as an approach @henare? If we do want to do that, I guess we need to work out how we're going to select addresses.

Are there any analytics set up we can put in place to help us get good data on this once it starts?

**Comment by henare** [comment]
>I think a staged roll out could be good...

That was a given for me.

>...I guess we need to work out how we're going to select addresses.

Yeah, I expected the bulk of the work on this issue was devising method and writing the tools to do the staged roll-out.

>Are there any analytics set up we can put in place to help us get good data on this once it starts?

Analytics such as?

**Comment by equivalentideas** [comment]
> I expected the bulk of the work on this issue was devising method and writing the tools to do the staged roll-out.

I'd find it really helpful if you could put that kind of stuff or things that are the assumptions for the issue in the description when you make it so we don't have to clear things up when we start discussion on it.

> Analytics such as?

Google analytics goal tracking for example, to produce a funnel breakdown. I'm not sure of the best way to monitor the response to what we're adding, but I think it's something we should have an idea of ahead of the roll out. For example, if no one signs up, I think it would helpful to have an idea of why so we can fix it.

Do you think this is something worth having a plan for before we roll out?

**Comment by henare** [comment]
>I'd find it really helpful if you could put that kind of stuff or things that are the assumptions for the issue in the description when you make it so we don't have to clear things up when we start discussion on it.

Okay will do. I submitted this quickly while we were on the phone together.

>Google analytics goal tracking for example, to produce a funnel breakdown. I'm not sure of the best way to monitor the response to what we're adding, but I think it's something we should have an idea of ahead of the roll out. For example, if no one signs up, I think it would helpful to have an idea of why so we can fix it.
>
>Do you think this is something worth having a plan for before we roll out?

Yes it sounds like it's worth having a plan for. I'm still not clear on what metrics you think we should be tracking though.

**Comment by equivalentideas** [comment]
> I submitted this quickly while we were on the phone together.

No worries :)

>  I'm still not clear on what metrics you think we should be tracking though.

I'm not sure either ;-) I think it's a separate issue to this so I'll break it out.

**Comment by henare** [comment]
>I think it's a separate issue to this so I'll break it out.

Good call.

**Comment by equivalentideas** [comment]
Over lunch I just watched a video from Thoughtbot about how they rolled out a new feature to one of their projects Upcase. Thought it might be useful to list their process here:

* They made a new column for Users: has_flashcards .
* They picked 10% of their users at random and set that to true.
* After they got some feedback and made changes, they did another 20%.
* The next round of feedback was converging around a general positive response and a few ideas for additions to the feature that they liked but thought were for a later release. They were satisfied that they had it in a good place for their first realse.
* They then removed test for has_flashcards == true from the feature so everyone had it and removed the column.

Do you think that sounds like a good approach for us @henare ?

**Comment by henare** [comment]
@equivalentideas Yes, I think it's a good idea to do a staged roll out to random people from our list of potential subscribers.
