### ISSUE TITLE
Track metrics to judge the success of the subscription process

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#747]
This is broken out from discussion on #745 

What are the key metrics we need to track so we can improve the subscription process so that when we roll it out we can see what's working and what isn't?

We can look to our flow chart in #692 to see the different points people will step through.

The steps in the key initial flow for people already with lots of alerts is:

* they click on the link in the trial banner in their email alert
* they click subscribe on the subscription page
* they submit their payment details and then hit the subscription confirmation page which means their payment has been successful

There are other flows like _signing up via the alert confirmation page_ and _signing up via the trial expired alerts_ , but I think let's get this initial one set up first.

* [x] we've already go a ga event registered on the subscribe button
* [ ] we can track people hitting the confirmation page with page views, but it could be good to put an event their as well so we can see the actual journeys through google analytics.
* [x] I think we'd need to put a ga email campaign param on the link from the trial banner to track that step, to track what happens to people coming to the site through that trial banner.

@henare can you think of anything else we might want to track at the moment? Or can you think of better ways to do this?

**Comment by henare** [comment]
> I think we'd need to put a ga email campaign param on the link from the trial banner to track that step, to track what happens to people coming to the site through that trial banner.

Good thinking! This sounds like the most important thing we haven't added yet.

**Comment by equivalentideas** [comment]
https://github.com/openaustralia/planningalerts/pull/749 adds the campaign tracking, I think we can track the subscription payment by counting the dollars in our bank account at this stage, so I think we close this if that merges.
