### ISSUE TITLE
Why are people making new comments on this year old application?

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#761]
There are lots of new, long and considered comments on this year old application?

https://www.planningalerts.org.au/applications/364483

Are they getting confused between this application and another? Do they know this one is a year old?

**Comment by henare** [comment]
Could just be that they get alerted to other people's comments so think it's active?

@equivalentideas Are you going to email some of them to ask?

**Comment by henare** [comment]
More info? https://twitter.com/WhitebridgeCA/status/638131778553688066

**Comment by henare** [comment]
Looks like it's still active so this is valid: http://apptracking.lakemac.com.au/modules/ApplicationMaster/default.aspx?page=myappwrapper&key=573207
