### ISSUE TITLE
Most of the items in the main navigation aren't relevant to most users

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#764]
The main navigation menu should provide quick access it the most important actions people want to take. Other items clutter the interface and add more information that is irrelevant to most people.

I’d say that for people who use PlanningAlerts the most important actions for most people are _viewing applications near your address_, _finding your address_ and _signing up for an alert_.

Currently the main navigation has 7 links:

![screen shot 2015-09-11 at 4 25 11 pm](https://cloud.githubusercontent.com/assets/1239550/9808362/c4179f9e-58a1-11e5-8650-598ea13ffb19.png)

Here's a bit of info on what's behind the different links and the percentage of people who visited the site and used that page (based on 1/4 million sessions).
- **Search** - 6% of sessions include a visit to the homepage that didn't enter via it (could be via menu search, home or other link). Search takes you to the home/landing page to do a search for a street address
- **Signup**  - 1.5% - Sign up for alerts with just your  address & email
- **FAQ** - 1% - Information about the site's functions and the planning system
- **Coverage** - 1% - lists councils covered
- **Get Involved**\- 0.3% - find different ways to help the project
- **Get the data** - 1% find out how to get and use the data from the project
- **About** - .5% - find out about the project & the people who made it
- **Donate** - .12% - donate to the project

The vast majority of people aren't going to the signup, faq, coverage, get involved, get the data, about or donate pages pages. Even the search link isn't used that much.

It's good that people are focused on the page content and aren't looking at pages that aren't relevant to them—but if they aren't interested in these links then they shouldn't be positioned as one of the most important things on most pages.

I propose that we move to a much simpler header that focuses on the key action people want to do apart from view applications they're been alerted about: search for an/their address.

We could move the other links to a footer navigation. This seems to be a common pattern, having a primary nav focused on the actions most people use, then a footer nav for specialist pages.

This impacts every page of the site, so shouldn't be taken lightly, but could also be a big win for the people using the site if it simplifies their experience.

Here's some simple user focused headers from other sites:

![screen shot 2015-09-11 at 5 35 10 pm](https://cloud.githubusercontent.com/assets/1239550/9809437/7a56846a-58ab-11e5-8e6e-479a14c2d074.png)
![screen shot 2015-09-11 at 5 33 25 pm](https://cloud.githubusercontent.com/assets/1239550/9809438/7a5bc920-58ab-11e5-81bd-9130aafe64f2.png)
![screen shot 2015-09-11 at 4 18 05 pm](https://cloud.githubusercontent.com/assets/1239550/9809382/037ff236-58ab-11e5-8831-344a246cc6fb.png)

All those sites are quite a bit more complex than PlanningAlerts, but their main navigation is much more focused on people completing their main tasks.

Here's a mobile site that I visit to view one kind of page (weather). I use it on widescreen cause it's so simple and gives me anything I need to know:
![screen shot 2015-09-11 at 5 23 29 pm](https://cloud.githubusercontent.com/assets/1239550/9809385/0f755572-58ab-11e5-849f-9863a833fb75.png)

Feels like #423 is related.

I'm not sure what the solution the final solution is, this has just been this has been nagging me and it seems like it could be a big win.

**Comment by henare** [comment]
What's the big win for people using the site? Is there something measurable we could test?

I ask because we have a good amount of traffic on the site which means we can quickly and effectively split test changes like this.

**Comment by equivalentideas** [comment]
> What's the big win for people using the site? Is there something measurable we could test?

The big win is more clarity about what the site is for when they arrive and focus on doing something useful for them. We could put the focus on searching for your address and test for increased engagement through new signups and searches.

**Comment by mlandauer** [comment]
I like the train of thought in this issue. It seems pretty clear that the main navigation isn't really fulfilling its function and we can probably do a lot better.
