### ISSUE TITLE
Make the map and street view bigger on wide screens

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#765]
![screen shot 2015-09-11 at 6 01 57 pm](https://cloud.githubusercontent.com/assets/1239550/9809859/3ccc4536-58af-11e5-8284-934e8c84feb5.png)

Currently the map and street view are quite small. The map gives you context of where the application is and the street view shows you the actual site.

The street view is currently so small that I find it of little use—I can't see the distinguishing features to recognise the site. Even in the area I live I often don't recognise the streets in the map.

I think that giving both these elements more space would give people more useful context/information to engage with.

One place to look for space is the margins of the page. They're currently inactive white space that could be put to use here. We could stretch these elements full with if we wanted and do something like this:

![img_4179](https://cloud.githubusercontent.com/assets/1239550/9809943/ec07ff22-58af-11e5-8f40-a50a85451116.jpg)

**Comment by henare** [comment]
Sounds good in principle :+1:
