### ISSUE TITLE
Put more focus on getting involved in the comment section

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#766]
Currently the biggest element in the comment section is a heading telling me the number of comments. Then in tiny text is a call to action telling me I can get involved. This seems backwards.

![screen shot 2015-09-11 at 6 10 20 pm](https://cloud.githubusercontent.com/assets/1239550/9810019/85da9dd0-58b0-11e5-96ac-6e7d93b19207.png)

When there are no comments, things are a bit better because the main message is 'Add your own comment', but then their is a big paragraph of text telling me about the comment process. This could be much shorter without loosing information I think.
![screen shot 2015-09-11 at 6 11 08 pm](https://cloud.githubusercontent.com/assets/1239550/9810031/9f360f3a-58b0-11e5-8368-e3715e132c91.png)

Then the placeholder text in the comment box just says 'comment'. This is an opportunity to give a nice example to show people how easy it is.

I think this section should be friendlier and simpler.

**Comment by henare** [comment]
>Then the placeholder text in the comment box just says 'comment'. This is an opportunity to give a nice example to show people how easy it is.

And to encourage people to make helpful comments, as we've been discussing recently. Like Meetup.com:

![selection_001](https://cloud.githubusercontent.com/assets/48945/9839741/cef3fdc4-5ac5-11e5-80c9-e12bae054310.png)

**Comment by equivalentideas** [comment]
> And to encourage people to make helpful comments, as we've been discussing recently.

:star2:

**Comment by equivalentideas** [comment]
I'm gonna break this down into some tasks:

* [ ] Simplify comment intro text
* [ ] make the placeholder text more encouraging.
* [ ] Make the call to action more prominent.

I think we could also move the comment count into an comment icon on the righthand side of the comment area, so it's still clear and catchy but not taking up the prime position:

![img_4182](https://cloud.githubusercontent.com/assets/1239550/9844118/09e96a8e-5b04-11e5-8835-f112858ad436.jpg)
