### ISSUE TITLE
Put more focus on comment button in alert emails

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#768]
Application in current alert email:

![screen shot 2015-09-14 at 9 43 01 am](https://cloud.githubusercontent.com/assets/1239550/9839812/3cc2ebd4-5ac7-11e5-8d77-c0e82fa67249.png)

Adding a comment is more of a 'call to action' than a link to visit, like the address title. We could make this clearer and put more focus on commenting by turning the “add comment link” into a button.

**Comment by mlandauer** [comment]
Seems like a good call
