### ISSUE TITLE
As someone interested in local development, when I'm viewing comments on a DA, provide me a link to the comment I can share, so I can promote and continue discussion in my networks

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#769]
We should help people to take the discussion of a DA to more people by sharing comments from the comment list. While it is possible to link to comments with their ids, we don't currently expose the links in any way.

Here are some examples of how other discussion platforms provide this:

![screen shot 2015-09-14 at 11 17 58 am](https://cloud.githubusercontent.com/assets/1239550/9840254/88a636d6-5ad2-11e5-9dad-6b3e6f1d9b3b.png)
![screen shot 2015-09-14 at 11 17 16 am](https://cloud.githubusercontent.com/assets/1239550/9840255/88aa4e7e-5ad2-11e5-87f8-4295aa0120f1.png)
![screen shot 2015-09-14 at 11 16 59 am](https://cloud.githubusercontent.com/assets/1239550/9840256/88ac8f5e-5ad2-11e5-89a9-97b8bc1cae30.png)
![screen shot 2015-09-14 at 11 22 03 am](https://cloud.githubusercontent.com/assets/1239550/9840271/dee5ee1a-5ad2-11e5-9cd0-7cc546c17406.png)

The conventional pattern is make the time stamp of the post a link.

Facebook also have a share button as part of the post module, and Discourse provides links for sharing on social networks specifically once you click the link icon:

![screen shot 2015-09-14 at 11 18 42 am](https://cloud.githubusercontent.com/assets/1239550/9840289/2ab33528-5ad3-11e5-8566-9bff1c7906d1.png)

**Comment by equivalentideas** [comment]
I think the simple step to do this is to make our timestamp on the comment a link to the comment:

![screen shot 2015-09-14 at 11 28 02 am](https://cloud.githubusercontent.com/assets/1239550/9840335/c0a782c8-5ad3-11e5-975d-32989ba29976.png)

**Comment by equivalentideas** [comment]
[The commit that closed this was reverted](https://github.com/openaustralia/planningalerts/commit/8dba983d6e915a8864b4adffe8b53487b1cb376d) so I'm reopening this.

I reverted it because we currently make the whole comment a link in the comments index. Wrapping a link in a link is invalid markup and creates an inconsistent experience in Safari, Firefox and Chrome: if there is no link in the comment the whole comment is clickable; if there is, just the heading is clickable and the link in the body is also clickable. This is an issue when a commenter adds a link or when we add a link to the time.

One solution would be to replace the wrapping link on the index page with just a link around the heading and add the link to the time (as above). The heading is the bit that refers to the application (the link target url), and is still a big target to touch/click.

Another solution would be to not add the link to time if the comment if wrapped in a link. We still have the link within link problem if people add a link in their comment—which was a bug I only realised after adding this link.

I think the first solution makes most sense at the moment.

**Comment by henare** [comment]
>One solution would be to replace the wrapping link on the index page with just a link around the heading and add the link to the time (as above). The heading is the bit that refers to the application (the link target url), and is still a big target to touch/click.

A problem with this is that the title refers to the *application* not the comment so you could expect it to go to the application page, not the comment anchor.

In fact, if you could make it obvious that the "Luke Bacon commented 8 minutes ago" link went to the comment and only did the link on that then you'd have solved it on the comment index page too, right? It would neatly link to the page, with the anchor intact and ready for sharing.

Don't forget that sharing a comment on the comment index page is unlikely because the comment is out of context. It's far more likely someone will share a comment when they're looking at an application they're interested in.

**Comment by equivalentideas** [comment]
> In fact, if you could make it obvious that the "Luke Bacon commented 8 minutes ago" link went to the comment and only did the link on that then you'd have solved it on the comment index page too, right? It would neatly link to the page, with the anchor intact and ready for sharing.

It seems that we actually did this already. Checkout https://www.planningalerts.org.au/applications/743048#comment61237

It's not obvious that this is a link though. I really like what discourse do:

![screen shot 2017-03-23 at 3 55 35 pm](https://cloud.githubusercontent.com/assets/1239550/24232755/4c7fc97c-0fe1-11e7-8808-6a5b937c42d3.png)

You could do it like that and add #1083

**Comment by mlandauer** [comment]
Since it appears we already have a link in the comment time to the link itself but it's not obvious, the change that we should make here is to make the link more obvious.

**Comment by katska** [comment]
The link to the comment isn't something you can easily share. It only updates the url to show that specific point in the page. Yes that's useful, but It's not a 'share this ( with other people who might also want to respond)' the only link we have that leads to an action is the 'report comment' link.

**Comment by katska** [comment]
Given the work we're doing on [TVFY](https://github.com/openaustralia/publicwhip/issues/1316) I'm joining a dot or two and thinking people may also want a little snippet to share of their own view on a thing here. Is that wonderfully validating, or just plain crazy? Or maybe there are subtler issues afoot there.
