### ISSUE TITLE
Do a survey and interviews with people who comment

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#770]
We need to start getting a better idea of who these people are and how they understand the commenting process.

I propose we do a short survey to get some information and find people for interviews and make observations about how they go through the commenting process

**Comment by equivalentideas** [comment]
Some questions to try and get answers to:

* What kind of people are commenting currently?
* How do they feel about the experience of commenting?
* How easily do they get through the process of commenting?
* Do people see the comments as a discussion between neighbours or just a message to council? or both?
* Who do they think these comments go to? Do they understand the difference between the council organisation and the councillors?

We can compose the survey to answer some basic stuff and get deeper with interviews.

**Comment by equivalentideas** [comment]
@henare could I get some quick feedback survey for PlanningAlerts commenters? https://docs.google.com/a/oaf.org.au/forms/d/1UjuduCYohuE8mrIcAcqbjss8kWLJB_ptczUsfP5kl8Q/viewform

Are their any other specific questions you're interested in?

It’s structured to:

* ease people in
* then get some more open ended responses to capture any observations they have about the system
* then ask if they’re up for interview

This should get us some useful responses from even the people who aren't up for an interview.

I'd like to send this to people who've made a comment in the last 3 months.

**Comment by henare** [comment]
>@henare could I get some quick feedback survey for PlanningAlerts commenters? 

At a quick glance it looks fine. Sorry I can't really be more helpful than that with quick feedback on something quite open ended like this.

**Comment by equivalentideas** [comment]
No worries.

I'm going to get the emails out of active admin, load them into civi crm and do an email out like the one we did in Jan.

**Comment by equivalentideas** [comment]
Working on the commenting section a bit has made me add a question, 'why did you comment on a development application?'

**Comment by equivalentideas** [comment]
Scheduled an email based on the very successful last survey email we sent out in Jan. The email text and subject and basically the same. I’ve sent a test out and checked it and scheduled the email to go around the same time as the last one, 8am tomorrow.

Subject: Help PlanningAlerts with a few quick questions

Body:

> Hi, Luke here from the charity behind PlanningAlerts, the OpenAustralia Foundation.
> 
> Firstly, thanks for being a part of the community making PlanningAlerts a success. I’m emailing you because you recently made a comment on a planning application in PlanningAlerts.
>
> We’re currently working to improve the commenting process you went through. We want to get to know the people who have commented so far, so we can work out the best approach.
>
> [**We’d greatly appreciate it if you could take a minute to fill out a quick questionnaire.**](#)
>
> Thanks again for your support.
>
> Luke Bacon, Designer
> OpenAustralia Foundation

**Comment by equivalentideas** [comment]
I'm going to wait until #788 is merged to line these up, because I want to see people using the most recent version of the comment for, with councillors in it.

Email to organise interviews:

Hi, Luke here from the OpenAustralia Foundation, the charity that runs PlanningAlerts.

A couple of weeks back you completed a questionnaire I sent you. We've had great answers that are helping us learn more about peoples’ experience making comments on a development applications in PlanningAlerts. This is one of the most important parts of PlanningAlerts and we want to make it easier for everyone to have their say.

You answered that you'd be happy to do a short follow up interview with us to help us learn more.

Are you available for 20 minutes some time this week or early next week?

Are you able to do the interview over Skype?

I'll be asking you:
* about the time you last commented
* to show me how you found the application you commented on using screen share in Skype.
* to try out an early prototype of some improvements to the commenting system that we're working on via Skype.

We'll be recording the session so that we can make notes and get the most out to it.

We won't share your response, from the survey or interview with anyone outside the OpenAustralia Foundation team. If you are happy with it, we may use quotes from your response, that aren't attributable to you, in a blog post about this process.

Thanks for your help with making PlanningAlerts better for everyone.

Luke

**Comment by equivalentideas** [comment]
Emailed four people to line up interviews.

**Comment by equivalentideas** [comment]
Blog post with observations from the survey responses https://www.openaustraliafoundation.org.au/2015/10/20/who-comments-in-planningalerts-and-how-could-it-work-better/

**Comment by equivalentideas** [comment]
Here's some observations from the first usability testing session with one of the survey responders. I'm extracting stuff from this onto their relevant issues. This person were very interested in planning and new quite a bit about the system. This represents one set of PlanningAlerts users, but it's really important to cover the test expert users in the rest of this testing.

### Email

They use Apple’s Mail.app on a big 20+ inch iMac monitor.

Mail.app showed banner with: “Mail thinks this message is Junk Mail.”
It didn't load images and no alt text showed. User wonders why images don't load some times but doesn't see the banner and click 'not junk' or 'load remote content'.

They had their mail window very wide so the text of each application stretched across their whole screen.

The text of the application descriptions was really tiny.

The person noted that the emails don't come in regularly and wonders why that is.

They read the descriptions and deletes the email if they find no applications interesting. Also deletes the email once they’ve looked into the applications it contains.

They’re not interested in applications related to liquor licenses. They are interested applications “in my area, ones that are vitally important” and:

> I'm concerned about ones that are going to be in the public view.
> I'm concerned about the big ones.

They generally find the amount of information about applications frustrating and so often decide on which applications to look into based on their street, “is it an interesting road?”.

> The other thing that bugs me is it's not explicit [the description on the applicaiton].
> They just say 'demolish', 'subdivide', there's no grading.
> Like that's a small job, probably going to cost 10000, or 100000.
> Where as the big jobs would cost 10 million...
> The cost indicates roughly how big its going to be.

You can only see the first few lines of the email subject: '5 new planning appli...'

Goes to view the application by clicking the application address.

Goes to add a comment on an application by clicking the 'Add your own comment' link.


### The application page

Suggested it would be really helpful to him if the architects drawings of what the development will look like was provided up front and on the street notices. Says this is what they do in Berlin.

> It's sort of a chore to go through [and work out if they're interesting].
> Obviously this [the street view image] is straight from Google.
> The address says Edgeware Rd, but the Google view is the lane at the back.
> I look at this and I think, “oh well, this is not important”,
> I'm not motivated to look at it any further.

They engage a lot with the street view image, clicking the arrows to move up and down the street.

Uses the 'Read more information' link to learn more about application.

Uses links in council page to see the applications planning diagrams.

When a page loads very quickly, they’re impressed.

> I'm not motivated to respond to that because I'm not that worried by it.

On another application, they tried to find out more about an application, but the council’s site had an application error for that page and wouldn't provide it.

### Comments

They were very enthusiastic about reading comments by other people:

> (enthusiastic) Yeah [I do read the comments by other people]!
> I almost had a dialog going the other day.


> I made a comment, Two people made negative comments,
> this third person came on and made a comment about my comment.
> Obviously that riled me up. He had his full name.
> I don't know what the system is, sometimes I just see the person's Christian name
> and some times I see the full name...
> This guy who made a snide remark about my snide remark, he had his full name
> so I went to google and looked him up and saw he works for so and so building company.
> I don't know if the council looks at stuff like that or not.


They look up the names of people who comment in Google to learn about who they are.

Over all they’re not sure what parts of the process are controlled by PlanningAlerts and what parts the council control. Not sure if we confirm comments, or if the council send the confirm email. Not sure if we decide what to display about the commenter and their name, or if it's the council.

They don’t revisit applications once they have commented on them, because they “feel powerless”.

They’d never seen the comments index before but were quite enthusiastic about it:

> wow some people write some really long ones. Thats good.
> South Yarra! You're in Victory as well?
> And you handle all of this from Sydney? That's brilliant.

Refers to comments as 'responses' and 'I write my response'

### The planning authority

> I've got a totally cynical view because the previous Major said to me,
> said to us [the heritage society], that they barely pay attention to the comments we get,
> but we do pay attention to the people next door to the applicant.
> The means they only’s about 5 neighbours who get any say.


> I don't pay attention to their formula letters.


> I don't think they can [actually listen to citizens], it's such a messy business.
> I hate the council, but on one hand I'm sympathetic,
> they really are bound by red tape.
> There are a lot of crazy people in the world,
> and they have to deal with [feedback] from all these crazy people...
> I don't think there's any way of know what they do with the feedback.
> The only way I could know is if I went to the council meeting,
> but for meet thats a pain in the bum. The council meets 6 km away,
> I'd have to get four trains to get there and back. So I'd spend 1.5 hours travelling.
> And the meetings are really aggravating...
> the municipal alderman system just reeks of the 19th Century,
> where these powerful people sit with their backs to the people and decide...
> it's not a happy experience.  I only go if it's really, really, really important.

### The commenting form

They are aware of and pays attention to the placeholder text.

> The annoying thing about the DA is
> you don't know if the person putting in the application is
> seriously proposing what they're suggesting.
> Sometimes they'll say they want a 10 story block of buildings
> and it's just so outrageous they know they're going to be knocked back.
> The frustrating thing for people like me is that it's just a game.
> How much time am I going to bother playing their game, especially when I don't trust council,
> the planning officer or the person putting in the DA. So I don't write long letters.
> I know the guy from the Heritage society and his letters are always clear,
> they always refer to the report which is very technical.
> I'm not an architect so—normal people can't understand what the processes are.

> I write my thing, which is only about 30 or 50 words.
> Then I put in my real name, put in that [email], and that [address] and it gets posted off.
> And then council, actually I don't know, is it council
> or is it you who sends a note to me asking me to confirm. I do that and I send it in.
> Then a council staff officer, up until recently would send me a letter.
> I've got no idea if any of my suggestions or comments or rude remarks
> or helpful remarks are listened to. There is a futility I suppose.

The comment form with councillors had a big error,
the option to write to councillors doesn't display. (this has been fixed in #828)

See’s the 'You’re too late' message in the comment form and asks whether they can still comment.

When they see the option to write to a councillor says “Oh, I don't trust them either”.

The line-height of the comment input is too thin.

Clicks the radio input quite precisely for the councillor, rather than their name.
It seems like this kind of affordance that the councillor is clickable is important.

Uses Safari’s autofill for the email and address.


### Comments and messages to council

They aren’t immediately aware of any difference between the types of comments.
They do notice that it’s yellow: “Is that because it’s the most recent one?”.

Sees the info 'Sent to Melissa Brooks about 5 hours ago. They are yet to respond.' 

> “They are yet to respond?” Melissa’s put in her comment and it's been sent through to you,
> but they haven't confirmed? Your testing that their email is real?
> I don't know who “They” are. “5 hours ago” I thought it was all computer generated.
> Or Melissa has sent it, and your machine has asked Melissa to verify,
> but Melissa is at work so she hasn't yet verified ...
> Oh! Laurie has sent it to Melissa. So Melissa is a councillor,
> so your asking for the local councillor to respond.

All this confusion seemed to come from not understanding that Melissa was the recipient. They didn't recognise who the councillor was so assumed they were the person who sent the email. They weren't drawn to the information at the top of the comment at all, but when they eventually saw it they understood what was going on.

### General

It didn't seem like they'd seen the authority page before or
the applications index page for an authority.

Seemed like they hadn’t used the search page before.

**Comment by kat** [comment]
@equivalentideas just attach the documents capturing your research here.

**Comment by equivalentideas** [comment]
We documented the results of this in a blog post last year https://www.openaustraliafoundation.org.au/2015/10/20/who-comments-in-planningalerts-and-how-could-it-work-better/ .

This fed into the design we've been doing on [Ask Your Councillors](https://github.com/openaustralia/planningalerts/milestones/Ask%20Your%20Councillors%20-%20Beyond%20MVP).
