### ISSUE TITLE
As an developer of PlanningAlerts, show me some stats about the use of the site, so I can better understand how it is being used

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#772]
I'm always surprised to hear how many people there are signed up for alerts, I thought there was around 25000, but Henare tells me there's much more.

A simple chart of new signups per week would be helpful on a stats page, like https://morph.io/users/stats or https://www.gov.uk/performance/prison-visits .

This would help us track the performance of our changes.

It would be also helpful to get a better understanding of how comments are being used and how our changes impact use. Metrics could include like:

* number of people who commented per week
* number of comments per person per week

**Comment by henare** [comment]
You can now easily see how many active alerts there are in the admin backend because of 0a867e9.

It's currently sitting at 37,800.

**Comment by equivalentideas** [comment]
One of the key aims of PlanningAlerts is to get more people engaged with local democracy. This is why we're working on improving the commenting system at the moment https://github.com/openaustralia/planningalerts/issues/773 :

> The aim is to strengthen the connection between citizens and local councillors around one of the most important things that local government does which is planning.

To measure how we're going with this, we can track the track _the number of first time commenters each week_. These are people who have taken a step to get involved in their local democracy through PlanningAlerts. We want to see an increasing number for people taking that step.

We want to consolidate their connection and help them become more engaged if they find it useful.

@henare just came up with the idea of tracking _the number of people who commented this week who have commented before_. Then we've got return commenters and new commenters adding up to the total number of commenters each week.

This seems like a good simple start to get us going.

**Comment by equivalentideas** [comment]
I'm gonna pick this up and try and get a first pass together.

I think periods of days, rather than weeks, will give us more rapid feedback and be more immediately useful.
