### ISSUE TITLE
[Broken into parts and closed] As someone interested in a local development application, help me write to my local councillor about it, so that I can get their help or feedback and find out where they stand on this development I care about

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#773]
From [our 3 month plan blog post](https://www.openaustraliafoundation.org.au/2015/06/25/the-next-3-months-are-going-to-be-really-busy-here-is-our-plan/):

> Then, Luke and Henare will start working on our next major project. The idea is simple. In PlanningAlerts allow people to write to their councillor about a development application on top of what it currently does which allows you to write a comment on a development application which directly feeds back into the official process.
>
> The aim is to strengthen the connection between citizens and local councillors around one of the most important things that local government does which is planning.
>
> This will actually be a surprisingly technically involved project which will involve quite a few different pieces. We will need to find out every councillor in the country, including their contact details (and hopefully their picture). We already starting collecting this data by writing scrapers. Then, information will need to get crowdsourced. We plan to store this information in PopIt (so it can be reused by others) and we will integrate PlanningAlerts with WriteIt to actually send the emails to the councillors.
>
> Then, of course, there’s the vital bit of making this work beautifully and simply within the existing PlanningAlerts application. This is the most fun, satisfying and crucial bit.

We also did this flow sketch at our kickoff meeting (not the best image quality):

![img_4184](https://cloud.githubusercontent.com/assets/1239550/9844848/ef2a69ae-5b09-11e5-8376-788874e29464.jpg)

This shows our idea for how messages to councillors would sit next to comments to council.

**Comment by equivalentideas** [comment]
I'm going to start this off by digging into a static prototype of the feature. During that process I'll bump up against the current [UX commenting issues](https://github.com/openaustralia/planningalerts/issues?q=is%3Aopen+is%3Aissue+label%3Acommenting+label%3AUX) and fix them as I go.

**Comment by henare** [comment]
Nice :ok_hand:

**Comment by equivalentideas** [comment]
Picking up from #755:

> and I had a think about how we can reduce the number of decisions a user has to make upfront. People just want to have their say and have it make an impact—I'm going to iterate this into a single form that presents different options depending on your choices.

I'm going to try a version of this where you get straight into writing your message, then get to choose who it goes to. During this step the implications of these decisions are explained. Then you finish off the final details (name and address), and the get a clear warning that your name and comment will be public before you post your comment.

I think the name should come before you choose who it will go to (and possibly even before the comment body) to give people some personal ownership over their words and discourage abuse.

Here's a rough sketch of this flow:
![img_4194](https://cloud.githubusercontent.com/assets/1239550/10036130/7e3b8730-61e6-11e5-9e90-637bde196b02.jpg)

**Comment by henare** [comment]
@equivalentideas are you planning to do this in such a way that the current commenting process experience is improved, i.e. it will be better even without enabling the writing to councillors feature?

**Comment by equivalentideas** [comment]
> @equivalentideas are you planning to do this in such a way that the current commenting process experience is improved, i.e. it will be better even without enabling the writing to councillors feature?

Yeah that's the plan, generally putting more input forward and explaining the important info when it's relevant #766 #371 #767

**Comment by equivalentideas** [comment]
This issue is really a whole feature, I'm going to break it apart into issues for the different steps involved so I can track this more clearly. Then I'll close this one.

Here's the bits to this feature I've identified so far, I'm sure more will come up:
![img_4228](https://cloud.githubusercontent.com/assets/1239550/10567606/099c2aa0-7655-11e5-9675-8b8ca0f38338.jpg)

**Comment by equivalentideas** [comment]
I've broken this into #809 #810 #811 #812 #813 . I'm gonna close this now, I'll add something to the title so it's clear this was broken up rather than completed.
