### ISSUE TITLE
Search for address with radius set results in error

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#776]
e.g. /?q=George+Street%2C+Redfern+NSW&radius=200

`[PlanningAlerts/production] ActionView::Template::Error: comparison of String with 1000 failed`

## Backtrace

    line 23 of [PROJECT_ROOT]/app/helpers/application_helper.rb: <
    line 23 of [PROJECT_ROOT]/app/helpers/application_helper.rb: meters_in_words
    line 3 of [PROJECT_ROOT]/app/views/applications/address_results.html.haml: _app_views_applications_address_results_html_haml___487536796_120097430

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/37075/faults/14825988)

**Comment by equivalentideas** [comment]
This has been fixed by @JWells in https://github.com/openaustralia/planningalerts/pull/905

See https://www.planningalerts.org.au/?q=George+Street%2C+Redfern+NSW&radius=200

:fireworks: :fireworks: :fireworks:
