### ISSUE TITLE
What do people do after their trial expires?

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#777]
Are people who get put onto a trial subscription unsubscribing to continue getting their alerts? or are they just not getting their alerts any more?

**Comment by henare** [comment]
Out of 150 people so far:

* 19 people have asked for and been given free subscriptions
* 2 people have unsubscribed all their alerts (1 on $34 and 1 on $15)
* 8 people have unsubscribed enough to start getting alerts again (3 people on $34 and 5 on $15)

**Comment by equivalentideas** [comment]
I'm looking at some of the info in Cuttlefish to see if we can understand anything more about these people who are getting expired subscription messages and aren't unsubscribing or subscribing.

**Comment by equivalentideas** [comment]
This issue has become a bit of a discussion about what people who don't subscribe or ask for a free subscription are doing—I'll change the title. I've just done a rough survey of a few potential subscribers’ pattern of opening alerts.

Behaviour changed:
* (2) They stop opening their alerts once the trial expires. They could be ignoring them or marking them as spam.
* (4) they often opened their alert emails before their trial ended, now the open them occasionally

Behaviour unchanged:
* (2) They occasionally opened alerts before, unchanged since trial
* (4) They opened most of their alerts, with their trial expired they continue to open most alerts

Doesn't open alerts ever:
* (1) They haven't opened an alert since a few months before the trial began.
* (4) People whom we have no record of them opening an alert, before or after their subscription began.
* (2) hard bouncing, they're never received an alert

I think there are a couple of interesting observations from this:

* A large number of people of 'potential subscribers' don't open or receive their alert emails. This could mean that pool of people we've marked as 'potential subscribers' is significantly smaller than expected because many of them don't open their alert emails.
* People continue to open their alert emails even after their trial has expired. This could mean they are getting useful information from the subject of the email? Why are they doing this?

This second point would suggest that we should experiment with the email subject line and text for expired subscribers, as people still see these messages and are still interested in their alerts.

The first point might suggest that our conversion rates against real potential subscribers are higher than expected, because we're actually dealing with a smaller pool than we thought. Not sure what to make of that yet.

**Comment by henare** [comment]
Since we started tracking things 41 people have clicked the link from their expired trial and only 4 from when they were first put onto a trial.

Digging into the latter case I found:

* One person removed all 5 alerts they had set up from 2014
* Despite having 3 alerts setup, another person has only got one alert since their trial expired
* 1 non-commercial subscription
* And another person that has been a subscriber for a year with 3 alerts. They often open their alerts and since their trial expired they do it a little less but they're still opening their emails.

So I've emailed the last person to ask them what's up.

**Comment by henare** [comment]
I'm now doing this a bit more systematically [in this spreadsheet](https://docs.google.com/spreadsheets/d/1ono2ICXrL4tKxJZypw8lzvy3JLolOygpmqhWTKlOIiI/edit#gid=911755964).

There's a big group we don't understand, that we should contact and ask some questions. These people are on an expired subscription, are still getting emails, and haven't done anything about it. Often they're even still opening the email - why?

**Comment by henare** [comment]
There are ~150 people that haven't done anything and are therefore still presumably getting the email. There's a much smaller subset of around 35 that we know have clicked the subscription link. Since this group is smaller, and more interesting, I think I'll trawl through them first.

**Comment by henare** [comment]
Out of the 36 people in that group, only 3 hadn't opened an email in the last month. So that comprehensively confirms that group is still regularly opening emails for some reason. Time to email them and ask why.

**Comment by henare** [comment]
I've emailed 9 people to start with.

**Comment by henare** [comment]
We're not doing the paid feature any more. Closing.
