### ISSUE TITLE
Submitting the comment form with a missing field causes a server error

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#778]
It should show a nice message to the user instead.

    [PlanningAlerts/production] ActionView::Template::Error: Missing partial comments/_comments_area, application/_comments_area with {:locale=>[:en], :formats=>[:html, :text, :js, :css, :ics, :csv, :vcf, :png, :jpeg, :gif, :bmp, :tiff, :mpeg, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :arb, :haml, :rabl]}. Searched in:  * "/srv/www/www.planningalerts.org.au/app/releases/20150918053200/app/views"  * "/srv/www/www.planningalerts.org.au/app/shared/bundle/ruby/2.0.0/gems/devise-3.4.1/app/views"  * "/srv/www/www.planningalerts.org.au/app/shared/bundle/ruby/2.0.0/bundler/gems/activeadmin-7e72b7881eb6/app/views"  * "/srv/www/www.planningalerts.org.au/app/shared/bundle/ruby/2.0.0/gems/kaminari-0.16.3/app/views"

## Backtrace

    line 40 of [PROJECT_ROOT]/app/views/applications/show.html.haml: _app_views_applications_show_html_haml__962219298_105754090
    line 25 of [PROJECT_ROOT]/app/controllers/comments_controller.rb: create

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/37075/faults/15376779)

**Comment by henare** [comment]
I think this is a regression @equivalentideas so assigning to you for a quick fix.

**Comment by henare** [comment]
Still doesn't work if you're an admin.

**Comment by equivalentideas** [comment]
I've tested this as admin and logged out, all working now.

**Comment by henare** [comment]
Good stuff :mortar_board:
