### ISSUE TITLE
Server error when trying to register for API key when you already have an account

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#780]
To reproduce:
- Register an account
- Sign out and try to register the same email address
- Server error. Instead we should show something helpful to the person

https://app.honeybadger.io/projects/37075/faults/15438003#notice-summary

**Comment by TheChirpyWitch** [comment]
Hey! I don't have access to Honeybadger and I can't seem to reproduce this error. When I try to sign up with the same email, I get a different mail saying that I am already registered. So is this still valid?

**Comment by henare** [comment]
Great question @TheChirpyWitch :hibiscus: I wasn't clear that this isn't to do with regular email alerts, it's about registering for an account to get an *API key*, which you do here: https://www.planningalerts.org.au/users/sign_up

**Comment by henare** [comment]
This is strange. I can't see why this error would have happened. We've always had [Devise's `validatable` module switched on](https://github.com/openaustralia/planningalerts/blob/a6451ed76eb5fb8c5e50243ef563199cba94f7b2/app/models/user.rb#L4-L5) which does Active Record validations and so shows this:

![selection_001](https://user-images.githubusercontent.com/48945/27161709-980f6304-51c0-11e7-880a-21f92416e448.png)

Those aren't very helpful and leak information (that the email address has an account) so I'll change this issue to be about improving them.

**Comment by henare** [comment]
>I'll change this issue to be about improving them.

I decided against that and instead opened #1164 and #1165.
