### ISSUE TITLE
Improve conversion on the subscriptions page

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#782]
Looking at Google Analytics, In the last month we've had about 70 people hit the subscription page via an email alert (mostly from people in their trial period). We've only recorded 2 clicks on the subscribe button on that page—one of those clicks resulted in a subscription. 19 people have requested free non-commercial subscriptions.

So people are clicking the subscribe links in their email, probably to get more information, and then not clicking the subscribe button on the page. What changes could we experiment with on the subscription page to convince more people to subscribe?

**Comment by henare** [comment]
Very interesting data! Your idea to de-emphasise the non-commercial subscription could be a simple iteration to test.

**Comment by henare** [comment]
We're going to remove this page now we're not doing the paid feature.
