### ISSUE TITLE
Rerun $5 subscription cohort test

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#783]
We had one subscription from a cohort of 50 at the $5 subscription rate. It came about a week after their subscription expired.

Comparing these results to the 0 subscriptions from the $34 and $15 cohorts of 50 would suggest that price is a factor in determining whether people will subscribe.

Let's rerun this test with another cohort of 50 to see if we can confirm this with repeatable results. @henare could you set this up please?

**Comment by henare** [comment]
I've run the following on the server to do this:

    cd /srv/www/www.planningalerts.org.au/app/current && /home/deploy/.rvm/wrappers/planningalerts.org.au/app/bundle exec rake planningalerts:subscriptions:rollout[planningalerts-5,50] RAILS_ENV=production

**Comment by henare** [comment]
Again, we had 1 subscriber. This person opens every email they get and subscribed after 1 week of having an expired subscription. They have 6 alerts set up and they're a property manager at a large firm.
