### ISSUE TITLE
How to publish local [PlanningAlerts] onto your Facebook page

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#786]
https://www.mysociety.org/2014/11/20/how-to-publish-local-fixmystreet-reports-onto-your-facebook-page/

Is this something people want? Then let's do it for PlanningAlerts!

**Comment by mlandauer** [comment]
It would be good to figure out somehow if this would be useful to people. I'm not a Facebook user so definitely not the person to know :-)

**Comment by mlandauer** [comment]
@katska any ideas on how we could easily figure out if this would be something useful to people?
