### ISSUE TITLE
Test moving the information about what commenter information will be public and where it will be send to

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#793]
Will people be more likely to comment if the introduction text is above the button rather than above the first text input?

I'd say people will be more likely to read and understand this text if it is above the button, because currently it it in between the 'add your comment' call to action and the place you do that. Is it currently just adding visual noise above the comment field, making the thought process to commenting more complex than it needs to be.

Aside from this idea, I think it would be good to move this down anyway to make the comment process seem more approachable up front.

Lets AB test this.

This is extracted from https://github.com/openaustralia/planningalerts/pull/788#issuecomment-143680325

**Comment by henare** [comment]
I think making the comment introduction much shorter and simpler can only be a good thing.

I'd be up for making this change if it was part of a broader reworking and refinement of what's in the introduction and what follows it.

**Comment by equivalentideas** [comment]
We've simplified the intro text a bunch since this issue was done, and we now have a very short nice intro into commenting. I'll close this.
