### ISSUE TITLE
The important information that there's a limited time to comment on an application is buried

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#794]
If there's only a few days to comment on an application, that's quite important information "You have 1 day left to officially respond to this application.". It's also adds an urgency to commenting.

Currently this information in one of several paragraphs under that 'Add your comment' heading:

![screen shot 2015-09-29 at 12 06 18 pm](https://cloud.githubusercontent.com/assets/1239550/10153809/8e06b010-66a3-11e5-8a85-ea35231a674c.png)

I think it should be moved above this section for two reasons:
1. This is information that will prompt you to comment so should lead you to the 'add your comment' section, not be a sub point of it.
2. This is important information that should be seen quite quickly when looking at the application.

It could go above the ''We found this application for you on the planning authority's website 7 days ago. It was received by them 1 day earlier." sentence, which is conceptually related but less important to people:

![screen shot 2015-09-29 at 12 08 48 pm](https://cloud.githubusercontent.com/assets/1239550/10153811/921503fa-66a3-11e5-98eb-17ccca244504.png)

We could AB test this to see what impact it has on commenting and alert signups.

**Comment by henare** [comment]
:+1: I like the idea of making it part of the text immediately below the comment header:

>You have 1 day left to officially respond to this application. Add your own comment!

**Comment by equivalentideas** [comment]
> :+1: I like the idea of making it part of the text immediately below the comment header:

Thanks @henare do you mean position 2 in this image? I was suggesting position 1 above.

![screen shot 2015-09-29 at 4 48 34 pm](https://cloud.githubusercontent.com/assets/1239550/10157081/42b4d28c-66ca-11e5-9366-1ab8a713f514.png)

**Comment by henare** [comment]
Position 2 is the most obvious because it enhances what's already there.

We currently have a separator between the application and the comments so including information about commenting in the application section would be muddling things up.

**Comment by equivalentideas** [comment]
> We currently have a separator between the application and the comments so including information about commenting in the application section would be muddling things up.

hmmm. I actually think it's more confusing to have this information inside the comment section and it's something that should get you interested in the comments and commenting, rather than something you discover once you're looking at the comments/commenting. We should have a play and go with whatever works best :balloon:

**Comment by equivalentideas** [comment]
Looks like we thought a good course of action would be to move the notice to position 2 discussed above. That also feels like a nice simple iteration.

**Comment by mlandauer** [comment]
I think this change is a good one

**Comment by kat** [comment]
agreed!

—
Katherine Szuminska

--- original message ---
On August 18, 2021, 10:37 AM GMT+10 ***@***.*** wrote:



I think this change is a good one

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.
--- end of original message ---
