### ISSUE TITLE
Form inputs don't have visible labels

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#795]
Currently the comment form has no visible labels:

![screen shot 2015-09-29 at 12 23 02 pm](https://cloud.githubusercontent.com/assets/1239550/10153958/f548a1a6-66a4-11e5-84ab-8194dcc8f1d7.png)

The placeholder text is used as the visual label, and when you start inputing text it disappears:

![screen shot 2015-09-29 at 12 27 32 pm](https://cloud.githubusercontent.com/assets/1239550/10154005/8e17594a-66a5-11e5-8c14-a9721fb3016c.png)

This is causes a number of usability problems as detailed in [this article](https://www.paciellogroup.com/blog/2011/02/html5-accessibility-chops-the-placeholder-attribute/):

> * For keyboard users this can be problematic as they must read ahead of current focus when filling in forms.
> * Users, especially those with memory impairments will not have the text label available for reference at the same time as filling in a field.
> * Users may think a text field is already filled in and skip over it. Data suggests that this can be an issue.
> * If the placeholder hint text is useful information it should be available while the user is filling in the field.

On top of this, the low contrast text (which is basically required for this patter because otherwise it will appear as pre-inputted text) is hard to see for people with limited sight or monitors with poor contrast. [The contrast of the text colour against the background doesn't meet the WCAG 2.0 standard for readable text contrast](https://leaverou.github.io/contrast-ratio/#rgb%28169%2C169%2C169%29-on-white).

**Comment by henare** [comment]
:+1: Nice. Alaveteli recently did a lot of form redesigning that incorporated things like this I think.
