### ISSUE TITLE
Two alerts with same address don't send email with the same frequency

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#806]
I've just come across someone who has an alert set up for addresses like 123 Fake Rd, Neutral Bay **NSW** 2089 and 123 Fake Rd, Neutral Bay **New South Wales** 2089

When I look these up in PlanningAlerts, I see both addresses have found applications 2,3,4,5,9 etc. days ago.

The alert for the address with "New South Wales" has sent emails 3, 4, 9,12, 24 etc. days ago.

The alert for "NSW" has send emails 23 days ago, about 2 months ago, about 4 months ago.

If these alerts as collecting the same applications, why aren't they sending with the same frequency?

This inconsistency seems like unexpected behaviour to me. Not sure what to make of this, but thought I'd note it here for discussion.

**Comment by mlandauer** [comment]
There's no way I'll be able to reproduce this problem - and there are all sorts of fairly innocent reasons why this could have happened.
