### ISSUE TITLE
Don't email me about comments that I made, it's annoying

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#807]
I got an email telling me about a comment I made. This was a little confusing at first and just annoying.

**Comment by henare** [comment]
I'm not sure about this. I quite like seeing my comments in amongst all the others. It also reinforces how the system works in peoples' minds.

**Comment by equivalentideas** [comment]
Maybe I was just annoyed because it was an email with only my comment.

> It also reinforces how the system works in peoples' minds.

I like that, I think it's more important that if people are a little confused at first. I'm gonna close this.
