### ISSUE TITLE
Comment performance table counts for days are different from what you see on comments index

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#808]
The date that a comment was posted, as shown on the [comments index](https://www.planningalerts.org.au/comments), is in local time. On the [performance page](https://www.planningalerts.org.au/performance) it shows commenter counts for dates based on when the comment was updated in UTC time. This means you'll see four commenters today in the comments index, and then on the performance page it will only list two commenters today, because two were in the morning local time and last night UTC.

This is confusing and weird.

**Comment by mlandauer** [comment]
We removed the performance page a while back so this isn't relevant anymore
