### ISSUE TITLE
Send comments made to councillors to the intended councillor

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#810]
How should the person’s message be presented to a councillor? What additional email and links do they need.

We’d like Councillors to respond helpfully to people’s messages and be respectful so that people feel they are being listened to, have a positive experience and continue to engage with local democracy.

The Councillor receiving the message needs to know:

* the name of the person commenting, so they can understand who they’re talking to and reply to them individually by name;
* which application the person writing to them is referring and where they can get more information about it;
* what the person is saying (they need to read the text of the message);
* that the message they're received was also posted publicly on PlanningAlerts and that their response will be public;
* whether or not the person is a local resident (not sure about this one?); and
* what they can do if the comment is abusive, so they don’t feel under attack and are reassured that abusive comments aren’t tolerated by PlanningAlerts.

**Comment by equivalentideas** [comment]
Here’s an idea, based on a made up message from me to Councillor Sam Iskandar:

Hi Sam Iskander,

You’ve got a new message from Luke Bacon in relation to a [local planning application for 232 King Street Newtown](https://www.planningalerts.org.au/applications/582479), “Use of public footway on King Street in association with the licensed 'Moo Gourmet Burgers', including 2 tables, 4 chairs and 2 barriers. Proposed hours of use are 11:00am to 10:00pm Monday to Sunday inclusive (renewal of previously approved application)”:

> Hi Sam,
>
> I think more street seating is great for Newtown as it really brings the street to life. Is their a way that we could make this easier for local restaurants and cafes? Of course we want space for pedestrians to have room to pass, whether they’re walking, using wheelchairs, riding skateboards, etc. .
>
> Maybe if there was a blanket rule, like 'every business can have seating as long as their are 3 meters of clear space for pedestrians to pass', then Council could save time dealing with these and businesses could get on with it. What do you think?

This message was [posted publicly on PlanningAlerts about 1 hour ago](#link_to_comment). You can publicly respond to this message by simply replying to this email.

If this comment is spam, abusive, unlawful or harassing you can [report it for removal from PlanningAlerts](#link_to_report_comment).

Best wishes,

PlanningAlerts

**Comment by equivalentideas** [comment]
If we want to include the person’s address, we could write:

> You’ve got a new message from Luke Bacon of 123 Fake Lane, Dreamville. They’re writing in relation to a local planning application for 232 King Street Newtown ...

This would help someone immediately know if they were dealing with one of the people they formally represent or someone else.

I'm not sure whether this needs to be included at this point. It feels like preempting a problem that we haven't seen in reality yet.

**Comment by equivalentideas** [comment]
Maybe this would be clearer if we broke up the first sentence a bit:

You’ve got a new message from Luke Bacon in relation to a [local planning application for 232 King Street Newtown](https://www.planningalerts.org.au/applications/582479). The application is for, “Use of public footway on King Street in association with the licensed 'Moo Gourmet Burgers', including 2 tables, 4 chairs and 2 barriers. Proposed hours of use are 11:00am to 10:00pm Monday to Sunday inclusive (renewal of previously approved application)”.
 
Luke Bacon writes:

> Hi Sam,
>
> ...

**Comment by henare** [comment]
This is working in #844 but we still need to change the template that's used (it's currently the same one as a planning authority comment).
