### ISSUE TITLE
Alert people in the area when someone writes to a local councillor

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#811]
This should work the same you get alerted about current comments, but use the style for messages to councillors instead of the official comment style. In other word, it should match what you seen in the comment feed on an application.

**Comment by henare** [comment]
As part of #844 this will already happen but they currently would just look like any other comment - we need to change this.

**Comment by equivalentideas** [comment]
I'm doing the text version of this as well as the html/css version.

**Comment by equivalentideas** [comment]
Here’s where this is at in the HTML email:

I've pulled the application address out into a header on the panel, like in the site, and added the application’s description to this. That clears up room and focus for the comment author’s name and the name of the councillor. We’re trying to make this a small iteration for the MVP, so I haven’t added colours like on the site because it appears too out of place in the grey and orange colour scheme of the email. I've also added the 'delivered to local councillor x. They are yet to respond' text to the bottom of the councillor comments to help people see that this comment is different from the others.

![screen shot 2015-11-09 at 2 09 50 pm](https://cloud.githubusercontent.com/assets/1239550/11025177/1e54c482-86ec-11e5-9d42-e426e4251018.png)

The text version just has who the comment was sent to added, and the description of the application so it’s clearer this is a comment on an application. I haven't added the 'delivered to ...' text I think it these text based versions need to be as simple as possible because we can't add much visual structure:

> Jacinta O'Brien wrote to local councillor Sylvie Ellsmore “To demolish part of the...” at 28 Terminus Street Petersham NSW 2049:
> 
> Wholeheartedly support this application!
> 
> View comment on PlanningAlerts:
> https://localhost:3000/applications/2?utm_campaign=view-comment&utm_medium=email&utm_source=alerts#comment182
> 
>  -----------------------------
> 
> Jennifer Killen commented on “To demolish part of the...” at 28 Terminus Street Petersham NSW 2049:
> 
> Very little information seems to be available except that the approval would allow one event every week for a year from 6pm until 2am.
> 
> Do the plans include noise insulation? The nature of the events is not indicated but they are more likely > to be dance parties than prayer meetings.
> 
> All night noise from the airport, which is much further from my house than this building, is already a > problem.
> 
> I do not want further sleep disturbance. Although this is an industrial area, the nearest dwelling is not far away.
> 
> Size of events is not defined. Plans for parking are not available. 
> More detail is needed
> 
> View comment on PlanningAlerts:
> https://localhost:3000/applications/2?utm_campaign=view-comment&utm_medium=email&utm_source=alerts#comment183
> 
> -----------------------------

**Comment by henare** [comment]
>We’re trying to make this a small iteration for the MVP

:+1: LGTM

**Comment by equivalentideas** [comment]
> :+1: LGTM

Awesome thanks for that. This is all merged so I'm going to call this closed.
