### ISSUE TITLE
Comment display in email is inconsistent with the website

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#817]
On the website comments have the name of the commenter first now but that's different to the email alert. Shouldn't they be consistent?

![selection_001](https://cloud.githubusercontent.com/assets/48945/10571709/6646e9a6-768d-11e5-9e71-50133d037ec7.png)

vs.

![selection_002](https://cloud.githubusercontent.com/assets/48945/10571715/73fe48be-768d-11e5-8901-ea8242e45c8b.png)

**Comment by equivalentideas** [comment]
> Shouldn't they be consistent?

Yep I think so :+1:
