### ISSUE TITLE
The typeface used is cold, rather than friendly; and not great for readability

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#821]
PlanningAlerts is meant to be a welcoming, comfortable place to get involved in shaping your local area. The typeface defining the tone of the site’s voice is cold, geometric and not the most readable by a long way. It should be humanist, friendly, open and inviting. I think confuses that character of the site.

Current typeface example:
![screen shot 2015-10-21 at 3 04 22 pm](https://cloud.githubusercontent.com/assets/1239550/10627477/b2314842-7805-11e5-975b-9cc24a9f6afe.png)

I noticed this is particularly a problem when we set the people who use the site's voice in this typeface: in the comments. This is meant to show how easy and approachable commenting is, but the tone of the typeface is machine-like :( :

![screen shot 2015-10-21 at 3 04 44 pm](https://cloud.githubusercontent.com/assets/1239550/10627480/ba9070b2-7805-11e5-938a-e57ac1770971.png)

This project also has a lot of users older than 60s. A more open, typeface, with more distinguishable characters, taller x-heigh, and more open counters (Sorry for the jargon) will make everything easier to read, particularly for people without perfect eyesight.

**Comment by mlandauer** [comment]
I think this would be a great thing to address as part of a bigger visual redesign of the site
