### ISSUE TITLE
The label “Comments” no longer reflects what’s in the comments area

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#824]
Now that we’re putting messages to councillors in the same area as submissions on the application, 'comments' isn't a clear label for the group of content.

A really good label will help people understand what this section means for them, and as the polar bear book says: “Labels should educate users about new concepts and help them quickly identify familiar ones.”

As few ways we can work out what this stuff should be labeled:
- define what the two types of comments are and do card sorting and brainstorm exercise
- look in our surveys and how people describe the concept on social media to see how users think about this.

**Comment by equivalentideas** [comment]
In usability testing one person referred to comments as 'responses' and 'I write my response'.

**Comment by henare** [comment]
>In usability testing one person referred to comments as 'responses' and 'I write my response'.

Sounds like a good place to start :+1:

**Comment by equivalentideas** [comment]
Terms used by people in the commenter’s survey and general users survey:

* response
* comment
* objection

I think “response” is see sounding like a good over arching term.

We need to work out labels for the types of comments and see how these fit together for users.
