### ISSUE TITLE
Yahoo Pipes is dead

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#826]
On our API page we suggest Yahoo Pipes. Thanks to Steve for emailing us to point out that Yahoo Pipes is [long] dead!

We need to remove Yahoo Pipes from the page but it would also be good to replace it with another suggestion. The question is what?

**Comment by Anishka0107** [comment]
I guess [Zapier](https://zapier.com/) is good substitute to Yahoo! Pipes.

**Comment by equivalentideas** [comment]
> I guess Zapier is good substitute to Yahoo! Pipes.

I'm not super familiar with Zapier, why do you think it would be good @Anishka0107 ?

It would be good to look at a few alternatives in the mix :) are there any open source options ❤️

**Comment by Anishka0107** [comment]
@equivalentideas 
https://github.com/superfeedr/superpipes seems like the best alternative for Yahoo! Pipes and is open-source as well. I guess I should use superpipes instead of Zapier in the PR.

**Comment by equivalentideas** [comment]
> I guess I should use superpipes instead of Zapier in the PR.

Before deciding on an option we should consider the pros and cons of a few alternatives. We might way up:

* what's the most common tool that people already use?
* what will be easy for API users to get started with?
* is there a tool that aligns with our aims, e.g. is FOSS and an ethical company etc. .

I suspect nothing will be perfect, but let's way up the options.

**Comment by Anishka0107** [comment]
@equivalentideas 
I have submitted a PR with Superpipes instead of Zapier as I feel it is the best open source available alternative and  was designed to actually replace Yahoo! pipes, when they had suspected the closing of Yahoo pipes.

**Comment by henare** [comment]
Rather than finding a Yahoo! Pipes replacement another approach to fixing this would be to rework this sentence to something useful for what API developers would expect these days.

**Comment by jamezpolley** [comment]
Thanks @Anishka0107
