### ISSUE TITLE
Set up form validation for the comment form with councillors

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#834]
For example, if you've selected to write to a councillor, you also need to select a councillor.

**Comment by henare** [comment]
@equivalentideas described to me that this is actually a bug.

As I understand it, if you select "write to a councillor" and don't select someone then the comment is actually sent to the authority. This is obviously not the desired behaviour from the person's perspective.

Is that right @equivalentideas?

**Comment by equivalentideas** [comment]
Yep that's right :+1:

**Comment by equivalentideas** [comment]
Fixed in e3fb82a
