### ISSUE TITLE
Submitting comment form created 500 error when I submitted a comment with a emoji 👍

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#837]
## Backtrace

```
line 21 of [PROJECT_ROOT]/app/controllers/comments_controller.rb: create
```

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/37075/faults/17523314)

**Comment by equivalentideas** [comment]
Dupe of https://github.com/openaustralia/planningalerts/issues/837
