### ISSUE TITLE
Characters aren't encoded right in application description on comment

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#841]
“Beast &amp; Bread - On-premises...”  should be “Beast & Bread”

see https://www.planningalerts.org.au/applications/577522

vs https://www.planningalerts.org.au/comments/53420/reports/new

**Comment by henare** [comment]
Well spotted, here too https://www.planningalerts.org.au/comments

Will this flow through to the emails?

**Comment by equivalentideas** [comment]
Just pushed fix for this to master https://github.com/openaustralia/planningalerts/commit/b9df4c2b50b374a8d9ea746264c637a5a1bce36f. Fixes it on the site and in emails:

![screen shot 2015-11-05 at 7 50 17 am](https://cloud.githubusercontent.com/assets/1239550/10951530/1ad3c838-8392-11e5-90ba-7b7f916ec171.png)
![screen shot 2015-11-05 at 7 33 10 am](https://cloud.githubusercontent.com/assets/1239550/10951531/1ad86ec4-8392-11e5-9d6e-32b65186fe20.png)

Also added a test to make sure this isn't getting marked as html_safe on it’s way through https://github.com/openaustralia/planningalerts/commit/50313af368420ef5971da7ce35acaf7a9f2b4260

**Comment by henare** [comment]
>Just pushed fix for this to master b9df4c2. Fixes it on the site and in emails:

:+1: 

>Also added a test to make sure this isn't getting marked as html_safe on it’s way through 50313af

That's pretty fancy.

Do you think it's also worth testing for the behaviour you don't want, i.e. injecting HTML and seeing it not come up properly?

**Comment by equivalentideas** [comment]
> Do you think it's also worth testing for the behaviour you don't want, i.e. injecting HTML and seeing it not come up properly?

That would be good. I'm not sure how test whether something is being rendered as HTML in a helper test. Would this go in a view test where we look for the page to `have_content` which checks text? So we could see if `<script>alert('danger danger');</script>` is in the page text or has been rendered to HTML?

**Comment by henare** [comment]
>I'm not sure how test whether something is being rendered as HTML in a helper test.

Test the output of the helper method. `expect(helper.display_description_with_address(@application)).to eql "Whatever string I wanted"`.

**Comment by equivalentideas** [comment]
> Test the output of the helper method.

But isn't it *how* the output is rendered that is important, not the contents of the output String is?

For example, isn’t it ok for the description to be "<script>alert('danger danger');</script>" as long as is not rendered as HTML on the page. Wouldn’t we want to render that as the description, because we don’t want to escape special characters like "&" or ">".

I'm still trying to get my head around all the escaping/html safe stuff :S

**Comment by henare** [comment]
I'm confused. It's pretty straightforward - you need to think how you want the application to behave and then test for that. The reason I suggested:

>Do you think it's also worth testing for the behaviour you don't want, i.e. injecting HTML and seeing it not come up properly?

...is that while testing that something is `html_safe` is all good and well - what does that actually mean in practice? Which is nicely illustrated by your comment:

>I'm still trying to get my head around all the escaping/html safe stuff :S

So that's why you test and that's why you need to test for behaviour so that you *know* your application is doing what you want.

**Comment by equivalentideas** [comment]
>  - what does that actually mean in practice?

Ah thanks @henare I get what you mean now. The bit I'm confused by is this:

> Do you think it's also worth testing for the behaviour you don't want, i.e. injecting HTML and seeing it not come up properly?

As I understand it, the only difference between a String we expect and don't is that it will be `html_safe?` or not. So I'm not sure what you mean by 'seeing it not come up properly'?

**Comment by henare** [comment]
>As I understand it, the only difference between a String we expect and don't is that it will be html_safe? or not. So I'm not sure what you mean by 'seeing it not come up properly'?

Cool, then you've answered my question:

>Do you think it's also worth testing for the behaviour you don't want

...

>the only difference between a String we expect and don't is that it will be html_safe?

...so we're already doing that, yay! Phew :sweat: We got there in the end.

**Comment by equivalentideas** [comment]
> Phew :sweat: We got there in the end.

Victory :postal_horn: Thanks for your help!

**Comment by henare** [comment]
Thanks for working it out :mega:
