### ISSUE TITLE
Research WriteIt for use with write to councillors

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#842]
We really don't want to reinvent the wheel when it comes to handling email conversations being done via the web (think Alaveteli) so [WriteIt](http://www.github.com/ciudadanointeligente/write-it) is the obvious choice.

Ideally we'd post a message to the WriteIt API when a person confirms their message to a councillor. When the councillor replies, WriteIt would feed that back into PlanningAlerts and so on.

**Comment by henare** [comment]
@equivalentideas templates are definitely a thing and they look pretty flash:

![templates](https://cloud.githubusercontent.com/assets/48945/10960686/fcd4071a-83d9-11e5-8a06-cd9eac33ae17.png)

**Comment by equivalentideas** [comment]
> @equivalentideas templates are definitely a thing and they look pretty flash:

Thanks great news :+1:

**Comment by henare** [comment]
OK, I've spent a couple of hours trying to get a sense of where the project's at.

![writeitpulse](https://cloud.githubusercontent.com/assets/48945/10961085/de9bc6ca-83de-11e5-89e9-f998bbe97c3b.png)

While it's not under heavy development right now, it's also in a state of transition because PopIt is no longer being developed. The only recent changes have been to start implementing the transition from PopIt to using EveryPolitician data. There still seems like there's lots to do to complete this transition which is understandable because they'll want to support their existing users that are still using PopIt.

Documentation is unsurprisingly sparse but this is never a deal-breaker. Oddly, things like the page explaining the API are not exposed in the UI, I just stumbled across the route, e.g. http://australia-representatives-henare-test.writeinpublic.com/en/manage/settings/api/

I've setup a [test instance](http://australia-representatives-henare-test.writeinpublic.com/en/) on WriteInPublic and I'll try and get something working with that tomorrow.

**Comment by henare** [comment]
Oh, I just got my test message and it's using Cuttlefish :smile:

**Comment by henare** [comment]
Moving this out of the MVP for the moment.

**Comment by henare** [comment]
I've [sent a message](https://groups.google.com/forum/#!topic/poplus/JFwRZ4ENj1k) to the Poplus list with some outstanding questions I have about WriteIt.

**Comment by henare** [comment]
I've had some useful responses to that message to the Poplus list. I think the next step is for us to set up our own instance of WriteIt to get a better understanding of how things work.

**Comment by henare** [comment]
Based on the previous comment we can close this and split it out into specific issues.
