### ISSUE TITLE
Alert commenter when a councillor replies to their message

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#846]
Extracted from #812.

**Comment by equivalentideas** [comment]
What does someone need to know when a councillor writes back to them?

For starters:

* Which application and message they’re talking about
* Which councillor replied to their message

**Comment by equivalentideas** [comment]
Here’s a draft of how this could go:

Hi Luke Bacon

Local councillor Melissa Brooks replied to you message about the development application “To demolish part of the...” at 28 Terminus Street Petersham NSW 2049:

> Hi Luke, thanks for your message.
> I like your ideas, they sounds like common sense to me. We’ll be discussing this planning application at an upcoming meeting and I'll be sure to raise your ideas with the council. The meeting will be at Marrickville Town Hall on Friday 5th September, you can come down and join the discussion if you like.
> 
> Best wishes
> Clr Melissa Brooks

You can view and share this reply on PlanningAlerts:
https://www.planningalerts.org.au/applications/587781

Your original message was:

> Hi Melissa,
> After following the comments on this application I had the idea that it could be good to change the planning rules so that cafes and restaurants that have main street access can all have seating up to a 1.5 meters without seeking approval. That would get more people out enjoying the street together and save everyone a lot of time with these applications. What do you think?

Best wishes

PlanningAlerts

**Comment by equivalentideas** [comment]
The beginnings of implementing this are in https://github.com/openaustralia/planningalerts/compare/5e1a45f67340...489e0b08fae5 

When a reply is added an email is sent to the commenter. It’s just missing most of the body text.

**Comment by equivalentideas** [comment]
Simplified this a bit by breaking down long intro sentence and replaces original comment text with a link:

Hi Luke Bacon,

Local councillor Mark Gardiner replied to [your message](#) about the planning application “To demolish part of the premises and carry out ground and first floor alterations and additions to a dwelling house” at 28 Terminus Street Petersham NSW 2049.

Local councillor Mark Gardiner wrote:

> Thanks for you message. I completely agree. You might want to checkout this cool website https://www.planningalerts.org.au/ . All the best, Mark

**[View and share the reply on PlanningAlerts](#)**

Best wishes,

PlanningAlerts

**Comment by equivalentideas** [comment]
First pass at this is on the working branch https://github.com/openaustralia/planningalerts/compare/489e0b08fae5...abe39ea8315f
