### ISSUE TITLE
Replies admin interface comment field is unwieldy

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#851]
It's currently a select box of every comment in the database. Not only is this not helpful, it's massive in production.

**Comment by equivalentideas** [comment]
I think this would be better as a text input with the comment’s `comment_id`. That’s easy to get and straightforward to enter.

**Comment by henare** [comment]
>That’s easy to get and straightforward to enter.

And you shouldn't need it with my fancy "add reply" link :wink:
