### ISSUE TITLE
Mixed content warning on pages with councillor images

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#854]

**Comment by henare** [comment]
@equivalentideas reminded me we said we could just include them as assets in the project for the MVP.

**Comment by henare** [comment]
>include them as assets in the project for the MVP

Hmm. It feels weird including them in the project when the councillor details aren't hardcoded - you need to manually enter them in the database.

How about we upload the images to S3 and then just put that URL as the `image_url` that's served over HTTPS?

**Comment by equivalentideas** [comment]
Sounds good. Did you want to make that an upload through the admin panel or manual upload and insert the url?

**Comment by henare** [comment]
We only need manual upload.

This is for the MVP, we shouldn't be doing it longer term because this data will come out of some automated thingo and not from people manually creating councillors in the admin interface.
