### ISSUE TITLE
Application claims to know a comment has been delivered, when it doesn't

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#855]
I like the sense of immediacy but since it's not really true, I don't think we should claim it's the case.

Changing it to "Delivered to local councillor Mark Gardiner. They are yet to respond." is an OK compromise.

![selection_001](https://cloud.githubusercontent.com/assets/48945/11055320/5a0182de-87ca-11e5-8b19-050afc97b0d8.png)

**Comment by equivalentideas** [comment]
> Changing it to "Delivered to local councillor Mark Gardiner. They are yet to respond." is an OK compromise

Do you mean just remove the 'less than a minute ago'? If so :+1: .
