### ISSUE TITLE
Allow comments to councillors feature to be disabled

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#856]
As part of the MVP it would be handy to be able to disable the feature if we need to for some reason.

The obvious way to implement this is to replace the current param-enabled feature (which we need to do anyway) with a config feature flag.

At the same time we should also remove the prototype code.

**Comment by equivalentideas** [comment]
Closed by f7d91f0

and the prototype code removed in 2164f4c8884a608ba1d424cd8e5fd75e28904272
