### ISSUE TITLE
State is incorrectly uncapitalised in some scenarios

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#859]
e.g. in this recently added scraper from @LoveMyData, "NSW" is incorrectly changed to "Nsw" https://www.planningalerts.org.au/applications/597377

**Comment by LoveMyData** [comment]
No idea how that happen, it is hard coded to append 'NSW, Australia' at the end.

**Comment by henare** [comment]
Don't worry Eric, it's not your scraper, it's the app.

**Comment by Tanuja-Sawant** [comment]
@equivalentideas may I take up this issue?

**Comment by Tanuja-Sawant** [comment]
Looks 'NSW' to me. Is this issue already resolved? @equivalentideas @henare

**Comment by henare** [comment]
All the recent applications look fine https://www.planningalerts.org.au/authorities/manly/applications

Thanks for spotting this @Tanuja-Sawant :sunglasses: I'm closing this as cannot reproduce.
