### ISSUE TITLE
Street view shows wrong location

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#860]
On a number of applications I've seen recently, the street view shows the lane behind the address, rather than the much more useful frontal view.

In user testing I saw this difference cause a lot of confusion. In one case it lead the person to think the application was for outdoor seating in a back ally, rather than on the main road. In 2 separate sessions, people heavily relied on the street view image to help them understand how an application would change a building. When the street view location was off, it had a very negative impact.

Here are a few examples of where the address is different from the street shown in the street view:
- https://www.planningalerts.org.au/applications/595753
- https://www.planningalerts.org.au/applications/582479 (the map pin and the streetview are off here)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_39iit)

**Comment by equivalentideas** [comment]
Another one, https://www.planningalerts.org.au/applications/597998,  someone points out in a comment:

> The photo posted for 57 Marion Street, is actually a photo of shop 59a Marion Street

**Comment by equivalentideas** [comment]
Here's one that is badly off https://www.planningalerts.org.au/applications/616326 . PlanningAlerts locates the address in Ocean Grove instead of Geelong. The address scraped “4 Richmond Court, Geelong”. When you search this address in google, you do get the correct address https://encrypted.google.com/maps/place/4+Richmond+Ct,+Geelong+VIC+3220,+Australia/@-38.1593535,144.3568343,13.4z/data=!4m2!3m1!1s0x6ad41416ebb908d9:0x9f7f054af8223114?hl=en

It seems relevant to this issue that google maps returns the correct address since we use the google maps api to geolocate addresses.

**Comment by adampryor** [comment]
Possible solution found...

- **See live demo here: https://jsfiddle.net/39owkxto/4/**
- Inspired by this post on SO: http://stackoverflow.com/questions/31176327/request-main-road-curbside-streetview-panoramas-instead-of-back-alleys-from-ap
- This introduces a dependency on Google Maps Directions Service (google.maps.DirectionsService). It would be wise to fallback to the existing method if Directions Service is not available for a particular location, for some reason.

Do you think this look like a good solution? Shall I go ahead and implement it? If so I'll need to brush up on pull/review/deployment processes.

**Comment by equivalentideas** [comment]
That's pretty awesome @adampryor thanks for researching this!

Are there any implications on performance we need to think about with this?

Do you know if this could this be used for the static images shown in the PlanningAlerts emails as well?

**Comment by adampryor** [comment]
Re Performance: I don't think there are significant performance implications. It requires some additional back-and-forth on the client side, but it doesn't seem to greatly harm the user experience, unless their connection is truly terrible.

I am concerned about handling edge cases gracefully, so I would want to create a large list of test addresses and ensure they are handled optimally, particularly ensuring that we don't break some cases which currently work.

@equivalentideas I am happy to prepare an arbitrary list of test addresses, but do you have a standard list of addresses that you typically use in these cases?

Re static images: The only solution that I can think of (that doesn't violate Google Maps T&Cs) would add an absurd level of additional complexity into the application or would require manual updates through a client-side admin tool, by loading the full interactive version in a browser, then reading off the location & heading values and saving them back into the database.

@equivalentideas Is this feature important enough to warrant taking on this huge overhead going forward? Perhaps a low-tech option could be to add a link to accompany the image which says: "<View online> for a better perspective"

**Comment by equivalentideas** [comment]
> Re static images: The only solution that I can think of (that doesn't violate Google Maps T&Cs) would add an absurd level of additional complexity into the application or would require manual updates through a client-side admin tool, by loading the full interactive version in a browser, then reading off the location & heading values and saving them back into the database.

Because the problem isn't too wide spread, I don't think it's worth that cost at this stage to try and improve the static images. It is a shame though because the static images are what most people see—we think that most usage of PlanningAlerts is looking at the emails.

If we can just improve the interactive maps on the website at this stage, that's still a good improvement to the many people arriving from the emails, or from search.

> @equivalentideas I am happy to prepare an arbitrary list of test addresses, but do you have a standard list of addresses that you typically use in these cases?

We don't, but that's a great idea to test this out in this way :+1:

I'm a bit concerned that people will see one image in their email, then click on the application and get a different image on the web. @adampryor In testing addresses would it be possible to do the static vs interactive new/current? That way we can better understand how that transition will work for people.

>  It requires some additional back-and-forth on the client side, but it doesn't seem to greatly harm the user experience

Thanks @adampryor :star: Is there a quick way you could roughly quantify the performance difference before the implementation? If it's mild I think it's worth it for people since it's a worse experience to get the wrong image than it be a few ms slower.

**Comment by adampryor** [comment]
@equivalentideas Due to the round-trip calls, it could typically add between 500ms and 1000ms before the map is viewable. This is significant but arguably acceptable. It should be noted that only this control will require the additional load time, it will not delay loading of the rest of the page or prevent interactions with other elements of the page.

During testing (and possibly even after deployment) it would be worth adding a simple toggle for developers/testers to switch between the old and new versions. (e.g. Overriding default version when a particular hash is included in the URL).

**Comment by equivalentideas** [comment]
Thanks @adampryor .

> This is significant but arguably acceptable.

That's spot on I recon. That's quite a long time, but if it's the difference between a helpful image and a misleading image for a significant number of applications, then it's worth it.

> During testing (and possibly even after deployment) it would be worth adding a simple toggle for developers/testers to switch between the old and new versions. (e.g. Overriding default version when a particular hash is included in the URL).

Would you be up for making a Pull Request to implement and test this?

**Comment by adampryor** [comment]
Apologies for radio silence. My hectic work schedule has prevented me from getting back to this. I will need someone else to pick this up from here.
