### ISSUE TITLE
Encourage councillors to sign up for PlanningAlerts emails, so they see peoples’ comments on applicaions

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#864]
We want to bring Councillors closer to people around the issue of development. One way to achieve this is to make sure Councillors are hearing the voices of people when they comment on development applications. This could:
- provide Councillors the opportunity to collect and draw attention to what residents are saying to the Council, and
- highlight to Councillors which applications are contentious or might need more attention

Currently people are making comments on applications. If Councillors are signed up to emails alerts for an area, they'll get notified of peoples comments. When we email Councillors about comments people are addressing to them, we could include a link to sign up for email alerts for that area. Then they'll receive these comments (plus development applications in the area).

**Comment by mlandauer** [comment]
I strongly suspect most councilors are aware of comments being sent in because there's a whole bureaucracy designed to receive those requests for the particular council that the Councillor is in
