### ISSUE TITLE
Highlight applications that have comments in search results

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#866]
We currently notify people about comments in their local area through email alerts. This is because:
- these are likely to be interesting applications;
- to show people what other’s are saying about planning; and,
- to demonstrate how easy it is to get involved in local democracy.

For these same reasons, it would also be helpful to highlight divisions that have comments when someone is viewing search results.

I think this should be done in a way that does not diminish the importance or visibility of applications without comments, because that is only one factor that makes an application of interest.

**Comment by equivalentideas** [comment]
The first step to this would be working out how to show whether (and maybe how many) comments a DA has had in search results.

It would be useful to look at some prior art, like lists of news articles or other kinds of posts that show comments or other related design patterns, to see if we can find anything useful for our case.

**Comment by hisayohorie** [comment]
@equivalentideas I did a bit of research, github actually do the showing of the icon only if there are comments. and a couple of other examples I find is to have a comment icon on each application in index page, and if there are comments, show the number of the comment. Here is the screenshot of git hub, twitter and medium. 

github comment
<img width="1090" alt="screen shot 2017-04-17 at 3 06 51 pm" src="https://cloud.githubusercontent.com/assets/12241881/25100907/05a65cac-2380-11e7-8c26-77622798aa3b.png">

twitter comment
<img width="581" alt="screen shot 2017-04-17 at 2 56 11 pm" src="https://cloud.githubusercontent.com/assets/12241881/25100930/1bc01c6c-2380-11e7-8b4e-0fff199ffda3.png">

medium comment
<img width="658" alt="screen shot 2017-04-17 at 2 57 50 pm" src="https://cloud.githubusercontent.com/assets/12241881/25100937/292b4fca-2380-11e7-8f94-e3ad2bd11643.png">

I think maybe we can do something similar? what do you think?

**Comment by equivalentideas** [comment]
Real nice work @hisayohorie 🌳 I think this is a great avenue to explore. Would you like to do a mock-up of how the divisions could appear with something like this?

I think example with the full word is clearest. That's how we do it on application pages as well, and if we introduce icons we should do it everywhere at once. I really like what you've highlighted about the github example where the lack or presence of the bit of information is part of what draws attention to it.

Note on wording: We currently use the term "comments" for this everywhere. We should be consistent here :)

**Comment by mlandauer** [comment]
Related to #1290

**Comment by mlandauer** [comment]
Fixed by https://github.com/openaustralia/planningalerts/pull/1303
