### ISSUE TITLE
Track total of number of active users over time

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#869]
To help us understand how our work on the site is impacting use, on the /performance page, we could show a chart of the number active users over time. This could include the percentage of people who have commented, so we can see how changes in the total number of commenters relate to changes in overall number of users.
- How many people are signed up for PlanningAlerts?
- How many of those people have commented?

Anecdotally we think that a lot of people only use PlanningAlerts from their email and rarely if ever visit the site. What are the important metrics to track around these people’s behaviour?

**Comment by mlandauer** [comment]
Removed the performance page. So, closing this.
