### ISSUE TITLE
questions to ask councillors about their role

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#870]
To find out how it's going help people make an impact, ask councillors about how they can help people have in impact 
* How long have you been a councillor?
* How often are you contacted by people about developments/DAs?
* How many times have you brought issues to council about a DA?
* Was this in response to people in their ward or their council asking for their representation?
* What are you allowed to do to help present your electorate's views about a development?
* What are you not allowed to do?
* What rules do you know about around talking to people in your electorate/ward or council about developments? How do you know about these rules?
* Can you tell me about when somebody contact you about a development and their involvement resulted in a good outcome for that person/people?
* Is there a story you can share about someone who contacted you which resulted in a negative outcome for that person/group of people?
* What do they see as an effective way for people in an area to be make a difference in council?

One thing we want to try and learn with this is to 'find out how people who effectively lobby their councillors connect with them' . (from #865)

**Comment by equivalentideas** [comment]
I've contacted one Marrickville Councillor to arrange a time to go through this with them.

**Comment by kat** [comment]
Another question - otherwise some of the other responses are out of context. How long have you been/were you a Councillor?

**Comment by equivalentideas** [comment]
I'm emailing a bunch of councillors from different areas to see if I can line up some calls.

**Comment by equivalentideas** [comment]
Just spoke to our first councillor (previous councillor actually), and documented the answers to our questions here https://docs.google.com/spreadsheets/d/1aXfmUFRDeb7tvq-j_LrNuxDkCUX5xzQinja-ZiDL1EI/edit#gid=0

**Comment by equivalentideas** [comment]
This fed into the 'ask the experts' bit of our recent mini Design Sprint. I'm closing this. Check out notes from the few conversations with councillors in the spreadsheet https://docs.google.com/spreadsheets/d/1aXfmUFRDeb7tvq-j_LrNuxDkCUX5xzQinja-ZiDL1EI/edit#gid=0
