### ISSUE TITLE
allow signup for statewide major projects

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#871]
Large projects affect people outside a 2km radius and also don't always have a clear boundary or street address - eg westconnex, barangaroo. Make it easy to find out about them by having a separate signup option for major projects.

**Comment by equivalentideas** [comment]
Received this email from a user talking about a near by major development that they didn't hear about:

> I presume it didn't appear on Planning Alerts because the application was not via CoM [City of Melbourne]? Is this right? And if so, how can I remain abreast of these sorts of truly enormous developments? Most of the Alerts I receive are for quite minor building modifications - not the sort of stuff that's much likely to affect me. No disrespect or lack of gratitude for your great work is intended!

They seem to be saying that they feel it's the major projects that will impact them more than small local developments... seems relevant to this issue.

**Comment by mlandauer** [comment]
I think the most general solution to this problem is to allow applications to have an area, not just a point. I think there's an issue specifically to add that. If so I think we should close this in favor of that issue.

**Comment by mlandauer** [comment]
Closing this issue in favour of the more general solution of adding boundary data to each application #304
