### ISSUE TITLE
How can citizens become more involving in setting the planning agenda rather than just responding to applications?

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#872]
This is a question from a conversation between @kat and I.

How could people organise to describe the types of development they wanted in their area, rather than individually responding to applications one by one? Could people more effectively impact development if they were preemptively talking to council about the type of development they want?

**Comment by mlandauer** [comment]
I think this is an important question but probably out of scope for planningalerts in its current form. So, closing this.
