### ISSUE TITLE
Repetition of alert area in email alert is noisy

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#873]
In each section of the alert email the area of the emails’s coverage is repeated: “within 2 km of 102 Gowrie Street, Newtown NSW 2042”. This text makes up about half the sentence.
![screen shot 2015-12-11 at 10 01 39 am](https://cloud.githubusercontent.com/assets/1239550/11731349/bfbca36a-9fee-11e5-978d-d6d15d79024b.png)

Since the alert only contains activity from this area, the person reading the email doesn't need to reread this in each section.

Could we reduce this repetition somehow by including the alert coverage area in the header or something? How important is this information to users anyway?

**Comment by mlandauer** [comment]
This feels like a good thing to look at with an overhaul of the entire design of the email
