### ISSUE TITLE
Track comments performance for individual councils

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#879]
Since we've turned on councillor comments for individual authorities, we need to see how that impacts the rate of comments overall for those authorities. Do comments drop off when we add the councillor option or is the overall rate of commenting unaffected?

One way to see this would be to add the number of comments over time to the chart on the [authority page](https://www.planningalerts.org.au/authorities/marrickville/), or we could add a new chart to the [authority’s comments page](https://www.planningalerts.org.au/authorities/marrickville/comments).

**Comment by henare** [comment]
:+1: I think a chart on the authority page is the way to go.

**Comment by equivalentideas** [comment]
> :+1: I think a chart on the authority page is the way to go.

That sounds like the simplest approach. I think the first dumb thing to do is add another chart, like the current one, underneath it like:

![screen shot 2016-01-05 at 10 12 47 am](https://cloud.githubusercontent.com/assets/1239550/12103263/e78eced6-b394-11e5-8259-5559ec638dbe.png)

Subsequently these charts could be refined or merged using a double y-axis approach.

**Comment by equivalentideas** [comment]
Deployed this and also made the charts display the values more accurately. The lot level of detail was making the comments chart really hard to get useful info from because you couldn't see weeks where there were no comments (see 8a2cb91 ).

![screen shot 2016-01-06 at 1 57 08 pm](https://cloud.githubusercontent.com/assets/1239550/12133865/989aaf68-b47d-11e5-9288-d156b0651657.png)

Commits:

42f8e2d Reduce the number of month labels as the ticks replace them
7b51a8b Make the y axis ticks a little more prominent
9ee4e53 Make the y axis grid a little chunkier
1633c01 Make the baseline of the x axis (0) bolder, it visually grounds the chart
8ae8a56 Make chart axis text more readable, bigger and darker
160e99a Add more spacing between chart and x axis text, it's cramped
3a0fc32 Make chart ticks more readable
8a2cb91 Make charts represent data in more detail
220d44d Use rails script tag helper
dd85b11 Group the inline javascript together
e86cd13 Add the chart title as part of the chart script
7225ef9 Add a chart showing the count of comments each week to the authority page
cb466b3 Provide json feed of comment count per week for authority
6252470 Add method for getting count of comments per week for authority
be325ab Add new route and controller action for returning comments per week json
