### ISSUE TITLE
When you click the link confirming your API account you should be signed in and on the API page

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#883]
Currently you're sent to the sign in page:

![selection_001](https://cloud.githubusercontent.com/assets/48945/12084014/4a3e5446-b301-11e5-8791-6f780fffcb26.png)

And when you sign in you're just sent to the home page:

![selection_002](https://cloud.githubusercontent.com/assets/48945/12084021/6a74e2a2-b301-11e5-9790-ec81d8bd4acc.png)

**Comment by mlandauer** [comment]
The new plan is to use user login more generally than just for API users. So we don't want to tie the user registration process together with the API. So closing
