### ISSUE TITLE
Chart y axis is weird occasionally

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#887]
On the 'Comments over time' chart of Scenic Rim Regional Council, the number labels on the y axis are wrong. There should be 3 ticks with "0", "1" and "2", but instead there are 5 ticks with "0", "00m", "1", "1.5" and "2".

![screen shot 2016-01-12 at 4 45 39 pm](https://cloud.githubusercontent.com/assets/1239550/12255823/006440f0-b94c-11e5-9bd8-3dd21cd5e01a.png)

**Comment by henare** [comment]
[Confirmed fixed](https://www.planningalerts.org.au/authorities/scenic_rim) in #1033.
