### ISSUE TITLE
Authority page charts are confusing for current period

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#888]
The x axis period for the comments and applications scraped charts on the authority page are 'per week' starting on Sundays. If it's Tuesday 12th January, the latest period is presented as 10-17 Jan, but it's really 10-12. This is confusing because the chart is lying to you.

![screen shot 2016-01-12 at 4 50 25 pm](https://cloud.githubusercontent.com/assets/1239550/12255935/35fd3202-b94d-11e5-8729-523201b25435.png)

Two possible solutions:
1. truncate the period to be 10-12th or 10th Jan - Today.
2. Don't show the current week. The problem with that is that you might want to check the impact of a change to the app mid week. But you'll be making a pretty limited assessment because there isn't a whole week of data to compare yet.

Option 2 feels better to me.

**Comment by equivalentideas** [comment]
Options two is what the GDS do, see https://www.gov.uk/performance/carers-allowance

**Comment by henare** [comment]
>Option 2 feels better to me.

:+1:

**Comment by equivalentideas** [comment]
Note that this chart was added to Alaveteli core, see https://chiedi.dirittodisapere.it/statistics#requests

So when we fix this we should fix it there too like good citizens.

Should the chart script be extracted to it's own project/gist?

**Comment by akve17** [comment]
hi @equivalentideas , I have some questions regarding this issue.

**Comment by akve17** [comment]
Is this is what you are looking for?? (please refer to the date section of the graph in the picture)
![screenshot from 2017-04-18 13-54-30](https://cloud.githubusercontent.com/assets/26615577/25121472/6cb1ae6e-243f-11e7-9b4b-a7b36c0f0759.png)

**Comment by akve17** [comment]
The graph is empty due to limited data available for Marrickville Council, but the date section only shows till current date , unlike the old version where the whole week is shown. In case it is merged with the original code , whenever the mouse is hovered on the spike of the current week it will give the information shown in the picture shown for the current week , which will regularly get updated.

**Comment by henare** [comment]
>Is this is what you are looking for??

Not quite. Above we decided option 2 was best, i.e. don't show the current week at all.

**Comment by akve17** [comment]
hi henare, can you explain me what the proposed solution is , so that i can make the required changes.
thanks:)

**Comment by akve17** [comment]
For the time being i will remove the text "Current Week" . It seems misleading because the date interval shown is from the beginning of the week to the current date .

**Comment by henare** [comment]
@akve17 as above :point_up: the proposed solution is to not show the latest week because the data is incomplete.

**Comment by akve17** [comment]
ohh ok ,so as i understand it , we don't have to show the current week at all. The week should be shown only after it has passed.
Am i correct??

**Comment by henare** [comment]
Yep, that's it :+1:

**Comment by akve17** [comment]
Can i get more real time data for Marrickville Council so that i can test my changes with it. I received only 6 applications  and zero comments for this week and no data for previous weeks.

**Comment by henare** [comment]
You'll need to create more test data yourself @akve17. You could either create your own dummy applications or make copies of the ones you've already got. The easiest way to do this will be to use the Rails console to create more applications in the database.

**Comment by mlandauer** [comment]
It's a pretty small issue but still seems worthwhile to address
