### ISSUE TITLE
Confusing error message on address search

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#889]
When you [submit the address "123 Broadway St, Ultimo NSW"](https://www.planningalerts.org.au/?q=135+Broadway+St+Ultimo+Nsw) into the application search form, you get the error:

> Please enter a full street address like ‘36 Sowerby St, Goulburn, NSW’

The real error is that it can't find that address because it doesn't exist (should be 123 Broadway, Ultimo...). This is really confusing because you have put in a full street address. In our analytics we can see that when this happens, people just keep hitting submit hoping that it will work :( .

The error messages on this page get seen by lots of people, so it's important they're as helpful as possible. Our tracking says that last week, we picked up 534 clicks to submit address searches, and an error messages was displayed 435 times.

![screen shot 2016-01-13 at 7 17 32 am](https://cloud.githubusercontent.com/assets/1239550/12275724/c6f6ee56-b9c5-11e5-92fb-01eed27993a0.png)

**Comment by henare** [comment]
Are you really saying 80% of address searches failed? That sounds like a really big problem and one that if we fix would have a massive benefit!

**Comment by equivalentideas** [comment]
> Are you really saying 80% of address searches failed? That sounds like a really big problem and one that if we fix would have a massive benefit!

We can actually see the queries people are making in GA. It's mostly searches for suburbs. I'd say we could probably give these people a more helpful result than we currently do. A lot of people seem to get stuck in a cycle of submitting searches and getting errors. Only around 10% of people who see an error end up clicking 'create alert'.

**Comment by henare** [comment]
I'm confused. Can you please answer yes or no to this:

>Are you really saying 80% of address searches failed?

If no, can you please elaborate on what you mean?

**Comment by equivalentideas** [comment]
> Are you really saying 80% of address searches failed?

Yes I think that's right.

From our Google Analytics event tracking:

* the search form submit button was clicked 534 times
* an error message on this form was shown 435 times

**Comment by henare** [comment]
Wow. How does that reconcile with the number of successful sign ups?

>you signed up for 295 new email alerts

**Comment by equivalentideas** [comment]
Only 5% of sessions included a visit to "/" (the application search page), so most signups come via an application page. Does that answer your question?

**Comment by henare** [comment]
Yes, thank you.

So fixing this seems like it could potentially lead to hundreds more sign ups a week - amazing find!

**Comment by equivalentideas** [comment]
> So fixing this seems like it could potentially lead to hundreds more sign ups a week - amazing find!

Maybe yes, we'd have to look at it more deeply.

In late December I added event tracking to all the forms. So we're now getting a lot more feedback on how often they error, which we can hopefully use to improve them for people.

**Comment by CloCkWeRX** [comment]
So I can only reproduce this with

https://www.planningalerts.org.au/?q=Ultimo+NSW

... which is annoying behaviour, because the autocomplete *suggested* that as a result then yelled at me for using it.


Supposedly the [API](https://developers.google.com/maps/documentation/javascript/places-autocomplete#add_autocomplete) docs let you specify an option for full addresses only:
```
address instructs the Places service to return only geocoding results with a precise address.
```

Alternatively; is suburb level accuracy that bad of a thing?

```
      elsif accuracy < 5
        "Please enter a full street address like ‘36 Sowerby St, Goulburn, NSW’"
      end
```

http://code.google.com/apis/maps/documentation/reference.html#GGeoAddressAccuracy

Constant | Description
0 Unknown location.
1 Country level accuracy.
2 Region (state, province, prefecture, etc.) level accuracy.
3 Sub-region (county, municipality, etc.) level accuracy.
4 Town (city, village) level accuracy.
5 Post code (zip code) level accuracy.
6 Street level accuracy.
7 Intersection level accuracy.
8 Address level accuracy.
9 Premise (building name, property name, shopping center, etc.) level accuracy.

Why not tolerate Town level accuracy and maybe hint to the user that we're only showing a snippet: searching for a full address will give better results.

**Comment by equivalentideas** [comment]
> Alternatively; is suburb level accuracy that bad of a thing? ... Why not tolerate Town level accuracy and maybe hint to the user that we're only showing a snippet: searching for a full address will give better results.

I think you're getting at the better solution here. People find it natural to search for a suburb, why not let them do this, rather than pushing back, and then guide them towards an address to subscribe with?

I also wonder, do people do a search, look at applications, then sign up to an alert via an application page?

**Comment by CloCkWeRX** [comment]
> do people do a search, look at applications, then sign up to an alert via an application page?

I think that's a reasonable assumption. If I find a new website, I might not be willing to hand out my home address if I don't understand it's value.

Alternatively, if I want to see development applications in somewhere *near* where I live; I might put in a suburb without a full address - I can't name a valid address/street/suburb combination in Tasmania; but I might want to see if coverage is national sorta thing.

**Comment by henare** [comment]
>I think that's a reasonable assumption. If I find a new website, I might not be willing to hand out my home address if I don't understand it's value.

:+1:

**Comment by gszathmari** [comment]
I am also having this bug. I am trying to select 31 King St, Sydney but I am receiving an error instead


![screen shot 2016-04-23 at 12 09 29]
![screen shot 2016-04-23 at 12 09 32](https://cloud.githubusercontent.com/assets/4806014/14758706/6258deba-094c-11e6-9229-3038cd215beb.png)
![screen shot 2016-04-23 at 12 09 29](https://cloud.githubusercontent.com/assets/4806014/14758707/625bf44c-094c-11e6-9574-626bf1f3b78d.png)

(https://cloud.githubusercontent.com/assets/4806014/14758705/5710766c-094c-11e6-8385-416e7cec7d09.png)

**Comment by henare** [comment]
Assigning this to @equivalentideas so he can check it as he reviews #948.

**Comment by equivalentideas** [comment]
Since making change [691b2a68 Only suggest street addresses in the address autocomplete](https://github.com/openaustralia/planningalerts/commit/691b2a683f55674f023d3781fb7097c311240e46) we've seen a drop off in these errors on the search form:

![screen shot 2016-06-23 at 2 28 11 pm](https://cloud.githubusercontent.com/assets/1239550/16291941/c9314aea-394f-11e6-932a-665dabdf69b5.png)

This is the overall conversion for signing up for alerts:
![screen shot 2016-06-23 at 2 38 26 pm](https://cloud.githubusercontent.com/assets/1239550/16291991/46e754f2-3950-11e6-884c-778d2cc80853.png)

After we made this change we see conversion move up from sitting around 2.0% to 2.5% (pretty early to tell and also probably slightly impacted by #979) :

![screen shot 2016-06-23 at 2 38 26 pm](https://cloud.githubusercontent.com/assets/1239550/16292029/ae2500ec-3950-11e6-841b-6cdb25d0445b.png)

> We can actually see the queries people are making in GA. It's mostly searches for suburbs.

After the change we now see hardly any errors about making a suburb search, in comparison to before.

That's the main focus of this issue. The [other problem mentioned above](https://github.com/openaustralia/planningalerts/issues/889#issuecomment-213651104) by @gszathmari is that we can't recognise what seems to be a good address. This seems like more of a Google address data issue, since we haven't changed anything on that but it seems to be fixed for the case mentioned here. I think that should be raised in a new issue if it pops up again.

Calling this closed by https://github.com/openaustralia/planningalerts/commit/691b2a683f55674f023d3781fb7097c311240e46
