### ISSUE TITLE
Spacing in replies is not retained

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#890]
This: https://www.planningalerts.org.au/applications/572115?#reply1

Should look like this: 

>Thank you Mary for your email.  You have highlighted many of my concerns with the development of so many unit developments in our city.  we are certainly losing many of our old trees.  In my view Greed is rampant across our city.
>
>sue
>
>Cr Sue Englart
>PORTFOLIO – ENVIRONMENTAL HEALTH,
>PARKS & RECREATION
> 
>City Hall, 541 Ruthven Street, Toowoomba
>PO Box 3021, Toowoomba Village Fair QLD 4350
>P 07 4688 6783   F 07 4631 9158  M 0499 774 271
>E sue.englart@toowoombaRC.qld.gov.au
>W www.toowoombaRC.qld.gov.au

Instead it's all squished up.

**Comment by equivalentideas** [comment]
Nice one @henare That's pretty nasty. I wonder if this also happens in the email version? If so we should fix that at the same time.

**Comment by equivalentideas** [comment]
Fixed in https://www.planningalerts.org.au/applications/572115#reply1
