### ISSUE TITLE
Import councillor Popolo data

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#897]
We need to automatically import councillor data (#885) and we're creating that data in Popolo (#896) so we need a way to import it (a daily rake task?).

**Comment by equivalentideas** [comment]
I'm starting this off by looking at the Polopo people importer that @henare made for the rada4you.org :

* [people.rb](https://github.com/OPORA/publicwhip/blob/develop/lib/data_loader/ukraine/people.rb)
* [popolo/rb](https://github.com/OPORA/publicwhip/blob/develop/lib/data_loader/ukraine/popolo.rb)

**Comment by henare** [comment]
As Luke suggests in the comment above we already access EveryPolitician Popolo data in publicwhip. Over the weekend I was thinking it might be a good idea to create a Gem that loads EveryPolitician biased Popolo data, along the lines of:

```ruby
popolo = Popolo.load_file("everypolician_popolo.json")
popolo.people
# returns array of People from the file
popolo.people.first
# returns the first Person
popolo.people.memberships
# an array of their Memberships
popolo.people.memberships.first.organisation
# the Organisation record
```

Bit it could also do [funky stuff](https://github.com/OPORA/publicwhip/blob/develop/lib/data_loader/ukraine/people.rb#L59) like:

```ruby
popolo.people.memberships.find(scheme: "rada").identifier
```

So it would allow the access and querying of an opinionated version of Popolo data in native Ruby. The advantages are that you wouldn't have to work out how to access and query Popolo data in Ruby every time you wanted to work with it - it would basically Just Work.

Since we already use Popolo data in Ruby in a specific way for publicwhip we could build quite a focussed gem to replace that and one that nicely worked for us in PlanningAlerts. Then hopefully it would continue to be expanded by the open source community.

**Comment by equivalentideas** [comment]
> it might be a good idea to create a Gem that loads EveryPolitician biased Popolo data

Wonderfully this gem already exists :stars: https://github.com/everypolitician/everypolitician-popolo

```
require 'everypolitician/popolo'
require 'open-uri'

url = 'https://raw.githubusercontent.com/openaustralia/australian_local_councillors_popolo/master/nsw_local_councillor_popolo.json'

popolo = Everypolitician::Popolo.parse(open(url).read)

popolo.persons
# returns array of People from the file

popolo.persons.first
# returns the first Person

popolo.persons.first.name
# returns the first Person’s name

popolo.organizations
# returns the array of Organizations
```

It doesn't do the nice connecting bits we want (yet), but it's good for basic access the data.

For example, you can't do:

```
popolo.persons.first.memberships.first.organization
```

But they are very open to PRs ;-)

**Comment by equivalentideas** [comment]
I'm going to start off by swapping out the [implementation in rada4you](https://github.com/openaustralia/planningalerts/issues/897#issuecomment-190028609) with the everypolitician-popolo gem to get my head around it.

**Comment by equivalentideas** [comment]
> I'm going to start off by swapping out the implementation in rada4you with the everypolitician-popolo gem to get my head around it.

We've now done this in https://github.com/OPORA/publicwhip/pull/204#issuecomment-196657356

We’ve also made a few contributions to the gem where we needed changes:

https://github.com/everypolitician/everypolitician-popolo/pull/16
https://github.com/everypolitician/everypolitician-popolo/pull/15
https://github.com/everypolitician/everypolitician-popolo/pull/18
https://github.com/everypolitician/everypolitician-popolo/pull/17

Now it's definitely high time we got back to this and created the councillor loader for PlanningAlerts.

**Comment by henare** [comment]
We need to do this so we can do #894 because we need to know the ID to pass to the WriteIt API. We're basically replacing the email address with an ID we can pass to WriteIt.

At the same time we have to maintain the same functionality now, i.e. that it imports the councillors we want, associates them with the correct council, and sets their name, photo, etc. correctly.

So what we should do as a first step is just make it import the existing details, including email, and then after that expand it to import the WriteIt ID.

**Comment by equivalentideas** [comment]
I'm gonna collect data for an authority so we can test our fancy new importer.
