### ISSUE TITLE
Allow people to subscribe to the planning alerts without getting an alert every time someone makes a comment on a planning alert

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#902]
Someone has emailed with feedback:

>  I'm interested in what is being built around my area but I don't need to know every time someone declares that the build is not in the character of the suburb or will negatively impact the amenity of the area :)

**Comment by mlandauer** [comment]
I'm inclined to think we shouldn't do this. Maybe it's more of a pro feature?
