### ISSUE TITLE
Work out how we'll collect all the councillors’ images and store them.

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#903]
Like collecting councillor emails, collecting a nice headshot for a councillor is quite a manual process. These can be available in a few different ways, such as:

* Available at a URL found on the council website
* In a PDF
* Not available at all

We need to think through how to collect and then store and do any processing we need.

**Comment by equivalentideas** [comment]
This relates to a few issues of how we'll get councillor data, but dropping here cause of image mention:

From @henare in chat:

> Just noticed some councillor, err, councillers data on the data.gov.au feed
> https://data.gov.au/dataset/2affc498-fa6c-4b8f-82d9-df1f2f65b74c
> Strange spelling aside it's interesting structured data - they even have image URLs. It might be worth contacting them and asking where it came from in case there's some mysterious database we don't know about

**Comment by henare** [comment]
I asked how EveryPolitician does this and got a really helpful response here: https://groups.google.com/forum/#!msg/poplus/3tBmu8dY0ao/VlHwysaCAQAJ

**Comment by CloCkWeRX** [comment]
Also: #46 added image_url - some of the data sets: http://data.gov.au/dataset?tags=councillors

**Comment by henare** [comment]
>Also: #46

What's the connection?

>added image_url - some of the data sets: http://data.gov.au/dataset?tags=councillors - nevermind, you alllllllllready knew that.

I didn't - that's awesome :sun_with_face: This is probably more related to #911.

**Comment by CloCkWeRX** [comment]
@henare edited

**Comment by henare** [comment]
>I asked how EveryPolitician does this and got a really helpful response here

Here's how EveryPolitician's thing works:

>It scrapes source images that are referenced in EveryPolitician's
>Popolo JSON into a 'gh-pages' branch of a GitHub repo. It then commits
>the result and pushes it back to GitHub. This script gets run once an
>hour by Heroku's scheduler, so any new images get picked up (and any
>old ones that disappear from the EP JSON are still available from the
>repo.

Our other option is to use something like [what we created for rada4you.org](https://github.com/OPORA/ukraine_verkhovna_rada_deputy_images). It's a scraper that runs once a day on morph.io. It fetches all the images referenced in a Popolo file and stores them on S3 at a predictable URL.

That seems a bit simpler that what EveryPolitician is doing and would seem to suit our needs for the moment. If we need to do image resizing down the line then we can use something like https://github.com/jpmckinney/image-proxy

**Comment by henare** [comment]
So to do that above we need to:

- [ ] Adapt https://github.com/OPORA/ukraine_verkhovna_rada_deputy_images
- [ ] Configure S3
- [ ] Set it up on morph.io
- [ ] Change where PlanningAlerts looks for images

**Comment by equivalentideas** [comment]
Here's where @henare has started on this https://github.com/openaustralia/australian_local_councillors_images

**Comment by henare** [comment]
I think https://morph.io/openaustralia/australian_local_councillors_images is more or less ready and I've extracted #969 so I'll close this.
