### ISSUE TITLE
Searching for an address shows no applications

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#907]
Reported by a user:

>Over the last week though when I type in my address, instead of a message on the screen which reads "Applications within 2 kms of 100 King St, Newtown NSW 2042" I now get the following message:
"Applications within 0 m of 100 King St, Newtown NSW 2042"

This is a huge bug obviously. Appears to be caused by #905.

**Comment by equivalentideas** [comment]
I missed this obviously crucial user journey in testing that PR :( Which has made me realise that we don't have an integration test for this. I'm going to write one now.
