### ISSUE TITLE
Clarify our abuse policy

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#912]
From time to time an application gets dozens of abusive comments. Many of these are extremely hateful and this creates a very unpleasant environment for the people that use PlanningAlerts and look after PlanningAlerts.

It's also unlikely that these comments help the commenter influence the application in the way they intend. This is because they're less likely to be taken seriously and often can't be taken into consideration because they're irrelevant to the planning process.

Sadly, the applications that attract these comments are almost always for a mosque and the people making these comments are almost exclusively directing their hatred at Muslims. Embarrassingly sometimes the application isn't even for a mosque but that doesn't stop the abusive commenters.

Currently the only thing we say about abuse is on our "Report comment" page:

>Reasons [for removing a comment] can include that the comment is spam, abusive, unlawful or harassing — in other words, where people are going out of their way to cause harm.

We always try to maintain a light touch with moderation on our sites. There's been no exception here and we've only censored directly abusive or harassing comments, in line with the policy above. Except the most extreme ones, even doing that troubled me somewhat because our censorship presents a distorted view of what some Australians genuinely (and scarily) think.

However this isn't the purpose of PlanningAlerts and it's a distraction from what the site does and also our work. We need to clarify our abuse policy so we're really clear what is and isn't acceptable so we can effectively deal with these types of applications.

I'm not going to prescribe what that means here now because we're in the middle of dealing with an incident now and so my judgement won't be the best. Please feel free to leave your thoughts and I'll aim to resolve this in the next month at the latest (_sets Slack reminder_).

**Comment by equivalentideas** [comment]
Great summary of this problem @henare :+1: 

> we're in the middle of dealing with an incident now and so my judgement won't be the best

This really highlights one of the impacts of this problem. It’s so unpleasant to deal with that it's hard to treat like a usual design problem in the moment. I'm gonna set a reminder for myself to come back to this next week and think about it.

**Comment by henare** [comment]
>I'm gonna set a reminder for myself to come back to this next week and think about it.

That's exactly what I've done :smiley:

**Comment by henare** [comment]
>Except the most extreme [comments], even [censoring directly abusive or harassing comments] troubled me somewhat because our censorship presents a distorted view of what some Australians genuinely (and scarily) think.

Someone suggested something interesting to me last night that could solve this. Instead of hiding the comments completely, hide the comments but allow them to be shown after warning the user.

Another idea I've had before is that we could just replace the text with a message saying the comment has been removed.

I like both those ideas because it doesn't airbrush reality. The second one seems pretty non-controversial and relatively easy to implement.

**Comment by henare** [comment]
I've extracted my thoughts on this into #922 and #923.
