### ISSUE TITLE
Add RSS feed of comments for one application

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#915]
This would be useful for tracking applications that are getting abusive comments for example.

**Comment by Tanuja-Sawant** [comment]
@equivalentideas may I take up this issue?

**Comment by henare** [comment]
@Tanuja-Sawant please do! If you'd like help please ping us here or in Slack :star:

**Comment by TheChirpyWitch** [comment]
Hey @henare and @equivalentideas , can you elaborate on what you would like to do in this issue? There already seems to be an RSS feed for applications as in index.rss.builder
Do you want to add RSS feed to each application as well?

**Comment by henare** [comment]
@TheChirpyWitch Yes, this issue is about adding an RSS to each application page that contains all of the comments for that application.

As the issue says we could use this for subscribing to applications we know are getting a lot of abuse so we can more proactively remove comments that violate our abuse policy. People could also subscribe to applications they're interested in to find out what other people are saying about it.

**Comment by mlandauer** [comment]
I think it's fair to say that RSS feeds have disappeared and gone to heaven. So closing
