### ISSUE TITLE
show details of hidden comments

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#917]
show the display name of commenter and [this comment has been hidden because it is abusive]  instead of the original message. @henare suggested considering for transparency being able to also click on that message to see the original comment.

**Comment by kat** [comment]
[this comment has been reported to moderators] and [this comment has been reported for abuse and has been hidden]

**Comment by equivalentideas** [comment]
We could also link to our lovely new (to be) abuse policy on the removed comment https://github.com/openaustralia/planningalerts/issues/923

**Comment by mlandauer** [comment]
We've implemented a very rough and ready early version of this which just shows that a comment was hidden by administrators.

I think we should leave this issue open to remind us to implement the rest of this
