### ISSUE TITLE
Add ATDIS councils

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#920]
## To be added as an authority
* Be sure to check 'auto run' is on

[Port Stephens](http://datracker.portstephens.nsw.gov.au/atdis/1.0/applications.json) -  [morph.io](https://morph.io/planningalerts-scrapers/portstephens) - Address abbreviations are a bit odd, but no doubt geocodable. http://www.portstephens.nsw.gov.au/ council@portstephens.nsw.gov.au

## Already being scraped - need to check for bugs / see if ATDIS feed is better

[Lismore](http://tracker.lismore.nsw.gov.au/atdis/1.0/applications.json) - [morph.io](https://morph.io/planningalerts-scrapers/lismore)
~~[Bankstown](http://atdis.bankstown.nsw.gov.au/atdis/1.0/applications.json) [morph.io](https://morph.io/planningalerts-scrapers/bankstown)~~ Feed is 404!
[Tamworth](https://eproperty.tamworth.nsw.gov.au/atdis/atdis/1.0/applications.json) - https://github.com/planningalerts-scrapers/tamworth/issues/1

## Problematic
[Ashfield](http://mycouncil2.solorient.com.au/Horizon/@@horizondap_ashfield@@/atdis/1.0/applications.json): [morph.io](https://morph.io/planningalerts-scrapers/ashfield) but https://github.com/planningalerts-scrapers/ashfield/issues/1

[Wellington](http://ebusiness.wellington.nsw.gov.au/Horizon/@@horizondap@@/atdis/1.0/applications.json) - https://github.com/planningalerts-scrapers/wellington/issues/1

[Upper Hunter Shire Council](http://203.89.74.68/atdis/1.0/applications.json) - blocked by https://github.com/planningalerts-scrapers/upper_hunter_shire/issues/1

[Leeton Shire Council](http://203.58.97.252/Horizon/@@horizondap@@/atdis/1.0/applications.json) - [source](https://github.com/planningalerts-scrapers/leeton) - https://github.com/planningalerts-scrapers/leeton/issues/1

[Gilgandra Shire Council](http://203.46.75.253/ATDIS/1.0/applications.json ) [morph.io](https://morph.io/planningalerts-scrapers/gilgandra) - blocked by https://github.com/planningalerts-scrapers/gilgandra/issues/1
[Cootamundra](http://myhorizon.cootamundra.nsw.gov.au/Horizon/@@horizondap@@/atdis/1.0/applications.json): [Source](https://github.com/planningalerts-scrapers/cootamundra) - Flakey
[Dubbo](https://planning.dubbo.nsw.gov.au/atdis/1.0/applications.json): [Source](https://github.com/planningalerts-scrapers/dubbo) [Morph.io](https://morph.io/planningalerts-scrapers/dubbo) - Annoyingly, some Lot addresses appear as "26L".

[Bogan](http://datracker.bogan.nsw.gov.au:81/atdis/1.0/applications.json) - [morph.io](https://morph.io/planningalerts-scrapers/bogan) https://github.com/planningalerts-scrapers/bogan/issues/1

[Bega](http://datracker.begavalley.nsw.gov.au/ATDIS/1.0/applications.json) - [Pull request](https://github.com/planningalerts-scrapers/Bega_Valley_Applications_on_Exhibition/pull/1) - Very Slow

## Done
~~http://da.ballina.nsw.gov.au/atdis/1.0/applications.json~~ Couldn't add: [bad data](https://github.com/planningalerts-scrapers/ballina_shire/commit/b344be524824800a93ea2b17ecd5042fab4f07b1)
~~http://datracker.muswellbrook.nsw.gov.au/atdis/1.0/applications.json~~
~~http://mycouncil.solorient.com.au/Horizon/@@horizondap@@/atdis/1.0/applications.json (Weddin)~~
~~http://mycouncil.solorient.com.au/Horizon/@@horizondap_cowra@@/atdis/1.0/applications.json~~
~~http://mycouncil.solorient.com.au/Horizon/@@horizondap_lpsc@@/atdis/1.0/applications.json~~
~~http://mycouncil.solorient.com.au/Horizon/@@horizondap_uralla@@/atdis/1.0/applications.json~~
~~http://mycouncil.solorient.com.au/Horizon/@@horizondap_walcha@@/atdis/1.0/applications.json~~
~~https://da.kiama.nsw.gov.au/atdis/1.0/applications.json~~
[Harden](http://myhorizon.harden.nsw.gov.au/Horizon/@@horizondap@@/atdis https://github.com/planningalerts-scrapers/ashfield/issues/1/1.0/applications.json) - [morph.io](https://morph.io/planningalerts-scrapers/harden)
[Bathurst](http://masterview.bathurst.nsw.gov.au/atdis/1.0/applications.json): [morph.io](https://morph.io/planningalerts-scrapers/bathurst)
[Nambucca](http://planning.nambucca.nsw.gov.au/PlanningServices/ATDISService.svc/applications.json): [Source](https://github.com/planningalerts-scrapers/nambucca) [Morph.io](https://morph.io/planningalerts-scrapers/nambucca)
[Warrumbundle](https://mycouncil.warrumbungle.nsw.gov.au:6443/Horizon/@@horizondap@@/atdis/1.0/applications.json) - [morph.io](https://morph.io/planningalerts-scrapers/warrumbungle) - But https://github.com/planningalerts-scrapers/warrumbungle/issues/1
[Walgett](http://myhorizon.walgett.nsw.gov.au/Horizon/@@horizondap@@/atdis/1.0/applications.json) - [morph.io](https://morph.io/planningalerts-scrapers/walgett)
[Gundagui](http://horizon.gundagai.nsw.gov.au/Horizon//@@horizondap@@/atdis/1.0/applications.json) - [morph.io](https://morph.io/planningalerts-scrapers/gundagai)
[Yass](http://mycouncil.yass.nsw.gov.au/Horizon/@@horizondap@@/atdis/1.0/applications.json
): [Source](https://github.com/planningalerts-scrapers/yass)   [morph](https://morph.io/planningalerts-scrapers/yass)
[Maitland](https://myhorizon.maitland.nsw.gov.au/Horizon/@@horizondap@@/atdis/1.0/applications.json): [Source](https://github.com/planningalerts-scrapers/maitland) - [morph](https://morph.io/planningalerts-scrapers/maitland)
[Berrigan](http://datracking.berriganshire.nsw.gov.au/Horizon/@@horizondap@@/atdis/1.0/applications.json) - [Source](https://github.com/planningalerts-scrapers/berrigan)  - [morph](https://morph.io/planningalerts-scrapers/berrigan)

**Comment by kat** [comment]
Since we've had strong interest from a group in Jambaroo (Kiama council) who have been on a journey for the last 3 years pushing their local council to get their DAs online, please can we prioritize that one?

**Comment by henare** [comment]
I've added Kiama: https://www.planningalerts.org.au/authorities/kiama/applications

I was planning to go through and quickly move any broken scrapers to ATDIS. Sadly and frustratingly I immediately hit a big hurdle which was a painful reminder that this is just not going to be possible.

Ballina have included [lot data in their street address field](https://github.com/planningalerts-scrapers/ballina_shire/commit/b344be524824800a93ea2b17ecd5042fab4f07b1). This breaks our geocoding and is obviously a horrible and just plain wrong address for humans to read. It's extra crazy because there's an ATDIS field for this specific purpose - why wouldn't you use that?!

This means we're going to have to painstakingly go through every feed to make sure it's not broken in creative ways like this.

While I was doing [Kiama](https://morph.io/planningalerts-scrapers/kiama#console) I noticed some scary weirdness too. The first page of results tells you there's 7 pages. The second says there's only 4. Huh?

```
Saving page 1 of 7
Saving page 2 of 4
Saving page 3 of 4
Saving page 4 of 4
```

Anyway the feed seems to be working so I'll just ignore that for now.

**Comment by CloCkWeRX** [comment]
I'm managing to hit

http://203.46.75.253/ATDIS/1.0/applications.json
http://203.89.74.68/atdis/1.0/applications.json
http://203.58.97.252/Horizon/@@horizondap@@/atdis/1.0/applications.json

ok in my browser - any chance these were down for maintenance; or is it something else?

**Comment by henare** [comment]
I can get them now too. Odd.

**Comment by CloCkWeRX** [comment]
That was gruelling. I've added scrapers for the majority of these and raised defects where present.

The 'ready to be added as an authority' feeds should just work exactly as expected; but are worth a review before they get added to planning alerts. I've linked to source/morph.io instance so its easy to see the results.

The others fail from a combination of
 * No DNS entries
 * Pagination bugs (3 distinct behaviours - looping, wrong total pages changing mid feed, and wrong current page/current page is NULL)
 * Data that is ignored presumably because it doesn't quite conform or
 * Network issues (timeouts, flakey servers that round robin you between working and failing instances, etc)

Tomorrow / through the week will be a matter of emailing the councils with broken tools individually to see what can be worked through.

After adding the working ones here, it might be worth closing this ticket down and continuing the long term fixes in the specific repos

**Comment by henare** [comment]
>That was gruelling. I've added scrapers for the majority of these and raised defects where present.

This is incredible, thank you so much Daniel :sweat_smile: 

>The 'ready to be added as an authority' feeds should just work exactly as expected; but are worth a review before they get added to planning alerts. I've linked to source/morph.io instance so its easy to see the results.

So good :ok_hand: I'll try to review and add these to PlanningAlerts in the next few days.

>Tomorrow / through the week will be a matter of emailing the councils with broken tools individually to see what can be worked through.

We also have contact with the NSW department. Hopefully @kat can suggest if it's worth contacting them as well.

>After adding the working ones here, it might be worth closing this ticket down and continuing the long term fixes in the specific repos

SGTM :shipit:

**Comment by CloCkWeRX** [comment]
> Henare: Shall we close and split out issues now?

I think so, we're

![image](https://cloud.githubusercontent.com/assets/365751/14237413/ba277a78-fa62-11e5-98eb-4d8af28e636c.png)

**Comment by henare** [comment]
Roaringly splendid work @CloCkWeRX :exclamation: :city_sunset:
