### ISSUE TITLE
Say on the comment form that abusive comments are not tolerated

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#922]
We should be clear and up front about this so everyone understands what is and isn't acceptable on PlanningAlerts. We should link to the complete abuse policy done as part of #923.

Extracted from #912 after some thought.

**Comment by equivalentideas** [comment]
Why have you assigned this to me @CloCkWeRX ?

**Comment by CloCkWeRX** [comment]
#937 is an implementation of this, you wanted to go another direction.

**Comment by equivalentideas** [comment]
> #937 is an implementation of this, you wanted to go another direction.

👌 I think my basic thoughts on this at the moment are that we should do #923 first and also do some sketching of a few different ways we could approach this issue before implementing it.

**Comment by mlandauer** [comment]
I agree that some reference to the abuse policy as a reminder that we're trying to create a safe space would be a good thing. It's not clear to me yet how to do that so it is effective
