### ISSUE TITLE
Clearly state our abuse policy somewhere we can link to it

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#923]
Currently the only thing we say about abuse is on our "Report comment" page:

```
Reasons [for removing a comment] can include that the comment is spam, abusive, unlawful or harassing — in other words, where people are going out of their way to cause harm.
```

We need to move that somewhere we can link to it for #922. We also need to expand and clarity that to make it clear that racist abuse is not tolerated.

While we're doing that it might be a good idea to revise it completely. Are there other abuse policies out there somewhere that we could use? Of course we shouldn't let revising it completely get in the way of doing the simple things above.

Extracted from #912 after some thought.

**Comment by CloCkWeRX** [comment]
http://www.google.com/intl/en-us/+/policy/content.html I think might be a good starting point, touching on a lot of areas

**Comment by henare** [comment]
I like this [from The Conversation](https://theconversation.com/sign_in) too:

>We welcome debate and dissent, but personal attacks (on authors, other users or any individual), abuse and defamatory language will not be tolerated. Nor will we tolerate attempts to deliberately disrupt discussions. We aim to maintain The Conversation as an inviting space to focus on intelligent discussions.
>
>Please be courteous.
>
>Read our community standards

**Comment by mlandauer** [comment]
Agree that this would be super valuable!
