### ISSUE TITLE
Allow an application to be marked for pre-moderation

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#924]
From time to time an application attracts lots of abusive comments or even comments that simply aren't helpful or relevant, e.g. https://www.planningalerts.org.au/applications/187121

We need a way for admins to mark an application as requiring pre-moderation. Once the flag is turned on any new comments would be marked for moderation after the user confirms them. That would mean an admin would then need to approve it.

Another benefit of this is that these problematic comments wouldn't be sent to council.

Extracted from #913.

**Comment by mlandauer** [comment]
I have mixed feelings about this one. These very contentious applications do occur every so often and I can see the huge value in stopping the worst behavior before it's public and sparks more bad behavior. However doing pre-moderation feels like a bit of a slippery slope where we are more actively "taking responsibility" for the comments
