### ISSUE TITLE
Help scraper contributors find issues to improve working scrapers

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#926]
Our lovely scraper contributors [watch the planningalerts-scrapers organisation on morph.io](https://morph.io/planningalerts-scrapers/mornington_peninsula/watchers). They get alerts when scrapers error and then go and fix them. Or, when they are in the fixing mood they go and look at the list of errored scrapers and fix a few. They also look at the list of authorities on the [Authorities page on PlanningAlerts](https://www.planningalerts.org.au/authorities) and look at the “possibly broken” ones.

There are [issues that would be nice to fix](https://github.com/planningalerts-scrapers/nsw_joint_regional_planning_panels/issues/2) on scrapers that _are_ working. Because people don't watch the scrapers on Github, they won't get notified. They also wont appear as “possibly broken” on PlanningAlerts.

One way to help people discover these issues would be to link to or list [issues on repos under the planningalerts-scrapers organisation on GitHub](https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Aplanningalerts-scrapers), so contributors can view these as a TODO list ;-).

**Comment by mlandauer** [comment]
We now have issues for all broken scrapers created automatically in planningalerts-scrapers/issues. That creates a really easy place for a developer to look and understand what the problems are
