### ISSUE TITLE
Wrong comment options show

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#928]
If an authority has no email address, but write to councillors is enabled for it, users incorrectly get the option to send a comment to the authority. We don't have an email for the authority so that is gonna :boom: .

**Comment by equivalentideas** [comment]
@kat suggests that we recommend people ask their councillor to forward their comment to the council

**Comment by archoo** [comment]
I found it odd that brisbane doesn't publish a general address.. I did try and snoop their enquiry form code, but i couldn't see anything useful.. They also don't publish an address for the lord mayor?!
I have sent some exploratory emails to logical addresses to see if one gets a response.. i'll update if i hear anything..
