### ISSUE TITLE
Remove confirmed attribute from models

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#943]
#931 introduced `confirmed_at` on the Comment model so `confirmed` is no longer required - we can just check if `confirmed_at` is present instead. We should be able to do the same for Alert and reduce this duplication.

**Comment by mlandauer** [comment]
Still relevant.

I also notice the `Alert` model doesn't have a `confirmed_at` but only a `confirmed` field

**Comment by katska** [comment]
@mlandauer still relevant then I'm guessing?
