### ISSUE TITLE
Upgrade to rspec 3

### ISSUE THREAD

**Issue by CloCkWeRX** [openaustralia/planningalerts#946]
We're affected by rspec/rspec-core#2210 - we can go bump the specs using something like transpec and upgrade to rspec 3 in a bit; but wanted to wait until the majority of stuff is merged/things are settled.

**Comment by CloCkWeRX** [comment]
Ugh, this is a complete pain. 

```
Finished in 22.94 seconds (files took 4.63 seconds to load)
580 examples, 115 failures, 4 pending
```

Most seem to be email-spec no longer returning unread emails the same way it used to / not being hooked in, even after bumping to version 2 / checking the setup. Looking more later.

**Comment by equivalentideas** [comment]
I've done this in https://github.com/openaustralia/planningalerts/compare/f9233a194c42...824c541
