### ISSUE TITLE
When I want to look at the json api data for an application/search/authority, give me a link to view it if I'm logged in

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#947]
I was just wanting to look at the JSON data for a council. I just wanted to see an example of the data.

I went to the coverage page, found a council, when to all their recent applications, and put .json on the end of the url. Blank page.

I then went to the 'Get the data' page and scrolled through the sections for the authority example.

I then copied the `?key=xxxx` bit and put that on the end of my other tab. Still nothing. I then when back and looked at the example again and noticed that the extension was '.js`.

This is a lot of manual messing around to get there.

Could we just have a `View as JSON` link that already has your key shown if you're logged in? Would that have saved me all the confusion?

**Comment by hisayohorie** [comment]
I'll work on this!
