### ISSUE TITLE
Send a tweet when a local councillor replies to someone

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#952]
When a local councillor replies to someone send a tweet like:

> .@councillor_louise just answered a someone’s question about local planning /link/
- highlights the humans behind local democracy
- incentivises the councillors to respond to people
- incentivises them to make good replies, and
- helps promote people’s messages to councillors (potentially increasing their impact).

**Comment by henare** [comment]
Could be a scraper on morph.io like @jacksongs' https://morph.io/jacksongs/lobbybot
