### ISSUE TITLE
Text email to Councillors is a bit robotic

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#953]
Unfortunately [we can't send HTML email via WriteIt yet](https://github.com/ciudadanointeligente/write-it/issues/1144), so we're sending [a text email](https://github.com/openaustralia/planningalerts/blob/master/app/views/comment_notifier/notify_councillor.text.erb) to let councillors know that someone has written to them.

Before the actual message the actual message the person has sent to them, we give the Councillor a really rotobo looking block with information about the application “address ... description ... link” :space_invader:  :computer: :speaker: :speak_no_evil: :

>Subject: Planning application at 27 Francis Street Enmore NSW 2042
>
> Hi Louise Councillor,
>
> You’ve got a new message from Luke Bacon in relation to a local
> planning application:
>
> Address: 27 Francis Street Enmore NSW 2042
> Description: To demolish part of the premises and carry out ground floor alterations and additions to a dwelling house
> Link: https://test.planningalerts.org.au/applications/397438?utm_campaign=view-application&utm_medium=email&utm_source=councillor-notifications
>
> Luke Bacon writes:
>
> I think this is just a test but the application is wonderful nonetheless.
>
> Church-key 90's hella chambray single-origin coffee, cardigan cronut. Thundercats pinterest cliche ennui. Cornhole typewriter tofu photo booth, marfa kale chips kitsch biodiesel authentic man bun four dollar toast. Irony whatever yr, 8-bit listicle skateboard scenester deep v sriracha etsy waistcoat cred. Pickled heirloom man braid brunch, meditation actually four loko. Humblebrag sriracha messenger bag literally scenester. Butcher +1 kickstarter viral.
>
>\=========================================================================
> 
> This message was posted publicly on PlanningAlerts. You can publicly
> respond to this message by simply replying to this email.
> 
> Best wishes,
>
> PlanningAlerts

We want Councillors to focus on the person they're writing to, rather than the system. Putting this robotic block up front distracts them from the main purpose of the email, the message and the person writing to them.

Could we move the block about the application to after the message? Then we could have a simpler intro like we have for the HTML version:

> You’ve got a new message from Luke Bacon in relation to a local planning application for 123 Test St, Over The Rainbow. The application is for, “Paving paradise”.
> Luke Bacon writes:
>
> G'day me lovely gnarwhale

**Comment by CloCkWeRX** [comment]
What's the subject look like? If there's address / dev app info mixed in there it might be doubling up a bit

**Comment by henare** [comment]
>Planning application at 27 Francis Street Enmore NSW 2042

**Comment by henare** [comment]
I think @CloCkWeRX might be on to something - could we just have the message text first up then put the boilerplate afterwards? That would make it look something like:

>Subject: Planning application at 27 Francis Street Enmore NSW 2042
>
>I think this is just a test but the application is wonderful nonetheless.
>
>Church-key 90's hella chambray single-origin coffee, cardigan cronut. Thundercats pinterest cliche ennui. Cornhole typewriter tofu photo booth, marfa kale chips kitsch biodiesel authentic man bun four dollar toast. Irony whatever yr, 8-bit listicle skateboard scenester deep v sriracha etsy waistcoat cred. Pickled heirloom man braid brunch, meditation actually four loko. Humblebrag sriracha messenger bag literally scenester. Butcher +1 kickstarter viral.
>
>From by Luke Bacon
>\=========================================================================
>
>Hi Jo Haylen, the above message was posted publicly on PlanningAlerts by
>Luke Bacon about this development application:
>
>Address: 27 Francis Street Enmore NSW 2042
>Description: To demolish part of the premises and carry out ground floor alterations and additions to a dwelling house
>Link: https://test.planningalerts.org.au/applications/397438?utm_campaign=view-application&utm_medium=email&utm_source=councillor-notifications
>
>You can publicly respond to this message by simply replying to this email.

**Comment by equivalentideas** [comment]
I'm gonna have a go at implementing this to see how "could we just have the message text first up then put the boilerplate afterwards" goes.

**Comment by equivalentideas** [comment]
Closed for now by merging #960
