### ISSUE TITLE
Prepare announcement blog posts for Write To Councillors project

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#956]
- [x] Announcement of the launch. This should be citizen focussed - what does it allow them to do that they couldn't before?
- [ ] Project/technical announcement. We should also do a blog post about how we did it and what was involved. This will be useful for other people wanting to do the same thing and it will also allow us to talk about how the data and infrastructure we've created for this project can be reused.

**Comment by henare** [comment]
It would be nice to come up with a phrase/name that better describes this thing than "Write To Councillors".

**Comment by equivalentideas** [comment]
> It would be nice to come up with a phrase/name that better describes this thing than "Write To Councillors".

We extracted this and complete it in #999 "Ask Your Councillors"

**Comment by equivalentideas** [comment]
Going to start by reading some OpenAustralia Foundation past project announcement blog posts:

* https://www.openaustraliafoundation.org.au/2012/11/28/you-have-the-right-to-know/
* https://www.openaustraliafoundation.org.au/2009/12/21/launching-our-new-website-planning-alerts/
* https://www.openaustraliafoundation.org.au/2014/10/21/they-vote-for-you/
* https://www.openaustraliafoundation.org.au/2014/02/27/morph-announcing-a-new-scraping-platform/

**Comment by equivalentideas** [comment]
The launch blog posts so far have a few features:

* Don't have to be very long to be effective
* They start by explaining the current situation, the start of the story to explaining why we built the thing
* The explain the problem being solved
* They have useful pictures

**Comment by equivalentideas** [comment]
Following the basic _problem_, _how this new thing makes a difference_, _now you can go do this thing_ structure, I've take the ideas we had earlier in the week about why the project is useful and mapped out a structure for the post:

![img_4695](https://cloud.githubusercontent.com/assets/1239550/16137443/c0165ee2-3476-11e6-87c9-8a7a66ce6372.jpg)

**Comment by equivalentideas** [comment]
I've tapping on this in here https://docs.google.com/document/d/1HQHXlObiqRXrFE1zMpEq5FSeBsRbmWPkFkTTOw522zs/edit

**Comment by equivalentideas** [comment]
I've got a first draft. I'm pretty happy with the structure, but I question some of the wording and I’m sure there are ways to simplify it: https://docs.google.com/document/d/1HQHXlObiqRXrFE1zMpEq5FSeBsRbmWPkFkTTOw522zs/edit

**Comment by henare** [comment]
It's looking really good @equivalentideas :+1: I've started making a few suggestions. I'll take a look again on Monday.

**Comment by equivalentideas** [comment]
> It's looking really good @equivalentideas 👍 I've started making a few suggestions. I'll take a look again on Monday.

Yep that’s great 👍

**Comment by equivalentideas** [comment]
Thanks for the feedback on the blog post @kat and @henare . I’m chuck it on our blog, and load it up as an email to all our PlanningAlerts users.

**Comment by henare** [comment]
Citizen announcement done https://www.openaustraliafoundation.org.au/2016/06/21/ask-your-local-councillors/ great work @equivalentideas :tada: 

Assigning to me for the technical blog post.

**Comment by henare** [comment]
Just wrapping up this issue.

Not long after the last comment I did start writing the first of what I thought would be a series of blog posts about what we were doing behind the scenes. These always feel like the right kind of posts to create when you start out. After all you want to talk up the amazing civic tech goodness that underpins this feature and others like it.

However whenever I go to write these type of posts I get lost. I think its partly because I'm not clear on who our intended audience for these posts are (other civic tech practitioners?). But it's probably because I'm just not used to talking up the things we do in this way so it just doesn't come naturally.

I really tried with this one but couldn't get it out. Rather than making me want to force myself to do it next time I actually think we should drop the idea of doing technical blog posts like these. Unless the inspiration hits, of course.
