### ISSUE TITLE
Reply permalinks on comments index don't link to comment correctly

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#964]
To reproduce:
- Go to comments page: https://www.planningalerts.org.au/comments
- Find a reply from a councillor
- Click permalink
- It links to https://www.planningalerts.org.au/comments#reply20 instead of https://www.planningalerts.org.au/applications/635635#reply20

**Comment by equivalentideas** [comment]
Fixed by @hisayohorie in https://github.com/openaustralia/planningalerts/pull/1131
