### ISSUE TITLE
Add councillors for all the existing authorities

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#968]
[Following the instructions in README.md](https://github.com/openaustralia/planningalerts#adding-councillors-for-an-authority), add councillors to all the authorities covered by PlanningAlerts so that people can write to them.

We've decided to aim for 50% of authorities covered as part of this milestone. We're going to target high population and high commenting rate authorities.
## ACT

No local councillors to write to in the ACT.
- ACT Planning & Land
## NSW
- [x] Albury City Council
- Auburn City Council – [has been suspended](http://www.auburn.nsw.gov.au/Govern1/Councillors/Pages/Councillors.aspx) and [being amalgamated](https://github.com/openaustralia/planningalerts/issues/998#issuecomment-232283005)
- [x] Ballina Shire Council
- Bankstown City Council - [being amalgamated](https://github.com/openaustralia/planningalerts/issues/998#issuecomment-232283005)
- [x] Bathurst Regional Council
- [x] Bega Valley Shire Council
- [x] Bellingen Shire Council
- [x] Berrigan Shire Council
- [x] Blacktown City Council
- [x] Blue Mountains City Council
- [ ] Burwood Council - [possibly broken]
- [x] Camden Council
- [x] Campbelltown City Council
- [x] Cessnock City Council
- [ ] City of Botany Bay - [possibly broken]
- [ ] City of Canada Bay
- City of Canterbury - [being amalgamated](https://github.com/openaustralia/planningalerts/issues/998#issuecomment-232283005)
- [ ] City of Lismore
- [x] City of Newcastle
- [ ] City of Ryde
- [x] City of Sydney
- [ ] City of Wagga Wagga
- [x] Coffs Harbour City Council
- [ ] Cowra Council - [possibly broken]
- [ ] Fairfield City Council - [possibly broken]
- [x] Gosford City Council
- [ ] Goulburn Mulwaree Council
- Great Lakes Council - [being amalgamated](https://github.com/openaustralia/planningalerts/issues/998#issuecomment-232283005)
- Greater Taree City Council - [being amalgamated](https://github.com/openaustralia/planningalerts/issues/998#issuecomment-232283005)
- [x] Griffith City Council
- Gundagai Shire Council - [being amalgamated](https://github.com/openaustralia/planningalerts/issues/998#issuecomment-232283005)
- [ ] Harden Shire Council
- [ ] Hawkesbury City Council
- Holroyd City Council - [being amalgamated](https://github.com/openaustralia/planningalerts/issues/998#issuecomment-232283005)
- [x] Hornsby Shire Council
- Hurstville City Council - [being amalgamated](https://github.com/openaustralia/planningalerts/issues/998#issuecomment-232283005)
- [ ] Kiama Municipal Council
- Kogarah City Council - [being amalgamated](https://github.com/openaustralia/planningalerts/issues/998#issuecomment-232283005)
- [x] Ku-ring-gai Council
- [x] Lake Macquarie City Council
- [ ] Lane Cove Council
- Leichhardt Municipal Council - [being amalgamated](https://github.com/openaustralia/planningalerts/issues/998#issuecomment-232283005)
- [x] Liverpool City Council
- [ ] Liverpool Plains Shire Council
- [ ] Maitland City Council
- [x] Manly Council
- [x] Marrickville Council
- [ ] Mosman Municipal Council
- [ ] Muswellbrook Shire Council
- [ ] Nambucca Shire Council
- [x] North Sydney Council
- NSW Department of Planning Major Project Assessments - Not a council
- NSW Independent Liquor and Gaming Authority - Not a council
- NSW Joint Regional Planning Panels - Not a council
- [ ] Orange City Council
- [x] Parramatta City Council
- [x] Penrith City Council
- Pittwater Council - [being amalgamated](https://github.com/openaustralia/planningalerts/issues/998#issuecomment-232283005)
- [ ] Port Macquarie-Hastings Council
- [ ] Port Stephens Council
- [x] Randwick City Council
- [ ] Rockdale City Council
- [ ] Shellharbour City Council
- [ ] Shoalhaven City Council
- [ ] Singleton Council
- [ ] Strathfield Municipal Council
- [x] Sutherland Shire Council
- [ ] Tamworth Regional Council
- [x] The Hills Shire Council
- [ ] Tweed Shire Council
- [ ] Uralla Shire Council
- [ ] Walcha Council
- [ ] Walgett Shire Council - [possibly broken]
- Warringah Council - [being amalgamated](https://github.com/openaustralia/planningalerts/issues/998#issuecomment-232283005)
- [ ] Warrumbungle Shire Council
- [x] Waverley Council
- [ ] Weddin Shire Council
- [ ] Willoughby City Council
- [ ] Wingecarribee Shire Council
- [x] Wollongong City Council
- [ ] Woollahra Municipal Council
- [x] Wyong Shire Council
- [ ] Yass Valley Council
## NT

Has local councils, but applications are tied to a single authority, not people's local councils. Seems like we can't support these application for now.
- Northern Territory Lands Group
## QLD
- [x] Brisbane City Council - Councillors loaded but Ask Your Councillors feature can't be switched on till https://github.com/openaustralia/planningalerts/issues/928 is solved or we get their email
- [x] Bundaberg Regional Council
- [x] Burdekin Shire Council
- [x] Cairns Regional Council
- [x] Charters Towers Regional Council
- [x] City of Ipswich
- [x] Fraser Coast Regional Council
- [x] Gold Coast City Council
- [x] Logan City Council
- [x] Mackay Regional Council
- [x] Moreton Bay Regional Council
- [x] Noosa Shire Council
- [x] Redland City Council
- [ ] Scenic Rim Regional Council - [possibly broken]
- [x] Sunshine Coast Regional Council
- [x] Toowoomba Regional Council
- [x] Townsville City Council
## SA
- [ ] City of Burnside - [possibly broken]
- [ ] City of Charles Sturt
- [x] City of Marion
- [x] City of Onkaparinga
- [x] City of Port Adelaide Enfield
- [x] City of Salisbury
- [x] City of Unley
- [x] Adelaide City Council
- Department of Planning, Transport and Infrastructure - Not a council
## TAS
- [x] Clarence City Council
- [ ] Hobart City Council
- [ ] Huon Valley Council - emails [not published](http://www.huonvalley.tas.gov.au/council/members/), other [details collected](https://github.com/openaustralia/australian_local_councillors_popolo/pull/84/)
- [x] Kingborough Council
- [x] Launceston City Council
- [ ] Sorell Council - [possibly broken]
## VIC
- [ ] Baw Baw Shire Council - [possibly broken]
- [x] Boroondara City Council
- [ ] Cardinia Shire Council
- [x] City of Ballarat
- [x] City of Casey
- [ ] City of Glen Eira
- City of Greater Geelong - [has been dismissed](http://www.geelongaustralia.com.au/councillors/default.aspx)
- [x] City of Kingston
- [ ] City of Stonnington - [possibly broken]
- [x] City of Yarra
- [x] Darebin City Council - [possibly broken]
- [x] Knox City Council
- [x] Melbourne City Council
- [x] Monash City Council
- [x] Moreland City Council
- [x] Mornington Peninsula Shire
- [ ] Nillumbik Shire Council
- [ ] South Gippsland Shire Council
- Streamlined Planning through Electronic Applications and Referrals - Not a council
- [ ] Surf Coast Shire Council
- Victorian Commission for Gambling and Liquor Regulation - Not a council
- [x] Yarra Ranges Shire Council
## WA
- [x] City of Busselton
- [ ] City of Cockburn - [possibly broken]
- [x] City of Fremantle
- [ ] City of Gosnells
- [ ] City of Perth
- [x] City of Swan
- [x] City of Vincent
- Development Assessment Panels - Not a council

**Comment by equivalentideas** [comment]
People in the City of Knox can now write to their local councillors https://www.planningalerts.org.au/applications/655413

**Comment by henare** [comment]
>No local councillors to write to in the ACT.

I guess that means the ACT Legislative Assembly has the elected officials people should be able to write to.

**Comment by equivalentideas** [comment]
The people of Melbourne can now write to their local councillors through PlanningAlerts https://www.planningalerts.org.au/applications/655218

Their councillors have some interesting Party name’s there https://www.vec.vic.gov.au/Results/melbourneresult2012.html#e2 hmmm.

**Comment by equivalentideas** [comment]
The people of Manly can now write to their local councillors through PlanningAlerts https://www.planningalerts.org.au/applications/655019 🏄

**Comment by equivalentideas** [comment]
The fine people of the Gold Coast can now write to their local councillors through PlanningAlerts 🐚  https://www.planningalerts.org.au/applications/648617

**Comment by equivalentideas** [comment]
🌅  The people of Lake Macquarie can now write to their local councillors through PlanningAlerts https://www.planningalerts.org.au/applications/655942

**Comment by equivalentideas** [comment]
The border dwellers of Albury can now write to their local councillors through PlanningAlerts ⛵ https://www.planningalerts.org.au/applications/655271

**Comment by equivalentideas** [comment]
The bush walkers of the Blue Mountains can now write to their local councillors via PlanningAlerts 🌄  https://www.planningalerts.org.au/applications/655095

**Comment by equivalentideas** [comment]
The people of **Bellingen** can now write to their local councillors via PlanningAlerts https://www.planningalerts.org.au/applications/655386

**Comment by equivalentideas** [comment]
**City of Sydney**-siders can now write to local councillors via PlanningAlerts https://www.planningalerts.org.au/applications/655854

**Comment by equivalentideas** [comment]
Citizens of **Waverley** can now write to their local councillors via PlanningAlerts 🐬 https://www.planningalerts.org.au/applications/655369

**Comment by equivalentideas** [comment]
Citizens in the **City of Marion** can now write to their local councillors via PlanningAlerts
https://www.planningalerts.org.au/applications/656052

**Comment by equivalentideas** [comment]
People in the **City of Unley** can now write to their local councillors via PlanningAlerts
https://www.planningalerts.org.au/applications/656283

**Comment by equivalentideas** [comment]
Citizens of the lovely **City of Port Adelaide Enfield** can now write to their local councillors via PlanningAlerts https://www.planningalerts.org.au/applications/656365

**Comment by equivalentideas** [comment]
The fine folks of the **City of Onkaparinga** can now write to their local councillors via PlanningAlerts https://www.planningalerts.org.au/applications/656259

**Comment by equivalentideas** [comment]
People can now write to **Logan City Councillors** about applications in PlanningAlerts https://www.planningalerts.org.au/applications/655892

**Comment by equivalentideas** [comment]
🎆  People can now write to **Blacktown city Councillors** about local planning through PlanningAlerts https://www.planningalerts.org.au/applications/657349

**Comment by equivalentideas** [comment]
People in **Launceston** can now write to their local councillors via PlanningAlerts
https://www.planningalerts.org.au/applications/649543

**Comment by equivalentideas** [comment]
We can now write to **Clarence City Councillors** via PlanningAlerts https://www.planningalerts.org.au/applications/659965

**Comment by equivalentideas** [comment]
😎  Sunshine Coasters can now write to their local councillors through PlanningAlerts https://www.planningalerts.org.au/applications/660232

**Comment by equivalentideas** [comment]
🌅  Hobbits of the Shire (**Sutherland Shire**) can now write to their local councillors through PlanningAlerts https://www.planningalerts.org.au/applications/659732

**Comment by equivalentideas** [comment]
We can now write to Wollongong City Councillors via PlanningAlerts https://www.planningalerts.org.au/applications/660268

**Comment by equivalentideas** [comment]
We can now write to **Penrith City Councillors** through PlanningAlerts https://www.planningalerts.org.au/applications/659816

**Comment by equivalentideas** [comment]
People up in **Townsville** can now write to their local councillors through PlanningAlerts https://www.planningalerts.org.au/applications/659357

**Comment by equivalentideas** [comment]
We can now write to **Liverpool City Councillors** in PlanningAlerts https://www.planningalerts.org.au/applications/659495

**Comment by equivalentideas** [comment]
We can now write to **Parramatta City Councillors** in PlanningAlerts https://www.planningalerts.org.au/applications/660269

**Comment by equivalentideas** [comment]
We can now write to **Monash City Councillors** in PlanningAlerts
https://www.planningalerts.org.au/applications/659524

**Comment by equivalentideas** [comment]
🎆  We can all now write to **Ipswich City Councillors** through PlanningAlerts https://www.planningalerts.org.au/applications/660546

**Comment by equivalentideas** [comment]
🏯  Newcastrians can now write to **Newcastle City Councillors** in PlanningAlerts https://www.planningalerts.org.au/applications/565436

**Comment by henare** [comment]
@equivalentideas [Novocastrians](https://en.wiktionary.org/wiki/Novocastrian), please! :wink:

**Comment by equivalentideas** [comment]
🍰  We can all now write to our **Moreland City Councillors** through PlanningAlerts thanks to @kat . https://www.planningalerts.org.au/applications/659899

**Comment by equivalentideas** [comment]
🌴 We can now write to **Moreton Bay Regional Councillors** through PlanningAlerts thanks to @kat https://www.planningalerts.org.au/applications/660594

**Comment by equivalentideas** [comment]
We can now write to **Kingston City Councillors** through PlanningAlerts https://www.planningalerts.org.au/applications/659896

**Comment by equivalentideas** [comment]
🎆  We can now all write to **The Hills Shire Councillor** through PlanningAlerts thanks to contributor Pip Brown.

https://www.planningalerts.org.au/applications/661118

**Comment by equivalentideas** [comment]
🏆  We can all now write to Adelaide City Councillors through PlanningAlerts thanks to @kat https://www.planningalerts.org.au/applications/661507

**Comment by equivalentideas** [comment]
:boat We can all now write to Fremantle City Councillors through PlanningAlerts https://www.planningalerts.org.au/applications/666456

**Comment by equivalentideas** [comment]
We can now write to Swan City Councillors through PlanningAlerts https://www.planningalerts.org.au/applications/666494

And they have fun pictures.

**Comment by equivalentideas** [comment]
🎆 🎆 🎆  We can now write to Ballina Shire Councillors that to contributor Pip Brown!

**Comment by equivalentideas** [comment]
We can now all write to **Bundaberg Regional Councillors** through PlanningAlerts thanks to @archoo 🍒  https://www.planningalerts.org.au/applications/666949

**Comment by equivalentideas** [comment]
🌴  We can now all write to **Cairns Regional Councillor** via PlanningAlerts, thanks to @archoo https://www.planningalerts.org.au/applications/667714

**Comment by equivalentideas** [comment]
🐠  We can now all write to **Fraser Coast Regional Councillors** in PlanningAlerts thanks to @archoo https://www.planningalerts.org.au/applications/664377

**Comment by equivalentideas** [comment]
🏆  You can write to **Mackay Regional Councillor** through PlanningAlerts now thanks to @archoo  https://www.planningalerts.org.au/applications/663575

**Comment by equivalentideas** [comment]
🔴  We can now all write to **Redland City Councillors** in PlanningAlerts thanks to @archoo https://www.planningalerts.org.au/applications/667230

**Comment by equivalentideas** [comment]
🐄  Write to **Bega Valley Shire Councillors** in PlanningAlerts thanks to contributor Pip Brown https://www.planningalerts.org.au/applications/600085

**Comment by equivalentideas** [comment]
🎆  You can now write to **North Sydney Councillors** in PlanningAlerts thanks to @kat https://github.com/openaustralia/australian_local_councillors_popolo/issues/49

**Comment by equivalentideas** [comment]
You can now write to **Casey City Councillors** through PlanningAlerts https://www.planningalerts.org.au/applications/660360

**Comment by equivalentideas** [comment]
🌠  We can now all write to **Campbelltown City Councillors** through PlanningAlerts https://www.planningalerts.org.au/applications/654861

**Comment by equivalentideas** [comment]
🌄  We can all now write to **Yarra Ranges Shire Council** thanks to @aidanarcher https://www.planningalerts.org.au/applications/669551

**Comment by equivalentideas** [comment]
We can now all write to Coffs Harbour City Councillors through PlanningAlerts thanks to Pip Brown ⛵ ⛵ ⛵ https://www.planningalerts.org.au/applications/671738

**Comment by equivalentideas** [comment]
We can all now write to Wyong Shire Councillors through PlanningAlerts 🐦 https://www.planningalerts.org.au/applications/672459

**Comment by equivalentideas** [comment]
You can now write to Mornington Peninsula Shire Councillors through PlanningAlerts 🐚 https://www.planningalerts.org.au/applications/666336

**Comment by equivalentideas** [comment]
You can now write to **Cessnock City Councillors** through PlanningAlerts https://www.planningalerts.org.au/applications/673739

**Comment by equivalentideas** [comment]
We can now write to **Hornsby Shire Council** through PlanningAlerts https://www.planningalerts.org.au/applications/673099

**Comment by equivalentideas** [comment]
You can now write to **City of Salisbury Councillors** through PlanningAlerts https://www.planningalerts.org.au/applications/671181

**Comment by equivalentideas** [comment]
You can write to **Ballarat City Councillors** through PlanningAlerts now https://www.planningalerts.org.au/applications/673340

**Comment by equivalentideas** [comment]
The fine people of Yarra City Council can now write to their local councillors through PlanningAlerts https://www.planningalerts.org.au/applications/673580

**Comment by equivalentideas** [comment]
Thanks to a contribution from @pipb we can all now write to **Camden Councillors** through PlanningAlerts 🎆 🌠 🎆 🌠 🎆 🌠

**Comment by equivalentideas** [comment]
📢  Now in PlanningAlerts, write to **Berrigan Shire Council** thanks to a contribution by @pipb 🍹 
https://www.planningalerts.org.au/applications/672899

**Comment by equivalentideas** [comment]
You can now write to **Vincent City Councillors** through PlanningAlerts https://www.planningalerts.org.au/applications/665740

**Comment by equivalentideas** [comment]
Brisbane City Council - Councillors loaded but Ask Your Councillors feature can't be switched on till https://github.com/openaustralia/planningalerts/issues/928 is solved or we get their email

**Comment by equivalentideas** [comment]
You can now ask your Burdenkin Shire Councillors about planning through PlanningAlerts Thanks to @archoo 🌴  https://www.planningalerts.org.au/applications/638826

**Comment by equivalentideas** [comment]
Question about this “Hot Air Station” https://www.planningalerts.org.au/applications/675683? 

Why not ask one of the Charters Towers Regional Councillors?

Thanks for collecting these @archoo 💯

**Comment by equivalentideas** [comment]
Ask your Noosa Shire Councillors about a planning application any time—https://www.planningalerts.org.au/applications/677340

**Comment by henare** [comment]
We're leaving this on the milestone until we've done 50% of authorities (73) in PlanningAlerts. Then we'll take it off the milestone but leave it open until it's done because it's such a great list.

**Comment by henare** [comment]
Just added the most commented council that didn't already have councillors - **Ku-ring-gai**

https://www.planningalerts.org.au/applications/685557

**Comment by equivalentideas** [comment]
Ask your City of Busselton about planning applications any time thanks to @gooch ! https://www.planningalerts.org.au/applications/719950

**Comment by equivalentideas** [comment]
I've switch the Ask Your Councillors feature off on councils that have just had elections in NSW. Once the councils have published there new lists of councillors with contact info we can update them and turn it back on.
