### ISSUE TITLE
Councillor images don't fit container perfectly for certain ratios

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#972]
The way the Councillor images are set into their container doesn't always lay them out as 'full bleed' like we want. See [this example](https://www.planningalerts.org.au/applications/655019):

![screen shot 2016-04-29 at 11 41 37 am](https://cloud.githubusercontent.com/assets/1239550/14906532/7b1cae60-0dff-11e6-9501-05faaeb59d1a.png)

**Comment by equivalentideas** [comment]
Another example https://www.planningalerts.org.au/applications/655271

**Comment by henare** [comment]
This will be fixed by https://github.com/openaustralia/australian_local_councillors_images/issues/5 so I'll close this.
