### ISSUE TITLE
Make the “Locate me automatically” button more prominent

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#975]
Users would click the “locate me automatically” link on the home page are twice as likely to subscribe for alerts, compared to people who manually enter an address. (20% conversion compared to 10%)

Currently this option is pushed back in the design compared to the address input field, and the submit search button.

![screen shot 2016-05-04 at 2 46 49 pm](https://cloud.githubusercontent.com/assets/1239550/15005376/1b57c0f8-1207-11e6-8c92-54d8047dcf6b.png)

I think we should try making this button much more prominent because people are clearly finding it a better way to find the address they want to subscribe to alerts for than by using the manual input. (see [discussion of their troubles here](https://github.com/openaustralia/planningalerts/pull/948#issuecomment-216455775) and [here](https://github.com/openaustralia/planningalerts/issues/889)).

Here's a few ideas for how we could make the link more prominent.
- Make it a button
- Move it above the form input, so it's like “locate me” or you can look up an address 
- Use colour to make it stand out
- Use a familiar “my location” icon to grab attention and illustrate the idea

Here's an example of how [askizzy.com present this](https://askizzy.org.au/category/housing/personalise/page/location) which I think is quite nice and simple:

![screen shot 2016-05-04 at 2 53 25 pm](https://cloud.githubusercontent.com/assets/1239550/15005449/0f042606-1208-11e6-85fb-95b1cdbaee25.png)

**Comment by mlandauer** [comment]
This looks like a quick win for sign up conversion. I think we should definitely do something like this!!
