### ISSUE TITLE
Don't suggest that people look up a suburb using the auto complete

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#978]
Currently the address search form auto-complete suggests you enter a suburb name. If you take the option they then get a form error ‘Enter a street address’.

We shouldn't suggest people do something that will lead them to an error. Many people see this error and then don't get out of this error cycle and never get to see the applications or sign up for the alerts they wanted.

![screen shot 2016-05-12 at 1 40 49 pm](https://cloud.githubusercontent.com/assets/1239550/15203448/32076b32-1847-11e6-8a10-c318ba42ad17.png)

Should it instead suggest a street address to you? On #948 I suggested this:

> if you start entering a suburb, the auto complete could suggest streets to reinforce that you should enter a street address

Extracted from https://github.com/openaustralia/planningalerts/pull/948

**Comment by equivalentideas** [comment]
I've made this change with 691b2a6 . Compare this to the screenshot above:

![screen shot 2016-05-13 at 12 27 32 pm](https://cloud.githubusercontent.com/assets/1239550/15236661/40e51bc2-190a-11e6-9458-c565cb331da4.png)

## How will we know if this is a good change for people?

We're looking to see:

* decrease in the ratio of search form submissions events to error displayed events
* decrease in the ratio of alert sign up form submissions events to error displayed events
* no reduction in the rate of new alert signups

I'll keep an eye on this over the next week and see how it goes.

**Comment by henare** [comment]
>I'll keep an eye on this over the next week and see how it goes.

@equivalentideas how did it go?

**Comment by equivalentideas** [comment]
> how did it go?

@henare let's have a squiz compared to [what I said above](https://github.com/openaustralia/planningalerts/issues/978#issuecomment-218940948):

> decrease in the ratio of search form submissions events to error displayed events

Here's the error display:
![screen shot 2016-06-23 at 3 58 31 pm](https://cloud.githubusercontent.com/assets/1239550/16293215/61efefec-395b-11e6-87fb-5e5ab5d6c549.png)

And here's the form submissions:
![screen shot 2016-06-23 at 3 59 46 pm](https://cloud.githubusercontent.com/assets/1239550/16293229/8e8e4288-395b-11e6-99e2-7f66c40848c1.png)

I think that ratio of errors to submissions has definitely improved—though we have seen submissions decrease. This could be because users aren't getting stuck in the cycle of submitting, seeing an error, submitting again.

> decrease in the ratio of alert sign up form submissions events to error displayed events

This has remained pretty static. Maybe because people hitting this error are coming off the applications page that has a pre-filled address, rather than coming through with a custom search of their own from the homepage?

> no reduction in the rate of new alert signups

In fact it's gone well in the other direction. Previously alert signups per week (as measured by our GA) have sat around 370 for a long time. Since we deployed this change signups per week are sitting around 530. Remember that we also deployed #979 [which we think it good for about 30 more signups a week](https://github.com/openaustralia/planningalerts/pull/979#issuecomment-227955924).

![screen shot 2016-06-23 at 4 51 22 pm](https://cloud.githubusercontent.com/assets/1239550/16294269/06d40974-3963-11e6-8a42-2fd74249d972.png)

So it seems that this has been really successful :)
