### ISSUE TITLE
Duplicate messages created in WriteIt from a single comment

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#981]
Sometime a comment is posted twice to the WriteIt API. This means that when the councillor replies, there is a 50/50 chance that their message will go to a message that the original PlanningAlerts comment does not know about. This means the reply cannot be found and loaded (discovered in #980).

It looks like CommentNotifier#send_comment_via_writeit! is failing after it has posted the comment to WriteIt. There are no checks to see if a comment exists, so it just DelayedJob tries to run the whole method again and posts a new WriteIt message to the API and updates the comment’s `writeit_message_id`.

One solution to this might be to do some kind of check to see if the comment is already on WriteIt. If it does then we would make sure we've recorded the correct `writeit_message_id` on the comment. But why is it failing in the first place?

**Comment by equivalentideas** [comment]
There's three of this one:

* http://planningalerts.writeit.ciudadanointeligente.org/en/thread/planning-application-at-190-marsden-road-dundas-valley-nsw-2117-2/
* http://planningalerts.writeit.ciudadanointeligente.org/en/thread/planning-application-at-190-marsden-road-dundas-valley-nsw-2117-3/
* http://planningalerts.writeit.ciudadanointeligente.org/en/thread/planning-application-at-190-marsden-road-dundas-valley-nsw-2117-4/

**Comment by henare** [comment]
>But why is it failing in the first place?

We should be able to see the error in Honeybadger.
