### ISSUE TITLE
the list of councillors makes them look corporate and unapproachable

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#985]

**Comment by equivalentideas** [comment]
I think we've made a big step forward on this with #996 , moving from

![screen shot 2016-06-09 at 11 16 32 am](https://cloud.githubusercontent.com/assets/1239550/15951032/fc979c98-2ef7-11e6-9f3b-1c3730219c93.png)

to

![screen shot 2016-06-10 at 9 41 04 am](https://cloud.githubusercontent.com/assets/1239550/15951036/014c1336-2ef8-11e6-93ac-fc0fd14c0efc.png)

I'm gonna close this with the expectation that we open new issues for iterations. @kat feel free to reopen this as well if you think it should be :)
