### ISSUE TITLE
turn 'now check your email' page into an opportunity to encourage the user to feel a sense of accomplishment in commenting

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#987]
see 'add_comments' wording - which is nice and straightforward but not very warm. Nor does it give me a sense that if I complete the action I'll have a sense of satisfaction.

We're looking to that moment in mailchimp where you're about to send a newsletter- that's a big deal. This is a bigger deal because you're putting your views out there in the community and that's the start of a new and wonderful relationship with your community but it's also a risk - because you might be objecting and/or not make any friends.

**Comment by equivalentideas** [comment]
@kat and I like “You go citizen!” and less like “This is your moment of glory”.

**Comment by mlandauer** [comment]
I like the steps of making it more human
