### ISSUE TITLE
comment confirmation email could be simpler and bolder

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#988]
related to #987 this step could be the next step in that story. Thank people for their bold move! 
![screen shot 2016-06-01 at 4 33 16 pm](https://cloud.githubusercontent.com/assets/95376/15700377/e15645c0-2816-11e6-8b20-1378880fb5d7.png)

**Comment by equivalentideas** [comment]
We could build a sense of responsibility by telling people how many locals are going to get this “Is this really what you mean to say?”.

**Comment by equivalentideas** [comment]
“I've read it and this is what I want to say, post it”

**Comment by mlandauer** [comment]
I really like the idea of using this email as a final "do you really mean to say this?"
