### ISSUE TITLE
when I've confirmed my comment, create a sense of success (in your community)

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#989]
relates to #987 and #988 it's a moment of glory..... but maybe not the last thing.

**Comment by mlandauer** [comment]
@katska any suggestions on wording for here?

**Comment by katska** [comment]
not yet, this is related to a whole flow and I think needs to be looked at together with related issues.

**Comment by katska** [comment]
@mlandauer How about start simple like 

SUCCESS!
Your comment on <DA description> at <DA ADDRESS>  sent to "NSW Sydney and Regional Planning Panels". 

Possibly some words on what happens next, what they should expect to happen next in broad terms and what they can do to follow up with the authority.

**Comment by katska** [comment]
I've ignored the community context for the moment, and will keep thinking about that. I think I'd prefer to look at the community context as a separate topic, rather than shoehorn in here.
