### ISSUE TITLE
you've confirmed your comment, now you feel good, share that feeling and grow a community around it

### ISSUE THREAD

**Issue by kat** [openaustralia/planningalerts#990]
now you've completed a comment and the world can see it - #990 share with your fellow community members. Is there an opportunity to organise or ask others to comment, reflect on your view here?

If it's someone's first comment should this be a different experience?

**Comment by equivalentideas** [comment]
People are currently using the facebook share button on the confirmation notice. What other ways might people like to share? Email seems like a good one, since these people clearly use it (they're signed up to PlanningAlerts).

**Comment by mlandauer** [comment]
We already make it easy for someone to share their comment on facebook
