### ISSUE TITLE
What happens when councillors add attachments to their email replies?

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#993]
Here a councillor has attached files to their email that they want people to see: http://planningalerts.writeit.ciudadanointeligente.org/en/thread/planning-application-at-apex-park-marsden-123-127-fourth-avenue-marsden-qld-4132/

What should happen?

Here's the exchange in PlanningAlerts https://www.planningalerts.org.au/applications/426103

**Comment by henare** [comment]
Interesting! I guess we should show links to the attachments like WriteIt does.

It would also be great if we could include those attachments in the email to the commenter so they don't have to do anything different to access them.
