### ISSUE TITLE
Duplicate councillors loaded

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#995]
Just hit load and got two versions of each councillor. Haven't looked into why this is yet.

![screen shot 2016-06-10 at 9 32 07 am](https://cloud.githubusercontent.com/assets/1239550/15949970/54f72232-2eee-11e6-8c31-626899ccf8d9.png)

**Comment by equivalentideas** [comment]
I've removed the duplicates manually and hit “load” again to pull in images. Worked as expected and didn't create duplicates.

**Comment by henare** [comment]
Strange. Stray whitespace?

I think we should close as cannot reproduce if we don't yet know why this happened in this circumstance.
