### ISSUE TITLE
When I'm looking at a DA, tell me if the address is heritage listed, so I better understand the impact and context of the development

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#997]
This might be useful for this http://api.heritagecouncil.vic.gov.au/documentation/VHD-v1

**Comment by equivalentideas** [comment]
This might also be useful http://data.environment.nsw.gov.au/dataset/standard-instrument-local-environmental-plan-height-of-buildings-hob

**Comment by mlandauer** [comment]
This feels like a very specific version of the suggestion in https://github.com/openaustralia/planningalerts/issues/1019. I'm not sure we're ready to go down this path
