### ISSUE TITLE
Messages can still be sent to councillors of amalgamated NSW councils

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#998]
The recent forced amalgamations of some NSW councils means that the elected councillors are no longer in service and have been replaced with administrators until the next election of councillors. For these councils the simple thing will be to disable councillor commenting for now.

**Comment by equivalentideas** [comment]
> For these councils the simple thing will be to disable councillor commenting for now.

I've been waiting to see what you think about this @henare . As always I think it's a question of what's most useful to people. Some of those councillors have written back to people and had useful interactions. There was another thought that removing the councillors is modelling the system we have rather than the system that might be better for people.

I'd be happy to remove, or leave them in for now—just feels like a tough situation for citizens either way.

We've held off collecting data for the amalgamated councils so we don't have too many councils in this situation.

**Comment by henare** [comment]
>Some of those councillors have written back to people and had useful interactions. 

That's very interesting and not what I expected!

>As always I think it's a question of what's most useful to people.

Indeed. I'd assumed removing them was best because they couldn't actually help people now that they're no longer in service as a councillor. I'd also assumed that many of them would have had their email accounts shut down. However given the above maybe my assumptions are incorrect?

**Comment by equivalentideas** [comment]
>  I'd also assumed that many of them would have had their email accounts shut down.

Apparently not yet, at least for Marrickville. Also I've heard that some of the councillors may be reinstated in some capacity. It's all pretty live right now. I think we wait to see what happens for another month.

**Comment by equivalentideas** [comment]
For reference, here's an example of a helpful exchange with a former councillor https://www.planningalerts.org.au/applications/666668#comment56328 . Here's another one where the councillor explains the situation and offers to talk more about it https://www.planningalerts.org.au/applications/662967#comment56082 .

**Comment by henare** [comment]
That comment about IHAP is very interesting.

>I think we wait to see what happens for another month.

I've closed this for now.

**Comment by equivalentideas** [comment]
At first I thought this was council staff replying for a removed councillor http://planningalerts.writeit.ciudadanointeligente.org/en/thread/planning-application-at-23-alfred-street-st-peters-nsw-2044-2/

On second reading, it could easily be the councillor replying.

> Please be advised that Marrickville Council has been replaced by the Inner West Council. The elected Councillors have been replaced by an Administrator. Please contact the Inner West Council for more information http://www.marrickville.nsw.gov.au/en/council/about-council/contact/

More to consider.

**Comment by henare** [comment]
I'm reopening this because we should take another look at it.

**Comment by henare** [comment]
Here's a few questions I'd like to answer:

* What's happening with the council websites of amalgamated councils? Have any been redeveloped yet or are they still separate?
* Are councillors on amalgamated councils still responding to emails or not? Are they useful responses?
* What's happening to councillors in the amalgamated areas? Are they on LRACs like many councillors from inner west councils?

**Comment by henare** [comment]
Here's the [mergers that have already happened](https://www.strongercouncils.nsw.gov.au/new-councils/):

* Armidale Regional Council : The merger of Armidale Dumaresq and Guyra Shire councils
* Canterbury-Bankstown Council : The merger of Bankstown City and Canterbury City councils
* Central Coast Council : The merger of Gosford City and Wyong Shire councils
* City of Parramatta Council : The merger of Parramatta City*, The Hills Shire*, Auburn City*, Holroyd City* and Hornsby Shire* councils
* Cumberland Council : The merger of Parramatta City*, Auburn City* and Holroyd City* councils
* Edward River Council : The merger of Conargo Shire and Deniliquin councils
* Federation Council : The merger of Corowa Shire and Urana Shire councils
* Georges River Council : The merger of Hurstville City and Kogarah City councils
* Gundagai Council : The merger of Cootamundra Shire and Gundagai Shire councils
* Hilltops Council : The merger of Boorowa, Harden Shire and Young Shire councils
* Inner West Council : The merger of Ashfield, Leichhardt Municipal and Marrickville councils
* Mid-Coast Council : The merger of Gloucester Shire, Great Lakes and Greater Taree City councils
* Murray River Council : The merger of Murray Shire and Wakool Shire councils
* Murrumbidgee Council : The merger of Jerilderie Shire and Murrumbidgee Shire councils
* Northern Beaches Council : The merger of Manly, Pittwater and Warringah councils
* Queanbeyan-Palerang Regional Council : The merger of Palerang and Queanbeyan City councils
* Snowy Monaro Regional Council : The merger of Bombala, Cooma-Monaro Shire and Snowy River Shire councils
* Snowy Valleys Council : The merger of Tumbarumba Shire and Tumut Shire councils
* Western Plains Regional Council : The merger of Dubbo City and Wellington councils

**Comment by henare** [comment]
>What's happening with the council websites of amalgamated councils? Have any been redeveloped yet or are they still separate?

None of the councils that we cover have merged their websites yet.

**Comment by henare** [comment]
>Are councillors on amalgamated councils still responding to emails or not? Are they useful responses?

Here's a list of councils being amalgamated that we've got councillors for:

* Gosford - no messages to councillors recently
* Wyong - no messages to councillors recently
* Parramatta - 3 comments to councillors, no responses
* Marrickville - Recently there's been a few messages to councillors (but mostly to council). [Most recent reply](https://www.planningalerts.org.au/applications/666668#comment56328) from a councillor says they have no say in planning any more.
* Manly - Only 1 comment to a councillor, about a month ago, no replies

**Comment by henare** [comment]
My conclusions:

* We don't need to update scrapers or councils on PlanningAlerts yet as they all still have separate websites. I expect this will change in the coming months but we can deal with that then
* I've noted all the councils that are pending amalgamation on [the issue about collecting councillor data](https://github.com/openaustralia/planningalerts/issues/968). This will mean volunteers won't attempt to collect out of date data
* I'm going to disable Ask Your Councillors on those few NSW councils that are being amalgamated where we already have data
